### PR TITLE
Use intra doc in network-gossip

### PR DESCRIPTION
**Pull request by liuchengxu**
So that we could jump to the definition easily.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
FYI: This crate is probably going to be removed next year or moved closer to grandpa, aka in a non-reusable way. 

It is currently only used by grandpa. Everything on Polkadot for example uses its own gossiping logic.

**Comment by bkchr** [comment]
@liuchengxu please run cargo fmt.

**Comment by liuchengxu** [comment]
@bkchr Thanks for the info, does that mean substrate will probably not provide the network gossiping support in the future? I notice that beefy also use this crate
https://github.com/paritytech/substrate/blob/c476b86c73a942c3a542e4a0ef0c2d73e4399271/client/beefy/Cargo.toml#L33

**Comment by bkchr** [comment]
It is not yet set in stone. Maybe there will be a replacement, maybe not. I just wanted to make you aware, in the end you could always copy the current code.

**Comment by liuchengxu** [comment]
@bkchr I'm also curious why polkadot does not use this crate instead using its own gossiping logic, are there any design considerations that could be useful for those who might have to develop their own gossiping network too?

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
> @bkchr I'm also curious why polkadot does not use this crate instead using its own gossiping logic, are there any design considerations that could be useful for those who might have to develop their own gossiping network too?

Best to read the implementors guide.

**Pull request merged**
