### PR TITLE
Add build substrate and subkey binaries for MacOS

### PR DESCRIPTION
**Pull request by General-Beck**
Testing on Mac OS is not enabled at this stage.  It doesn't seem reasonable to test everything on every PR. I can add testing on MacOS for example with a tag. If necessary, write here and I will add it.

### CODE REVIEW

**Comment by gnunicorn** [comment]
>  It doesn't seem reasonable to test everything on every PR.

Why not? especially running `cargo test --all` should be done (just to ensure that no one on a mac finds themselves with failing tests for code they didn't change). I'd rather have the tests run than the binaries build if the question is which one to perform.

**Comment by General-Beck** [comment]
@gnunicorn Let's check it out.the fact is that we are currently limited to one build machine and one task per build machine, since we use the shell runner. and `cargo test --all` & `cargo check -all` can take a long time. 
Let's check it out

**Comment by gnunicorn** [comment]
Tests seem to take 30min, build about 22min combined. Not sure we need `check` _and_ `test`... though the earlier might finds and import that is-test-only, this is unlikely to be a mac-specific problem. If resoucres are a constraint, I'd vote for running `test` on mac – maybe make it non-mandatory to pass first – keeping the other ready in the file but deactivated because overall it'd be good to do all!

**Comment by bkchr** [comment]
Having just 1 runner will put a huge blocker into the CI. We are already having problems with 6 runners for the normal tests.

**Comment by gnunicorn** [comment]
agreed. what would be needed to get more runners, @General-Beck ?

**Comment by General-Beck** [comment]
@gnunicorn I also want all tests to run, like [here](https://github.com/General-Beck/rust-actions-template/actions/runs/60473552). But today we will discuss with the DevOps what we will need in order to run several tests on the mac in parallel. Now the problem is this, 1 runner - 1 job on Mac OS. These are the features, we are looking for a scaling solution.

**Comment by gavofyork** [comment]
realistically, 80% of the value comes from just a `cargo check --all`. maybe another 19% of value comes from intergration tests on the binary. unit-tests are highly unlikely to be platform-dependent and given our CI backlog troubles, I wouldn't want to exascerbate it further by re-running all the unit-tests on all platforms all the time.

**Comment by General-Beck** [comment]
@gavofyork `cargo check --all` does not take much time 3-5 min [ref](https://gitlab.parity.io/parity/substrate/-/jobs/452578). much more time is spent on [tests](https://gitlab.parity.io/parity/substrate/-/jobs/456523). But here we see [errors](https://gitlab.parity.io/parity/substrate/-/jobs/452599), even if the [Linux](https://gitlab.parity.io/parity/substrate/-/jobs/452544) test passes successfully. As a compromise, we can leave only `cargo check` for commits, and test only for the master/nigthly test. And also go through the entire cycle before release.

**Comment by General-Beck** [comment]
and here's another magic, restarting the [test](https://gitlab.parity.io/parity/substrate/-/jobs/456523) was successful

**Comment by General-Beck** [comment]
I propose to leave the `cargo check --all` and `cargo build subkey` for MacOS. If necessary, we will add new runners and add the substrate build. 
Now it looks like [this](https://gitlab.parity.io/parity/substrate/pipelines/89401), if there are no objections, I will correct the CI file before the merge and it will be possible to finish with this PR.

**Comment by s3krit** [comment]
LGTM. Don't forget to remove before merging ;) :
`     - /^[0-9]+$/ #Remove before merge `

**Comment by gavofyork** [comment]
@General-Beck doesn't build?

**Comment by General-Beck** [comment]
all built, waiting for approve and after final edits will I be able to merge

**Comment by gavofyork** [comment]
everyone happy with this now, then? cc @gnunicorn

**Comment by gnunicorn** [comment]
bot merge

**Pull request merged**
