### PR TITLE
Update yamux to version 0.4.5

### PR DESCRIPTION
**Pull request by twittner**
See https://github.com/paritytech/yamux/blob/develop/CHANGELOG.md#045 for details.

### CODE REVIEW

**Comment by twittner** [comment]
Yes, repositories with a committed `Cargo.lock` need to manually update. I was about to open another PR for Polkadot. Do you have an alternative suggestion in mind?

**Comment by bkchr** [comment]
Sadly not :( (I assume you have updated the reference in libp2p, so that the next libp2p update enforces this?)

**Comment by twittner** [comment]
https://github.com/paritytech/polkadot/pull/927

**Comment by twittner** [comment]
So would you prefer to wait for a new libp2p release instead of receiving PRs like this?

**Comment by bkchr** [comment]
I think they are okay, at least for Polkadot. Substrate is questionable, but better safe than sorry :P

**Pull request merged**
