### PR TITLE
generic hash

### PR DESCRIPTION
**Pull request by guanqun**
An attempt to make the hash type parameter generic. Not fully done, but need some guidance if I'm on the right track...

### CODE REVIEW

**Comment by guanqun** [comment]
@dvdplm

**Comment by guanqun** [comment]
Looks like we're not using the latest nightly? Probably we should use a newer docker image? @chevdor 

```
error[E0635]: unknown feature `panic_handler`
  --> /builds/parity/substrate/substrate/runtime-std/src/lib.rs:21:43
   |
21 | #![cfg_attr(not(feature = "std"), feature(panic_handler))]
   |                                           ^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by pepyakin** [comment]
@guanqun https://github.com/paritytech/substrate/pull/686 this should fix this issue, try to rebase on the latest master.

**Comment by guanqun** [comment]
@pepyakin Thanks a lot! Rebased now.

**Comment by gavofyork** [comment]
Yeah - we can merge the macro part into the relevant crate (since it's strictly better), but we can't use it since the general idea of having a monomorphic runtime environment is at odds with providing a general runtime API. Essentially, we cannot have an environment whose extern functions have "generic" (read: arbitrary) semantics since the runtime (of which there may be several that the environment serves) cannot know in advance what the semantics are.

**Comment by guanqun** [comment]
Thanks for the explanation, I've picked up only the macro changes, as it's not used by other code except the testing part, not sure how useful it is.

**Comment by gavofyork** [comment]
nice to have :)

**Pull request merged**
