### PR TITLE
Scheduler is already at V4

### PR DESCRIPTION
**Pull request by ggwpez**
Looks like we forgot to bump the scheduler code version from V3 to V4 here https://github.com/paritytech/substrate/pull/11649  

Chains who deployed a scheduler/genesis without this patch should manually set the scheduler version to 4 and not use `v3::MigrateToV4`.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2242117

**Review by bkchr — APPROVED** [review]

**Review by sam0x17 — APPROVED** [review]

**Review by KiChjang — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-38/2122/1

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/substrate-developer-newsletter-february-2023-notable-updates-for-frame-devs-new-deep-dives-released-calling-builders-to-apply-to-rfps-and-bounties/2137/1

**Pull request merged**
