### PR TITLE
Multiple improvements to the `decl_module!` macro

### PR DESCRIPTION
**Pull request by bkchr**
1. Removes weird `where origin = Origin where system = System` and replaces with more rusty syntax:
  `where origin = Origin, system = System`.
2. Makes it possible to easier implement `deposit_event` by either writing `fn deposit_event() = default` which creates the default implementation or by using `fn deposit_event(my_event: MyEvent) { //myimpl }` which supports any custom implementation. This fixes: https://github.com/paritytech/substrate/issues/920
3. Calls are now required to be implemented directly in the `decl_module!` macro. This reduces boilerplate code, as now extra `impl<T: Trait> Module<T>` block is required. 

This currently does not compile on stable, we need to wait for Thursday (23.10), where the required feature will be released as stable with rust 1.30.0.

### CODE REVIEW

**Comment by gavofyork** [comment]
doesn't build, needs resolving...

**Comment by bkchr** [comment]
Yeah as written in the description, this requires rust 1.30.0 that should be released today.

**Comment by chrisdcosta** [comment]
I'm not sure if this is related I think this may be causing breaking changes to custom modules (Gavin's demo?) - I'm getting compile errors `error: no rules expected the token /`normalize/` this error originates in a macro outside of the current crate` on rust 1.30.0 with or without function code in the  `impl<T: Trait> Module<T>`

**Comment by bkchr** [comment]
@chrisdcosta do you have more context for me? Did you tried to redo gav's demo? If yes, you now need to place your implementation directly into the `decl_macro!`.

So before you had something like:
```
decl_macro! {
    struct Module {
        fn my_call(origin, data:i32) -> Result;
    }
}

impl Module {
   fn my_call(origin, data: i32) -> Result { 
        //my impl
   }
}
```

Now you have to write it like:

```
decl_macro! {
    struct Module {
        fn my_call(origin, data: i32) -> Result { 
            //my impl
        }
    }
}
```

**Comment by chrisdcosta** [comment]
Yes I'd seen the changes in the SRML modules. I was building using the paired-down demo version of substrate generated by `substrate-node-new` but it may have been installed before your recent updates from master. Am checking this now.

**Comment by bkchr** [comment]
Okay

**Comment by chrisdcosta** [comment]
OK I've tied this error down - it's not a problem with the build - it's my use of a type definition for `origin` in the struct following the live demo. 

In the live demo the function signature for `set_payment` inside the struct Module explicitly typed the first argument `fn set_payment(_: T::Origin, value: T::Balance) -> Result {...}`. 

This causes the error - and presumably is because the changes mean that if `origin` is typed in the `where` of the struct definition it does not now need to be specified in the structs own function signatures. Is this correct?

**Comment by chrisdcosta** [comment]
Should add that it now compiles correctly like this `fn set_payment(_origin, value: T::Balance) -> Result {...}`

**Pull request merged**
