### PR TITLE
Add a --no-private-ipv4 CLI option

### PR DESCRIPTION
**Pull request by tomaka**
Fix https://github.com/paritytech/polkadot/issues/543

If passed, the `--no-private-ipv4` CLI option will prevent the networking from trying to connect to the ranges `10.0.0.0/8`, `172.16.0.0/12` and `192.168.0.0/16`.

### CODE REVIEW

**Comment by tomaka** [comment]
Thinking about it, should we maybe do `--only-global-ipv4` instead?
This would also cover `127.0.0.0/8`, `169.254.0.0/16` (loopback), and so on.

**Comment by arkpar** [comment]
> Thinking about it, should we maybe do `--only-global-ipv4` instead?
> This would also cover `127.0.0.0/8`, `169.254.0.0/16` (loopback), and so on.

Don't we filter these out in discovery already?

**Comment by arkpar** [comment]
Would that prevent the peerset from connecting to already known private addresses when using `--no-private-ipv4`? It should be possible to switch this CLI option on and off without clearing the peerset file.

**Comment by tomaka** [comment]
> Don't we filter these out in discovery already?

No, as they might be legitimate.
Maybe we should filter them out of Kademlia, but I'm not sure if it's ok to do so.

**Comment by tomaka** [comment]
> Would that prevent the peerset from connecting to already known private addresses when using --no-private-ipv4? It should be possible to switch this CLI option on and off without clearing the peerset file.

We don't have a peerset file yet, but yes that would prevent all already-known addresses from being attempted.

**Comment by tomaka** [comment]
cc @joepetrowski 
Devops might want to enable this option.

**Comment by gregorst3** [comment]
@tomaka  Hello, there is an internal ip range missing: 100.64.0.0/10  https://datatracker.ietf.org/doc/html/rfc6598.

**Pull request merged**
