### PR TITLE
Add extra debug log for rejected transaction

### PR DESCRIPTION
**Pull request by NikVolf**
Currently, we are rather log-blind if transaction is rejected immediately (can't even see tx hash)

### CODE REVIEW

**Comment by bkchr** [comment]
We return an error if a transaction can not be added, so why are we "blind"?

**Comment by NikVolf** [comment]
> We return an error if a transaction can not be added, so why are we "blind"?

we don't know which transaction is errored:
warning below records this:

```
2021-02-08 22:15:21.171 WARN tokio-runtime-worker sc_rpc::author: Failed to submit extrinsic: Transaction pool error: Invalid transaction validity: InvalidTransaction::Payment
```

**Comment by bkchr** [comment]
I meant you see this on the sending side, aka the one that send the transaction.

I just read the code of this function again and it is really confusing. Now you want to add another debug message that will not be shown in "normal" mode where we would just see the warning. So, I still don't see the benefit. Can you not just refactor this whole function to have the tx hash accessible for the warning?

In the end, if the transaction could not be decoded properly, we would still only see the warning, because your debug message would not be printed.

**Comment by gnunicorn** [comment]
any progress on this?

**Comment by gnunicorn** [comment]
closing due to a lack of progress.

**Pull request closed without merging**
