### PR TITLE
Add log rotation and switch to flexi_logger

### LINKED ISSUE #5926: Log rotation
Substrate logs to stderr and stdout. It is impossible to organize log rotation without copying previously logged data. E.g. `logrotate` has to be configured with `copytruncate` option that copies the file and truncates it, losing some data in the process.

Would be best to use a logger that supports rotation out of the box, or at least allows reopening output file on `SIGHUP`
https://github.com/emabee/flexi_logger looks promising, as long as there's no performance regression.

### PR DESCRIPTION
**Pull request by pscott**
This PR adds the option to rotate logs. It does so by switching to another crate for loggin (previously `env_logger`, now `flexi_logger`).

A similar PR was already [merged](https://github.com/paritytech/substrate/pull/6564) and [reverted](https://github.com/paritytech/substrate/pull/6627).

I would ask the reviewers to:
1. Thoroughly read the [original issue](https://github.com/paritytech/substrate/issues/5926).
2. Test and play a little bit with the configurations (using `--log`, `--log-directory`, `--log-age`, and `--log-size`). (cc @ddorgan )

This PR also fixes the problem of:
- `AgeOrSize`: if `--log-age` AND `--log-size` are specified, the log rotation will happen once either the AGE or the SIZE gets reached.
- Quitting if the Logger error'd: previously we would simply error and not start the client. Now the client simply prints an error message.

Closes #5926 
polkadot companion: https://github.com/paritytech/polkadot/pull/1450

### CODE REVIEW

**Comment by pscott** [comment]
Please note that [logger.rs](https://github.com/paritytech/substrate/blob/master/client/cli/src/logger.rs) was added by #6564 but not properly reverted by #6627 because of #6620 .. :p

**Comment by ddorgan** [comment]
@pscott what happened to doing it the standard linux way? e.g. a SIGUP flushes and logrotate rotates.

**Comment by pscott** [comment]
> @pscott what happened to doing it the standard linux way? e.g. a SIGUP flushes and logrotate rotates.

Since [this comment](https://github.com/paritytech/substrate/issues/5926#issuecomment-657659696) said:
> Though custom log rotation would still be useful I think. Not all platforms have journald and for and end users it might be easier to use something build-in.

I thought using flexi_logger with custom log rotation was the way to go. I think there's no clear consensus atm (see [original issue](https://github.com/paritytech/substrate/issues/5926)), so this PR is here because the work was already done, but we could as well decide not to merge it.

If I understand @ddorgan you'd want SIGUP to flush and rotate? No custom "rotation" provided out of the box?

PS: stupid question but how would this work on windows? (I have no idea how logs are usually handled on windows...)

**Comment by pscott** [comment]
Since `init_logger` now returns a Result, should this PR be tagger `breaksapi`?

**Comment by pscott** [comment]
Since `init_logger` now returns a Result and requires an extra parameter, I tagged `breaksapi`.  Feel free to remove :)

**Comment by gnunicorn** [comment]
closing because of inactivity.

**Pull request closed without merging**
