### PR TITLE
Remove /self from mandatory rpc reviews.

### PR DESCRIPTION
**Pull request by tomusdrw**
There is a lot of PRs that touch RPC somehow, but usually I'm not the necessary person to review them.

### CODE REVIEW

**Comment by bkchr** [comment]
bot merge

**Comment by sjeohp** [comment]
bot is redeploying

**Comment by sjeohp** [comment]
bot merge

**Comment by sjeohp** [comment]
if you don't mind, please leave this for another 10mins while we redeploy again to check handling of the insubstantial tag

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
