### PR TITLE
replace storage version to pallet version

### PR DESCRIPTION
**Pull request by gitwithterrence**
This PR replaces storage version to pallet version

Resolves [  Replace storage version to pallet version #10755  ](https://github.com/paritytech/substrate/issues/10755)

### CODE REVIEW

**Comment by kianenigma** [comment]
This probably needs a migration on live networks?

**Comment by MC-Terrence** [comment]
> Hey, is anyone still working on this? Due to the inactivity this issue has been automatically marked as stale. It will be closed if no further activity occurs. Thank you for your contributions.

@xlc can you kindly review this?

**Comment by MC-Terrence** [comment]
> Hey, is anyone still working on this? Due to the inactivity this issue has been automatically marked as stale. It will be closed if no further activity occurs. Thank you for your contributions.

@shawntabrizi can you kindly look at this?

**Comment by ggwpez** [comment]
I guess it does need a migration to remove the old `StorageValue`s.

**Pull request closed without merging**
