### PR TITLE
Run and monitor a "chaos network"

### PR DESCRIPTION
**Pull request by gterzian**
This PR is not intended to be merged for now, more as a way to share the ongoing work. It could be used as a separate branch to run some tests on a server, or perhaps we'll find a way to merge it in master later. 

The issue is at https://github.com/paritytech/substrate/issues/1776

### CODE REVIEW

**Comment by arkpar** [comment]
I've already did some work on a similar framework in `core/service/test`. Unfortunately the consensus integration test that I've written was later removed by someone when doing refactoring. Perhaps this code still can be useful.

**Comment by gterzian** [comment]
> Perhaps this code still can be useful.

Yes, would you perhaps have the commit handy where the removal took place?

**Comment by arkpar** [comment]
https://github.com/paritytech/substrate/pull/883/files#diff-8dcf55bb02e5a4cae989141cba16b32cL274

**Comment by gterzian** [comment]
@rphmeier @gavofyork Could ask you to run this branch locally with just a `cargo run --release`, and let me know if you see any of the problems you're thinking off happening? I can only see that when nodes are disconnected for a while, they sometimes take a long time to start syncing again(while we you restart they sync immediately). In any case, trying to narrow down the problems we're looking for and see if they can be reproduced. 

Re running this conitniously, I think the  easiest way would be to run this on a server and hook it up to [sentry](https://github.com/getsentry/sentry-rust) for reporting.

**Comment by rphmeier** [comment]
@gterzian Giving it a shot now -- I wouldn't expect that we see serious GRANDPA issues within a few minutes, as we've only seen them pop up in practice over the course of days.

**Comment by rphmeier** [comment]
Two things I notice:
  - One node has 12 peers and the others have 1
  - GRANDPA doesn't appear to finalize anything

**Comment by gterzian** [comment]
@rphmeier Yet I can comfirm that I have also seen:

1. It seems nodes don't always re-connect with all peers after having been disconnected, so even though they still sync ok, their peer numbers is not equal to the size of the network. If you do a `ctrl-c` and restart, all nodes will re-connect with all others(so it seems there is something happening on start-up that doesn't always happen on an ongoing basis).
2. Also nodes seem to be a little slow in syncing sometimes, you can see a few nodes, probably those that have been disconnected, staying behind. Sometimes they end up syncing after a while. Again, if you restart the network they will all sync immediately and very quickly. 
3. "finalized" is always zero.

**Comment by gterzian** [comment]
Sentry seems to have a nice integration with Rust https://docs.sentry.io/platforms/rust/

**Comment by rphmeier** [comment]
@gterzian we need to get this in a state where it works correctly at least some of the time. Maybe there are libp2p issues

**Comment by gterzian** [comment]
> get this in a state where it works correctly at least some of the time

I'll look into the 0 finalize issue...

**Comment by bkchr** [comment]
What is the status of this? Will there be any progress in the near future or can we close this one?

**Comment by gterzian** [comment]
Closing this experiment, we'll be running the chaos testnet with an orchestrator tool without the need to change the rust code...

**Pull request closed without merging**
