### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by bkchr** [comment]
Please. Don't open one pull request per single edit.
Please merge all of your changes into one pr and reopen it.

**Comment by elopio** [comment]
Ok, I'll try :man_shrugging:. But that takes slightly more time, so probably I won't be fixing as many typos as I could.

**Comment by bkchr** [comment]
I don't know why that takes more time. Just read all the code you want to read, fix typos while doing this and at the end of the day you send one pr. If you send each day a pr, fine. But not 3 prs, over one hour or similar.

**Comment by elopio** [comment]
It's not that it takes a lot of time more. It's that it takes a little more time. I'm usually reading random source code at the end of my work day, directly in github. I open a file, read, see a typo, hit edit, hit commit, hit pull request. Go on reading. This takes very very little time and brain power.

I don't know if I will find more typos, so I prefer to do it immediately, when I have context over what's going on, and before I forget I had a commit hanging around.

Setting the bar just a little bit higher than that usually makes me run for dinner, drinks, or bed without thinking of anything else. I just shut down all the devices without thinking if I had some fixes in progress. Real life beats typos.

I understand you would prefer to have less pull requests to review. Of course. However, my experience as maintainer has been that if you encourage contributors to help in whatever way fits them best, even on tiny thinks like proof-reading your documentation, they will come back and become every day more engaged.

But I do see your point. And it's your project, the last thing I want to do is to add noise. I will try. I still have lot's of substrate to read :man_facepalming:.

One tip: run [codespell](https://github.com/codespell-project/codespell) in pull requests. It catches most of the things I've fixed.

**Comment by bkchr** [comment]
Thanks for your detailed explanation :)

**Pull request merged**
