### PR TITLE
Update wasmtime to 0.29.0

### PR DESCRIPTION
**Pull request by bkchr**
This updates wasmtime to 0.29.0 and its new api.

- Removes the state-holder and makes use of the data that is being attached to the state
- Make `WasmRuntime` trait take mut self

Closes: https://github.com/paritytech/substrate/issues/9068

polkadot companion: https://github.com/paritytech/polkadot/pull/3834

### CODE REVIEW

**Comment by gilescope** [comment]
It's a shame the reads require `&mut` now, but I guess the context does get changed. I almost wonder if we could hide that away behind some internal mutability...

**Review by gilescope — APPROVED** [review]
I get it now: `memory_as_slice_mut` removed for  `data_mut` ( https://docs.wasmtime.dev/api/wasmtime/struct.Store.html#method.data_mut ). Yeah that's much nicer.

FYI: I see the dev release of the next version of wasmtime just dropped - looks like some module loading speedups just landed (not that I know what a veneer is...)

**Comment by gilescope** [comment]
Looks like you'll have to bump the zstd on polkadot...

**Review by pepyakin — APPROVED** [review]
The changes look good. Some nits left above.

**Comment by bkchr** [comment]
> The changes look good. Some nits left above.

Forgot to push my changes :D

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
