### PR TITLE
Integrate contracts into substrate-demo runtime

### PR DESCRIPTION
**Pull request by pepyakin**
Also, the way contract address is calculated is changed. 

`ext_create` now takes one additional parameter: salt (`u64`), which is ultimately passed into the `contract_address_for`. You can read about motivation in [KIP-4](https://github.com/kovan-testnet/KIPs/blob/33a116649116ddad656302311080438264bb2dba/KIPs/kip-4.md). 

Additionally, `data` (input parameter for constructor) is also passed to the `contract_address_for `. This was changed to make address calculation mechanism to be similar to pwasm's one, where input data is also accounted for address calculation (since it is a part of the constructor code there).

`contract_address_for` for substrate-demo has the following formula: 

```
blake2_256(blake2_256(code) + blake2_256(data) + LE(salt) + origin)
```

### CODE REVIEW

**Comment by gavofyork** [comment]
not super keen on salt - we can just introduce a "salt" into the init code to avoid this.

**Comment by pepyakin** [comment]
Me too. But I'm not keen on the introducing salt into the init code either, for the same reason why we pass init code and data separately (like we are doing in pwasm). 

In pwasm we do this because of compatibilty with ethereum, where you don't have separate "data" field. In case of EVM this works fine since it just a bunch of instructions and data, but in case of wasm, which have a strict binary format, it is merely a hack: we just concatenate input data to the end of wasm init code. This trailing data makes the wasm binary invalid and we detect this in pwasm loader and strip all trailing data and treat it as input data. But that said, this is a better solution than trying to modify init code wasm binary: you can't get away with monkey patching the data section because you need to preserve binary format. Moreover, you need to be careful to not overwrite existing data in data section and update the initial memory page count if input data doesn't fit in. There might be other caveats that I can't come up with now. All of this makes me think that modifying init code is not feasible.

Back to salt: we can make it an ABI problem, user can always modify data and just ignore it in their constructor. But this will introduce some burden in the userspace: constructors should provide a way to supply some space for the salt in data they accept.

**Comment by gavofyork** [comment]
> we can make it an ABI problem 

Indeed. I'd prefer to dirty the user space (when needed) than dirty the core protocol specification on which all userspace rests.

**Comment by pepyakin** [comment]
Ok, removing salt then!

**Comment by pepyakin** [comment]
Removed salt and rebased @gavofyork

**Comment by gavofyork** [comment]
more resolving :) @pepyakin

**Pull request merged**
