### PR TITLE
Fixed typos in upgrade readme.

### PR DESCRIPTION
**Pull request by gilescope**
I'm terrible at spelling so I have a spellchecker in my vscode setup and it picked up a few things.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
Please merge master.

**Review by shawntabrizi — APPROVED** [review]

**Comment by bkchr** [comment]
ping @gilescope

**Comment by gilescope** [comment]
Ah @bkchr I assumed you were asking me to rebase to latest master? ok done.

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
thank you @gilescope

**Pull request merged**
