### PR TITLE
Fix ui tests (E0308 error)

### PR DESCRIPTION
**Pull request by DarkEld3r**

### CODE REVIEW

**Comment by Kianenigma** [comment]
Not sure if it is just me but almost always (my suspicion is when I have RLS running) my cargo is kind enough to report each error twice. If other people feel the same, would be nice to tweak these tests to: If you see this error string once or twice it is a pass. My current workflow is to always ignore these tests locally.

**Comment by bkchr** [comment]
Sir @Kianenigma, I don't understand what you want to tell us.

**Comment by Kianenigma** [comment]
I think this will clear things up: 

I constantly get this (I think when RLS is running, usually cargo clean makes it okay but just for once):

```
EXPECTED:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0053]: method `test` has an incompatible type for trait
  --> $DIR/type_reference_in_impl_runtime_apis_call.rs:20:17
   |
14 |         fn test(data: u64);
   |                       --- type in trait
...
20 |         fn test(data: &u64) {
   |                       ^^^^ expected u64, found &u64
   |
   = note: expected type `fn(u64)`
              found type `fn(&u64)`

For more information about this error, try `rustc --explain E0053`.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

ACTUAL OUTPUT:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0053]: method `test` has an incompatible type for trait
  --> $DIR/type_reference_in_impl_runtime_apis_call.rs:20:17
   |
14 |         fn test(data: u64);
   |                       --- type in trait
...
20 |         fn test(data: &u64) {
   |                       ^^^^ expected u64, found &u64
   |
   = note: expected type `fn(u64)`
              found type `fn(&u64)`

error[E0308]: mismatched types
  --> $DIR/type_reference_in_impl_runtime_apis_call.rs:18:1
   |
18 | / impl_runtime_apis! {
19 | |     impl self::Api<Block> for Runtime {
20 | |         fn test(data: &u64) {
21 | |             unimplemented!()
22 | |         }
23 | |     }
24 | | }
   | |_^ expected u64, found &u64
   |
   = note: expected type `u64`
              found type `&u64`

Some errors have detailed explanations: E0053, E0308.
For more information about an error, try `rustc --explain E0053`.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

**Comment by bkchr** [comment]
I still don't understand where you get this error. But rust often introduces new errors, like this one. This will be solved with this pr, as the new error apparently is now in stable rust.

**Pull request merged**
