### PR TITLE
Adds composable.finance to ss58 registry

### PR DESCRIPTION
**Pull request by seunlanlege**

### CODE REVIEW

**Comment by seunlanlege** [comment]
welp can't sign CLA

**Review by gilescope — APPROVED** [review]
LGTM

**Comment by bkchr** [comment]
@gilescope can you please stop adding the `BD0` label. The point of the label is that it is added by the business side, so we know that it is worked on.

**Comment by gilescope** [comment]
Ah ok. Will do.

**Review by BenWhiteJam — APPROVED** [review]
fine from BD side.

- [x] contact
- [x] testnet
- [x] code repo
- [x] support
- [x] community

**Pull request merged**
