### PR TITLE
Move polkadot build check to polkadot and check status in substrate

### PR DESCRIPTION
**Pull request by cecton**
More details in https://github.com/paritytech/polkadot/pull/1426

polkadot companion: https://github.com/paritytech/polkadot/pull/1426

### CODE REVIEW

**Comment by cecton** [comment]
@TriplEight as you can see now the polkadot-companion-status step fails because the polkadot companion PR has not been approved yet.

(I still need to finish some things in polkadot .gitlab-ci.yml)

**Comment by cecton** [comment]
@TriplEight It is almost ready to merge but I won't be able to do it alone:
1. The build in polkadot must pass. It started failing but I couldn't reproduce it locally. Logs [here](https://gitlab.parity.io/parity/polkadot/-/jobs/599041).
2. The requirement for continuous-integration/gitlab-check-polkadot-companion-build on GitHub must be removed (as this step has been removed)
3. I updated the doc but I think it would be best to make an announcement on the channel because with this change, the companion PR must be in the description of the polkadot pr too (both links must be present)

(The reason for 3. is because on substrate it checks the status of the polkadot PR while on Polkadot it needs to know which branch of substrate needs to be used for the build)

**Comment by s3krit** [comment]
We should probably also remove or edit `.github/workflows/polkadot-companion-labels.yml` also - Its current purpose is to monitor the status of the companion-build job and apply a label to the PR if it fails. I get the suspicion it's not actually been that useful an action anyway.

>2. The requirement for continuous-integration/gitlab-check-polkadot-companion-build on GitHub must be removed (as this step has been removed)

We'll need to get someone in the [dev-admin](https://github.com/orgs/paritytech/teams/dev-admin) team to do this.

**Comment by cecton** [comment]
(Wait before doing so because there is still this problem of Cargo.lock to update in polkadot)

**Comment by cecton** [comment]
I'm closing this PR because after discussion (and checking history) I realized that this solution won't solve the issue I currently have with the companion pr process.

**Pull request closed without merging**
