### PR TITLE
Add Capped tally to limit votes when approval might change drastically

### PR DESCRIPTION
**Pull request by olanod**
## Whale mitigation in OpenGov

This PR introduces an idea to mitigate the big influence users with big capital can have when voting on referenda with relatively low support with a follow up topic to avoid gaming the solution.

### Capped votes

Users voting with large amount of funds(conviction and delegations included) can change the approval ratio considerably with a single vote, this has proven be problematic as single individuals not only can decide the fate of entire proposals but also introduce a big voting bias as future voters might follow the new trend blindly without realizing it was set by a single voter instead of the entire community.

Here I propose a `Capped` struct that implements `VoteTally` and wraps `Tally` to check the methods that mutate the internal ayes, nays data of the struct, limiting the mutation so that the approval after the vote doesn't exceed the defined `MaxVoteSlippage` percentage(not sure if slippage would be the right name).

The concept of a whale therefore becomes relative, having the nice side effect(IMO) that early whales might want to keep coming back to review the proposal later on to cast their vote again with an updated conviction(also giving teams the change to improve their proposal and persuade early retractors), or whales would simply have the incentive to vote later on reducing the bias they introduce with their heavy conviction. 

### Whale alert track

The previous method could be gamed with automation spreading funds across multiple accounts. My second proposal would be to have a track in governance that allows citizens to report malicious/anti democratic behavior of a set of accounts(i.e. the accounts controlled by the whale), the reporter provides enough evidence to the general community or to a specific origin that looks after the community's code of ethics(Alliance?) and if approved the reported accounts would lose all of the funds used for the vote that would get transferred to the reporter. The reporter also places a deposit that could be lost in case the accounts are reported unfairly without sufficient proof.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2299858

**Comment by adamsteeber** [comment]
Aside from the question of whether whales should or shouldn't have such power over referenda, this is still incredibly foolish since it wouldn't allow anyone to vote on referenda. Assuming that this code will work and that I understand the intent, the first voter on a referendum would change the approval by infinity percent, therefore no one would ever be able to cast a vote.

So let's say you try to fix that issue by making the `MaxVoteSlippage` a function of the number of votes, with a vertical asymptote at x=1, allowing a first vote. How should that function decrease? What should the slippage threshold be for the second vote? The third vote? The 10th, 100th, or 1000th vote? As you can see, this is a non-trivial configuration.

This concept simply does not work at all.

Regarding the question of whale influence, I truly believe that users with the largest token balances *should* have the most power. If I go out and by $1,000,000 worth of KSM and lock that KSM with 6x conviction on a referendum, you'd better believe I'll want that reflected in the tally no matter what. Users with the largest balance have the most to gain or lose, so in theory they should support proposals that will improve the network and reject proposals that will make it worse. They should also be among the most educated on referenda because of how consequential their votes are; they wouldn't want to vote AYE on a catastrophic referendum that would make their investment go to zero and they wouldn't want to vote NAY on a referendum that will revolutionize and improve the technology.

**Comment by Tomen** [comment]
Despite being a foolish attempt to fix your perceived problem, you fundamentally misunderstand the underlying assumptions of the network. People do not exist as primitives, only tokens. Actors which a large amount of tokens at stake control the network. They have the most to win and lose, so they have the biggest say in the direction of the network.

You cannot find a way around this.

**Comment by olanod** [comment]
Closing for now. I'll revisit the topic of "power balancing" with a different less controversial approach :)

**Pull request closed without merging**
