### PR TITLE
Migrate node authorization pallet to FRAME v2

### PR DESCRIPTION
**Pull request by kaichaosun**
Related to https://github.com/paritytech/substrate/issues/7882 https://github.com/paritytech/substrate/issues/8293

### CODE REVIEW

**Comment by thiolliere** [comment]
## ⚠️ Breaking Change  ⚠️ 

From [checking upgrade guidelines](https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines)

> storages now use PalletInfo for module_prefix instead of the one given to `decl_storage`: use of this pallet in `construct_runtime!` needs careful updating of the name in order to not break storage or to upgrade storage (moreover for instantiable pallet). If pallet is published, make sure to warn about this breaking change.

So users of the pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed depending on the configuration of the pallet.

**Review by thiolliere — APPROVED** [review]
looks good to me.

**Review by ascjones — APPROVED** [review]
LGTM. Can you confirm the metadata pre and post migration is the same?

**Comment by kaichaosun** [comment]
@ascjones Here is the diff: https://www.diffchecker.com/spxo73UK
The difference is expected, which is a small refactor and @thiolliere also mentioned in the comments.

**Pull request merged**
