### PR TITLE
[fix lint warnings: Uniques pallet] fix clippy::missing_docs_in_private_items warnings

### PR DESCRIPTION
**Pull request by sacha-l**
This PR fixes 6 out of the 8 lint warnings emitted by the missing_docs_in_private_items lint in the Uniques pallet by adding docs to the relevant types. The remaining 2 warnings have to do with the outer macro pattern I believe and may need to be addressed as a separate task (cc @sam0x17):

```sh
warning: missing documentation for a module
   --> frame/uniques/src/lib.rs:441:12
    |
441 |     #[pallet::call]
    |               ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_docs_in_private_items
    = note: requested on the command line with `-W clippy::missing-docs-in-private-items`

warning: missing documentation for an associated function
   --> frame/uniques/src/lib.rs:280:29
    |
280 |     #[pallet::generate_deposit(pub(super) fn deposit_event)]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_docs_in_private_items
```

This is part of an ongoing effort from the https://github.com/orgs/paritytech/teams/devrel team to improve developer experience.

### CODE REVIEW

**Review by jsidorenko — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Why do we need docs on private things?

**Comment by aaronbassett** [comment]
> Why do we need docs on private things?

Adding docs to public items should be our priority, but we should also try and document the private items because we frequently tell folks to "read the code" when it comes to learning Substrate.

If we were only directing people to the rustdocs then completely agree that we would only **need** to document those elements which make up the public interface—although having the private items documented certainly wouldn't hurt _us_—but as we're explicitly directing people to read the code too, then we really should try to ensure that all of the code is documented.

**Comment by sacha-l** [comment]
bot merge

**Comment by sam0x17** [comment]
> Why do we need docs on private things?

tooltips in RA when people are poking around. I actually document all my private items across the board in my crates, for my own sanity.

**Review by sam0x17 — APPROVED** [review]

**Comment by sacha-l** [comment]
bot merge

**Comment by sacha-l** [comment]
@sam0x17  - can you ask the bot nicely to merge ? I don't have authorization 🙈

**Comment by sam0x17** [comment]
> @sam0x17 - can you ask the bot nicely to merge ? I don't have authorization see_no_evil

looks like cumulus and zombienet are still failing

**Comment by jsidorenko** [comment]
bot merge

**Comment by ggwpez** [comment]
bot rebase

**Pull request merged**
