### PR TITLE
Fuse the import queue receiver

### PR DESCRIPTION
**Pull request by tomaka**
cc https://github.com/paritytech/substrate/issues/6871

Avoids a panic if the executor decides to drop the task.

### CODE REVIEW

**Comment by tomaka** [comment]
> can you expand on why the task is being dropped by the executor?

I have no idea

**Comment by mxinden** [comment]
In that case wouldn't merging this pull request rather hide the underlying issue instead of fixing it?

**Comment by tomaka** [comment]
I did this a bit more properly.

It is possible that, on node shutdown, by a huge coincidence, the background import queue task gets shut down while the network worker is about to call `poll_actions`. In other words, this PR does fix a rare but potentially legitimate problem.

It doesn't explain https://github.com/paritytech/substrate/issues/6871, but it might lead to the error being different the next time, which will give us more clues.

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
