### PR TITLE
nix: substrate depends on openssl

### PR DESCRIPTION
**Pull request by gilescope**
I noticed if I didn't do this I sometimes hit compile errors so we must depend on openssl at the moment.

### CODE REVIEW

**Comment by burdges** [comment]
Interesting, maybe ring could replace openssl in some dependency.

**Review by bkchr — APPROVED** [review]

**Comment by gilescope** [comment]
I'd certainly trust rustls given that google's security people are keen on using that inside curl. 
All the usages of openssl are from `jsonrpc-client-transports`.

**Comment by gilescope** [comment]
(Hopefully jsonrpsee will be dependent on rustls.)

**Comment by niklasad1** [comment]
> (Hopefully jsonrpsee will be dependent on rustls.)

Yes, it is currently at least :)

**Review by niklasad1 — APPROVED** [review]

**Review by andresilva — APPROVED** [review]

**Comment by andresilva** [comment]
bot merge

**Comment by andresilva** [comment]
bot merge force

**Pull request merged**
