### PR TITLE
Remove Clone bound on specialization in TestNetFactory

### PR DESCRIPTION
**Pull request by gterzian**
In support of https://github.com/paritytech/polkadot/pull/202

### CODE REVIEW

**Comment by gterzian** [comment]
@rphmeier Looks like we might also want to make `Block` an item on the testnet factory, because for example `PolkadoProtocol` implements `NetworkSpecialization` but not with the test block... What do you think?

**Comment by gterzian** [comment]
Ok so the issue that I think I am running into is the following:

TestNetFactory as an item `type Specialization: NetworkSpecialization<Block> + SpecializationFactory;`, where `Block` is `test_client::runtime::Block`. 

However, we want to plug in any NetworkSpecialization<B: BlockT>, for example `Specialization<Block> for PolkadotProtocol` where `Block` is `polkadot_primitives::Block`. 

Any ideas on how to do that? 

The error I am currently getting at https://github.com/paritytech/polkadot/pull/202 is 

```
 the trait `substrate_network::specialization::NetworkSpecialization<sr_primitives::generic::Block<sr_primitives::generic::Header<u64, polkadot_primitives::BlakeTwo256, sr_primitives::generic::DigestItem<substrate_primitives::H256, substrate_primitives::ed25519::Public, substrate_primitives::ed25519::Signature>>, substrate_network::test::Extrinsic>>` is not implemented for `PolkadotProtocol`
```

**Comment by gterzian** [comment]
Ok looks like I can fix the `test_client::runtime::Block` on the polkadot side with compiler flags. 

It still looks like removing the `Clone` bound is a good idea, otherwise we'll have to make the entire `PolkadotProtocol` `Clone` as well... 

Ready for review.

**Comment by gterzian** [comment]
Should this target `master` or `polkadot-master`? It's meant to support https://github.com/paritytech/polkadot/pull/202

**Comment by arkpar** [comment]
`master` first. And then it can be cherry-picked into `polkadot-master` if needed.

**Comment by rphmeier** [comment]
The goal of polkadot-master is just to have a stable commit for (now less-unstable) APIs that Cumulus needs.

**Pull request merged**
