### PR TITLE
Try to remove the caching from the build

### PR DESCRIPTION
**Pull request by pepyakin**

### CODE REVIEW

**Comment by gavofyork** [comment]
would be nice to prefetch those downloads.

**Comment by pepyakin** [comment]
if I understand it correctly, It looks like it's faster to download them directly rather than from the cache.

**Comment by gavofyork** [comment]
if they can be made available in the docker itself, then it really ought to be faster...

**Comment by gavofyork** [comment]
this won't be so great for office internet...

**Pull request merged**
