### PR TITLE
Update documentation for uniques (This PR renames classes and instances to collections and items in the Uniques pallet in order to follow the commonly accepted NFTs terminology.)

### PR DESCRIPTION
**Pull request by simonsso**
The documentation was outdated after merge of #11389

Using the widely spread term collections and item instead of the previous class and instance.

### CODE REVIEW

**Comment by jsidorenko** [comment]
Doesn't the phrase `an asset item` look weird?
I would suggest checking the Readme file of the new NFTs pallet and taking the copy from here. https://github.com/paritytech/substrate/blob/master/frame/nfts/README.md

**Comment by simonsso** [comment]
> Doesn't the phrase `an asset item` look weird?

Ehh maybe ... looks ok to me but I am (1) a software developer and (2) not a native speaker, so anyone who masters the art of writing for humans may help.

**Review by jsidorenko — APPROVED** [review]

**Review by gilescope — APPROVED** [review]

**Comment by jsidorenko** [comment]
bot merge

**Comment by jsidorenko** [comment]
@simonsso could you pls merge master into your branch?

**Comment by jsidorenko** [comment]
bot merge

**Pull request merged**
