### PR TITLE
Fix escaping of the wasm file path

### PR DESCRIPTION
**Pull request by DemiMarie-parity**
This correctly escapes the wasm file path.

### CODE REVIEW

**Comment by bkchr** [comment]
Can you please explain what this fixes and what the error is?

**Comment by DemiMarie-parity** [comment]
@bkchr The problem would appear if the wasm file path contained a double quote and/or backslash.  Using `{:?}` avoids this problem, since its result on `&str` is valid Rust syntax no matter what the `str` contains.

**Comment by DemiMarie-parity** [comment]
@bkchr the path does not need to be escaped before it can be used as a file name, but it does need to be escaped to be used as a string literal.

**Comment by bkchr** [comment]
> @bkchr the path does not need to be escaped before it can be used as a file name, but it does need to be escaped to be used as a string literal.

Yeah that is right, however your current solution is not correct and I will not accept it. We can do the following:
```
fn wasm_binary_path_escaped(&self) -> String {
    self.0.display().to_string().escape_default().to_string()
}

fn wasm_binary_path(&self) 0> &Path {
    &self.0
}
```

Than we have it correct.

**Pull request merged**
