### PR TITLE
frame/benchmarking: baseline weights independent of complexity params

### PR DESCRIPTION
**Pull request by dharjeezy**
remove complexity  `i` param as  described in this issue #10638

Polkadot address: 12ZNas89oEagaxLVNbpqmvfMxdrGrqN7gJKSpwthTUPZsrku

### CODE REVIEW

**Comment by ggwpez** [comment]
Hi @dharjeezy !  
The `weight.rs` files are calculated from the output of the benchmark results, they are auto-generated.  
It is not possible to just manually modify them.  
  
You would have to change the benchmarks (in baseline.rs) themselves.  
Once this is done, the benchmarking bot can re-calculate the weights.

**Comment by dharjeezy** [comment]
Hello @ggwpez i tried writing the benchmarks by removing the iteration so as to remove the `i` parameter, but i am getting 0 as Weight generated(without the `i` parameter) when i run the benchmarks for addition, subtraction, multiplication, and division.

**Comment by ggwpez** [comment]
> Hello @ggwpez i tried writing the benchmarks by removing the iteration so as to remove the `i` parameter, but i am getting 0 as Weight generated(without the `i` parameter) when i run the benchmarks for addition, subtraction, multiplication, and division.

The compiler probably optimized it out. I suspect this is how we got the bogus value in there in the first place.  
When I have the time later I will try to find a solution.  
Maybe we need to use something slightly more complicated than just `+=`, or write the final result to storage, will see.

**Comment by dharjeezy** [comment]
> > Hello @ggwpez i tried writing the benchmarks by removing the iteration so as to remove the `i` parameter, but i am getting 0 as Weight generated(without the `i` parameter) when i run the benchmarks for addition, subtraction, multiplication, and division.
> 
> The compiler probably optimized it out. I suspect this is how we got the bogus value in there in the first place. When I have the time later I will try to find a solution. Maybe we need to use something slightly more complicated than just `+=`, or write the final result to storage, will see.

Alright. I should hold off on the solution you can come up with so I can implement yh?

**Comment by dharjeezy** [comment]
> > Alright. I should hold off on the solution you can come up with so I can implement yh?
> 
> You can also try to find out how to do it if you want, I will have other issues to work on.

Alright. I will try to. Thanks!

**Comment by ggwpez** [comment]
Still relevant but not going to happen here.

**Pull request closed without merging**
