### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by kianenigma**

### CODE REVIEW

**Comment by pepyakin** [comment]
Due to the recent discussion on riot, I piggybacked on this PR to remove myself from some parts, only leaving the parts where I think I am more or less the only one who deeply understand the code. Also removed @Robbepop from the contracts module.

**Comment by gnunicorn** [comment]
@kianenigma I suppose this needs to be updated to master for the polkadot companion?

**Comment by rphmeier** [comment]
Please remove @DemiMarie-parity from all of the consensus stuff also

**Comment by DemiMarie-parity** [comment]
@rphmeier thank you for mentioning that ― my work has shifted elsewhere.

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
