### PR TITLE
Move EnsureOneOf into the dispatch.rs, make an interface more general

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
polkadot companion: https://github.com/paritytech/polkadot/pull/4405
skip check-dependent-cumulus

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Review by KiChjang — APPROVED** [review]

**Comment by KiChjang** [comment]
Well, this is a bit awkward... the cumulus companion CI check is failing, because the cumulus PR requires changes from the polkadot companion PR, but the cumulus companion CI check doesn't use the polkadot companion to compile with the cumulus companion, sooo... wat do?

**Comment by Mr-Leshiy** [comment]
@shawntabrizi , @KiChjang do I need to do any update here to fix it ? Or as I understood it is related to the another repositories ?

**Comment by kianenigma** [comment]
the cumulus companion check is a bit broken. I think you are good @Mr-Leshiy.

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
