### PR TITLE
expose transport, peer_info and discovery in sc-network

### PR DESCRIPTION
**Pull request by klbrvik**
## What does it do?

Makes `discovery`, `peer_info` and `transport` mods public in `sc-network`.

## Why?

Makes it easy to develop lightweight binaries that want to become of libp2p swarm and use libp2p's `NetworkBehaviour`s.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2827727

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2827735

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2828435

**Review by altonen — APPROVED** [review]

**Review by dmitry-markin — APPROVED** [review]

**Comment by bkchr** [comment]
@klbrvik can we move on with this?

**Comment by klbrvik** [comment]
@bkchr some CI checks were failing, as soon as they pass I'm moving from `Draft` to `Ready for review`

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
