### PR TITLE
[assets tx payment] configurable default asset

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
- [X] **Description:** 
 
Allows user to configure default tx payment asset. See https://github.com/paritytech/substrate/discussions/12055

  - Is there something left for follow-up PRs?
Seems benchmarking can be improved, so not sure I have examples how to do multi assets in this repo (so it should be tested in cumulus).

cumulus companion:https://github.com/paritytech/cumulus/pull/1572

- [ ] **Labels:** You labeled the PR appropriately if you have permissions to do so:
  - [ ] `A*` for PR status (**one required**)
  - [ ] `B*` for changelog (**one required**)
  - [ ] `C*` for release notes (**exactly one required**)
  - [ ] `D*` for various implications/requirements
  - [ ] Github project assignment
- [ ] **Related Issues:** Related https://github.com/ComposableFi/composable/pull/1456
- [ ] **2 Reviewers:** You asked at least two reviewers to review. If you aren't sure, start with GH suggestions.
- [x] **Style Guide:** Your PR adheres to [the style guide]
- [X] **Runtime Version:** You bumped the runtime version if there are breaking changes in the **runtime**. No breaking runtime, only compile time.
- [X] **Docs:** You updated any rustdocs which may need to change.
- [ ] **Polkadot Companion:** Has the PR altered the external API or interfaces used by Polkadot?
  - [ ] If so, do you have the corresponding Polkadot PR ready?
  - [ ] Optionally: Do you have a corresponding Cumulus PR?

### CODE REVIEW

**Comment by ggwpez** [comment]
cc @shawntabrizi

**Comment by dzmitry-lahoda** [comment]
seems like other prs also fail with 
```
     Compiling pallet-contracts v4.0.0-dev (/builds/parity/mirrors/substrate/frame/contracts)
  error: generic arguments must come before the first constraint
     --> /builds/parity/mirrors/substrate/frame/uniques/src/lib.rs:114:4
      |
  113 |             Success = Self::AccountId,
      |             ------------------------- constraint
  114 |             Self::Origin,
      |             ^^^^^^^^^^^^
  115 |             Self::CollectionId,
      |             ^^^^^^^^^^^^^^^^^^ generic arguments
      |
  help: move the constraint after the generic arguments
      |
  112 |         type CreateOrigin: EnsureOriginWithArg<Self::Origin, Self::CollectionId, Success = Self::AccountId>;
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  warning: ignoring -C extra-filename flag due to -o flag
  warning: `pallet-uniques` (lib) generated 1 warning
  error: could not compile `pallet-uniques` due to previous error; 1 warning emitted
  warning: build failed, waiting for other jobs to finish...
```

**Comment by ggwpez** [comment]
bot rebase

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/parachain-technical-summit-next-steps/51/21

**Comment by dzmitry-lahoda** [comment]
i will rebase soon to latest master

**Comment by dzmitry-lahoda** [comment]
Fixed merge conflicts and updated to latest master on my branch. Not sure, seems there is no way to reopen PR with stale bot. Only to create new one. 

Here is updated branch https://github.com/dzmitry-lahoda-forks/substrate/tree/dz/assets-tx-config

**Pull request closed without merging**
