### PR TITLE
pallet-utility: Only disallow the `None` origin

### PR DESCRIPTION
**Pull request by bkchr**

### CODE REVIEW

**Review by dvdplm — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Could add a test - but not a must.  
Cumulus check is being fixed here https://github.com/paritytech/cumulus/pull/1613/

**Comment by bkchr** [comment]
> Could add a test - but not a must.

https://github.com/paritytech/substrate/pull/12321 already contained tests for ensuring that `None` is not allowed.

**Comment by xlc** [comment]
Can we have this merged and back ported. https://github.com/paritytech/substrate/pull/12321 is a regression that breaks the ability for governance to use batch call.

That also means we need more tests.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/security-vulnerability-executing-unauthorized-xcm-messages/553/4

**Comment by ntn-x2** [comment]
@bkchr I see that this PR has not been backported into 0.9.29. Would that be possible?

**Comment by bkchr** [comment]
@ntn-x2 done.

**Pull request merged**
