### PR TITLE
Ignore peers that are not synced during sync status check

### PR DESCRIPTION
**Pull request by nazar-pc**
This addresses my comment from https://github.com/paritytech/substrate/pull/11547/files#r889214514

Basically there is no reason to take into account peers that have best number below ours.

### CODE REVIEW

**Comment by bkchr** [comment]
Hmm, how often do you really have 7000 syncing nodes? I'm not sure if that maybe opens some other attack vector. @arkpar WDYT?

**Comment by nazar-pc** [comment]
We're aiming for network with hundreds of thousands of nodes, so I guess the answer is... all the time? With over 25k of consensus nodes during non-incentivized testnet I can totally expect inrush of thousands of non-synced nodes into the network after some announcement and this is a potential attach vector that will cause extra forking.

**Comment by nazar-pc** [comment]
The way I see this, there isn't any benefit in looking at peers that are obviously not synced in determining whether local peer is synced, it can't possibly add any useful context, but it may hurt in specific cases.

**Review by bkchr — APPROVED** [review]

**Comment by arkpar** [comment]
Makes sense to me

**Comment by nazar-pc** [comment]
Closing as obsolete after https://github.com/paritytech/substrate/pull/11817

**Pull request closed without merging**
