### PR TITLE
Realize tracing rotation of  substrate

### LINKED ISSUE #9079: How to realize tracing log output to file and log rotation？
Our chainx is developed based on substrate, but for logs, we want to achieve:
- Logs are output to the console and file at the same time
- Log file segmentation

Similar to：

~~~
├── log
│   ├── chainx.log.2021-06-04
│   ├── chainx.log.2021-06-05
│   ├── chainx.log.2021-06-06
│   ├── chainx.log.2021-06-07
│   ├── chainx.log.2021-06-08
│   ├── chainx.log.2021-06-09
│   ├── chainx.log.2021-06-10
│   ├── chainx.log.2021-06-11
~~~

Current difficulties:
	[Tracing has been initialized globally by subtrate, so we can't add log rotation to it](https://github.com/paritytech/substrate/blob/master/client/tracing/src/logging/mod.rs#L261)

   ~~~rust
   tracing::subscriber::set_global_default(subscriber.with(profiling))?;
   ~~~

How can we better solve this problem？

### PR DESCRIPTION
**Pull request by AAweidai**
This pr is mainly because I have implemented a simple version of the log segmentation function myself to fixes #9079.

Please correct me.

### CODE REVIEW

**Review by bkchr — COMMENTED** [review]
https://docs.rs/tracing-appender/0.1.2/tracing_appender/rolling/index.html

why isn't that used?

**Comment by AAweidai** [comment]
> https://docs.rs/tracing-appender/0.1.2/tracing_appender/rolling/index.html
> 
> why isn't that used?

Because it does not implement regular log cleaning.

**Comment by bkchr** [comment]
What is regular log cleaning?

**Comment by AAweidai** [comment]
> What is regular log cleaning?

Using the tracing_appender module directly, all the segmented data will be saved. After a period of time, if we don’t need the old logs, we need to clean them up manually. In other words,if we only want to save the logs of the last 30 days, tracing_appender cannot be supported.

**Comment by bkchr** [comment]
I would like to see support for this in upstream and no self made solution.

**Pull request closed without merging**
