### PR TITLE
feat: support custom HostFunctions for NativeElseWasmExecutor

### PR DESCRIPTION
**Pull request by yjhmelody**
We know parachain could not use some host functions in polkadot side. Maybe it is not correct to force all chain use `SubstrateHostFunctions` in `NativeElseWasmExecutor`. 
This PR try to generalize it.
It also keep the same style with `WasmExecutor` that could define all host functions by custom.

BTW, in cumulus side, maybe it could offer a ParachainHostFunctions type.

### CODE REVIEW

**Comment by bkchr** [comment]
You can already provide custom host functions? 

The default Substrate host functions should stay as this is still a Substrate executor.

**Comment by yjhmelody** [comment]
> You can already provide custom host functions?
> 
> The default Substrate host functions should stay as this is still a Substrate executor.

Yeah, So I still  make`SubstrateHostFunctions` be the default type. But if we want to disable some host functions, `NativeElseWasmExecutor` could not support it, but `WasmExecutor ` could.

**Comment by bkchr** [comment]
> Maybe we do not want to use `SubstrateHostFunctions` but want to use custom functions in `NativeElseWasmExecutor` in the future.

Do you speak here about some concrete plan that you got? Or is this pr just some potential thing that may at some point some may needs?

**Comment by yjhmelody** [comment]
> > Maybe we do not want to use `SubstrateHostFunctions` but want to use custom functions in `NativeElseWasmExecutor` in the future.
> 
> 
> 
> Do you speak here about some concrete plan that you got? Or is this pr just some potential thing that may at some point some may needs?

Have no concrete plan now.
But the concrete host functions are useful for parachain too？

**Comment by bkchr** [comment]
> But the concrete host functions rather than substrate host function are useful for parachain too？

In what way?

**Comment by yjhmelody** [comment]
> In what way?

Maybe some projects can avoid using host functions prohibited by polkadot in the early development, or when a project supports both WasmExecutor and NativeElseWasmExecutor, some people want their host functions to be consistent.

You are right, for now, there may only be a clear benefit if you need to override or disable host functions

**Comment by bkchr** [comment]
Overriding is also supported. Just add the function to the extra host functions. 

I'm going to close this for now. Thank you anyway.

**Pull request closed without merging**
