### PR TITLE
Fix storage layer limit

### PR DESCRIPTION
**Pull request by athei**
Fixup for #10808

We cannot use atomics to store the storage layer counter because of the native runtime: In the native runtime multiple different calls into the runtime happen concurrently on the same memory. In the wasm case every call gets its own wasm instance with its own memory as it should be.

Storage access works as global data because the client uses thread local data for it.

### CODE REVIEW

**Comment by xlc** [comment]
can we use atomics for wasm runtime only?

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
> can we use atomics for wasm runtime only?

AFAIK yes, but in this case, there is probably not a significant overhead between the two options here. I think using overlay storage is fine, and it will never commit anything to the runtime since it always resets.

**Review by kianenigma — APPROVED** [review]

**Comment by athei** [comment]
Calling into the host should still be way slower than using atomics or environmental. But in this case it doesn't matter because it isn't a function that is called a lot of times.

I think a proper solution would be to pick up [this PR](https://github.com/paritytech/substrate/pull/11155) and add some `thread_local!` storage in case of native. I might do that soon.

**Comment by athei** [comment]
I don't get why the companion is failing. It seems unrelated. Was something missing from https://github.com/paritytech/substrate/pull/11136 ?

**Pull request merged**
