### PR TITLE
[ci] Make travis verbose to prevent timeout on git pull

### PR DESCRIPTION
**Pull request by gnunicorn**

### CODE REVIEW

**Comment by gnunicorn** [comment]
@dvdplm yes and with our huge parity-repo this happens quite easily. Unfortunately, this doesn't fix it :( .

**Comment by dvdplm** [comment]
> huge parity-repo

Maybe reducing the cloning depth could help? https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth

**Comment by gnunicorn** [comment]
@dvdplm generally yes, however that pull happens within cargo, and I am unaware we can configure that.

However, trying [the `travis_wait` command](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) you pointed out.

**Comment by gnunicorn** [comment]
currently broken because of #553 and the now broken dependencies.

**Comment by gnunicorn** [comment]
deprecated in favor of #568.

**Pull request closed without merging**
