### PR TITLE
Alternative sysvar setup for Windows

### PR DESCRIPTION
**Pull request by Swader**
The command line setup did not work for me. This adds instructions and images on how to do it through the UI.

### CODE REVIEW

**Comment by Swader** [comment]
[clabot:check]

**Comment by kianenigma** [comment]
Thanks for the PR!

I wonder: 
- Why would the original approach not work? is there a common pitfall? 
- I am not against having this additional section, but if we do, the images should preferably be placed in one file or a way to render while taking less vertical space. I think all of them can fit in one image with _steps_.

**Comment by shawntabrizi** [comment]
@Swader I think the better solution is to move these specific instructions into the Substrate Developer Hub?

I too am interested to know why these steps do not work. I wrote them having tested on my personal windows machine and actually got a few people to install on their windows machine too with the same instructions.

**Comment by Swader** [comment]
@kianenigma I agree the rendering is... less than pretty. Wasn't sure how else to do it without breaking user flow (i.e. see this _yet another document_).

@shawntabrizi  They did not work for me. See image below. This is the error I get for every one of the lines in the instruction paragraph. @lsaether confirmed some others saw this problem too.

image

**Comment by bkchr** [comment]
You need to use powershell

**Comment by Swader** [comment]
The readme specifically references CMD, and in CMD (and Git Bash) all instructions up until this point work. So this should be specifically mentioned then.

**Comment by shawntabrizi** [comment]
@Swader can you make this PR that change to specifically use PowerShell rather than adding the extra images?

Or do you think that is not sufficient?

**Comment by Swader** [comment]
It should be sufficient. Let me test and if so, I'll make the PR update.

**Comment by Swader** [comment]
Powershell works fine

**Pull request merged**
