### PR TITLE
Remove node-runtime dependency from node-rpc.

### PR DESCRIPTION
**Pull request by ethernomad**
The node-runtime dependency is not used and increases build times.

### CODE REVIEW

**Comment by bkchr** [comment]
Please commit the `Cargo.lock` as well.

**Comment by ethernomad** [comment]
Commited Cargo.lock

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
