### PR TITLE
contracts: Replace cargo feature `unstable-interface` with config

### PR DESCRIPTION
**Pull request by athei**
Hiding a behavior changing config behind a cargo feature wasn't a good idea. We all know how easy this feature can be flipped on due to unification. Also, feature are just flat out annoying and we want to avoid them when possible.

This is why we replace the `unstable-interface` feature with a config knob in this PR. Gives the runtime much more confidence that this feature is actually off. The only grumble that remains is that we need to enable it to perform runtime benchmarks. But at least we don't introduce another config knob with room for error. This also makes sure that the tests for unstable interfaces are always run and stabilization is merely removing one attribute.

polkadot companion: https://github.com/paritytech/cumulus/pull/1916

### CODE REVIEW

**Review by agryaznov — APPROVED** [review]
LGTM

**Review by xermicus — APPROVED** [review]

**Comment by athei** [comment]
bot merge

**Comment by agryaznov** [comment]
> You called your cumulus companion "polkadot companion".

same here 🙈

**Comment by athei** [comment]
And it still worked. Weird :)

**Pull request merged**
