### PR TITLE
Add benchmarking support for digest items

### PR DESCRIPTION
**Pull request by notlesh**
This PR provides a mechanism for pushing digest items into the `benchmark overhead` and `benchmark extrinsic` pipelines. It is a potential fix for #12142. The rationale for it is thoroughly described there, but briefly: this solves the dependency problem where an inherent requires a pre-runtime digest to be present.

Note that I tested a similar fix through Moonbeam against an older version of Substrate (`v0.9.26`) but have not tested the code in this PR. I'll be happy to do so if there is support for it in the first place.

### Companions
 - [X] `polkadot`: https://github.com/paritytech/polkadot/pull/5958
 - [X] `cumulus`: not needed
 - [ ] `nimbus`: not required, but could be used to demonstrate that this works

### TODO
 - [X] no-op companion PRs
 - [ ] test - can be accomplished by implementing in [nimbus](https://github.com/PureStake/nimbus/) which is where this all started
 - [ ] any documentation required (minor breaking changes)

polkadot companion: https://github.com/paritytech/polkadot/pull/5959

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Nice.  

It still needs companions and a fmt. In the future we can think about putting all of these args in a config struct to have fewer companion requirements.

**Comment by notlesh** [comment]
I am working on implementing `benchmark overhead/extrinsic` in nimbus because I'll be able to test this change there (the problematic inherent/digest pair lives in that repo).

However, I believe this is mergeable as-is.

**Comment by notlesh** [comment]
Cumulus doesn't need a companion PR, but it does need build against my polkadot companion. How can we do that?

**Comment by ggwpez** [comment]
> I believe this will build if CI will run against my polkadot companion (am I missing something?)

Looks like it. But it also needs a Cumulus comp, since we also expose these commands there…

**Comment by notlesh** [comment]
> > I believe this will build if CI will run against my polkadot companion (am I missing something?)
> 
> Looks like it. But it also needs a Cumulus comp, since we also expose these commands there…

I don't think it does unless it's compiling a branch other than `master` (I can't tell from the CI log). Cumulus master looks like it doesn't implement `BenchmarkCmd::Overhead` or `Benchmark::Extrinsic`.

It looks to me like the CI failure here is coming out of polkadot, example:

```
/builds/parity/mirrors/substrate/extra_dependencies/polkadot/cli/src/command.rs:555:14
1950    |
1951555 | ...                   cmd.run(client.clone(), inherent_data, &ext_factory)
1952    |                           ^^^ --------------  -------------  ------------ supplied 3 arguments
1953    |                           |
1954    |                           expected 4 arguments
```

Is `cumulus` not being built against my polkadot companion?

**Comment by ggwpez** [comment]
bot merge

**Comment by notlesh** [comment]
I recreated my companion PR from my personal repo so I could enable edits from maintainers. Sorry for the mess...

**Comment by bkchr** [comment]
bot merge

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
