### PR TITLE
[fix lint warnings: Uniques pallet] fix clippy::doc_markdown warnings

### PR DESCRIPTION
**Pull request by sacha-l**
This PR fixes the 481 warnings emitted by the `doc_markdown` lint for the Uniques pallet. 

**Note:** These lint warnings should no longer happen for newly generated weight files thanks to #14535. 

This is part of an ongoing effort from the https://github.com/orgs/paritytech/teams/devrel team to improve developer experience.

### CODE REVIEW

**Comment by ggwpez** [comment]
bot bench $ pallet dev pallet_uniques

**Review by jsidorenko — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
@sacha-l can you please run the linter again?  
The weights got updated by the bot now.

**Comment by ggwpez** [comment]
>Ran it locally - there's still some warnings:

What command are you running?  
If you want to have this also working in the future then we need to integrate it into the CI, otherwise someone will silently break it.  
Updating these files manually does not really work, since they auto-generated, so any change will be over-written eventually.

**Comment by sacha-l** [comment]
> What command are you running?

`cargo clippy -- -A clippy::all -W clippy::doc_markdown --no-deps` 

> Updating these files manually does not really work, since they auto-generated, so any change will be over-written eventually.

Yes - shouldn't we update the template with the backticks?

**Comment by ggwpez** [comment]
bot bench $ pallet dev pallet_uniques

**Comment by sacha-l** [comment]
bot merge

**Pull request merged**
