### PR TITLE
Updating shell.nix nightly

### PR DESCRIPTION
**Pull request by gilescope**
The 2022-02-10 nightly can't build a dep we're pulling in:

There's a sig that returns `impl IntoIterator<Item = (&'static str, OsString)>` and an Option is being returned as the concrete implementation of the iterator but it's incorrectly not allowing a `?` in the method.

### CODE REVIEW

**Review by andresilva — APPROVED** [review]

**Review by ggwpez — COMMENTED** [review]
Does not work for me…  
```pre
$ nix-shell --run "cargo check --workspace --all-targets --all-features"

error[E0428]: the name `can_build_child_tree` is defined multiple times
    --> utils/frame/remote-externalities/src/lib.rs:1195:8
     |
1102 |     async fn can_build_child_tree() {
     |           ------------------------- previous definition of the value `can_build_child_tree` here
...
1195 |     async fn can_build_child_tree() {
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^ `can_build_child_tree` redefined here
     |
     = note: `can_build_child_tree` must be defined only once in the value namespace of this module

    Checking beefy-gadget v4.0.0-dev (/home/vados/substrate/client/beefy)
warning: unused import: `std::env`
  --> frame/support/test/tests/construct_runtime_ui.rs:18:5
   |
18 | use std::env;
   |     ^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `frame-support-test` (test "construct_runtime_ui") generated 1 warning
For more information about this error, try `rustc --explain E0428`.
error: could not compile `remote-externalities` due to previous error
warning: build failed, waiting for other jobs to finish...
```

A CI check would help to spot these regressions.

**Comment by gilescope** [comment]
Good spot. That test is unlikely to pass on anyone else's machine than his. I don't think he intended to commit that version. I've removed it.

**Comment by ggwpez** [comment]
It somehow still fails… I will open a CI ticket, maybe we can get a check?  
```pre
error: environment variable `SNAP` not defined
    --> frame/state-trie-migration/src/lib.rs:1587:36
     |
1587 |             OfflineConfig { state_snapshot: env!("SNAP").to_owned().into() },
     |                                             ^^^^^^^^^^^^
     |
     = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: environment variable `WS_API` not defined
    --> frame/state-trie-migration/src/lib.rs:1589:16
     |
1589 |                 transport: std::env!("WS_API").to_owned().into(),
     |                            ^^^^^^^^^^^^^^^^^^^
     |
     = note: this error originates in the macro `std::env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: environment variable `SNAP` not defined
    --> frame/state-trie-migration/src/lib.rs:1590:26
     |
1590 |                 state_snapshot: Some(env!("SNAP").to_owned().into()),
     |                                      ^^^^^^^^^^^^
     |
     = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Review by bkchr — APPROVED** [review]

**Comment by gilescope** [comment]
bot merge

**Comment by gilescope** [comment]
bot merge

**Pull request merged**
