### PR TITLE
Feat executive final_checks

### PR DESCRIPTION
**Pull request by honeywest**
add header.extrinsics_root().check_equal(&extrinsics_root);

### CODE REVIEW

**Comment by bkchr** [comment]
Can you please give any description why you need this?

**Comment by honeywest** [comment]
Code comparison.
above:
header.state_root().check_equal(&storage_root);

**Comment by bkchr** [comment]
> Code comparison.
> above:
> header.state_root().check_equal(&storage_root);

I know this. What you mean by code comparison?

**Comment by honeywest** [comment]
Code consistency  or Symmetry

**Comment by bkchr** [comment]
I thought again about this change and it is not required. The storage root will be different when the extrinsics root is different. Meaning we don't require this.

**Pull request closed without merging**
