### PR TITLE
Load sync states from the chain spec on the light client

### PR DESCRIPTION
**Pull request by expenses**
A follow-up to #7225 and part of https://github.com/paritytech/substrate/issues/6804.

* https://github.com/paritytech/substrate/blob/a9b22d4e901c2633f92fefc6cbfbf1d3a9971ecc/bin/node/cli/res/flaming-fir.json managed to sync to the head of the chain.
* https://github.com/paritytech/substrate/blob/e1180c25423dfe45b8027e331bcf99676424f1a5/bin/node/cli/res/flaming-fir.json does not.

Some questions about the PR that we should:

1. Is there a better way of getting a sync state header to load correctly without all the hacky `allow_missing_parent` code?
2. Is there a better way to debug problems in the code other than replacing errors with panics?
3. How can we best prune the `EpochChanges` tree? See https://github.com/paritytech/substrate/pull/7225#issuecomment-702220812.

### CODE REVIEW

**Comment by expenses** [comment]
>     * https://github.com/paritytech/substrate/blob/a9b22d4e901c2633f92fefc6cbfbf1d3a9971ecc/bin/node/cli/res/flaming-fir.json managed to sync to the head of the chain.
> 
>     * https://github.com/paritytech/substrate/blob/e1180c25423dfe45b8027e331bcf99676424f1a5/bin/node/cli/res/flaming-fir.json does not.

We should probably try and find out what the difference between the two is :thinking:

**Comment by expenses** [comment]
> > ```
> > * https://github.com/paritytech/substrate/blob/a9b22d4e901c2633f92fefc6cbfbf1d3a9971ecc/bin/node/cli/res/flaming-fir.json managed to sync to the head of the chain.
> > 
> > * https://github.com/paritytech/substrate/blob/e1180c25423dfe45b8027e331bcf99676424f1a5/bin/node/cli/res/flaming-fir.json does not.
> > ```
> 
> We should probably try and find out what the difference between the two is thinking

* The first chain spec for commit `a9b22d4e901c2633f92fefc6cbfbf1d3a9971ecc` is for block [`118347`](https://polkadot.js.org/apps/#/explorer/query/118347) which contains a new session and new grandpa authorities.
The second for commit `e1180c25423dfe45b8027e331bcf99676424f1a5` is for block [`198161`](https://polkadot.js.org/apps/#/explorer/query/198161) which seems to be a more regular block.

**Review by cheme — COMMENTED** [review]
I do not know if 'allow_missing_parent' can be avoided, if it can't, it could also think of naming it 'snapshot_syncing' or something that refer to the actual action it is used for.
Still 'allow_missing_parent' is similar to existing 'allow_missing_state' (probably for light client), so maybe that is not a good idea at all place.
Generally loading from a snapshot do not use the same trust assumption, so I do not find this that surprising it is needed (maybe some specific api or trait could make it looks less hacky, I think making code generic may help here but that should be next steps).

**Comment by gnunicorn** [comment]
Closing due to the PR being stale for a while.

**Pull request closed without merging**
