### PR TITLE
clean the interface of supports map

### PR DESCRIPTION
**Pull request by kianenigma**
Cleans some legacy code. We remove the complicated trait that allowed both `Supports` and `SupportMap` to have the same `impl Evaluate`. The former is never needs to be evaluated anyhow. 

Almost certainly insubstantial. The only real code that is being changed is a few less checks in `fn feasibility_check`, but I strongly assert that all of the removed check were totally redundant. I invite any reviewer to challenge about that.

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by emostov — APPROVED** [review]
🏎️

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
Jesus, finally I can merge this. The CI has been super flaky today.

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
