### PR TITLE
Allow to wrap or overwrite low-level tcp-transport.

### PR DESCRIPTION
**Pull request by fixxxedpoint**
Extension of the api of the `sc-service` package that allows to wrap or even overwrite the default tcp-transport that is used by the `sc-network`. It should allow one to add some custom functionality to low-level networking layer, e.g. manual back-pressure on the network layer, additional logging/sniffing, etc.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2731424

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2731475

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2731509

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2731525

**Review by dmitry-markin — APPROVED** [review]
LGTM, thanks!

As a note, we are about to add QUICK support, so this may change to accept different transport builders for TCP and UDP.

**Comment by altonen** [comment]
Can you give a more concrete example what you need this for?

**Comment by fixxxedpoint** [comment]
> Can you give a more concrete example what you need this for?

Limiting bandwidth of incoming connections/streams.

**Comment by fixxxedpoint** [comment]
> I'm against this change, here's why:
> 
>     1. backpressure for incoming connections should be handled by the notification/request-response protocol implementations by not polling the substream. Having a wrapper over the transport is IMO not in line with our long-term vision. I can't comment on the specifics because your example is too vague.
> 
>     2. exposing the details of the networking library used by `sc-network` all the way to `sc-service` is definitely not line with our long-term visions. We would rather see more decoupling between `sc-network` and `libp2p`, not more. We'll be publishing work soon that would allow rather trivially exercise backpressure on notification protocols. If that is not sufficient for your needs, then I would suggest forking Substrate and implementing this for your fork. If you can explain in more detail what is it that you wish `sc-network` provided, we can research if it's possible to do that without exposing the details of `libp2p`.

Goal: don't let a peer to flood my node with too many messages, create a backpressure on per connection basis. I want my solution to be implemented within node itself, not by means of some reverse proxy, etc.

Used definition of backpressure: when a peer is actively sending too many messages, TCP layer (or some other transport layer) is not accepting new messages from such peer, no new messages from such peer are buffered anywhere, and it shouldn't make other connections/protocols starve (probably this is OS dependent or a completely different story in case of QUIC). TCP probably notifies such peer by not sending acknowledgements or actively changing connection params.

Discussion related with your points:
1. not polling a substream of a notification protocol won't help with anything since messages there just land on a `UnboundedChannel` (or perhaps you meant something else or it already changed?). `request-response` protocols look better for the handling/dropping part, but I don't see how can I use them to create a backpressure on per-peer TCP level actually. Additionally, I don't know how they can be used from the level of `sc-service::build_network` API. Our protocol is already implemented using `notifications` mechanism - I didn't test its `request/response` version.

2. I don't like this change either ;). It's made to be just a minimal set of changes required to achieve my goal, originally designed to be stored only in our fork (to be easy to maintain with future mergin). I can easily decouple it from `libp2p`, introduce some more cleaner API. What I like about it is that it gives me full control over TCP layer. Without it, if I want to use different mechanism, I need to search through huge portion of codebase and look for any `UnboundedChannels` (or some other things) or use some memory profiling tool to figure if some protocol or its new version does exactly what I need and don't `leak` messages. Where can I find some description/discussion about on-going changes to `notification` protocols?

**Comment by altonen** [comment]
Firstly I agree with you on the point about `UnboundedChannel`s and we're putting effort into getting rid of them but it takes time with all other stuff that is going on.

When I referred to not polling the substream, I was indirectly referring to the changes we'll be publishing soon (sorry for confusion). Right now it doesn't make sense because of all the unbounded channels but after that change (with some future refactoring) it would be possible to exercise backpressure in both directions. I wrote [this document](https://hackmd.io/cr8haaYmQeSYAU6PU8b4eQ) a while ago which defines the high-level overview of the changes we're making in the notifications code. I don't know how useful you'll find it w.r.t. your troubles but the long-term goal is to enable backpressure on per-substream basis.

All that said, I don't think per-connection backpressure is on the "near future" roadmap but it is something that we've internally discovered useful and I'm looking into it (not actively). If you want that right now, I would say those changes would have to be made in libp2p. You can look into the yamux implementation inside libp2p which is responsible for handling the connection with the remote peer and whether it's feasible to implement backpressure for that component. If it's too much work, I'd look into implementing your protocols using the request-response protocol. Yamux already defines the maximum amount of substream you can have per connection and the `sc-network` will provide the ability to exercise backpressure for those substreams.

In closing, considering the state in which `sc-network` is now and all the open issues we have, we'd have to reserve the right to remove this feature at any time so this would be considered unstable and I'd wager it might be removed in the future with no replacement but I'm not 100% certain of that. Currently my personal opinion is that any change that pertains to libp2p, irrespective of how high or low-level it is, would be considered unstable just so we have free hands to refactor `sc-network` without tying our hands too much. That's why I would say it makes more sense to keep it in your fork if you need this feature and what we can provide through `sc-network` is not enough. Is there a reason why this change needs to be upstreamed to Substrate in the first place?

**Comment by bkchr** [comment]
Going to close this based on the comment of @altonen

**Pull request closed without merging**
