### PR TITLE
Removing a trailing `MaxSegmentLength`

### PR DESCRIPTION
**Pull request by georgesdib**
Cleaning up a left over variable after #9760

### CODE REVIEW

**Review by gilescope — APPROVED** [review]
LGTM

**Review by KiChjang — APPROVED** [review]

**Comment by KiChjang** [comment]
bot merge

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@georgesdib please merge master

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
