### PR TITLE
Rename `ModuleToIndex` to `PalletRuntimeSetup`

### PR DESCRIPTION
**Pull request by bkchr**
Besides the renaming it also adds support getting the name of a pallet
as configured in the runtime.

# Migrating changes

For anyone coming here to migrate its old to the new code:

1. Replace all occurrences of `ModuleToIndex` to `PalletRuntimeSetup`.
2. Replace any usage of `module_to_index` with `index`.

polkadot companion: https://github.com/paritytech/polkadot/pull/1743

### CODE REVIEW

**Comment by bkchr** [comment]
I hate my naming. @shawntabrizi or anyone else has a better idea, please say it

**Comment by shawntabrizi** [comment]
I would call this "PalletInfo"?

**Review by thiolliere — APPROVED** [review]
Looks good to me,
I like the name PalletRuntimeSetup as it contains the information given by the setup of the runtime. But I'm ok with PalletInfo. Maybe PalletSetup is better ?
I feel "PalletIdentity"/"PalletId" is too vague somehow :-) but anyway fine.

**Comment by kianenigma** [comment]
➕  `PalletId `

**Comment by bkchr** [comment]
Renamed it to `PalletInfo`

**Comment by bkchr** [comment]
@kianenigma and @shawntabrizi please review :D

**Review by shawntabrizi — APPROVED** [review]

**Comment by gnunicorn** [comment]
bot merge

**Pull request merged**
