### PR TITLE
release `sp-core 7.0.0` and `sp-runtime 7.0.0`

### PR DESCRIPTION
**Pull request by niklasad1**
Needed by subxt because `sp-core` recently bumped  `parity-util-mem` which has a guard against multiple versions which makes very difficult to use any substrate related dependencies in subxt without patching all substrate related crates.

I used to the `subpub tool` to bump the crates and related crates.

polkadot companion: https://github.com/paritytech/polkadot/pull/6290
cumulus companion: https://github.com/paritytech/cumulus/pull/1881

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
I am not the best one to review this but LGTM.

**Review by bkchr — APPROVED** [review]

**Comment by niklasad1** [comment]
@ascjones shall wait with this PR until https://github.com/paritytech/substrate/issues/12658 is merged?

Otherwise, we would have to make two releases.

**Comment by ascjones** [comment]
> @ascjones shall wait with this PR until #12658 is fixed?
> 
> Otherwise, we would have to make two releases.

Trouble is, I don't think that https://github.com/paritytech/substrate/issues/12658 is going to be done in the immediate future: I don't have time at the moment to do it personally.

So in order to unblock downstream releases I'm leaning towards merging this and doing a release. WDYT?

**Comment by niklasad1** [comment]
> So in order to unblock downstream releases I'm leaning towards merging this and doing a release. WDYT?

all right, let's release it then

**Comment by niklasad1** [comment]
bot merge

**Comment by kianenigma** [comment]
Why are we referencing local dependencies with a `version` anyway? it is really just torture with merge conflicts to keep them up to date.

For any dep that's based on `path`, should we just remove `version`?

**Comment by niklasad1** [comment]
> Why are we referencing local dependencies with a version anyway? it is really just torture with merge conflicts to keep them up to date.

Because we want to publish some crates on crates.io such `sp-core`, `sp-runtime` and similar which are used in subxt then the `version field` is required.

**Comment by kianenigma** [comment]
but I mean inside of substrate, all local dependencies should not need to reference e.g. the version of things like `sp-core`, but sub-xt can still refer to the version.

**Comment by niklasad1** [comment]
ah I see,

Sure, personally I'm not sure which crates are meant be published or not but especially for test crates and similar that's unnecessary for sure but introduced by this PR.

Changing that would imply lots new merge conflicts :grimacing: but perhaps worth it in the long run

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/publish-substrate-to-crates-io/949/11

**Pull request merged**
