### PR TITLE
Fix: Off-chain-worker example

### PR DESCRIPTION
**Pull request by cuteolaf**
Update the divider in off-chain-worker example

### CODE REVIEW

**Review by davxy — APPROVED** [review]
If you don't mind, can you please take the opportunity to also fix the comment above?

> Depending if the block is even or odd we will send a `Signed` or `Unsigned` transaction

Thank you

**Review by bkchr — APPROVED** [review]
Yeah please update the comment

**Comment by cuteolaf** [comment]
@bkchr @davxy The comment is updated.

**Comment by davxy** [comment]
bot merge

**Pull request merged**
