### PR TITLE
pallet-assets: Rename `total_supply` to `amount`

### PR DESCRIPTION
**Pull request by bkchr**
We are actually passing the `amount` on assets being minted and not the total supply.

Closes: https://github.com/paritytech/substrate/issues/13210

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2308964

**Review by joepetrowski — APPROVED** [review]

**Review by muharem — APPROVED** [review]

**Comment by muharem** [comment]
Formatting failing. 
Wonder if we should include the label notifying an api change?

**Comment by joepetrowski** [comment]
> Formatting failing. Wonder if we should include the label notifying an api change?

Oh yeah, we should, it will affect indexing services.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2312222

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/substrate-developer-newsletter-february-2023-notable-updates-for-frame-devs-new-deep-dives-released-calling-builders-to-apply-to-rfps-and-bounties/2137/1

**Pull request merged**
