### PR TITLE
Merge txpool-runtime-api with txpool-api

### PR DESCRIPTION
**Pull request by tomusdrw**
Related: #4318

To avoid crate bloat we merge runtime-api of the transaction pool (~10 lines crate) with the primitives of the transaction pool. The downside is `no_std` support, but I think it's manageable.

### CODE REVIEW

**Comment by bkchr** [comment]
Hmm, more crates provide better parallelization opportunities for rustc/cargo. So, why do remove the number of crates? :D

**Comment by tomusdrw** [comment]
> Hmm, more crates provide better parallelization opportunities for rustc/cargo. So, why do remove the number of crates? :D

That's a good point, but I also feel that too many crates causes cognitive overload. And while I'd like us to for instance to split `sp-core/sp-runtime` to smaller (more domain-specific) crates, I feel like separating `runtime-api` from it's primitives is just unnecessary. I'm not very opinionated on this particular change though, so if there is another person that has doubts let's just close this PR.

**Comment by rockbmb** [comment]
> The downside is `no_std` support, but I think it's manageable.

Hello @tomusdrw,

In the sentence I quoted could you perhaps have meant

> The downside is no `no_std` support, but I think it's manageable.

?

**Comment by tomusdrw** [comment]
@rockbmb I meant that there is additional maintenance cost to support `no_std`, because we need to add `default-features = false` to all crates and have `std` feature explicitly enable `std` feature of crates we depend on.
`no_std` is definitely supported if you, because we use that `RuntimeApi` in all default runtimes in this repo.

**Pull request merged**
