### PR TITLE
Add ss58 registration details for Stafi

### PR DESCRIPTION
**Pull request by Tore19**
Description

Added symbols, decimals and website of Stafi Network

https://stafi.io
https://stafi.subscan.io

Thanks!

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@Tore19 please merge master

**Comment by Tore19** [comment]
Hi, @bkchr 

Seems I don't have permission to merge. Do I need to apply or anything else?

image

**Comment by bkchr** [comment]
@Tore19 you should merge master into your branch, not merge this branch into master.

**Comment by bkchr** [comment]
@Tore19 ping

**Comment by Tore19** [comment]
> @Tore19 please merge master

@bkchr Hi, done! Thanks for your reminder!

**Review by bkchr — APPROVED** [review]

**Pull request merged**
