### PR TITLE
node-template: remove redundant types from runtime

### PR DESCRIPTION
**Pull request by disconnect3d**
Removes `BlockId`, `SignedBlock` and `CheckedExtrinsic` as they are unused within the runtime currently and the `BlockId` was defined twice.

### CODE REVIEW

**Comment by disconnect3d** [comment]
To add on this, this was flagged by the https://github.com/est31/warnalyzer tool, along with some other stuff:

```
node/src/cli.rs:16:6: unused Field '0'
node/src/cli.rs:18:12: unused Field '0'
node/src/cli.rs:21:13: unused Field '0'
node/src/cli.rs:24:15: unused Field '0'
node/src/cli.rs:27:14: unused Field '0'
node/src/cli.rs:30:15: unused Field '0'
node/src/cli.rs:33:13: unused Field '0'
node/src/cli.rs:36:9: unused Field '0'
node/src/cli.rs:40:12: unused Field '0'
node/src/main.rs:1:1: unused Mod ''
node/src/main.rs:11:4: unused Function 'main'
pallets/template/src/lib.rs:32:20: unused Type 'T'
pallets/template/src/lib.rs:40:21: unused Type 'T'
pallets/template/src/lib.rs:50:19: unused Field '0'
pallets/template/src/lib.rs:50:24: unused Field '1'
pallets/template/src/lib.rs:55:17: unused Type 'T'
pallets/template/src/lib.rs:73:56: unused Field '0'
runtime/src/lib.rs:57:10: unused Type 'AccountIndex'
runtime/src/lib.rs:69:10: unused Type 'DigestItem'
runtime/src/lib.rs:85:11: unused Type 'BlockId'
runtime/src/lib.rs:127:11: unused Const 'DAYS'
runtime/src/lib.rs:304:10: unused Type 'SignedBlock'
runtime/src/lib.rs:306:10: unused Type 'BlockId'
runtime/src/lib.rs:320:10: unused Type 'CheckedExtrinsic'
```

The `AccountIndex` and `DigestItem` are already proposed to be removed in https://github.com/paritytech/substrate/pull/9149.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge 

ty

**Comment by bkchr** [comment]
@disconnect3d please merge master

**Comment by bkchr** [comment]
ping @disconnect3d

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
