### PR TITLE
pallet-tips | port to frame v2

### PR DESCRIPTION
**Pull request by shamb0**
# pallet-tips | port to frame v2

related #7882 | Has dependency on  #8196 , #8193

:warning: Breaking Change :warning:

From https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

```
storages now use PalletInfo for module_prefix instead of the one given to decl_storage: 
Thus any use of this pallet in construct_runtime! should be careful to update name 
in order not to break storage or to upgrade storage (moreover for instantiable pallet). 
If pallet is published, make sure to warn about this breaking change.
```

So users of the treasury pallet must be careful about the name they used in construct_runtime!. Hence the runtime-migration label, which might not be needed depending on the configuration of the treasury pallet.

### CODE REVIEW

**Comment by thiolliere** [comment]
is it ready to review ?
I think it will need a specific migration code in order to move the items away from Treasury into the correct pallet prefix.

**Comment by shamb0** [comment]
Hello @thiolliere, Please consider this PR inhold, This PR has dependency on [PR #8196](https://github.com/paritytech/substrate/pull/8196), bit facing some challenges in rebasing it.
Will pick it up once #8196 is merged.

**Comment by shawntabrizi** [comment]
closing because stale

if you want to update, feel free to reopen.

**Comment by shamb0** [comment]
Sure @shawntabrizi , will reopen after merging with latest master :+1:

**Pull request closed without merging**
