### PR TITLE
*: Update to Prometheus v0.10.0

### PR DESCRIPTION
**Pull request by mxinden**
We just pushed a new release candidate for the Prometheus crate: https://github.com/tikv/rust-prometheus/pull/340

Opening up this pull request to test the release candidate for now. Once it is promoted to a release we can proceed with this pull request.

### CODE REVIEW

**Comment by tomaka** [comment]
Nothing weird on Grafana.

**Review by romanb — APPROVED** [review]

**Comment by mxinden** [comment]
Let's not merge yet as it is still set to the release candidate. I will promote the release candidate to a release soon (https://github.com/tikv/rust-prometheus/pull/341).

**Comment by mxinden** [comment]
bot merge

**Comment by mxinden** [comment]
> The PR is currently unmergeable.

Guessing it is missing another core-dev approval. @tomaka would you once more do the favor?

**Review by tomaka — APPROVED** [review]

**Comment by mxinden** [comment]
bot merge

**Pull request merged**
