### PR TITLE
fix and test default instance for collective

### PR DESCRIPTION
**Pull request by thiolliere**
Some structs were lacking default instance, this is now tested and fixed.

cc @JoshOrndorff

### CODE REVIEW

**Comment by bkchr** [comment]
I thought that `DefaultInstance` is not required?

**Comment by thiolliere** [comment]
indeed it must not be required.

but Default is already put on Trait so we should be coherent if we want this module to have a default instance we need to put it on event and origin as well.

**Comment by bkchr** [comment]
If we add the `DefaultInstance` can we not drop the PhantomData?

**Comment by thiolliere** [comment]
the PhantomData is not needed, even without this pr change it was not needed but I'm actually surprised because the variants only capture `system::Trait + I`.

So now phantomdata is removed as it is not necessary

**Pull request merged**
