### PR TITLE
Exclude sp-*-fuzzer from release process

### PR DESCRIPTION
**Pull request by gnunicorn**

### CODE REVIEW

**Comment by gnunicorn** [comment]
fixed the issue, reverting the always on. ready for review and merge.

**Comment by gnunicorn** [comment]
a) they are needed for two jobs though (check and publish)
and b) fight with @s3krit, who made me do that in the first place :p .

**Comment by bkchr** [comment]
Why isn't `cargo unleash` respecting `publish = false`?

**Comment by gnunicorn** [comment]
> Why isn't `cargo unleash` respecting `publish = false`?

[It does](https://github.com/gnunicorn/cargo-unleash/blob/5578fd19e521a03843e4811644a6691cb8e879dc/src/cli.rs#L311-L321) (and that is more complicated than expected), but [it isn't set on that crate](https://github.com/paritytech/substrate/blob/ebf9df376bd129e7410bab05bb2c30ea993e83e4/primitives/phragmen/fuzzer/Cargo.toml#L2-L10).

But you are right, that's the better approach. Will set the `publish = false` on that. Doing another test run after.

**Comment by s3krit** [comment]
Looks good to me. Let's wait for unleash-check to pass, then don't forget to uncomment before merging with master:

```
  # only:
  #   - master
  #   - tags
```

**Comment by kianenigma** [comment]
fwiw I also have a fuzzer in `frame/staking` that you might want to ignore here as well?

**Comment by gnunicorn** [comment]
@kianenigma they are already marked properly.

looks like there is another (unrelated) problem with unleash now. Will raise a second PR for it though.

**Pull request merged**
