### PR TITLE
Bounties use SpendOrigin

### PR DESCRIPTION
**Pull request by gavofyork**
Bounties now use the spend origin which is much better for Gov2

TODO
- [x] Update tests.
- [x] Update benchmarks.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2101547

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2102164

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2102779

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_bounties

**Review by ggwpez — APPROVED** [review]

**Review by muharem — APPROVED** [review]

**Pull request merged**
