### PR TITLE
Simplify math by using MAX associated const

### PR DESCRIPTION
**Pull request by gilescope**
Use `u32::MAX` rather than `u32::max_value()`. Easier to read code.

(I will do the min as a separate PR so that it's a little easier to review the PR - unless you'd prefer them both in the same?)

(Also should we have `Weight::MAX`, `BallanceOf::<T>::MAX` and `Bounded::MAX` ? if so happy to do that in a separate PR)

### CODE REVIEW

**Comment by gilescope** [comment]
Let me redo that - seemed to not start from the right place.

**Comment by andresilva** [comment]
IMO this is going a bit too much into "personal opinions" direction and you'll probably get some push back from these changes. I personally don't think there's any difference in comprehension between `u32::max_value()` vs `u32::MAX`. Just my 2 cents though.

**Comment by bkchr** [comment]
Yeah, there is really no difference.

**Comment by andresilva** [comment]
@ordian I didn't know that, in that case it seems sensible.

**Pull request closed without merging**
