### PR TITLE
Migrate finality-grandpa to the 2018 edition

### LINKED ISSUE #1783: Migrate substrate-finality-grandpa to the 2018 edition
It hasn't been covered in #1415 in order to simplify back-porting from the `alexander-backports` branch.

### PR DESCRIPTION
**Pull request by DarkEld3r**
Additionally several "variable does not need to be mutable" warnings have been fixed and the unused `hex-literal` dependency has been removed.

Closes #1783.

### CODE REVIEW

**Comment by rphmeier** [comment]
We have 3 open and substantial PRs for finality-grandpa -- I would guess that all of them have conflicts with this. Maybe we should ice this?

**Comment by bkchr** [comment]
Is this is an insubstantial PR, it should be fairly easy to integrate into the others? What is holding the others of being merged?

**Comment by DarkEld3r** [comment]
I don't insist on merging: these are relatively simple changes that can be done later.

**Comment by rphmeier** [comment]
Sure, let's just merge this then.

**Pull request merged**
