### PR TITLE
add event for when a slash is reported, next to enactment.

### PR DESCRIPTION
**Pull request by kianenigma**
in light of recent slashing events in Kusama, this makes it easier to track.

Backports a small part of #12420 to master.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2138958

**Review by bkchr — APPROVED** [review]

**Review by lexnv — APPROVED** [review]

**Comment by kianenigma** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2141524

**Comment by kianenigma** [comment]
Since we're gonna merge https://github.com/paritytech/substrate/pull/12420 soon, no need for this.

**Pull request closed without merging**
