### PR TITLE
I want to use this address prefix, thanks

### PR DESCRIPTION
**Pull request by hex2100**
try to pull it

### CODE REVIEW

**Comment by xlc** [comment]
Prefix greater than 48 are reserved.

**Comment by hex2100** [comment]
> Prefix greater than 48 are reserved.

If i use a prefix lower than 48, is it okay to repeat with other project?

**Comment by xlc** [comment]
Only if you have the consensus from other project

**Comment by hex2100** [comment]
> Only if you have the consensus from other project

I choose to use 27

**Pull request closed without merging**
