### PR TITLE
Release: Bump sp-crates to release on crates.io

### PR DESCRIPTION
**Pull request by lexnv**
This PR bumps the version of the following crates and all the dependency crates:
- sp-core
- sp-core-hashing
- sp-runtime
- sp-keyring
- sp-version

This is in preparation for a crates.io release of those crates.

The release is needed for us to merge the work regarding the light client integration in [subxt](https://github.com/paritytech/subxt/pull/965/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R81-R85).

This was automatically created with https://github.com/paritytech/subpub.

polkadot companion: https://github.com/paritytech/polkadot/pull/7300
cumulus companion: https://github.com/paritytech/cumulus/pull/2643

// @paritytech/subxt-team

### CODE REVIEW

**Review by jsdw — APPROVED** [review]
Awesome! I'm looking forward to getting automated crates.io releases back..

**Review by niklasad1 — APPROVED** [review]

**Review by sam0x17 — APPROVED** [review]

**Comment by lexnv** [comment]
Tested out the polkadot / cumulus companions with `diener` patch and `cargo update -p` for the updated sp crates, will merge this and modify the `Cargo.lock` of the companions once the substrate branch=master is updated

**Comment by lexnv** [comment]
bot merge

**Comment by lexnv** [comment]
bot merge

**Pull request merged**
