### PR TITLE
Include Bitswap into request response protocols

### PR DESCRIPTION
**Pull request by altonen**
Include bitswap protocol into the list of enabled request response protocols. Previously the code stored the bitswap into another vector stored in `sc_network::config::Params` but didn't extend the protocol vector that contained the protocols that were given to `Behaviour`, essentially leaving Bitswap disabled even if `--ipfs-server` was provided on the command line.

### CODE REVIEW

**Review by kpp — APPROVED** [review]

**Review by dmitry-markin — APPROVED** [review]

**Review by skunert — APPROVED** [review]

**Comment by altonen** [comment]
bot merge

**Comment by alebaffa** [comment]
Hi, sorry to commet on this after 3 months, but I also found this issue (still open) https://github.com/paritytech/substrate/issues/7915 where it is said that
> Ok, then request-response can't be used for implementing bitswap because it requires opening a new stream for each response.

Thanks for clarifying. Sorry again.9

**Comment by sinkingsugar** [comment]
This didn't fix much.
substrate side we receive requests from ipfs clients, but ipfs clients never get substrate responses currently.

**Comment by altonen** [comment]
@alebaffa @sinkingsugar 

Looking at  [this implementation](https://github.com/ipfs-rust/libp2p-bitswap/blob/master/src/protocol.rs#L42) of Bitswap protocol, it would lead me to believe we can implement the protocol over the request response protocol meaning there might be some discrepancy between the "right way" and our way of implementing the codec. I'll look into how we might go about fixing this.

**Comment by altonen** [comment]
Unfortunately it seems that the Bitswap protocol cannot be built on top of the request response protocol if we want to be compatible with go-ipfs and js-ipfs. There is a way for us to add support for the protocol while keeping it still as a generic protocol living above `sc-network`, issue #12850 tracks the progress of this

**Pull request merged**
