### PR TITLE
using the prefix 52

### PR DESCRIPTION
**Pull request by differs**
merge it please , thank you

Thank you for your Pull Request!

Before you submitting, please check that:

- [x] You added a brief description of the PR, e.g.:
  - What does it do?
  - What important points reviewers should know?
  - Is there something left for follow-up PRs?
- [x] You labeled the PR appropriately if you have permissions to do so:
  - [x] `A*` for PR status (**one required**)
  - [x] `B*` for changelog (**one required**)
  - [ ] `C*` for release notes (**exactly one required**)
  - [ ] `D*` for various implications/requirements
  - [ ] Github's project assignment
- [ ] You mentioned a related issue if this PR related to it, e.g. `Fixes #228` or `Related #1337`.
- [ ] You asked any particular reviewers to review. If you aren't sure, start with GH suggestions.
- [ ] Your PR adheres to [the style guide](https://github.com/paritytech/substrate/blob/master/docs/STYLE_GUIDE.md)
  - In particular, mind the maximal line length of 100 (120 in exceptional circumstances).
  - There is no commented code checked in unless necessary.
  - Any panickers have a proof or removed.
- [ ] You bumped the runtime version if there are breaking changes in the **runtime**.
- [ ] You updated any rustdocs which may have changed
- [ ] Has the PR altered the external API or interfaces used by Polkadot? Do you have the corresponding Polkadot PR ready?

Refer to [the contributing guide](https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc) for details.

After you've read this notice feel free to remove it.
Thank you!

✄ -----------------------------------------------------------------------------

### CODE REVIEW

**Comment by differs** [comment]
using prefix 52

**Comment by gavofyork** [comment]
Please point us to your testnet/codebase. Once we verify that your project has reasonable need of a Substrate prefix, we'll be happy to reserve the code.

**Comment by differs** [comment]
> Please point us to your testnet/codebase. Once we verify that your project has reasonable need of a Substrate prefix, we'll be happy to reserve the code.

My souce code :https://github.com/differs/Legends
view it at telemetry :https://telemetry.polkadot.io/#/Legends
wallet:https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.pot-game.tech#/staking

**Comment by shawntabrizi** [comment]
When you are ready to provide the information needed, you can reopen this pr

**Pull request closed without merging**
