### PR TITLE
change $location from tt* to ty and remove unnecessary cb_* versions

### PR DESCRIPTION
**Pull request by deepink-mas**
change $location from tt* to ty and remove unnecessary cb_* versions

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3180780

**Comment by ggwpez** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot bench $ pallet dev pallet_balances

**Review by ggwpez — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
