### PR TITLE
Fix db initialization for light client

### LINKED ISSUE #7125: paritydb panics when used for light client
So we stopped using our custom sled db setup and noticed that it doesn't work.

The problem comes from optimizations being enabled for column::STATE which has col_id 1, which aren't valid when using the light client that has KEY_LOOKUP as col_id 1. As a workaround the optimizations can be disabled.

### PR DESCRIPTION
**Pull request by arkpar**
Closes #7125

### CODE REVIEW

**Comment by arkpar** [comment]
@svyatonik does light::columns::CACHE contain trie nodes keyed by the node hash?

**Comment by svyatonik** [comment]
No, it isn't related to state trie or to any other tries. It is where [list cache component](https://github.com/paritytech/substrate/tree/master/client/db/src/cache) is [storing](https://github.com/paritytech/substrate/blob/master/client/db/src/cache/list_storage.rs#L94) its [entries](https://github.com/paritytech/substrate/blob/master/client/db/src/cache/list_entry.rs#L42). The cache (it should be renamed into storage at some point) stores e.g. encoded authorities sets, changes tries configurations.

Re optimizations - there's no column that stores state trie nodes on the light client, so the right way imo is to disable state-related optimizations on the light node. I.e. `state_col` is `None` on the light node

**Comment by arkpar** [comment]
> Re optimizations - there's no column that stores state trie nodes on the light client, so the right way imo is to disable state-related optimizations on the light node. I.e. state_col is None on the light node

Would it be correct to assume that this is the most frequently accessed column and therefore it should get more cache memory allocated to it?

**Comment by svyatonik** [comment]
I have no any proofs, but I feel that most frequently accessed light columns are: `KEY_LOOKUP` and `HEADERS`.`The CACHE` column is on the third place.

**Review by svyatonik — APPROVED** [review]

**Review by gavofyork — APPROVED** [review]

**Comment by gavofyork** [comment]
bot merge

**Pull request merged**
