### PR TITLE
DUMMY [do not merge][CI] Provision `bm3` into a gitlab runners fleet

### PR DESCRIPTION
**Pull request by radupopa2010**

### CODE REVIEW

**Comment by radupopa2010** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime westend-dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ runtime pallet pallet_system

**Comment by TriplEight** [comment]
/cmd queue -c bench-bot $ runtime pallet pallet_system

**Comment by TriplEight** [comment]
/cmd queue -c bench-bot $ runtime pallet pallet_system

**Comment by TriplEight** [comment]
/cmd queue -c bench-bot $ runtime pallet pallet_system

**Comment by TriplEight** [comment]
/cmd queue -c bench-bot $ runtime pallet pallet_system

**Comment by mordamax** [comment]
/cmd queue -c bench-bot $ runtime pallet pallet_system

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ runtime pallet pallet_system

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ runtime westend-dev pallet_balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ runtime dev pallet_balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by radupopa2010** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev balances

**Comment by joao-paulo-parity** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c test-bench-bot $ pallet dev pallet_balances

**Comment by radupopa2010** [comment]
/cmd queue -c test-bench-bot $ pallet dev pallet_balances

**Pull request closed without merging**
