### PR TITLE
Don't connect to reserved nodes if they're banned

### PR DESCRIPTION
**Pull request by tomaka**
This PR is an alternative to https://github.com/paritytech/substrate/pull/9003. We should either merge this one or https://github.com/paritytech/substrate/pull/9003, but not both.

This PR changes `alloc_slots` to not open substreams with reserved nodes if they are banned.
Since reputations apply globally, this would mean that for example the sync code can ban a node due to an anomaly, and it would close the collation and validation substreams as well.

It also makes sure that `alloc_slots` is immediately called if a node gets disconnected because it is banned, which we didn't do before. This change is also in https://github.com/paritytech/substrate/pull/9003

### CODE REVIEW

**Comment by ordian** [comment]
Do I understand correctly, that in the following example the status quo is:
1. peer gets banned by sync protocol
1. we disconnect from the peer on all peersets
1. we reconnect to it on a given peerset when another peer connects of disconnects on that peerset (when `alloc_slots` is called)

The only difference in this PR (apart from the fix for non-reserved peers) is that we additionally check reputation on step 3, is that right?

However, it's rather surprising that reconnects may only happen at indefinite points in time or not happen at all. Would it reasonable to also try to connect to reserved peers e.g. every minute? OTOH, I don't want to make the behavior even more complex, so feel free to ignore.

**Review by ordian — APPROVED** [review]

**Comment by tomaka** [comment]
> The only difference in this PR (apart from the fix for non-reserved peers) is that we additionally check reputation on step 3, is that right?

Yes!

> However, it's rather surprising that reconnects may only happen at indefinite points in time or not happen at all. Would it reasonable to also try to connect to reserved peers e.g. every minute? OTOH, I don't want to make the behavior even more complex, so feel free to ignore.

Reputations automatically regress towards 0 over time, so the reconnect to the reserved node will happen once the node goes above the ban threshold again.

**Comment by tomaka** [comment]
This is good to merge, right?

**Review by ordian — APPROVED** [review]

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
