### PR TITLE
Add ss58 prefix for HydraDX

### PR DESCRIPTION
**Pull request by jak-pan**
Add ss58 prefix for HydraDX chain companion https://github.com/polkadot-js/common/pull/872

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by joepetrowski — APPROVED** [review]

**Comment by bkchr** [comment]
@jak-pan please merge master

**Comment by jak-pan** [comment]
> @jak-pan please merge master

done

**Review by gavofyork — APPROVED** [review]

**Comment by gavofyork** [comment]
needs a master merge once again

**Comment by jak-pan** [comment]
> needs a master merge once again

Do we want to keep the note about 48+ being reserved? I think it was removed before...

**Comment by jak-pan** [comment]
Another merge.

**Comment by jak-pan** [comment]
Guys, some people frontrun us already. Our network is live and we want to upgrade. Would be great if we can get rid of the dependency override. Pretty please?

**Comment by apopiak** [comment]
bot merge

**Pull request merged**
