### PR TITLE
removes use of sc_client::Client from sc_basic_authorship

### PR DESCRIPTION
**Pull request by seunlanlege**
see #4452

### CODE REVIEW

**Comment by gnunicorn** [comment]
@seunlanlege please merge latest master and fix the conflicts

**Comment by bkchr** [comment]
Why do we merge refactors on code freeze?

**Comment by gnunicorn** [comment]
_feature_ freeze. During alpha we still accept not-too-involved fixes and changes to the API for improvements. These won't be accepted anymore during beta.

**Comment by gnunicorn** [comment]
@seunlanlege merge again? this conflicts now – then set the looks-good label and I happily merge it.

**Pull request merged**
