### PR TITLE
Actually respect locks of zero

### PR DESCRIPTION
**Pull request by gavofyork**
When using `set_lock` to lock zero funds, it should not be a no-op (unlike `extend_lock`, in which it is).

### CODE REVIEW

**Review by vstam1 — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2836745

**Review by KiChjang — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by gavofyork** [comment]
> What happens then when `set_lock` has a 0 amount? Does it function like `remove_lock`?

Any previous lock should no longer constrain the balance liquidity, similar to if `remove_lock` is called. However, it is not specified whether any storage on chain is reclaimed, as it is with `remove_lock`. In the `fungible` API, `set_freeze(0)` is explicitly defined as being equivalent to `thaw()`.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2838771

**Comment by gavofyork** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2850379

**Review by kianenigma — APPROVED** [review]

**Review by sam0x17 — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2871417

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2871416

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2871848

**Comment by gavofyork** [comment]
bot merge

**Comment by xlc** [comment]
someone needs to write some tests for this

**Review by alokeutpal — APPROVED** [review]

**Pull request merged**
