### PR TITLE
Pallets: Assets `destroy_accounts` releases the deposit

### PR DESCRIPTION
**Pull request by muharem**
Destroy accounts should release the existence deposits if any.

Currently, when accounts are being destroyed, deposits are not released. The `dead_account` function is executed forcefully, allowing the removal of the asset even if some accounts were not removed correctly. 
In the PR we release the deposits on the account destroy and do not force the  `dead_account` function.

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Review by sam0x17 — APPROVED** [review]

**Review by gavofyork — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3067865

**Review by juangirini — APPROVED** [review]

**Comment by muharem** [comment]
bot merge

**Comment by muharem** [comment]
bot rebase

**Comment by muharem** [comment]
bot merge

**Pull request merged**
