### PR TITLE
Use `ArgAction::Set` for enable-offchain-indexing flag

### PR DESCRIPTION
**Pull request by skunert**
Follow up for https://github.com/paritytech/substrate/pull/12381
There are some places where we pass `enable-offchain-indexing=true` to binaries.

This does not work by default anymore in clap 4 which uses `ArgAction::SetTrue` as default. This means that the occurence of the flag sets the value to true and additional values are not allowed.

While I think the new approach makes more sense, there are some users of this flag and we should not break it if not necessary.

### CODE REVIEW

**Review by koute — APPROVED** [review]
Are there any other places where people might have reasonably used the `--arg=true` form? Maybe we should do this everywhere? (I'm not necessarily suggesting we should; just thinking out loud.)

**Review by michalkucharczyk — APPROVED** [review]
Is there a way to indicate that `--flag=true` is deprecated?

**Comment by skunert** [comment]
> Are there any other places where people might have reasonably used the `--arg=true` form? Maybe we should do this everywhere? (I'm not necessarily suggesting we should; just thinking out loud.)

I think this is a non-issue for our other flags. I investigated a bit and this specific flag has specified a `value_name` in the clap attribute. This attribute is what required a value to be present previously (you can not do the same on our other bool flags. e.g. `--validator=true` is not allowed) . I was also thinking of just changing this, but a search on github found several deployment files and our devops repo also has a few occurences.

> Is there a way to indicate that --flag=true is deprecated (when used)?

We could take a look at the raw arguments and look for this specifically, but there is no clap-specific way to look for this.

**Comment by skunert** [comment]
bot merge

**Pull request merged**
