### PR TITLE
[DO NOT MERGE] Try nextest

### PR DESCRIPTION
**Pull request by alvicsam**
Try to run `cargo nextest` instead `cargo test` in `test-linux-stable` job

Part of https://github.com/paritytech/ci_cd/issues/334

### CODE REVIEW

**Comment by ggwpez** [comment]
Nice that the CI team is trying this out, I have been using this for the speedup!  
The base command is `cargo nextest run` instead of `cargo nextest`.

**Comment by alvicsam** [comment]
Thx for the hint :)

**Comment by alvicsam** [comment]
@ggwpez do you use it locally? Strangely enough tests doesn't work with `nextest` in our CI

**Comment by alvicsam** [comment]
Thanks! I'll try to fix it and run with the options you provided

**Comment by alvicsam** [comment]
`node-cli` tests continue to fail with `nextest`

**Comment by ggwpez** [comment]
> `node-cli` tests continue to fail with `nextest`

They are quite CPU intensive, we could increase the timeouts there.  
Can you check the CPU usage of the runner?

**Comment by alvicsam** [comment]
I checked the CPU during the run. When `node-cli` started it wasn't used heavily. 
Nextest docs says: `The timeout is 60 seconds by default`. I'm not sure that they fail because of it. The strange thing is that the failed tests are not the same, they may vary but all of them belongs to `node-cli`.

These tests usually fail:
 - `node-cli::running_the_node_and_interrupt running_the_node_works_and_can_be_interrupted`
 - `node-cli::running_the_node_and_interrupt running_two_nodes_with_the_same_ws_port_should_work`
 - `node-cli::purge_chain_works purge_chain_works`
 - `node-cli::temp_base_path_works temp_base_path_works`

**Comment by alvicsam** [comment]
I added `--retries=3` and it seems that it helped

**Comment by TriplEight** [comment]
> I added `--retries=3` and it seems that it helped

this would mean that there are flaky tests. But AFAIK this was not the case and we didn't have to repeat the tests with the usual `cargo test`. Please try with a timeout, we've quite some long system/midule tests.

**Comment by bkchr** [comment]
The mentioned tests are probably not written in a way of being "parallelizable" because they run a full node. However, I think we probably could fix this.

**Comment by ggwpez** [comment]
I think we need to fix the node tests first, or what are you trying now?

**Comment by alvicsam** [comment]
Until they are fixed we can run them as a workaround in a different job. I was checking how much time will it take.

**Comment by alvicsam** [comment]
Closing the PR, because the were several big changes in CI, so it's easier to start from scratch

**Pull request closed without merging**
