### PR TITLE
chore: export propose_with and init_with_now

### PR DESCRIPTION
**Pull request by yjhmelody**
I need it to reimplent these traits.
I may also want to pub all fields of `Proposer`

### CODE REVIEW

**Comment by bkchr** [comment]
When you make functions public, they require docs. Please do this.

**Comment by yjhmelody** [comment]
Sir it's done.

**Comment by yjhmelody** [comment]
Anyone could give me a feedback?

**Comment by yjhmelody** [comment]
Hi @bkchr I have add docs.

**Pull request closed without merging**
