### PR TITLE
Release primitive crates

### PR DESCRIPTION
**Pull request by ascjones**
Following on from major version upgrade of `parity-scale-codec` https://github.com/paritytech/substrate/pull/10825. Based on https://github.com/paritytech/substrate/pull/10451, https://github.com/paritytech/substrate/pull/10772 and https://github.com/paritytech/substrate/pull/10790

```
cargo set-version --bump major -p sp-tracing
cargo set-version --bump major -p sp-version 
cargo set-version --bump major -p sp-keyring  
cargo set-version -p sp-keystore -- 0.12.0 
cargo set-version -p sp-externalities  -- 0.12.0
cargo set-version -p sp-state-machine  -- 0.12.0
cargo set-version --bump major -p sp-trie
cargo set-version --bump major -p sp-io
cargo set-version --bump major -p sp-rpc
cargo set-version --bump major -p sp-storage
cargo set-version --bump major -p sp-runtime
cargo set-version --bump major -p sp-wasm-interface
cargo set-version --bump major -p sp-runtime-interface
cargo set-version --bump major -p sp-core
cargo set-version --bump major -p pallet-contracts-primitives
cargo set-version --bump major -p sp-application-crypto
cargo set-version --bump major -p sp-arithmetic
cargo set-version --bump major -p sp-runtime-interface-proc-macro
cargo set-version --bump major -p sp-core-hashing-proc-macro
```

Unleash:

```
cargo unleash em-dragons --dry-run \
            -p \
            pallet-contracts-primitives \
            sp-core \
            sp-runtime-interface \
            sp-runtime-interface-proc-macro \
            sp-wasm-interface \
            sp-runtime \
            sp-storage \
            sp-rpc \
            sp-io \
            sp-trie \
            sp-state-machine \
            sp-externalities \
            sp-keystore \
            sp-application-crypto \
            sp-tracing \
            sp-version \
            sp-keyring \
            sp-arithmetic \
            sp-core-hashing-proc-macro
```

### CODE REVIEW

**Comment by ascjones** [comment]
I understand that it is okay to ignore the companion checks in this case https://github.com/paritytech/substrate/pull/10451

**Review by athei — APPROVED** [review]

**Review by lexnv — APPROVED** [review]

**Comment by ascjones** [comment]
bot merge

**Comment by kianenigma** [comment]
bot force merge

**Comment by bkchr** [comment]
:robot:

**Pull request merged**
