### PR TITLE
Change BlockHashCount Parameter in Node/Node Template

### PR DESCRIPTION
**Pull request by joepetrowski**
Makes [this change](https://github.com/paritytech/polkadot/pull/1086) in the Substrate Node and Node Template.

Not sure if `test-utils` is necessary.

### CODE REVIEW

**Comment by bkchr** [comment]
Tests need to be updated.

**Comment by xlc** [comment]
Now the question is, does parachain need to apply this change as well?

**Comment by joepetrowski** [comment]
> Now the question is, does parachain need to apply this change as well?

No, a parachain would not need to apply this. It only affects for how long users will be able to submit mortal extrinsics to the parachain.

**Comment by xlc** [comment]
I know this is not a required change, but will it be a recommended change?

**Comment by joepetrowski** [comment]
I think it depends on who you expect to use the chain. If you expect custodians or anyone with longer signing processes to provide support for your chain, then yes.

**Comment by shawntabrizi** [comment]
The effects on the chain at this size is negligible anyway. I dont really see the downside for anyone not to bump to a value like this.

**Comment by bkchr** [comment]
> The effects on the chain at this size is negligible anyway. I dont really see the downside for anyone not to bump to a value like this.

This is a little bit of a weird view :D If everybody just copies everything from us, this parameter could just have been a const value :P 

In the end every chain needs to decide on their own what they need. If you for example have a 30 seconds block time, it would mean that you have 20 hours with the current value we set here^^

**Comment by xlc** [comment]
I see, so 2400 blocks is 4 hours for chain with 6s block time. We have 4s block time so will need a higher number to achieve 4 hours but I still feel it may not be long enough for some multi-sign custodians signing flow edge cases. But I don't see too much issue just using immortal tx for that case.

But regards to this PR, it will be good to have some comments explain where the number 2400 is coming from and the effects of modify it. There are just too many hidden knowledges required to configure a production level parachain. Most of other devs won't be monitoring every single PR in Substrate/Polkadot.

**Pull request merged**
