### PR TITLE
Add runtime-benchmarks for frame-benchmarking

### PR DESCRIPTION
**Pull request by zjb0807**
Add `runtime-benchmarks` feature for frame-benchmarking to control baseline benchmarks. 

polkadot companion: paritytech/polkadot#4387
cumulus companion: paritytech/cumulus#802

### CODE REVIEW

**Comment by bkchr** [comment]
What is the reason for this pr?

**Comment by zjb0807** [comment]
> What is the reason for this pr?

`benchmarks` related code should be enabled in `#![cfg(feature = "runtime-benchmarks")]`, otherwise some scenarios will cause pollution.(.e.g `--no-default-features --target=wasm32-unknown-unknown`)

https://github.com/open-web3-stack/open-runtime-module-library/runs/4281316679?check_suite_focus=true

**Comment by bkchr** [comment]
> 

Why has your bencher the crate imported when the `runtime-benchmarks` feature is not enabled?

**Comment by zjb0807** [comment]
> Why has your bencher the crate imported when the `runtime-benchmarks` feature is not enabled?

This is a module that imports some methods of `frame_benchmarking`, not runtime, so there is no `runtime-benchmarks` feature.
 I think the `benchmarks` related code should be enabled with `runtime-benchmarks` feature. 
@shawntabrizi

**Review by bkchr — APPROVED** [review]

**Comment by shawntabrizi** [comment]
Looks like there is a lot more places this needs to be updated?

**Comment by zjb0807** [comment]
> Looks like there is a lot more places this needs to be updated?

Other places just import the `frame-benchmarking` without calling the `benchmarks` in `frame-benchmarking`, so it does not affect. I can add on if needed.

**Comment by zjb0807** [comment]
gitlab-check-dependent-cumulus error:
```
the package `parachain-template-runtime` depends on `frame-benchmarking`, with features: `runtime-benchmarks` but `frame-benchmarking` does not have these features.
```
gitlab-check-dependent-polkadot error:
```
the package `kusama-runtime` depends on `frame-benchmarking`, with features: `runtime-benchmarks` but `frame-benchmarking` does not have these features.
```

But the feature is added. And paritytech/polkadot#4387 works on my machine.  Is there a problem with CI?

**Comment by zjb0807** [comment]
The Polkadot and Cumulus companion don't execute `diener patch`.  How to fix the problem?

**Review by shawntabrizi — APPROVED** [review]

**Comment by kianenigma** [comment]
CI is broken for now. We either wait or merge later manually. Thanks!

**Pull request merged**
