### PR TITLE
BlockId removal: &Hash to Hash

### PR DESCRIPTION
**Pull request by michalkucharczyk**
It changes &Block::Hash argument to Block::Hash.

This PR is part of BlockId::Number refactoring analysis (paritytech/substrate#11292)

polkadot companion: paritytech/polkadot#6246
cumulus companion: paritytech/cumulus#1818

### CODE REVIEW

**Review by koute — APPROVED** [review]

**Review by acatangiu — COMMENTED** [review]
I'm not convinced about **why** we want to switch to `Copy`ing `Hash` around instead of passing by-reference.

`Hash` is probably not big enough to get any perceivable performance penalty coming from `Copy`s (see some benchmarks for small structs [here](https://www.forrestthewoods.com/blog/should-small-rust-structs-be-passed-by-copy-or-by-borrow/)), but this is changing from 8 byte reference copies to 32 byte value copies, so in theory at least, it's worse.

Looking at the PR, I don't see any relevant improvements to code readability or maintainability coming from this change, so like I said, why do it?

**Comment by koute** [comment]
> `Hash` is probably not big enough to get any perceivable performance penalty coming from `Copy`s (see some benchmarks for small structs [here](https://www.forrestthewoods.com/blog/should-small-rust-structs-be-passed-by-copy-or-by-borrow/)), but this is changing from 8 byte reference copies to 32 byte value copies, so in theory at least, it's worse.

In theory it can also be better. (: That's because now instead of a pointer which will have to be dereferenced it can just pass around the hash directly in registers (which, AFAIK, on amd64 and aarch64 it should do, splitting it up between two floating point registers).

Probably won't make much difference in practice either way though. But the fact stands that `Hash` is `Copy`, so it's kinda weird to pass it through a reference.

**Comment by michalkucharczyk** [comment]
This commit is "fixing" the API changed in commits: 87f3fdea8f, 1f17288074, ea71267aeb, 5ae005c244, 1802a115e8, 967080b44e, f5ed51def3, e791929a7b, e34b840b88, f3139874cb. I should have been using by copy from the beginning. 

As @koute already commented copy can be better as compiler may decide to use registers.

Also the code readability _slightly_ improves as you don't have to use `&/*`.

**Review by acatangiu — APPROVED** [review]

**Comment by bkchr** [comment]
> Probably won't make much difference in practice either way though. But the fact stands that `Hash` is `Copy`, so it's kinda weird to pass it through a reference.

I second this. Having `Hash` implement `Copy` is probably some coming from the point of making the usage easier. None of the code here would also be really degenerate performance wise, when the copy would be "slow".

**Review by bkchr — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
bot merge

**Comment by michalkucharczyk** [comment]
bot merge

**Pull request merged**
