### PR TITLE
[ci] Disable publish-crates-locally

### PR DESCRIPTION
**Pull request by alvicsam**

### CODE REVIEW

**Review by rcny — APPROVED** [review]

**Review by altaua — APPROVED** [review]

**Comment by ordian** [comment]
Why not just set 
>   allow_failure:                   true

**Comment by alvicsam** [comment]
@ordian because the job tries to upload 12198 files and directories as artifacts and this is too much. I'd prefer to disable it completely for now and find out with @joao-paulo-parity how it can be improved.

**Comment by alvicsam** [comment]
@joao-paulo-parity there are no artifacts now. Should we still collect them in this job?

**Comment by joao-paulo-parity** [comment]
> there are no artifacts now. Should we still collect them in this job?

@alvicsam yes. This PR specifically doesn't produce artifacts because it has no changes at the moment, but other PRs will.

**Comment by joao-paulo-parity** [comment]
I've verified that the job doesn't exhibit the same problematic behavior on several occasions, so closing this

**Pull request closed without merging**
