### PR TITLE
[Fix] Bump tuple element number in frame-support.

### PR DESCRIPTION
**Pull request by ruseinov**
We're currently at the tuple element limit, when we reach that - the runtime compilation fails with a cryptic error. This PR bumps the tuple element number by 50% to ensure nobody hits this. 

Details could be found here: https://substrate.stackexchange.com/questions/7212

### CODE REVIEW

**Review by sam0x17 — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Could also do it in the runtime node.

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot rebase

**Comment by bkchr** [comment]
bot merge

**Comment by ruseinov** [comment]
> Could also do it in the template node.

No need it seems, there are only a few pallets attached. Now that we have a decent error - it should be more straightforward for others.

**Pull request merged**
