### PR TITLE
add an assert

### PR DESCRIPTION
**Pull request by guanqun**

### CODE REVIEW

**Comment by rphmeier** [comment]
Not sure if we want to merge this as is. Looking through the state-db code recently, it doesn't seem to adhere to our prove-or-remove policy for panics, and favors assertions over returning errors. If this was a debug assert I would merge.

**Comment by guanqun** [comment]
If it's a `debug_assert`, actually we don't need that, because the overflow in debug mode would simply panic.

**Comment by guanqun** [comment]
hmm. then we could probably close this PR.

**Comment by guanqun** [comment]
Closing the ticket.

**Pull request closed without merging**
