### PR TITLE
Remove deprecated batch verification

### PR DESCRIPTION
**Pull request by bkchr**
This removes the deprecated batch verification. This was actually never really activated. Nevertheless, we need to keep the host functions around to support old runtimes which may import these host functions. However, we do not give access to these functions anymore. This means that any new runtime can not call them anymore. The host function implementations we keep will not do batch verification and will instead fall back to the always existing option of directly verifying the passed signature. `finish_batch_verification` will return the combined result of all the batch verify calls.

This removes the `TaskExecutorExt` which only existed to support the batch verification. So, any code that used this extension can just remove the registration of them. It also removes `SignatureBatching` that was used by `frame-executive` to control the batch verification. However, there wasn't any `Verify` implementation that called the batch verification functions.

polkadot companion: https://github.com/paritytech/polkadot/pull/6999

### CODE REVIEW

**Comment by ggwpez** [comment]
>Nevertheless, we need to keep the host functions around to support old runtimes which may import these host functions

DQ but can they be feature gated since we mostly dont need them?

**Review by davxy — APPROVED** [review]

**Comment by bkchr** [comment]
> DQ but can they be feature gated since we mostly dont need them?

You can not use these functions anymore by calling `sp_io::crypto::start_batch_verification`. These are only given to the wasm executor to have them callable by old runtimes.

**Review by melekes — APPROVED** [review]

**Review by skunert — APPROVED** [review]

**Review by koute — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/april-updates-for-substrate-and-polkadot-devs/2764/1

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-41-v0-9-42/2828/1

**Pull request merged**
