### PR TITLE
Create attribute macro for defining common defaults for config associated types

### LINKED ISSUE #3335: Simplify test setup
They are many duplicated setup code required for any new modules, mostly config `system::Trait`. There must be a way to avoid duplicate this code all over the places.
It also make any modification to `system::Trait` tedious as it have to change every single module test setup.

I am not sure what is the best way, but at least a macro can avoid most of the duplications.

https://github.com/paritytech/substrate/blob/9b3e9f32cd5243d2eeff3d5d8337033aa64c091b/srml/aura/src/mock.rs#L35-L63

### PR DESCRIPTION
**Pull request by KiChjang**
May potentially fix #3335.

This PR introduces two new attributes, `#[pallet::default_type]` and `#[frame_support::use_default_config_for]`, for the purpose of simplifying the setup of commonly used types for the associated types in a pallet's `Config` trait.

`#[pallet::default_type(type)]` can be put before a `Config` trait associated type to indicate the default value that the associated type should have. Note that the type provided to the attribute does not get evaluated during pallet construction and only during runtime construction. This means the following is possible:

```rust
// pallet.rs
trait Config: frame_system::Config {
    #[pallet::default_type(Call)] // can be used here even though `Call` is not defined in this pallet
    type Call: Parameter + GetDispatchInfo;
}

// runtime.rs
#[frame_support::use_default_config_for(Call)]
impl pallet::Config for Runtime {}

construct_runtime! {
    // ...
}
```

`#[frame_support::use_default_config_for(ident)]` can only be put on trait impl items that implement the `Config` trait for pallets. The type names provided to the attribute must exist in the `Config` trait definition as associated type items and must also have a `#[pallet::default_type]` declared, otherwise the compiler will emit the following error:

```
error: associated type `YourTypeNameHere` does not have a default type specified, or does not exist
```

If this is a desired change, we could then begin documenting `Config` associated type items and explaining what the default types are and how they behave.

### CODE REVIEW

**Comment by bkchr** [comment]
> ```rust
> #[frame_support::use_default_config_for(Call)]
> impl pallet::Config for Runtime {}
> ```

But this still means that the user needs to know what kind of fields a trait has to add them there?

**Comment by KiChjang** [comment]
Yes, you'd still need to specify the names of the associated type items that you'd want to use the default for. I suppose I could also make an attribute macro or a new syntax that allows you to use the default types for all associated types in a Config impl, perhaps it's just `#[frame_support::use_default_config]` or `impl_default_config_for!(path::to::Config)`.

Either way, the problem that you describe (i.e. default type being `Call` but it isn't actually defined during runtime construction) can possibly be solved by more documentation on the config associated type items, detailing what the default is and what is expected to exist. I suppose we could also try creating a special mechanism for types that are defined by `construct_runtime!`...

**Comment by xlc** [comment]
I am not sure how much code this is saving.

An alternative approach is instead of use associated type, replace as much of them as possible to methods with default implementation. Something similar to

https://github.com/paritytech/frontier/blob/7e6ab0ca9ffc074ebba4329606ecb90cfc27ec72/frame/evm/src/lib.rs#L146-L148

So this 

https://github.com/paritytech/substrate/blob/8f5b446ee4c1cff407a2888985178cf692166428/frame/system/src/lib.rs#L171-L173

can become this

```rust
/// The maximum length of a block (in bytes). 
 #[pallet::constant] 
 fn block_length() -> limits::BlockLength> { 10000 }
```

But this is going to be another major breaking change and changes the macro syntax.

**Comment by kianenigma** [comment]
@xlc's idea is interesting. The downside would be lack of enforcing const, but I think it is a worthwhile approach. I think we can and should retire all these `type`s and move to a combination of `fn` and `const`.

**Comment by shawntabrizi** [comment]
I think XLC's idea is one we should follow anyway. Sounds like it would simplify a lot of the definitions, and practically speaking provides the same functionality.

**Pull request closed without merging**
