### PR TITLE
Don't start evicting peers right after `SyncingEngine` is started

### PR DESCRIPTION
**Pull request by altonen**
Parachain collators may need to wait to receive a relaychain block before they can start producing blocks which can cause `SyncingEngine` to incorrectly evict them.

When `SyncingEngine` is started, wait 2 minutes before the eviction is activated to give collators a chance to produce a block.

### CODE REVIEW

**Review by pepoviola — COMMENTED** [review]
Can we also update the comment in [here](https://github.com/paritytech/substrate/pull/14216/files#diff-425626fdb3e3c19324b6180105e4e2174d942c5b09f3594dabf2574fb929411aR79) to be 30 seconds.
Thanks!!

**Review by pepoviola — APPROVED** [review]

**Comment by skunert** [comment]
For my understanding: If I see correctly, the reputation of a peer that is evicted because of inactivity is lowered. After what time will that same evicted peer be able to connect again?

**Comment by altonen** [comment]
> For my understanding: If I see correctly, the reputation of a peer that is evicted because of inactivity is lowered. After what time will that same evicted peer be able to connect again?

If there are no peers with higher reputation, the peer is selected again right away and `Notifications` tries to reconnect but because they were disconnected, there is a 10-30 second back-off. After that back-off is done, the connection is retried. So I'd say around 30 seconds.

**Review by bkchr — APPROVED** [review]
It is a hack, not super nice. So, let's hope we can remove this in the near future.

@altonen do we already have some issue to remove this eviction logic after your refactorings?

**Comment by altonen** [comment]
> It is a hack, not super nice. So, let's hope we can remove this in the near future.
> 
> @altonen do we already have some issue to remove this eviction logic after your refactorings?

We can remove it soon. [The notification PR](https://github.com/paritytech/substrate/pull/14197) is published already and [here](https://github.com/paritytech/substrate/blob/notification-service/client/network/sync/src/engine.rs#L736-L743) the code checks if it can accept the peer and if it fails, the handshake will fail for the remote peer and it won't have peers that rejected it.

**Review by dmitry-markin — APPROVED** [review]

**Review by wirednkod — APPROVED** [review]

**Comment by altonen** [comment]
Btw I noticed that changes introduced in #13800 have made syncing tests visibly slower. If you checkout to its parent or revert the commit, they execute in around 60 seconds and after those changes the execution time ~10 seconds slower.

**Comment by altonen** [comment]
bot rebase

**Review by melekes — APPROVED** [review]
👍

**Comment by altonen** [comment]
bot rebase

**Pull request merged**
