### PR TITLE
Transaction pool benchmarks: Reusing Nonce 

### PR DESCRIPTION
**Pull request by Doordashcon**
This attempts to solve #9970

### CODE REVIEW

**Comment by Doordashcon** [comment]
When I attempt adding the second scenario to `transaction_pool_benchmark` I encounter this error message?

```bash
'main' panicked at 'Submits tx to pool: Pool(TooLowPriority { old: 11986, new: 11986 })`
```

**Comment by Doordashcon** [comment]
bump

**Comment by Doordashcon** [comment]
@bkchr pls take a look at my work so far

**Comment by Doordashcon** [comment]
bump

**Comment by bkchr** [comment]
> When I attempt adding the second scenario to `transaction_pool_benchmark` I encounter this error message?
> 
> ```shell
> 'main' panicked at 'Submits tx to pool: Pool(TooLowPriority { old: 11986, new: 11986 })`
> ```

This is expected by your changes. In general I don't know if my issue makes that much sense anymore.

**Comment by Doordashcon** [comment]
Ah I see, will close this then

**Pull request closed without merging**
