### PR TITLE
.maintain/monitoring: Normalize alerting rules

### PR DESCRIPTION
**Pull request by mxinden**
- Start alert names with their component and end with the describing
adjective.

- Describe alert duration in `message` with `for more than` across all
alerts.

### CODE REVIEW

**Review by haikoschol — APPROVED** [review]

**Comment by haikoschol** [comment]
@mxinden I assumed you waited with updating the tests for any feedback regarding wording and hence did not wait with approving until the tests pass. :)

**Comment by mxinden** [comment]
> I assumed you waited with updating the tests for any feedback regarding wording and hence did not wait with approving until the tests pass. :)

@haikoschol :D I am tempted to say yes, but to be honest, I simply forgot that max-from-the-past wrote these.

**Comment by mxinden** [comment]
@gabreal is anything fixed on `LowNumberOfNewBlocks` that needs updating before merging this?

**Comment by gabreal** [comment]
Not that I'm aware of, looks good to go :+1:

**Review by gabreal — APPROVED** [review]

**Comment by mxinden** [comment]
bot merge

**Pull request merged**
