### PR TITLE
WIP: Fix failing docs on warns

### PR DESCRIPTION
**Pull request by TriplEight**
Fixes the previous flag that apparently didn't do the job.

@danforbes I think it would make sense to fix the docs to make CI pass on this job right here. To make this faster, I've removed everything else from CI while this is in WIP state.

It's handy to track the pipelines for this PR with https://gitlab.parity.io/parity/substrate/-/pipelines?page=1&scope=all&ref=7670

To debug: remove `-Dwarnings` in https://github.com/paritytech/substrate/pull/7670/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7R133 to see all the warnings at once

### CODE REVIEW

**Comment by danforbes** [comment]
@TriplEight can you give me a sense of the priority on this as well as estimated effort you think will be required to address it?

**Comment by TriplEight** [comment]
@danforbes apparently, failing on warnings didn't ever work for this job. So just a [random job](https://gitlab.parity.io/parity/substrate/-/jobs/740109) succeeds and `Ctrl+F` `warning:` shows 143 matches.
Not to say drop everything, but our docs have quite a lot of warnings.

**Comment by thiolliere** [comment]
I think we can fix all doc warning, this fix almost all of them except nalgebra and authority-discovery https://github.com/paritytech/substrate/pull/7710

**Comment by danforbes** [comment]
@mxinden can you help with the broken link in the docs for the authority discovery worker? I think it was committed here https://github.com/paritytech/substrate/pull/7368/files#diff-da93fe21a550b47fbf80544c1d1144276be1b5c39354597883ddce0a935cf39eR96

**Comment by mxinden** [comment]
@danforbes I pushed https://github.com/paritytech/substrate/pull/7670/commits/f618f8ddf40817b0bc34a718d7fd61f5dbe0c13e fixing the link. Thanks for the pointer.

**Comment by TriplEight** [comment]
Thanks all!
Does it mean I can undo the debug CI setup and merge?

**Comment by thiolliere** [comment]
cargo doc will still complains about nalgebra
To fix it I asked them to backport their doc fix.
But we can also ask linregress to make a new version with latest nalgebra.
Or ignore nalgebra doc grumbles but I don't know how

**Comment by gnunicorn** [comment]
any progress on this?

**Comment by thiolliere** [comment]
nalgebra will probably never fix for its old version: https://github.com/dimforge/nalgebra/issues/807
I don't expect linregress ppl to make a new major release just for fixing doc.

So maybe we can do a script on our side to ignore the failing dor of nalgebra or push nalgebra to release the minor version somehow. nalgebra dev is dimforge, https://www.dimforge.com/, he should be reachable and accept donation. that may be a way to solve.

**Comment by TriplEight** [comment]
maybe it makes sense to [skip testing](https://doc.rust-lang.org/rustdoc/documentation-tests.html#attributes) these particular ones, merge and have a tracking issue to unskip them?

**Comment by thiolliere** [comment]
I don't know how to avoid the ci to test the doc of nalgebra. it is not one of our crate

**Comment by TriplEight** [comment]
do we actually care documenting deps? `--no-deps                    Don't build documentation for dependencies`

**Comment by TriplEight** [comment]
or `        --exclude <SPEC>...          Exclude packages from the build` to exclude something specific

**Comment by thiolliere** [comment]
> do we actually care documenting deps? `--no-deps Don't build documentation for dependencies`

I think it could work but actually I personally prefer to have deps documented.
Something we can do is to check doc without deps in the CI and but still generate doc with deps, it seems a good solution to me

**Comment by TriplEight** [comment]
so I think it makes sense to add to this job two runs
1. run it with `--no-deps and -Dwarnings` to fail on what's ours, in the case of it passes, we produce the docs
2. run it with `-Dwarnings` to keep track that's something's still broken

**Comment by TriplEight** [comment]
wait a sec, it has been `         time cargo +nightly doc --no-deps --workspace --all-features --verbose` with `--no-deps` all along.

**Comment by TriplEight** [comment]
FYI the current command `cargo +nightly doc --no-deps --workspace --all-features --verbose` will fail

either with 
```
   Compiling proc-macro-error-attr v1.0.4
     Running `sccache rustc --crate-name build_script_build --edition=2018 /ci-cache/cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-attr-1.0.4/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=0e1ad2f9b429b0a6 -C extra-filename=-0e1ad2f9b429b0a6 --out-dir /ci-cache/target/debug/build/proc-macro-error-attr-0e1ad2f9b429b0a6 -L dependency=/ci-cache/target/debug/deps --extern version_check=/ci-cache/target/debug/deps/libversion_check-b51661b575c73396.rlib --cap-lints allow`
error: Unrecognized option: 'i'

error: could not document `sp-std`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name sp_std primitives/std/src/lib.rs -o /ci-cache/target/doc --cfg 'feature="default"' --cfg 'feature="std"' --error-format=json --json=diagnostic-rendered-ansi -L dependency=/ci-cache/target/debug/deps -in-header /builds/.maintain/rustdoc-header.html -Dwarnings --crate-version 3.0.0` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: Unrecognized option: 'i'

error: build failed
```

or
```
   Compiling num-traits v0.2.14
     Running `sccache rustc --crate-name build_script_build /ci-cache/cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.14/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="libm"' --cfg 'feature="std"' -C metadata=a0aa44b6f788a097 -C extra-filename=-a0aa44b6f788a097 --out-dir /ci-cache/target/debug/build/num-traits-a0aa44b6f788a097 -L dependency=/ci-cache/target/debug/deps --extern autocfg=/ci-cache/target/debug/deps/libautocfg-126bc84acbac0b8c.rlib --cap-lints allow`
error: Unrecognized option: 'i'
error: Unrecognized option: 'i'


error: could not document `substrate-test-utils-test-crate`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type bin --crate-name substrate_test_utils_test_crate test-utils/test-crate/src/main.rs -o /ci-cache/target/doc --error-format=json --json=diagnostic-rendered-ansi --document-private-items -L dependency=/ci-cache/target/debug/deps -in-header /builds/.maintain/rustdoc-header.html -Dwarnings --crate-version 0.1.0` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by thiolliere** [comment]
my bad I got confused about nalgebra because when testing locally warning were raised, I fixing master now and will open a PR

**Review by gabreal — COMMENTED** [review]
`build-rust-doc` job looks like before but everything else is missing.

**Comment by TriplEight** [comment]
it's still in the debug state

**Comment by gnunicorn** [comment]
closing for a lack of progress.

**Pull request closed without merging**
