### PR TITLE
Remove package aliases from node template

### PR DESCRIPTION
**Pull request by JoshOrndorff**
A few months ago the majority of `Cargo.tmol` files throughout the Substrate code base were refactored to not alias crates. This PR cleans up a few that were missed in the node template.

### CODE REVIEW

**Comment by bkchr** [comment]
You need to fix the warning.

**Comment by bkchr** [comment]
> LGTM. Anyone know why that check test is failing?

Because there is a warning?

**Comment by gnunicorn** [comment]
sure, but the warning seems unrelated to these changes.

**Comment by JoshOrndorff** [comment]
Indeed the warning is coming from `native_executor.rs` which I haven't touched.
```
 warning: function is never used: `say_hello_world`
   --> client/executor/src/native_executor.rs:461:6
    |
461 |         fn say_hello_world(data: &str) {
    |            ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default
```

According to `git blame` that bit was last changed in https://github.com/paritytech/substrate/pull/4129

**Comment by bkchr** [comment]
Just delete the method^^

**Comment by bkchr** [comment]
Okay, deleting isn't correct. Sorry. This will fail.

**Comment by bkchr** [comment]
Please merge master and apply the following patch:
```
diff --git a/client/executor/src/native_executor.rs b/client/executor/src/native_executor.rs
index 5641755ef..bca1aa97d 100644
--- a/client/executor/src/native_executor.rs
+++ b/client/executor/src/native_executor.rs
@@ -483,5 +483,7 @@ mod tests {
                                2,
                        );
                });
+
+        my_interface::say_hello_world("hey");
        }
 }
```

**Pull request merged**
