### PR TITLE
Remove partial key size limit from trie codec

### PR DESCRIPTION
**Pull request by cheme**
This PR remove the partial key size limit of the trie codec.
Previous size limit was set to U16::max nibbles, and not really meant to be reach.
It occurs that when reach, (as reported), the state will not be readable, and generally previous idea to truncate key does not sounds practical (difficult to implement with rocksdb key prefixing and even if it can be deterministic, storing at a truncated key will lead to a state that is not really usable).
After this change limit will be hardware limit (u32 with wasm u64 native), runtime should therefore enforce they are not reaching these limits, more generally the codec is not suited at all for big keys and any sane runtime will never reach these numbers (even old limit), but it will be good if the codec behave properly though.

### CODE REVIEW

**Comment by bkchr** [comment]
This requires an update of the spec.

Also please add some test.

CC @athei this is especially important for contracts. There should be some sensitive upper limit on key lengths.

**Comment by cheme** [comment]
I did add a test on the upper limit (was already implemented from my attempted at implemented key truncate from codec change only).
I find this test not too usefull though, but got no other idea what to test.
Alternatively we can also change the node codec trait to allow returning an error and error on the upper limit, but would require more changes.

**Comment by athei** [comment]
> CC @athei this is especially important for contracts. There should be some sensitive upper limit on key lengths.

Thanks. We are already limiting the key:
https://github.com/paritytech/substrate/blob/696bdc67af5fd83aca318263dbd405593b043ba3/frame/contracts/src/lib.rs#L331-L332

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@cheme does this requires an update of the spec?

**Comment by cheme** [comment]
> @cheme does this requires an update of the spec?

I would think no (except for cumulus pvf maybe, but I would really not expect the limit to be reach somewhere (otherwhise should put the change also behind a new version of storage root and keep old codec)).

**Comment by bkchr** [comment]
I more meant, is the spec currently already mentioning any upper limit that we should remove?

**Comment by cheme** [comment]
Ok :face_palm: , added https://github.com/w3f/polkadot-spec/issues/578

**Review by arkpar — APPROVED** [review]

**Comment by arkpar** [comment]
bot merge

**Comment by bkchr** [comment]
@cheme can you please run cargo fmt?

**Pull request merged**
