### PR TITLE
wasm: Update from v6.0.2 to v8.0.1

### PR DESCRIPTION
**Pull request by lexnv**
Update `wasmtime` from v6.0.2 to v8.0.1.

Having an older version causes build errors in subxt with smoldot.
Subxt relies on sp-runtime which was bringing wasmtime v6.0.2, while smoldot has wasmtime v8.0.1.

This change reflects in `sp-runtime`, `sp-core`, `sp-keyring` primarily. 

https://github.com/paritytech/subxt/pull/965

polkadot companion: https://github.com/paritytech/polkadot/pull/7268
cumulus companion: https://github.com/paritytech/cumulus/pull/2623

// @paritytech/subxt-team

### CODE REVIEW

**Review by KiChjang — APPROVED** [review]

**Review by jsdw — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2861567

**Comment by koute** [comment]
Please wait with merging this; I need to run a few benchmarks first to make sure the performance has not regressed.

**Review by koute — APPROVED** [review]
Performance seems fine; LGTM!

**Comment by lexnv** [comment]
bot merge

**Pull request merged**
