### PR TITLE
Remove contracts RPCs

### PR DESCRIPTION
**Pull request by athei**
Those RPCs are redundant and should be called via `state_call`. Polkadot.js and `cargo contract` both already migrated. This means all our tooling should not break after this change.

This will greatly reduce boilerplate and maintenance burden for those APIs.

@statictype ContractsUI is the last user dependent on those RPCs (instantiation dry-run). We will wait with merging until it migrated away.

cumulus companion: https://github.com/paritytech/cumulus/pull/1685

## Porting Guide

The high level contracts API in polkadot.js already uses `state_call` so upgrading to the latest version here is enough. If you are using `api.rpc.contracts` directly you need to switch to `api.call.contractsApi`.

### CODE REVIEW

**Review by ascjones — APPROVED** [review]
:raised_hands:

**Review by cmichi — APPROVED** [review]

**Comment by athei** [comment]
Blocked until ContractsUI no longer uses the `instantiate` RPC (ETA end of week).

**Comment by athei** [comment]
bot merge

**Comment by ggwpez** [comment]
The diener step in the cumulus companion fails in some [MRs](https://github.com/paritytech/substrate/pull/12402) now with some missing error: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/1908582

**Comment by eggachecat** [comment]
Now the tutorial is broken due to this change I think
see
https://docs.substrate.io/tutorials/work-with-pallets/contracts-pallet/
section [Expose the Contracts API]

What can I do?

**Comment by athei** [comment]
You no longer need to add the RPCs. Have a look at [this](https://github.com/paritytech/substrate/tree/master/bin/node/runtime) as an example.

**Comment by alebaffa** [comment]
Though the documentation still is broken in the exposed API part:
```rust
pallet-contracts-rpc-runtime-api = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
```
this does not work anymore with `polkadot-v0.9.33`. Though, in this PR I see a new  `pallet-contracts-runtime-api` that does not exist either in the repo. I am a bit confused. 
How to fix this?

**Comment by donkey-donkey** [comment]
> You no longer need to add the RPCs. Have a look at [this](https://github.com/paritytech/substrate/tree/master/bin/node/runtime) as an example.

thank you for this.
would you mind explaining what this line about calculating the gas limit means.
https://github.com/paritytech/substrate/blob/0a27e54514338b71204e7321192fbd32dae3b950/bin/node/runtime/src/lib.rs#L2010

thanks again

**Comment by donkey-donkey** [comment]
> If the caller of the runtime API does not supply a `gas_limit` we just set it to the maximum weight of a block. Usually, a caller of the API does not know the limit because finding out that limit is the main purpose of using the API (dry run).

Very Nice.! 
thanks

**Comment by xiaozeplus** [comment]
I want to add `contract pallet` into `polkadot-v0.9.31`, and I only add `pallet-contracts-primitives` and `pallet-contracts`. When I deployed a contract, I got a problem:
image

how can I solve it? are there any tutorials I can follow?

**Pull request merged**
