### PR TITLE
Intend to reactivate cargo-unleash check

### PR DESCRIPTION
**Pull request by gnunicorn**
It appears the bug it was deactivated for has been resolved a while ago. Trying to reactivate the checks.

polkadot companion: https://github.com/paritytech/polkadot/pull/4257
cumulus companion: https://github.com/paritytech/cumulus/pull/730

### CODE REVIEW

**Review by adoerr — APPROVED** [review]
The `BEEFY` part LGTM

**Review by TriplEight — APPROVED** [review]
LGTM

**Comment by TriplEight** [comment]
I think this needs a rebase.

**Comment by gnunicorn** [comment]
well, this is a mess again. It looks like someone (outside our company) [has published a `-dev`-versioned, broken crate of ours to crates.io](https://crates.io/crates/sc-allocator) – and now cargo unleash (appropriately) picks that and as a result the publishing test fails. Gotta sleep over what to do about this now...

**Comment by TriplEight** [comment]
@gnunicorn what's the plan on removing the `   allow_failure:                   true`, is it stable enough?

**Comment by gnunicorn** [comment]
I think so, @TriplEight . But it still takes quite a while and with certain improvements to the test, this might be blocking longer than necessary....

**Pull request merged**
