### PR TITLE
Service builder refactoring

### PR DESCRIPTION
**Pull request by cecton**
WIP for #4587

### CODE REVIEW

**Comment by NikVolf** [comment]
Why is this closed?

**Comment by gnunicorn** [comment]
because the author is taking care of other things and won't continue this for now. the issue is still open and unassigned, so up for grabs :) .

**Comment by cecton** [comment]
@bkchr maybe we should keep the branch for now as it can be useful for the chain ops part for the next person. Don't worry, I keep track of my branches it will be deleted at some point

**Comment by expenses** [comment]
I'm interested in taking over this PR!

**Comment by cecton** [comment]
I delete my branch since it is not needed anymore. Thanks @expenses :heart:

**Pull request closed without merging**
