### PR TITLE
Unify rpc api and implementation name

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Different rpc api and impl naming is confusing, I'm not sure if I need to modify `sc-rpc` to be consistent, like

~~`Author` ==> `AuthorRpc`~~
~~`Chain` ==> `ChainRpc`~~
~~`System` ==> `SystemRpc`~~
~~`State` ==> `StateRpc`~~
~~`ChildState` ==> `ChildStateRpc`~~
~~`Offchain` ==> `OffchainRpc`~~
~~`Dev` ==> `DevRpc`~~

 polkadot companion: https://github.com/paritytech/polkadot/pull/5569

### CODE REVIEW

**Review by niklasad1 — COMMENTED** [review]
I don't care that much as long the naming is consistent in the codebase and these with `Rpc` in the names are just merge nits because the jsonrpsee branch has been around for a long time.

AFAIU, all these `Rpc` naming  in the structs are "not needed"/redundant because they are placed in `mod rpc` or in dedicated rpc crate.

My preference would just my: `struct Namespace` and `trait NamespaceApi` however that might require are other code to do `use rpc_namespace::Namespace as NamespaceRpc`.

@bkchr I guess you and the client team has to decide what you want. 

I don't like extra `Rpc` in the names but I don't care that much.

**Comment by koushiro** [comment]
I just wanna keep consistency for the rpc api and struct impl name, without extra Rpc  is okey for me.

**Comment by bkchr** [comment]
> AFAIU, all these `Rpc` naming in the structs are "not needed"/redundant because they are placed in `mod rpc` or in dedicated rpc crate.

Sounds reasonable to me. @koushiro so can you please make them all without the `Rpc`.

**Comment by koushiro** [comment]
Done. @bkchr PTAL again

**Review by niklasad1 — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@koushiro can you please merge master

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
