### PR TITLE
Fix benchmarks: set cache_size to higher value

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by cecton** [comment]
It feels weird that this value (128) is hardcoded at so many different places.

**Comment by NikVolf** [comment]
hmm.. according to `parity-common/kvdb-rocksdb`, cache size is in MiB, but it does not explain performance degradation by setting it to 128

probably something is getting rounded to 0 somewhere

**Comment by cecton** [comment]
I mean, maybe we should put a const somewhere with the value (or parametrize it in sc_service::Configuration)... because right now if we need to change the value we have to do it in 5 different places.

**Comment by NikVolf** [comment]
> I mean, maybe we should put a const somewhere with the value (or parametrize it in sc_service::Configuration)... because right now if we need to change the value we have to do it in 5 different places.

this is rather out of scope of this pr, I want to resolve issue with benchmarks reporting degradation of 10x caused by https://github.com/paritytech/substrate/pull/5271

And at the moment, I am not sure that only benchmarks are affected

**Comment by bkchr** [comment]
Before the linked pr the value was set to `None`. This meant we used the default size per column that kvdb sets. And that is way higher as 128MB *per* column.

If we set `128MB`, it means that all columns needs to share this and the state gets 90% of this.

**Comment by NikVolf** [comment]
> Before the linked pr the value was set to `None`. This meant we used the default size per column that kvdb sets. And that is way higher as 128MB _per_ column.
> 
> If we set `128MB`, it means that all columns needs to share this and the state gets 90% of this.

I think there is error in calculations (rounding) somewhere

Now setting cache-size = 128 basically disables rocksdb cache and leads to this 10x-20x degradation ^^^

**Comment by bkchr** [comment]
Yes we round these numbers: https://github.com/paritytech/substrate/blob/master/client/db/src/utils.rs#L236

However, this is not your problem. You have the problem that I explained above. `128MB` is for *all* columns, while the state column gets `90%` of it.

Before when the value was `None`, it set the default value [here](https://github.com/paritytech/parity-common/blob/master/kvdb-rocksdb/src/lib.rs#L191) in kvdb.

**Comment by NikVolf** [comment]
Well know if we run `--db-cache=64` we get 0 Mb cache for all columns besides state column, which is not correct (cache should never be disabled for any column, and 0 disables it).

But it still not explains such degradation with 128 value.

**Comment by NikVolf** [comment]
> You have the problem that I explained above.

This does not explain degradation. Such degradation is only possible when cache is disabled.

**Comment by bkchr** [comment]
Why only when the cache is disabled? Even when you have much less cache, the performance could degrade heavily as stuff is constantly paged out of cache. A small cache leads to the same behaviors as a disabled cache.

**Comment by NikVolf** [comment]
> Why only when the cache is disabled? Even when you have much less cache, the performance could degrade heavily as stuff is constantly paged out of cache. A small cache leads to the same behaviors as a disabled cache.

True, but have no idea how to profile it, I think node performance might be affected as well with these settings. One or several of the column cache might also be too small. Probably not the state one, since it takes 90%. I think setting it to some minimum value (5MiB) might help.

**Comment by bkchr** [comment]
We set the value `128MB` after some testing. The point was to have validators running without using  abusive amounts of memory. 
When syncing you need to increase this value to get better performance, but this is expected.

**Comment by NikVolf** [comment]
> We set the value `128MB` after some testing. The point was to have validators running without using abusive amounts of memory.
> When syncing you need to increase this value to get better performance, but this is expected.

I know, still there is no explanation for some observations.

**Comment by NikVolf** [comment]
Ok, observations show that this is state cache that is not enough (for benchmarks at least). This is probably indication of some weird behaviour when specifying `memory_budget` for kvdb-rocksdb. Because before we didn't specify it and should've got 128Mb per for state column, now we specify 256Mb that should get more than 128Mb for state column and still we get regression (which is eliminated by specifying 384 🤷‍♀️).

**Pull request merged**
