### PR TITLE
Remove on_exit from grandpa

### PR DESCRIPTION
**Pull request by NikVolf**
After #5092 is merged this is probably not required

### CODE REVIEW

**Comment by rphmeier** [comment]
cc @gnunicorn

**Comment by gnunicorn** [comment]
please [tag as described in the wiki page to get things merged during freeze](https://github.com/paritytech/substrate/wiki/Feature-freeze-towards-2.0#process-to-get-prs-merged-during-the-freeze) – I promise I check it regularly.

**Comment by NikVolf** [comment]
I thought it was going in after freeze, but since freeze now takes longer, I’ll put tags

**Comment by NikVolf** [comment]
Don’t merge this yet, previous one should be merged first (#5092)

**Comment by gavofyork** [comment]
should be ready now @NikVolf @gnunicorn ?

**Comment by NikVolf** [comment]
> should be ready now @NikVolf @gnunicorn ?

I'll rebase in a sec

**Comment by NikVolf** [comment]
> > should be ready now @NikVolf @gnunicorn ?
> 
> I'll rebase in a sec

done

**Comment by gnunicorn** [comment]
@NikVolf needs another merge, sorry.

**Pull request merged**
