### PR TITLE
update paritydb and remove dev deps on rocksdb

### PR DESCRIPTION
**Pull request by cheme**
This pr update paritydb for substrate to 0.4.2, and remove the need to have rocksdb build when testing most of substrate crate by removing the dev-dependency from sc-client-db and node-service.

Warning the removal of "rocksdb" as default of "sc-service" might need some parachain or dependant project to add the feature.
Same with "node-testing".

This change can looks like a regression (additional "rocksdb" feature), but I propose it mainly to avoid compiling rocksdb-sys on cargo check or cargo test with some crates.

### CODE REVIEW

**Comment by bkchr** [comment]
> Warning the removal of "rocksdb" as default of "sc-service" might need some parachain or dependant project to add the feature.

Not sure we should do this. IMO, if we are 100% that ParityDB works without any problems, then we should get rid off rocksdb.

> but I propose it mainly to avoid compiling rocksdb-sys on cargo check or cargo test with some crates.

You can just install rocksdb. I'm doing this since years to not always recompile rocksdb.

**Comment by cheme** [comment]
> You can just install rocksdb. I'm doing this since years to not always recompile rocksdb.

may be an idea too

**Comment by cheme** [comment]
Can also switch this PR to just parity-db version update (which the bot could have done I think).

**Comment by cheme** [comment]
There is no strong need for this (I can keep this branch for later). ping @arkpar about making parity-db the default, but I think I prefer to switching this PR to a straightforward version update for now.

**Review by ggwpez — APPROVED** [review]

**Comment by hbulgarini** [comment]
@cheme, is the description of this PR still valid? was the rocksdb change reverted? We are trying to understand if there is any needed action for anyone using rocksdb.

Thanks for clarifying!

**Comment by cheme** [comment]
Yes I did revert them (I kind of regret doing so, but here we are sure nothing broke for other projects).

**Comment by cheme** [comment]
So no needed action anymore :)

**Pull request merged**
