### PR TITLE
Add ExternalitiesExt for TestExternalities

### PR DESCRIPTION
**Pull request by ParthDesai**
Implements `ExternalitiesExt` trait For `TestExternalities` contained in state-machine primitive. So, that we can use simplified api to register, deregister or reference an extension in tests.

### CODE REVIEW

**Review by bkchr — COMMENTED** [review]
Not sure why you need this? All this functionality is already exposed?

**Comment by ParthDesai** [comment]
> Not sure why you need this? All this functionality is already exposed?

Functionality is exposed yes. But you need to get type_id for the extension and use the `ExtensionStore` trait api.  Implementing this trait for `TestExternalities` will allow developer to use simpler syntax to access extensions. 

Besides, this trait is already implemented for objects implementing `Externalities` trait but since `TestExternalities` does not implement `Externalities` trait, it is not implemented for it.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
