### PR TITLE
once_cell in std from 1.70

### PR DESCRIPTION
**Pull request by gilescope**
While Lazy is not yet stable we can reduce our dependencies a bit.

Depends on https://github.com/paritytech/substrate/pull/14399 being merged.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3007878

**Review by koute — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by sam0x17** [comment]
> Looks like the CI images have to be updated to include Rust 1.70.

Indeed but according to CI team they also can't be until the next version so looks like this will have to wait: https://github.com/paritytech/ci_cd/issues/816#issuecomment-1592952569

**Comment by altaua** [comment]
> > Looks like the CI images have to be updated to include Rust 1.70.
> 
> Indeed but according to CI team they also can't be until the next version so looks like this will have to wait: [paritytech/ci_cd#816 (comment)](https://github.com/paritytech/ci_cd/issues/816#issuecomment-1592952569)

Nah, I have worked around that issue in https://github.com/paritytech/polkadot/pull/7386; there are a few other blockers before I can get 1.70 out but it should be doable early next week.

**Review by lexnv — APPROVED** [review]
LGTM! I think this is ready for merge, now that CI is up to date to 1.70 👍

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3051557

**Comment by gilescope** [comment]
https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3051557 - looks like one of the CI jobs is still using an old rust version.

**Comment by altaua** [comment]
> https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3051557 - looks like one of the CI jobs is still using an old rust version.

Yep, sorry about that! I forgot to update the rust version on our new mac runners. Fixed.

**Review by sam0x17 — APPROVED** [review]

**Comment by gilescope** [comment]
bot merge

**Pull request merged**
