### PR TITLE
Finish removing support for legacy network protocol

### LINKED ISSUE #5670: Remove legacy single substream tracking issue
Here's a tracking issue for things to do before removing the legacy single substream:

- [x] (1) Implement answering finality proof requests. (https://github.com/paritytech/substrate/pull/5718)
- [x] (2) Switch to the new blocks protocol. There should probably be a CLI flag that makes it possible to disable this, in case things don't work. (#5760)
- [x] (1) Send the `Role` in the registered notifications protocols (#5665)
- [x] (1) Send the `Status` message in the handshake of the `block-announces` protocol (#5726).
- [x] (2) No longer make it mandatory to open the legacy substream. Can only be done after a release that includes all the items with (1).
- [ ] Remove the legacy substream. Can be only be done after a release that includes (2).

### PR DESCRIPTION
**Pull request by tomaka**
Close #5670 

The so-called legacy network protocol was already half-non-functioning. We broke its features over time, such as performing block requests and sending transactions. The reason why it wasn't completely removed earlier is because older versions still open this substream for handshaking purposes, even though they don't make use of it once it's open.

This PR finishes removing it entirely.
The changes were very straight forward. It is purely code removal.

It seems that Rust does not always properly warn about unused code, as it didn't warn me about the `upgrade::legacy` module being unused even though it was. There might be more old code that can be removed, but I don't know where.

### CODE REVIEW

**Review by romanb — APPROVED** [review]
:+1:

**Comment by tomaka** [comment]
Deploying the PR has brought up a new kind of disconnect reason:

image

(the red and violet peaks on the right aren't present on the left side)

However this is very minor and I suggest to not worry about these old nodes.

**Comment by tomaka** [comment]
Nothing unusual on the burnin node.

**Comment by tomaka** [comment]
Needs a second approval for merging.

**Comment by tomaka** [comment]
bot merge force

**Review by bkchr — APPROVED** [review]

**Comment by tomaka** [comment]
bot merge

**Comment by tomaka** [comment]
bot merge force

**Pull request merged**
