### PR TITLE
[DNM] testing cmd bot

### PR DESCRIPTION
**Pull request by mordamax**

### CODE REVIEW

**Comment by mordamax** [comment]
bot help

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2653894

**Comment by mordamax** [comment]
bot help

**Comment by mordamax** [comment]
bot fmt

**Comment by mordamax** [comment]
bot help

**Pull request closed without merging**
