### PR TITLE
Add arithmetic dispatch errors.

### LINKED ISSUE #8544: Add `Overflow` to `DispatchError`
Almost any pallet dealing with numbers will be checking at some point for overflows / underflows in their math.

Each pallet that wants to do that will need to write a custom Error into their pallet for that.

I think `Overflow` is generic enough that it could fit into the `DispatchError` enum, and thus be accessible to all pallets without any extra code.

To complete this issue, all existing uses of custom `Overflow` or `Underflow` errors should be replaced with `DispatchError::Overflow`

### PR DESCRIPTION
**Pull request by shaunxw**
- [x] Introduce `Arithmetic(ArithmeticError)` variant.
- [x] Replace custom arithmetic errors in FRAME.
- [x] Replace overflow/underflow in `TokenError`.
- [x] Add token and arithmetic errors in `DispatchError` equality test.

Closes #8544

### CODE REVIEW

**Comment by shawntabrizi** [comment]
great :)

**Comment by shawntabrizi** [comment]
@jacogr I think this is a breaking change for you?

**Review by shawntabrizi — APPROVED** [review]
this makes sense to me

**Comment by jacogr** [comment]
Not a breaking change, but does require an backwards-compatible adjustment.

**Review by bkchr — APPROVED** [review]

**Pull request merged**
