### PR TITLE
*: Update to libp2p v0.30.0

### PR DESCRIPTION
**Pull request by mxinden**
Update to the latest rust-libp2p release (https://github.com/libp2p/rust-libp2p/releases/tag/v0.30.0).

//CC @romanb @tomaka

### CODE REVIEW

**Review by romanb — APPROVED** [review]

**Review by tomaka — APPROVED** [review]

**Comment by mxinden** [comment]
This has been running on a sentry node for 24h without issues. Graphs do not show any oddness. Unless there are any objections I will merge later today.

**Comment by mxinden** [comment]
Updated to include https://github.com/libp2p/rust-libp2p/pull/1831.

**Comment by mxinden** [comment]
Current status: Debugging consistent failure of `chain_spec::tests::test_connectivity`.

**Comment by tomaka** [comment]
> Current status: Debugging consistent failure of chain_spec::tests::test_connectivity.

If that helps, I ended up doing this in order to debug similar test failures:
https://github.com/paritytech/substrate/pull/7464/commits/259ddd74088e53e7c6a9b0a62a8d1573a0063ce3

**Comment by mxinden** [comment]
Still debugging the `chain_spec::tests::test_connectivity` failure. Results thus far:

- Based on `git bisect` this failure starts with https://github.com/libp2p/rust-libp2p/pull/1821/.

- Kademlia random queries yield as expected 9 results (10 nodes -1 for oneself).

- Nodes are added to the kbuckets.

- Running without light-clients still yields connectivity issues.

- As expected with https://github.com/libp2p/rust-libp2p/pull/1821/ `DiscoveryOut::Discovered` events are delayed till a Kademlia substream negotiation was successful. Thus maybe this is due to the order of identify and discovery events. With `DiscoveryOut::Discovered` now potentially being triggered after an `IdentifyInfo` event.

Will look further into this tomorrow.

**Comment by tomaka** [comment]
Just to be sure: the way we insert/update entries in the k-buckets when an `identify` message is received is entirely equivalent to the "automatic discovery" that https://github.com/libp2p/rust-libp2p/pull/1821 modifies, correct?

Many connections we open will not open any Kademlia substream, and thus as far as I understand would simply never trigger a k-buckets update after https://github.com/libp2p/rust-libp2p/pull/1821.

**Comment by mxinden** [comment]
For the record the failure is related to a race condition between opening a new connection, the PSM being aware of that new connection and opening our custom protocols. This would be fixed with https://github.com/paritytech/substrate/pull/7464.

**Comment by mxinden** [comment]
bot merge

**Pull request merged**
