### PR TITLE
Just a typo

### PR DESCRIPTION
**Pull request by gavofyork**

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2481485

**Comment by ggwpez** [comment]
bot rebase

**Comment by ggwpez** [comment]
bot bench $ pallet dev pallet_salary

**Review by KiChjang — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2481634

**Comment by gavofyork** [comment]
bot merge

**Pull request merged**
