### PR TITLE
Fix compilation of service metrics on Windows

### PR DESCRIPTION
**Pull request by bkchr**
@akru could you test this please?

Fixes: https://github.com/paritytech/substrate/issues/5528

### CODE REVIEW

**Comment by akru** [comment]
@bkchr Thank you very much! It really fixes windows build: https://github.com/airalab/robonomics/runs/566002536

**But** brokes wasm build: https://github.com/airalab/robonomics/runs/566002445

**Comment by bkchr** [comment]
@akru fixed ;)

**Comment by akru** [comment]
@bkchr looks like something wrong with Linux build: https://github.com/airalab/robonomics/runs/566833022 do you have this problem?

BTW, what’s about cross platform CI building for substrate? :)

**Comment by akru** [comment]
I see, let’s check it

**Comment by bkchr** [comment]
@akru This was my bad. It is already fixed in the last commit.

**Comment by gnunicorn** [comment]
now it's wasm again...

**Pull request merged**
