### PR TITLE
refactor CI

### PR DESCRIPTION
**Pull request by TriplEight**
- Fix: changed deprecated `dependencies` to more flexible `needs`. This, among others, allows running jobs not in stage-by-stage manner, but right after the needed job succeeds.
- all CI images moved to `paritytech` registry
- check stage for jobs under 1 minute, sanity checks: `check-runtime`, `test-dependency-rules`, `check-line-width`, `check-signed-tag`, 
- removed unneeded variables, moved others
- added default variables everywhere, they were overridden
- more `interruptible` jobs
- moved `test-dependency-rules` job to be executed on k8s, it doesn't need CI docker env
- moved `check-polkadot-companion-status` to the build stage to be executed alongside with `check-polkadot-companion-build`

### CODE REVIEW

**Comment by TriplEight** [comment]
@gabreal can I move `check-polkadot-companion-status` job to the `check` stage?

**Comment by TriplEight** [comment]
For the reference: 
current [master](https://gitlab.parity.io/parity/substrate/pipelines/93779) pipeline
current [PR](https://gitlab.parity.io/parity/substrate/pipelines/94319) pipeline

**Comment by TriplEight** [comment]
@gabreal where is the Dockerfile for `parity/azure-ansible:v1`?

**Comment by gabreal** [comment]
> @gabreal can I move `check-polkadot-companion-status` job to the `check` stage?

hmm, not sure. would suggest to keep the status check along with the tests in order to see if that pr would build with the companion while testing the pr.

**Comment by gabreal** [comment]
> @gabreal where is the Dockerfile for `parity/azure-ansible:v1`?

idk, @ddorgan added it.

**Pull request merged**
