### PR TITLE
ci: enable build for pre-tags

### PR DESCRIPTION
**Pull request by gabreal**
https://github.com/paritytech/devops/issues/419

building and publishing rustdocs is requested to happen for pre-tags as the distance to official tagged releases is too long.

### CODE REVIEW

**Comment by gabreal** [comment]
the https://github.com/substrate-developer-hub/rustdocs.git repository has **4.1Gb** now. @shawntabrizi can we host it maybe differently? ci jobs are taking more and more time to check it out every time a tag or master is being build.

**Comment by JoshOrndorff** [comment]
Does this change apply to tags? or just branches?

Regarding the size of https://github.com/substrate-developer-hub/rustdocs, I notice there are both `v1.0` and `v1.0.0` directories. Is that intentional?

**Comment by gabreal** [comment]
> Does this change apply to tags? or just branches?

https://docs.gitlab.com/ee/ci/yaml/#onlyexcept-basic :
"only defines the names of branches and tags for which the job will run."

> Regarding the size of https://github.com/substrate-developer-hub/rustdocs, I notice there are both `v1.0` and `v1.0.0` directories. Is that intentional?

`v1.0` are the docs from substrate `v1.0` branch, `v1.0.0` is from the run of the tag.

**Comment by bkchr** [comment]
> the https://github.com/substrate-developer-hub/rustdocs.git repository has **4.1Gb** now. @shawntabrizi can we host it maybe differently? ci jobs are taking more and more time to check it out every time a tag or master is being build.

Can we not "prune" aka delete old revisions? 

And could CI not only fetch the HEAD?

**Comment by gabreal** [comment]
`.git` folder has `1.6Gb`
entire repo `4.7Gb`

**Comment by shawntabrizi** [comment]
> the https://github.com/substrate-developer-hub/rustdocs.git repository has **4.1Gb** now. @shawntabrizi can we host it maybe differently? ci jobs are taking more and more time to check it out every time a tag or master is being build.

I am open to pretty much any suggestion. We only set things up this way because it made sense at the time for what we were looking to do. If the scope of the repo is changing, process can as well.

**Comment by JoshOrndorff** [comment]
Thanks for the link to the gitlab docs. This solves https://github.com/paritytech/devops/issues/419 so I've approved.

I've moved the discussion about the size of the rustdocs repo to an issue there and tagged you all. That issue could also be moved to devops repo if that makes more sense.

Thank for writing this @gabreal !

**Comment by JoshOrndorff** [comment]
@gabreal I pushed this tag about an hour ago https://github.com/paritytech/substrate/releases/tag/pre-v2.0-3e65111 but I don't see a corresponding directory at https://github.com/substrate-developer-hub/rustdocs . Is there something else I need to do to trigger the build?

**Comment by bkchr** [comment]
The tag probably needs to include the commit of this pr.

**Comment by gabreal** [comment]
exactly. the tag is already on gitlab: https://gitlab.parity.io/parity/substrate/-/tags
it just doesn't contain this pr.

**Comment by JoshOrndorff** [comment]
Oh I see. That makes sense. Is there anything we can do manually to build the rustdocs for 3e65111?

**Comment by gabreal** [comment]
one could build and push them manually like running the task manually. triggering that for the ci is more complicated. one would have to tweak ci pipelines on a dedicated branch forking off from that tag and manually set the publishing path.

**Comment by JoshOrndorff** [comment]
Just to be sure I'm understanding, I could checkout out the correct Substrate commit, run `cargo doc` locally, and manually commit those docs to the [hosted rustdocs repo](https://github.com/substrate-developer-hub/rustdocs)?

That sounds easy enough. I'll give it a go.

**Pull request merged**
