### PR TITLE
Change request-resposes to try connect to peer if not connected yet

### PR DESCRIPTION
**Pull request by tomaka**
Close https://github.com/paritytech/substrate/issues/5536

The initial implementation had an explicit check against establishing new connections. It turns out that there is a need, such as for validator-to-validator communications

As a result of this change, I've opened https://github.com/paritytech/substrate/issues/7036

### CODE REVIEW

**Review by romanb — COMMENTED** [review]
I think there are still errors logged in `request_responses.rs` if an inner behaviour emits `DialPeer` or `DialAddress`. These error logs should probably be removed now.

**Review by romanb — APPROVED** [review]

**Comment by tomaka** [comment]
Actually, let me put this on ice. We're not sure that we're going to need this.

**Comment by gnunicorn** [comment]
@tomaka what's the plan here?  Can we close this then?

**Comment by tomaka** [comment]
Still unclear whether we need this or not, but it's not like we're losing much by closing this PR.

**Pull request closed without merging**
