### PR TITLE
Update Matrix and secrets

### PR DESCRIPTION
**Pull request by chevdor**
## todo

- [x] remove usage of `MATRIX_ROOM_ID` (switch to matrix)
- [x] rename `MATRIX_ACCESS_TOKEN` into `RELEASENOTES_MATRIX_V2_ACCESS_TOKEN`
- [x] create `RELEASENOTES_MATRIX_V2_ACCESS_TOKEN`
- [x] remove usage of `POLKADOT_DEVOPS_MATRIX_ROOM_ID`

## after merge

- [ ] delete secrets
   - [ ] `MATRIX_ROOM_ID`
   - [ ] `MATRIX_ACCESS_TOKEN`   
   - [ ] `POLKADOT_DEVOPS_MATRIX_ROOM_ID`

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-hfuzz
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3267316

**Comment by chevdor** [comment]
bot rebase

**Review by lazam — APPROVED** [review]

**Review by wabkebab — APPROVED** [review]

**Review by EgorPopelyaev — APPROVED** [review]

**Review by alvicsam — APPROVED** [review]

**Review by altaua — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Comment by chevdor** [comment]
bot rebase

**Comment by chevdor** [comment]
bot merge

**Comment by sennhann29** [comment]
🙏🙏⛽️

**Pull request merged**
