### PR TITLE
Introduce temporary GitLab & GHA benchmarking jobs

### PR DESCRIPTION
**Pull request by rcny**
This PR makes the following changes to the project's pipeline as a part of https://github.com/paritytech/ci_cd/issues/256:

* add `bench-test-full-crypto-feature` job as a clone of `test-full-crypto-feature`. `test-full-crypto-feature` was chosen for this benchmarking test because it runs fast and jobs won't be queuing on the special single concurrency bench runner
* disable `sccache` for this job with unsetting `RUSTC_WRAPPER` environment variable
* calculate job's total `script` execution time and push the result to the metrics storage

GitHub Actions workflow was added with the same feature set as its GitLab counterpart.

### CODE REVIEW

**Comment by rcny** [comment]
Temporarily blocked by the lack of network access, fix is [here](https://gitlab.parity.io/parity/devops/-/merge_requests/270).

**Comment by rcny** [comment]
> Temporarily blocked by the lack of network access, fix is [here](https://gitlab.parity.io/parity/devops/-/merge_requests/270).

Waiting for the fix to be applied.

**Comment by rcny** [comment]
Networking issue is fixed.

**Comment by rcny** [comment]
Networking issue is fixed.

**Comment by TriplEight** [comment]
had to tab the comments inside of the `run:` blocks to make them somewhat readable - my editor too doesn't highlight them.

**Review by TriplEight — APPROVED** [review]

**Comment by dvdplm** [comment]
Looks sane to me, but @bkchr and @andresilva should take a look too.

**Review by bkchr — APPROVED** [review]

**Comment by TriplEight** [comment]
Grafana with metrics https://grafana.parity-mgmt.parity.io/d/AovynCc7z/gitlab-gha-benchmarking-jobs?orgId=1&from=now-2d&to=now

**Pull request merged**
