### PR TITLE
[Fix] Get target count from TargetList instead of storage

### PR DESCRIPTION
**Pull request by ruseinov**

### CODE REVIEW

**Review by Ank4n — APPROVED** [review]

**Review by kianenigma — APPROVED** [review]

**Comment by ruseinov** [comment]
bot merge

**Comment by ruseinov** [comment]
@kianenigma the two checks that are stuck aren't even showing up in the gitlab pipeline :/

**Comment by ruseinov** [comment]
bot rebase

**Comment by ruseinov** [comment]
bot merge

**Pull request merged**
