### PR TITLE
Add a InherentDataProviderError trait for inherents error handling

### PR DESCRIPTION
**Pull request by expenses**
See #2688. Currently, `ProvideInherentData` uses `String`s for errors, which is not ideal. This commit introduces a `InherentDataProviderError` trait for errors and `InherentError` as a type alias for `Box<dyn InherentDataProviderError>`.

### CODE REVIEW

**Comment by bkchr** [comment]
First, thank you for the pr. However, given the generic architecture of the inherent data providers, I don't see any reason for this pr. While I think that having better errors is a good idea, for the inherent data providers it makes no sense at all. Especially replacing a String with a Box. 

The linked issue is more about the consensus engines and their error types. For them it makes sense to define an enum, as you can forsee all possible error types. 

Given that, I'm against this pr.

**Comment by expenses** [comment]
Example of a potential error enum after this change:
```rust
#[derive(derive_more::Display, Debug)]
enum AuraError<B: BlockT> {
    #[display(fmt = "Could not fetch authorities at {:?}: {:?}", _0, _1)]
    FetchAuthorities(B::Hash, consensus_common::Error),
    #[display(fmt = "Could not extract timestamp and slot: {:?}", _0)]
    ExtractTimestamp(consensus_common::Error),
    #[display(fmt = "{:?}", _0)]
    Runtime(RuntimeString),
    #[display(fmt = "{:?}", _0)]
    Client(ClientError)
}

impl<B: BlockT> InherentDataProviderError for AuraError<B> {}

impl<B: BlockT> From<AuraError<B>> for InherentError {
    fn from(error: AuraError<B>) -> Self {
        Box::new(error) as Self
    }
}
```

**Comment by bkchr** [comment]
`Aura` could also see any other inherent error, if there occurs any error in the runtime while creating the inherent extrinsics. It does not only sees its own errors. So, the potential enum should look like:

```
#[derive(derive_more::Display, Debug)]
enum AuraError<B: BlockT> {
    #[display(fmt = "Could not fetch authorities at {:?}: {:?}", _0, _1)]
    FetchAuthorities(B::Hash, consensus_common::Error),
    #[display(fmt = "Could not create inherent extrinsics: {}", _0)]
    InherentExtrinsics(String),
    #[display(fmt = "{:?}", _0)]
    Runtime(RuntimeString),
    #[display(fmt = "{:?}", _0)]
    Client(ClientError)
}
```

**Comment by expenses** [comment]
See #2688.

**Pull request closed without merging**
