### PR TITLE
new crate sc-light

### LINKED ISSUE #6036: Move light features into their own crate
With moving client into sc-service, we also made the light client features internal to sc-service. While this is fine for now, it means that you can't easily construct the equivalent of a light client without using the sc-service's `ServiceBuilder` anymore. However, only the `new_light` function in there is bound to client, everything else should be either in the respective crates (e.g. executor in `sc-executor`) or at least accessible without the need for `sc-service`. We should move `service/client/light/{executor,backend,blockchain,fetcher}` into a new crate `sc-light` to offer a single simple place to reuse the components.

### PR DESCRIPTION
**Pull request by seunlanlege**
This moves the folder `service/client/light` to it's own crate enabling configurable light client behaviour.
closes #6036

### CODE REVIEW

**Comment by bkchr** [comment]
What is the reasoning behind this pr? You just moved everything into service. What is with the full client code parts?

**Comment by seunlanlege** [comment]
hey @bkchr, so I forgot to link the issue, but see #6036
cc @gnunicorn :raising_hand_man:

**Comment by seunlanlege** [comment]
@gnunicorn all green :yum:

**Comment by gavofyork** [comment]
merge conflicts

**Pull request merged**
