### PR TITLE
Rename `pallet-random-collective-flip` to Insecure...

### PR DESCRIPTION
**Pull request by ggwpez**
Breaking change to explicable state the fact that the `randomness-collective-flip` pallet should not be used for production use-cases. Renames `pallet-randomness-collective-flip` to `pallet-insecure-randomness-collective-flip`.  
Cumulus companion: https://github.com/paritytech/cumulus/pull/2159  

There is currently no alternative other than to bridge to a secure randomness source.

What should happen with the crates.io release? Just leave it as it?

### CODE REVIEW

**Review by sam0x17 — APPROVED** [review]

**Comment by kianenigma** [comment]
> Breaking change to explicable state the fact that the `randomness-collective-flip` pallet should not be used for production use-cases. Renames `pallet-randomness-collective-flip` to `pallet-insecure-randomness-collective-flip`.
> 
> There is currently no alternative other than to bridge to a secure randomness source.
> 
> What should happen with the crates.io release? Just leave it as it?

cc @joao-paulo-parity

IMO we should remove/yank the old one.

**Review by kianenigma — APPROVED** [review]

**Review by lexnv — APPROVED** [review]

**Comment by athei** [comment]
It might be worthwhile to report the crate here: https://rustsec.org/contributing.html to inform users. I did the same when deprecating `parity-wasm`.

**Comment by joao-paulo-parity** [comment]
re https://github.com/paritytech/substrate/pull/13301#issuecomment-1414198886

Before advising on a solution, I'll have to understand what's the intended outcome of this change. By the discussion, I _infer_ that:

- `pallet-insecure-randomness-collective-flip` would be henceforth published for non-production use cases.
  The `-insecure-` component in the name is supposed to get the "non-production" point across.
- We need to deter or prevent further usage of `pallet-randomness-collective-flip` (which would no longer be published) for production use-cases

I don't know if I got it right, so I'll describe some assorted considerations.

---

Adding `publish = false` to `frame/insecure-randomness-collective-flip/Cargo.toml` will prevent the crate from being published if that's the intention.

---

To **deter** further usage of `pallet-randomness-collective-flip`, the advisory suggestion from https://github.com/paritytech/substrate/pull/13301#issuecomment-1414846039 seems like the way to go. The downside is that users won't notice the deprecation warning unless their project has some integration with security databases (e.g. RustSec through `cargo deny` or [GitHub Advisory Alerts](https://github.com/advisories/GHSA-74w3-p89x-ffgh)).

To **prevent** further usage of `pallet-randomness-collective-flip` we'd need to either yank all published versions or remove the crate from `crates.io`. There's no API for crate removal at this time, so we'd have to request it manually through `crates.io`'s help channels; based on https://stackoverflow.com/questions/52639162/how-to-delete-a-published-crate-from-crates-io and https://github.com/rust-lang/crates.io/pull/1506#issuecomment-429102810 they'd probably not comply with the request in this case. Indeed, it seems like the yanking approach would be our only option.

I don't think there's a clear-cut "right approach" for this situation. The prevention path is the most destructive and bothersome one, so do we need to go that far? It seems like the advisory would enough. It might be worthwhile to consider what has historically happened for other projects throughout similar circumstances and try to reason based on that.

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
Doing the *deter* solution would be a good first step IMO. We dont want to really "break" other peoples projects, just ensure they have to rename it in their `Cargo.toml` and understand why.

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
