### PR TITLE
Migrate pallet-democracy to pallet attribute macro

### PR DESCRIPTION
**Pull request by shaunxw**
Part of #7882.

Converts the `Democracy` pallet to the new pallet attribute macro introduced in #6877.

Following the upgrade guidelines here: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines.

## ⚠️ Breaking Change ⚠️ 

From https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

> storages now use PalletInfo for module_prefix instead of the one given to decl_storage: Thus any use of this pallet in construct_runtime! should be careful to update name in order not to break storage or to upgrade storage (moreover for instantiable pallet). If pallet is published, make sure to warn about this breaking change.

So users of the `Democracy` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed depending on the configuration of the `Democracy` pallet.

polkadot companion: https://github.com/paritytech/polkadot/pull/3030

### CODE REVIEW

**Comment by shaunxw** [comment]
Please review :)

**Review by shawntabrizi — APPROVED** [review]

**Review by thiolliere — APPROVED** [review]
sorry for the late review, looks good to me

**Comment by thiolliere** [comment]
Democracy is the name of the pallet in polkadot/kusama so no need for migration

**Comment by thiolliere** [comment]
bot merge

**Pull request merged**
