### PR TITLE
Vesting pallet - make WithdrawReasons configurable

### PR DESCRIPTION
**Pull request by Lezek123**
Updates the vesting pallet to support custom `WithdrawReasons` for the vesting lock.
The reason for this is that it's not always desirable for the unvested funds to be spendable on transaction fees.
In some runtime configurations the fees may go to block author which would allow the vesting funds to leak.
Giving users more granual control w.r.t. how the unvested funds can be spend seems like a justified improvement.

polkadot companion: https://github.com/paritytech/polkadot/pull/5929

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Looks fine to me.  
Needs a `merge origin/master` to make the CI happy.

**Review by shawntabrizi — APPROVED** [review]

**Comment by kianenigma** [comment]
bot rebase

**Comment by kianenigma** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
