### PR TITLE
[network] Extend `Notifications` logs with `SetId` where missing

### PR DESCRIPTION
**Pull request by dmitry-markin**
This should simplify debugging of `ProtocolController` & `Notifications` state machine synchronization issues.

### CODE REVIEW

**Review by altonen — APPROVED** [review]
Maybe we should also downgrade the warnings for `peerset` to debug?

**Comment by dmitry-markin** [comment]
> Maybe we should also downgrade the warnings for `peerset` to debug?

What do you mean exactly? Change `trace` to `debug` in logs like `PSM <= Dropped`?

**Review by michalkucharczyk — APPROVED** [review]

**Comment by dmitry-markin** [comment]
I also created an issue to fix how reserved peers are disconnected when they are banned: https://github.com/paritytech/substrate/issues/14407

**Comment by dmitry-markin** [comment]
bot merge

**Pull request merged**
