### PR TITLE
[CI] Add check for draft PRs

### PR DESCRIPTION
**Pull request by s3krit**
This PR adds a `.pre` CI job in gitlab to check the draft status of the PR. If it is draft, we exit with failure status, thus causing the pipeline to not run. It's a slightly hacky solution (an exit code causing the rest of the jobs to be 'skipped' would be better but that's [not been implemented yet](https://gitlab.com/gitlab-org/gitlab/-/issues/16733)).

Currently doesn't use an API token so we *might* run into rate limits - we are granted 60 requests every hour, and it will run every time there is a push to a PR. If this happens, I will add an API token (which gives us 1000 an hour).

### CODE REVIEW

**Comment by s3krit** [comment]
Hmm I just noticed that changing a PR's status from draft to not-draft won't trigger another pipeline run.  @TriplEight know any magic to make that happen?

**Comment by gnunicorn** [comment]
Here, the overview currently waits though... this is a bit confusing UX wise...

image

**Comment by TriplEight** [comment]
@s3krit pipelines are triggered when the mirroring delivers a new commit. That's by default. So supposedly there were some commits under the "draft" and either they didn't trigger the mirroring (most likely) being saved in some git tree location other than we mirror, or have some feature in git object that doesn't trigger external CIs.

**Comment by s3krit** [comment]
@TriplEight well the issue is that there have been no commits since the transition from draft to request-review, which is likely going to be the case. I think I will create a github action subscribed to the PR state change, that then sends a pipeline trigger to gitlab.

**Comment by gnunicorn** [comment]
bot merge

**Pull request merged**
