### PR TITLE
Use correct prefix needed by child trie in contract

### PR DESCRIPTION
**Pull request by thiolliere**
to put raw and get raw in child it needs the child trie id to start with a specific prefix.

I don't know which is responsible for that, I implemented so that contract is responsible at the generation of the trie id to make it correct.

Also this PR update a test,
also I commit locks changes (I just run ./script/build.sh) that can be reverted.

### CODE REVIEW

**Comment by thiolliere** [comment]
oups issues on test.

**Comment by thiolliere** [comment]
yes but also it is way more error prone to having to prepend the prefix at each call in srml/contract.

**Comment by pepyakin** [comment]
Yes, you're right this is more urgent. We might want to iterate on the following PRs.

**Comment by cheme** [comment]
That is why putting the prefix in child api seems better to me, but it is really not much of an issue : even if we change later, the only impact will be longer trie_id than needed in contract instantiated with the deprecated implementation.

**Pull request merged**
