### PR TITLE
contracts: No longer put delta keys back after a failed restoration

### PR DESCRIPTION
**Pull request by athei**
With the introduction of storage transactions it is no longer necessary to put the delta keys pack to the restorer contract on failure. This is because the error will trigger the current's contract storage transaction to rollback anyways. Please note that restoration can only be triggered from within a contract so we know that there is a transaction ongoing.

This also extends the existing restorations tests to also explicitly check whether the delta keys is still there after a failed restoration

### CODE REVIEW

**Comment by thiolliere** [comment]
as far as I cann see seal_restore_to doesn't rollback anythin, it just calls directly:
```rust
		if let Ok(()) = ctx.ext.restore_to(
			dest,
			code_hash,
			rent_allowance,
			delta,
		).map_err(|e| ctx.store_err(e)) {
			ctx.trap_reason = Some(TrapReason::Restoration);
		}
		Err(sp_sandbox::HostError)
```

**Comment by athei** [comment]
Every call of a contract is executed under a storage transaction which is rolled back on error:
https://github.com/paritytech/substrate/blob/2bc674a10957a3dd9ed30a5c1256e9134d9a5cab/frame/contracts/src/exec.rs#L399

The error from `seal_restore_to` is bubbled up until this point.

**Review by thiolliere — APPROVED** [review]
looks good to me, I thought a failing restore_to would return to contract execution, but no it traps. Thus it is indeed rollbacked.

**Review by ascjones — APPROVED** [review]
LGTM

**Comment by athei** [comment]
bot merge

**Pull request merged**
