### PR TITLE
Update `subkey` README.md

### PR DESCRIPTION
**Pull request by NukeManDan**
getsubstrate.io is not maintained.

Perhaps other things should be updated here in this PR too - open to suggestions!

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
>getsubstrate.io is not maintained.

Hm, I will try to find out what we can do about this.

**Comment by ggwpez** [comment]
bot merge

**Comment by kianenigma** [comment]
@Rashmirreddy probably best to decommission this as well.

**Comment by aaronbassett** [comment]
`getsubstrate.io` is mentioned in a few other public places as well:

- [paritytech/polkadot](https://github.com/paritytech/polkadot) · [‎README.md](https://github.com/paritytech/polkadot/blob/0b56bcdb07752f3c2f369963d2c47eced549320d/README.md?plain=1#L167)
- [paritytech/substrate](https://github.com/paritytech/substrate) · [‎docs/README.adoc](https://github.com/paritytech/substrate/blob/5591c9b8cb346e356d2e9a63064af2f61bd54bd1/docs/README.adoc#L122)
- [paritytech/substrate-up](https://github.com/paritytech/substrate-up) · [‎README.md](https://github.com/paritytech/substrate-up/blob/48af1b6cbb6314b4c958d1a9a4a6b445230aa784/README.md?plain=1#L20)
- [paritytech/parity-website](https://github.com/paritytech/parity-website) · [‎blog/how-to-build-your-own-blockchain-using-parity-substrate/index.mdx](https://github.com/paritytech/parity-website/blob/de90c798b745aa5e498633bc551df0506501fbff/blog/how-to-build-your-own-blockchain-using-parity-substrate/index.mdx#L24)

I'm also happy to update these docs if `getsubstrate.io` is getting decommissioned.

Where would be best to create a new issue to track this? [paritytech/scripts](https://github.com/paritytech/scripts)?

**Pull request merged**
