### PR TITLE
Add PolkaFoundry, PolkaSmith SS58 address

### PR DESCRIPTION
**Pull request by thanhtung6824**
This PR adds an account prefix for PolkaFoundry, PolkaSmith network.

Github: https://github.com/polkafoundry/newpolka
Website: https://polkafoundry.com/

### CODE REVIEW

**Comment by thanhtung6824** [comment]
Hi @BenWhiteJam. Could you review it?

**Comment by BenWhiteJam** [comment]
@thanhtung6824 can you please reach out in Element?

**Review by BenWhiteJam — APPROVED** [review]
fine from BD side.

- [x] contact
- [x] testnet
- [x] code repo
- [x] support
- [x] community

**Comment by bkchr** [comment]
@thanhtung6824 can you please merge master

**Comment by thanhtung6824** [comment]
@BenWhiteJam Thank you for reviewing ;) 
@bkchr I've merged from master.

**Comment by bkchr** [comment]
Ty

**Review by bkchr — APPROVED** [review]

**Pull request merged**
