### PR TITLE
check line width not needed

### PR DESCRIPTION
**Pull request by gilescope**
(`cargo fmt` already checks this)

### CODE REVIEW

**Review by TriplEight — APPROVED** [review]
thanks!

**Review by thiolliere — APPROVED** [review]

**Comment by thiolliere** [comment]
bot merge

**Review by kianenigma — APPROVED** [review]
great!

**Comment by gilescope** [comment]
The test is failing because it's run in release mode and we don't panic in release mode:

```
	fn insert_node_unchecked(&mut self, mut node: Node<T>) {
		if let Some(tail) = &self.tail {
			if *tail == node.id {
				// this should never happen, but this check prevents one path to a worst case
				// infinite loop.
				debug_assert!(false, "system logic error: inserting a node who has the id of tail");
				crate::log!(warn, "system logic error: inserting a node who has the id of tail");
				return
			};
		}
<snip>
```

Hope peeps are happy with the test fix?

**Comment by thiolliere** [comment]
how did it end up in master then ? CI changed ?

**Review by thiolliere — APPROVED** [review]
the modification of the test makes sense to me

**Comment by thiolliere** [comment]
@emostov if you want you can take a look at the test fix

**Comment by thiolliere** [comment]
bot merge

**Comment by emostov** [comment]
> @emostov if you want you can take a look at the test fix

yup, changes look good to me - thanks

**Pull request merged**
