### PR TITLE
feat: add event SkepticsChosen event in society

### LINKED ISSUE #13275: add `SkepticsChosen` event to society
as it helps with reporting. Although, we've been wanting to merge #11324 for ages as well... but no harm in adding the few lines of a new event to the v1 pallet.

### PR DESCRIPTION
**Pull request by gitofdeepanshu**
Fix #13275

## Description 
Added event `SkepticsChosen` in society v1 pallet.

## ToDo
- [x] add event
- [x] add tests

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
One test please.

**Comment by gitofdeepanshu** [comment]
> One test please.

Hey @ggwpez , can you point me to the code where I can find similar tests? I tried searching for similar tests in the society pallet's tests but couldn't find tests that check for emitted events.

**Comment by ggwpez** [comment]
The function that you can use here is called `assert_last_event`. For example in the [society tests](https://github.com/paritytech/substrate/blob/3e9182366f31ee93473a43d2afedf1357e2df7a8/frame/alliance/src/tests.rs#L549).  
Note that events are not deposited in the genesis event, so somewhere a `System::set_block_number(1)` is needed.

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
