### PR TITLE
remove unused deps pulled by parity-util-mem

### PR DESCRIPTION
**Pull request by ordian**

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by thiolliere — APPROVED** [review]
don't we want to add feature `std` of parity-util-mem when `std` feature is activated ?

**Comment by ordian** [comment]
> don't we want to add feature std of parity-util-mem when std feature is activated ?

I don't think so, this is a dev-dependency and the `std` feature of `parity-util-mem` doesn't seem to be used in tests.

**Comment by ordian** [comment]
daec823677de5cdf3148f944e29a0a2032ac23d9 fixes a warning (`blake2s_simd` is no longer used).

**Comment by thiolliere** [comment]
> > don't we want to add feature std of parity-util-mem when std feature is activated ?
> 
> I don't think so, this is a dev-dependency and the `std` feature of `parity-util-mem` doesn't seem to be used in tests.

Yes ok then

**Comment by ordian** [comment]
bot merge

**Comment by thiolliere** [comment]
bot merge

**Pull request merged**
