### PR TITLE
Remove the legacy requests-answering protocols

### PR DESCRIPTION
**Pull request by tomaka**
Finishes removing support for the block requests, finality requests, and light client requests protocols from `protocol.rs`.

All these protocols are already handled by other pieces of code elsewhere.

I'm marking this as `onice` because I first would like to confirm with https://github.com/paritytech/substrate/pull/6698 that we don't receive such requests anymore. At the moment it seems to be the case on my personal node, as this metric stays at 0, but I'd like to see it deployed on nodes that get more traffic.

### CODE REVIEW

**Comment by tomaka** [comment]
Update: it turns out that we still receive some requests, albeit very few and on isolated nodes. I need to investigate first.
This PR will likely remain on ice for at least another week or so.

**Comment by tomaka** [comment]
We still receive block requests on the legacy substream, therefore I've changed the PR remove everything but the block requests.

**Comment by gavofyork** [comment]
Needs resolving.

**Comment by tomaka** [comment]
bot merge

**Comment by tomaka** [comment]
bot rebase

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
