### PR TITLE
Update wasmtime to 0.27

### PR DESCRIPTION
**Pull request by pepyakin**
A couple of notes:

- Now we are fair about unsafeness of runtime creation via an compiled artifact.
  This change was prompted by the change in wasmtime which made
  `deserialize` rightfully unsafe. Now `CodeSupplyMode` was hidden and
  the `create_runtime` now takes the blob again and there is now a new
  fn for creating a runtime with a compiled artifact.
- This is a big change for wasmtime. They switched to the modern backend
  for code generation. While this can bring performance improvements, it
  can also introduce some problems. In fact, 0.27 fixed a serious issue
  that could lead to sandbox escape. Hence we need a proper burn in.

This would require a change to PVF validation host as well.

polkadot companion: https://github.com/paritytech/polkadot/pull/3114

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by pepyakin** [comment]
While we are waiting for the situation with regalloc dealt with, I added a filter for everything related to the `regalloc` crate. Now this needs a burnin.

**Comment by bkchr** [comment]
@pepyakin did you created an upstream pr?

**Comment by pepyakin** [comment]
Yes, https://github.com/bytecodealliance/regalloc.rs/pull/123

**Comment by pepyakin** [comment]
The [burn-in](https://github.com/paritytech/polkadot/pull/3132) synced without any issue.

**Comment by pepyakin** [comment]
bot merge

**Pull request merged**
