### PR TITLE
babe: remove error fallback from threshold calculation

### LINKED ISSUE #5753: Make  BABE's `calculate_primary_threshold​` test more robust.
It uses `?`on `None`, which should logically never happen, and falls back to `u28::max`. However, if the underlying logic of `BigUint` changed, it could happen. Instead of that fallback, we should use `expect` with proofs making clear that if that assumption changes, we need to handle these cases properly.

### PR DESCRIPTION
**Pull request by andresilva**
When doing the primary threshold calculation in BABE we default to returning `u128::max_value()` in case any error happens in intermediary computations. The computations should not fail and instead "proofs" are given in expects.

Fixes #5753.

### CODE REVIEW

**Comment by andresilva** [comment]
We should do a full resync of kusama with this patch to make sure that the given assumptions weren't violated so far.

**Comment by gnunicorn** [comment]
> We should do a full resync of kusama with this patch to make sure that the given assumptions weren't violated so far.

is this pending prior to a merge?

**Comment by andresilva** [comment]
Just started a Kusama sync with this PR, #5501 and #5514 (Wei had already tested those though). It will still take a while to sync everything from scratch, so if you prefer we can merge this optimistically and revert in case something broke (it shouldn't but I just want to make sure all the invariants actually hold).

**Comment by andresilva** [comment]
Sync completed, no issues.

**Pull request merged**
