### PR TITLE
Rename folder: primitives/sr-primitives -> primitives/runtime

### PR DESCRIPTION
**Pull request by kigawas**
This follows #4223, it should not break anything

`sr-*` can also be renamed in other prs

### CODE REVIEW

**Comment by tomusdrw** [comment]
Just spoke with @ben and we will prepare a meta issue with the list of all expected renames. This should be a series of smaller PRs that shouldn't really be conflicting. I'll probably do it in few hours.

**Comment by kigawas** [comment]
@tomusdrw 
How about the meta issue? I suggest we only rename one folder per pr to mitigate conflicts

**Comment by tomusdrw** [comment]
@kigawas Sorry for the delay, here it is: https://github.com/paritytech/substrate/issues/4318

**Comment by bkchr** [comment]
Needs to be resolved.

**Pull request merged**
