### PR TITLE
Add Sora network SS58 Address

### PR DESCRIPTION
**Pull request by vmarkushin**
This PR adds an account prefix for Sora network.

Signed-off-by: Vladislav Markushin <negigic@gmail.com>

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by vmarkushin** [comment]
@bkchr seems like @gavofyork is a bit busy, can we bring someone to review this faster?

**Comment by shawntabrizi** [comment]
@vmarkushin can you merge master

**Review by apopiak — APPROVED** [review]

**Comment by pgolovkin** [comment]
@apopiak thanks for the approve. 
When this PR might be merged?

**Comment by apopiak** [comment]
bot merge

**Pull request merged**
