### PR TITLE
Rename pallet trait `Trait` to `Config`

### PR DESCRIPTION
**Pull request by thiolliere**
## Breaking changes:

* renames `Trait` to `Config` in all pallets (but pallets can still be declared using `Trait` for trait name)
* renames `Trait` associated type in `Dispatchable` trait to `Config`.

## Description

This PR renames the pallet trait `Trait` to `Config`.

Note that macro still accept having the trait named `Trait` (as tested in `frame/support/test/tests/pallet_with_name_trait_is_valid.rs`). But all pallet defined in substrate now use `Config` instead of `Trait` for their name.

This PR also rename the struct `Config` to `ConfigCache` in `pallet-contracts` in order not to have collision.

Also construct_runtime use the name `Config` for the optional part `GenesisConfig` of a pallet. This can now leads to confusion. But I don't know how to print deprecation in macros :-/ so I prefer to let as is.

To make this PR I did `find . -name "*.rs" -exec sed -i "s/\([^[:alnum:]]\)Trait\([^[:alnum:]]\)/\1Config\2/g" {} \;`
This missed the line where Trait is last word ( `Trait\n` ). So I manually corrected them.
Then I revised all changes and checkout the one which are not relevant (like in doc sometime `Trait` refer to just a rust trait).

polkadot companion: https://github.com/paritytech/polkadot/pull/2014

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]
It compiles, so... approved.

**Comment by kianenigma** [comment]
> This PR also rename the struct Config to ConfigCache in pallet-contracts in order not to have collision.

Someone from contracts should also check, this, otherwise let's do this.

**Review by kianenigma — APPROVED** [review]

**Review by wheresaddie — APPROVED** [review]
approved as it compiles .. :+1:

**Review by athei — APPROVED** [review]

**Comment by thiolliere** [comment]
bot merge

**Comment by ordian** [comment]
bot merge force

**Comment by kianenigma** [comment]
> bot merge force

So who will this command listen to? anyone can force? :P

**Comment by thiolliere** [comment]
as far as I see on https://github.com/paritytech/parity-processbot it does check if merge is allowed so it should check the approve/coredevs/... stuffs

**Pull request merged**
