### PR TITLE
Migrate the pallet macros of some tests and benches

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Polkadot address: 15XuanNimo5951s3RjFTPX1AvYVnCwfr3SDhb3AV4fQF3LpK

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
^ @koushiro

**Comment by koushiro** [comment]
@shawntabrizi updated

**Review by KiChjang — APPROVED** [review]

**Comment by KiChjang** [comment]
bot merge

**Pull request merged**
