### PR TITLE
Reduce overhead of sync state checking

### PR DESCRIPTION
**Pull request by koute**
These `any()` loops were using 5.4% of CPU; now they don't even show in the profile.

I picked this approach since it seemed the simplest and most future-proof, that is: there's no need to manually track and insert a `peer_download_in_progress = false` line everywhere where the `peer.state` might be changed or where the `peer` might be `remove`d altogether (and risk missing some place now and/or in the future after some refactoring); it happens automatically when the state's switched or dropped.

I admit that I'm not super familiar with this code, so I'm not sure if this is the best way to fix it; if you want me to do it in a different way please say so and I'll be happy to oblige.

### CODE REVIEW

**Comment by tomaka** [comment]
The sync state machine is fully synchronous, I don't think it's a good idea to introduce locks

**Comment by koute** [comment]
> The sync state machine is fully synchronous, I don't think it's a good idea to introduce locks. The `Arc<AtomicBool>`s that you add could simply be `bool` and it be more simple and have the same effect.

Sorry, maybe the name is not perfect, but it *is* a bool, it's just an `Arc<AtomicBool>` so that it can be automatically set to `false` on `Drop` without doing it manually. (:

I can change it into a normal `bool`, but then that will have to be set to `false` manually instead of letting `Drop` automatically take care of it.

**Comment by arkpar** [comment]
There's already a mechanism that prevents excessive examinations of sync state when `poll` is called too frequently. That's the `PendingRequests` enum, (should be called `AllowedRequests` btw`). For the exclusive warp/state sync we can add a `None` variant. Set to `None` when there's an active state request and back to `All` when the response is complete.
I can make a PR for it if you want, @koute

**Comment by koute** [comment]
> There's already a mechanism that prevents excessive examinations of sync state when `poll` is called too frequently. That's the `PendingRequests` enum, (should be called `AllowedRequests` btw). For the exclusive warp/state sync we can add a `None` variant. Set to `None` when there's an active state request and back to `All` when the response is complete. I can make a PR for it if you want, @koute

@arkpar That might be better; if you could whip up a PR I could hook it up to the profiler and see whether this PR will still be necessary or not.

**Comment by arkpar** [comment]
See #10843

**Comment by koute** [comment]
https://github.com/paritytech/substrate/pull/10843 achieves the same effect, so let's go with that one.

**Pull request closed without merging**
