### PR TITLE
add TypeInfo trait bound for pallet-assets' attribute config

### PR DESCRIPTION
**Pull request by 0x8f701**
close: #10030

### CODE REVIEW

**Comment by bkchr** [comment]
bot merge

**Comment by GopherJ** [comment]
@bkchr can we backport this to polkadot-v0.9.11 branch? I kind need it

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Comment by GopherJ** [comment]
@bkchr do you know why the CI always fail?  Am I wrong on something?

**Comment by bkchr** [comment]
Backported

**Pull request merged**
