### PR TITLE
Fix polkadot companion test

### PR DESCRIPTION
**Pull request by bkchr**

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
even on insubstantial now?

**Review by TriplEight — APPROVED** [review]

**Comment by bkchr** [comment]
> even on insubstantial now?

Bot is broken :P

**Comment by shawntabrizi** [comment]
everything is broken

**Pull request merged**
