### PR TITLE
Revert "Abstracts elections-phragmen pallet to use NposSolver (#12588)"

### PR DESCRIPTION
**Pull request by gpestana**
This reverts commit 4be5dd2937ab9fffd4f13772b547450a95a59018 (i.e. https://github.com/paritytech/substrate/pull/12588)

### CODE REVIEW

**Review by rossbulat — APPROVED** [review]

**Review by kianenigma — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Some benchmarking error blocking the CI https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2435418

**Comment by ggwpez** [comment]
bot merge

**Comment by gpestana** [comment]
bot merge

**Comment by kianenigma** [comment]
had my dose of flaky CI for the week, if after the restart it is not green I will just manually merge.

**Pull request merged**
