### PR TITLE
Add codeownership for runtime lib.rs's files

### PR DESCRIPTION
**Pull request by sergejparity**
This PR update CODEOWNERS file by assigning code ownership of `runtime's` `lib.rs` files to @paritytech/substrateteamleads according to this [issue](https://github.com/paritytech/ci_cd/issues/233)
Whether submitted PR touches one of above mentioned files it will require at least one approval from  @paritytech/substrateteamleads

### CODE REVIEW

**Comment by sergejparity** [comment]
> As a team lead that never touches anything related to the runtime whatsoever (I don't think I was concerned by this issue), can I somehow exclude myself/disable these notifications?
Hi @tomaka 
I'm afraid it is quite problematic. Other solution would be to use persons list instead of paritytech/substrateteamleads group. But this will require manual update on every group change.

**Comment by tomaka** [comment]
I could also remove myself from that GitHub team. I don't really see what it brings to be in there.

**Review by TriplEight — APPROVED** [review]

**Comment by kianenigma** [comment]
I kinda feel like it is 100x more important to have this in polkadot repo. The `substrate-node` is not deployed anywhere and is essentially a kitchen sink of all pallets.

**Comment by TriplEight** [comment]
@kianenigma don't worry, `CODEOWNERS` will be everywhere at some point.

**Review by alvicsam — APPROVED** [review]

**Comment by gnunicorn** [comment]
> @tomaka  I could also remove myself from that GitHub team. I don't really see what it brings to be in there.

I agree with this. I think we should re-consider using that team and/or Github team structure for that in general. This team was initially created to allow for some release-based shortcuts and overwrites, but hasn't been maintained nor given any other special privileges or responsibilities since. I doubt that it is (as it currently exists) up to date in terms of the members, nor is it maintained and – in this area – shoots further than what is applicable. I and @tomaka (as current members of that team) shouldn't even have these privileges. I think using a newly created `runtime-owners`-github-team makes a lot more sense...

**Comment by TriplEight** [comment]
Well, actually this change is not needed for how we decided to implement this check. It will be a separate CI job and all this logic including mentioning the reviewers groups.
@gnunicorn you're right, this should be a separate group. In my opinion, all these groups assignments should be maintained by security team and be a part of on-/offboarding processes.

**Pull request closed without merging**
