### PR TITLE
Import hex_literal into runtime only for benchmarks.

### PR DESCRIPTION
**Pull request by kianenigma**

### CODE REVIEW

**Comment by sjeohp** [comment]
An annoying thing about the projects api is that it needs to be added to a project column (ie not triage), not just a project

**Comment by kianenigma** [comment]
Is it mandatory though? Like, every insubstantial PR also needs a project?

**Comment by sjeohp** [comment]
If a substrate team lead requests the merge then the project is bypassed, but otherwise currently yes.  We will add a check for `insubstantial` soon and at the same time bypass project for prs with sufficient core reviews, so ultimately project should only be required for project leader merges (!= substrate team leads).  It's still pretty messy atm.

**Comment by shawntabrizi** [comment]
bot merge

**Comment by sjeohp** [comment]
my mistake - project is already bypassed if there are sufficient core reviews

**Pull request merged**
