### PR TITLE
Rename `decl_module` to `decl_dispatch`

### PR DESCRIPTION
**Pull request by shawntabrizi**
* Renamed all instances of `decl_module` to `decl_dispatch`
* added `$crate::` to all the macro uses so that it is automatically expored
* Created a forwarder macro which simply takes any existing usage of `decl_module` and forwards to `decl_dispatch`
* Added a deprecated flag to show a warning when `decl_module` is used
* Updated all instances of `decl_module` within Substrate
* Bumped spec version and compiled new Wasm

Solves https://github.com/paritytech/substrate/issues/1960

EDIT:

Error looks like:
```
Compiling srml-contract v0.1.0 (C:\Users\shawn\Documents\GitHub\substrate\srml\contract)
warning: use of deprecated item 'sr_api_hidden_includes_decl_storage::hidden_include::decl_module': The `decl_module!` macro has been renamed to `decl_dispatch!`. `decl_module!` will be removed in Substrate v1.1.
  --> srml\session\src\lib.rs:24:62
   |
24 | use srml_support::{StorageValue, StorageMap, for_each_tuple, decl_module, decl_event, decl_storage};
   |                                                              ^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default
```

### CODE REVIEW

**Comment by shawntabrizi** [comment]
When this is ready to merge, we need to also update all documentation

**Comment by bkchr** [comment]
I just wanted to comment on the issue, but now you are faster. I think we should not go this way of renaming it to `decl_dispatch`. We not only create dispatchables with this macro, we also accept stuff like `deposit_event`, `on_finalise` and `on_initialise`. So, the new name hides some functionality.

**Comment by xlc** [comment]
Is it possible to create a `Module` struct without `decl_dispatch`/`decl_module`?
Is it possible to create a runtime module without the `Module` struct?

**Comment by bkchr** [comment]
@xlc: You can create all the stuff the macro is doing manually, that works.

**Comment by xlc** [comment]
My point is the current decl_module does more thing than just declare dispatchable functions. It also declare the Module struct, which is mandatory struct for a runtime module. 
I expect decl_dispatch will be an optional macro that does not need to be used for runtime module without dispatchable functions. e.g. the fees module.

**Comment by gavofyork** [comment]
ok - i'm not that bothered. if it's going to be more confusing for people then we can ditch the idea.

**Pull request closed without merging**
