### PR TITLE
contracts: deposit_event benchmarks refactoring

### PR DESCRIPTION
**Pull request by agryaznov**
Tune the *per_byte* benchmark for deposit_event host function.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2734897

**Comment by agryaznov** [comment]
bot clean
bot bench $ pallet dev pallet_contracts

**Comment by agryaznov** [comment]
bot clean

**Comment by agryaznov** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by agryaznov** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2742527

**Comment by agryaznov** [comment]
bot bench $ pallet dev pallet_contracts

**Pull request closed without merging**
