### PR TITLE
Removal of light client from substrate

### PR DESCRIPTION
**Pull request by gilescope**
As discussed in the retreat we are simplifying before refactoring by not shipping a light client out of the box with substrate. (Current users should look towards https://github.com/paritytech/substrate-connect as a purpose built solution to this usecase)
 
The client network tests that support light client requests use a full light client at the moment which is why more is not initially removed.

polkadot companion: https://github.com/paritytech/polkadot/pull/4105

skip check-dependent-cumulus

### CODE REVIEW

**Comment by bkchr** [comment]
Status?

**Comment by arkpar** [comment]
There's a lot of stuff that may be removed from `client/db` as well. Also I guess we can remove everything related to CHTs as well.

**Comment by TriplEight** [comment]
skip check-dependent-cumulus

**Comment by bkchr** [comment]
> @arkpar the problem I have removing the light client db is that the networking tests test light client rpc functionality and the 'test' light client uses the light client db at the moment.

Just have read this. The task of this pr is to remove this stuff. I mean these light client tests make sense and should stay, but then we need a refactoring or whatever. However, most/all of the crate should be removed.

**Comment by arkpar** [comment]
@bkchr I'll remove the rest of the light client stuff along with CHTs and change tries in the follow-up PR. I think we can merge this one as it is.

**Comment by gilescope** [comment]
bot merge

**Pull request merged**
