### PR TITLE
cumulus v0.9.30 cherry pick bench fix from master

### PR DESCRIPTION
**Pull request by muharem**
Cherry pick the benchmarks fix from master
Fix PR https://github.com/paritytech/substrate/pull/12482

substrate companion branch: cumulus-v0.9.30
polkadot companion branch: release-v0.9.30
cumulus companion branch: polkadot-v0.9.30

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
The CI shows a merge conflict but GitHub does not…

**Comment by chevdor** [comment]
Let's not modify the `polkadot-v0.9.30` branch as Polkadot v0.9.30 was already released.
Can you edit this PR against https://github.com/paritytech/substrate/tree/cumulus-v0.9.30 please ?

**Comment by muharem** [comment]
> Let's not modify the `polkadot-v0.9.30` branch as Polkadot v0.9.30 was already released. Can you edit this PR against https://github.com/paritytech/substrate/tree/cumulus-v0.9.30 please ?

done

**Comment by chevdor** [comment]
After a bit of convincing, our CI turned green on a few more points:
https://gitlab.parity.io/parity/mirrors/substrate/-/pipelines/222413

**Comment by chevdor** [comment]
```
cargo test --no-run --message-format json-render-diagnostics --workspace --exclude node-cli --release --features runtime-benchmarks --locked
```
passed locally.

**Review by chevdor — APPROVED** [review]

**Pull request closed without merging**
