### PR TITLE
Move sc-allocator to sp-allocator

### PR DESCRIPTION
**Pull request by yjhmelody**
Since allocator can be no_std, we should make it be so.
It make sense when use such as wasmi.

### CODE REVIEW

**Comment by gilescope** [comment]
`sp-` is for code that is shared between the client and the runtimes. 

Are you intending that runtimes might want to use it in future?

**Comment by yjhmelody** [comment]
> `sp-` is for code that is shared between the client and the runtimes.
> 
> Are you intending that runtimes might want to use it in future?

Yes.

**Comment by yjhmelody** [comment]
@gilescope Any other problems ?

**Comment by gilescope** [comment]
Not from me :-)

**Comment by yjhmelody** [comment]
@bkchr Can we move the crate ?

**Comment by yjhmelody** [comment]
@gilescope Hi, could anyone else give me feed back ? I want to push on this PR.

**Comment by koute** [comment]
>>  Are you intending that runtimes might want to use it in future?
>
> Yes.

Could you expand on your motivation as to why you want to do this?

**Comment by yjhmelody** [comment]
> Could you expand on your motivation as to why you want to do this?

Just want to use this allocator for wasmi in no_std.

**Comment by yjhmelody** [comment]
@koute Any other confused?

**Comment by koute** [comment]
So do you want to use this as an allocator for smart contracts running under wasmi?

This allocator isn't really a general-purpose allocator, and isn't really meant to be used for anything other than a runtime allocator. We also can't really change it *too much* due to backward-compatibility concerns (since it's exposed by the client through the host API any substantial changes might make it impossible to sync a chain from scratch).

Have you considered using something like [wee_alloc](https://crates.io/crates/wee_alloc) or [bumpalo](https://crates.io/crates/bumpalo)? Those crates would be more appropriate to use in a `no_std` context.

**Comment by yjhmelody** [comment]
More precisely we want to run one runtime in another runtime.

**Comment by gilescope** [comment]
Mind blown. Gotta hear the use case for this.

**Comment by yjhmelody** [comment]
Anyone could give me a feedback?

**Pull request closed without merging**
