### PR TITLE
Fix db metadata updates for existing headers

### PR DESCRIPTION
**Pull request by arkpar**
Makes sure finality and "best" status are still applied when re-importing existing blocks. A case for cumulus.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
This looks good.

However, I'm still not very happy that you can shoot yourself in the foot by setting some lower block as best block and we may end in some irreversible situation. (Because we the mapping from block number to hash doesn't exist anymore)

**Review by andresilva — APPROVED** [review]

**Comment by arkpar** [comment]
Setting lower block as best block is required by BABE fork choice rule. BABE prefers primary blocks even if there are sibling secondary blocks with more children. I guess we could produce an error when the head is reset too far behind by an arbitrary chosen number of blocks.

**Comment by bkchr** [comment]
>  I guess we could produce an error when the head is reset too far behind by an arbitrary chosen number of blocks.

Yeah, could we not use `canonicalization_delay` for that?

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
