### PR TITLE
Make language consistent. referendums -> referenda

### PR DESCRIPTION
**Pull request by JoshOrndorff**
I feel strongly that we should choose a single proper plural for referendum, although I don't feel strongly _which_ one we choose.

Mirriam-Webster says either is okay (https://www.merriam-webster.com/dictionary/referendum).

This PR settles on `referenda`

### CODE REVIEW

**Comment by joepetrowski** [comment]
I prefer referenda and [so do most publications](https://books.google.com/ngrams/graph?content=referendums%2C+referenda&case_insensitive=on&year_start=1800&year_end=2010&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Creferendums%3B%2Cc0%3B%2Cs0%3B%3Breferendums%3B%2Cc0%3B%3BReferendums%3B%2Cc0%3B.t4%3B%2Creferenda%3B%2Cc0%3B%2Cs0%3B%3Breferenda%3B%2Cc0%3B%3BReferenda%3B%2Cc0#t4%3B%2Creferendums%3B%2Cc0%3B%2Cs0%3B%3Breferendums%3B%2Cc0%3B%3BReferendums%3B%2Cc0%3B.t4%3B%2Creferenda%3B%2Cc0%3B%2Cs0%3B%3Breferenda%3B%2Cc0%3B%3BReferenda%3B%2Cc0).

Should make sure it's OK to rename these public functions though.

**Comment by gavofyork** [comment]
This breaks the API. Will need a runtime version bump and entry in release notes.

**Comment by JoshOrndorff** [comment]
I guess this got auto-closed when I force pushed. Should have known better. I've bumped the version number on my fork, but unsure where the release notes go.

Also unsure how to proceed. Maybe one of:
1. Someone with more permissions re-opens
2. Start a new PR
3. Forget about about this change

**Comment by bkchr** [comment]
Your commit history contains no commits, that must be the reason why github closed it. You have done something wrong while pushing your commits. Please always use merge commits to make reviewing easier.

**Pull request closed without merging**
