### PR TITLE
Fix broken link to democracy pallet.

### PR DESCRIPTION
**Pull request by humb1t**
Old link was broken, and I put a new one.

### CODE REVIEW

**Comment by thiolliere** [comment]
it seems this readme is automatically generated, all documentation links are broken I don't know if it worth it fixing them manually.

**Review by kianenigma — CHANGES_REQUESTED** [review]
Indeed this needs to be fixed in the source code documentation. 

I think fixing all links is a b=huge endeavour and before we do it we must make sure we have a CI check for it, otherwise the results will be broken very soon again.

**Comment by thiolliere** [comment]
Those links are broken in the source code. it works for the generated doc https://substrate.dev/rustdocs/v2.0.0-rc6/pallet_sudo/index.html

Maybe rust now has new ways to link to other crates that I'm not aware of though.

**Comment by bkchr** [comment]
Maybe we should just remove this "related" module. Because it actually doesn't make that much sense.

**Pull request merged**
