### PR TITLE
Update syn and fix compilation

### PR DESCRIPTION
**Pull request by bkchr**
Fixes: https://github.com/paritytech/substrate/issues/11706

polkadot companion: https://github.com/paritytech/polkadot/pull/5701
cumulus companion: https://github.com/paritytech/cumulus/pull/1388

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Comment by xlc** [comment]
can we have this back ported to 0.9.24

**Review by dvdplm — APPROVED** [review]

**Comment by bkchr** [comment]
> can we have this back ported to 0.9.24

You can just pin syn in your project.

**Comment by xlc** [comment]
Not as a library. But we have a workaround https://github.com/open-web3-stack/open-runtime-module-library/pull/779

**Review by KiChjang — APPROVED** [review]

**Comment by bkchr** [comment]
> Not as a library. But we have a workaround [open-web3-stack/open-runtime-module-library#779](https://github.com/open-web3-stack/open-runtime-module-library/pull/779)

Yeah downstream would need to do this. But yeah, I will backport it.

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
