### PR TITLE
sp-core-hashing: use the `digest::Digest` trait to handle the hashing function uniformly

### PR DESCRIPTION
**Pull request by koushiro**
## Description

- Replace some dependencies (in order to use `digest::Digest` to handle the hashing functions uniformly)

  - use `sha3` instead of `tiny-keccak`  for `Keccak256` and `Keccak512`
  - use `blake2` instead of `blake2-rfc` for `Blake2b64`, `Blake2b128`, `Blake2b256` and `Blake2b512`

- Reduce some boilerplate code

---

polkadot companion: https://github.com/paritytech/polkadot/pull/4907

polkadot address: 15XuanNimo5951s3RjFTPX1AvYVnCwfr3SDhb3AV4fQF3LpK

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by cheme** [comment]
Looks like keccak implementation is now on par with tiny-keccak, but looks like blake is a bit underperforming (only on small data, seems to be a constant overhead).
Will check again next week.

**Comment by cheme** [comment]
Well difference is actually not that relevant at size different than 32 bytes, so switching could be a good idea.

**Review by cheme — APPROVED** [review]
Looking at of both blake crate, the rust-crypto one did update its simd backend for recent compiler, so that is a big win for those who want to do a custom build (requires nightly).

But the perfs seems to be ~6% slower for 128 bytes content (overhead looks constant).

So I am a bit mixed on the switch, but would go for it. CC\ @burdges in case there is other reason for staying with blake2-rfc or tiny-keccak.

**Comment by burdges** [comment]
I'd raise this issue on rust-crypto/hashes crate.  We can ask if they want help improving those and/or put a bounty on improvements or offer funding.

**Comment by burdges** [comment]
I'll caution however that storage should eventually migrate toward custom hashing, for which the digest crate does not suffice, but it's fine for when using regular hash functions of course.

**Comment by cheme** [comment]
> I'd raise this issue on rust-crypto/hashes crate. We can ask if they want help improving those and/or put a bounty on improvements or offer funding. It's also possible they know build conditions that improve performance.

Not sure the little overhead is worth chasing (on the other hand if we find a way to build with simd there is good gain).

**Comment by koushiro** [comment]
@bkchr @cheme  could you merge this PR?

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
