### PR TITLE
Prepare `sp-runtime` for publication

### PR DESCRIPTION
**Pull request by dvdplm**
Prepare `sp-runtime` for publication.

Screenshot 2021-12-10 at 14 58 51

### CODE REVIEW

**Review by niklasad1 — APPROVED** [review]
LGTM,

needs a polkadot companion though.

**Comment by jsdw** [comment]
> needs a polkadot companion though.

Why is that?

**Comment by dvdplm** [comment]
> needs a polkadot companion though.

I don't think I can open a companion before the crates are published. I'll make one as soon as the crates from this PR are published.

**Review by insipx — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> > needs a polkadot companion though.
> 
> I don't think I can open a companion before the crates are published. I'll make one as soon as the crates from this PR are published.

Ignore it.

**Pull request merged**
