### PR TITLE
Remove deprecated old weight items

### LINKED ISSUE #14666: [Deprecation] deprecate "old" weight items
The deprecated items in `frame/support/sec/[weights.rs` need to be removed

### PR DESCRIPTION
**Pull request by Doordashcon**
related to paritytech/polkadot-sdk#144

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3328667

**Comment by juangirini** [comment]
bot fmt

**Review by juangirini — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Nice!

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
