### PR TITLE
Define ss58 prefix inside the runtime

### PR DESCRIPTION
**Pull request by athei**
Historically, the ss58 prefix is declared as a [property of a chain spec](https://github.com/paritytech/substrate/blob/b44221489f0c491e2b1d797a9c7f65ef6f045ed6/client/chain-spec/src/lib.rs#L145). These properties are inaccessible for the runtime but [can be queried verbatim by any RPC client](https://github.com/paritytech/substrate/blob/b44221489f0c491e2b1d797a9c7f65ef6f045ed6/client/rpc-api/src/system/mod.rs#L52-L54) in order to learn about the prefix of a chain along with other properties like the currency symbol or denomination.

While ss58 parsing is firmly **not**  one of the runtime's responsibilities there are other reasons why the runtime might want to know about this prefix. One of them is using it as an identifier of the chain. At least in order to expose it to contracts. 

To that end we promote the ss58 prefix from a chain spec property to a member of the frame_system configuration trait so that the runtime is aware of this value. The frame_system module exposes it in its metadata so that rpc clients can access it. The chain spec property based approach to learn about the ss58 prefix is therefore considered deprecated. @jacogr 

There is a `fn chain_id` [runtime interface](https://github.com/paritytech/substrate/blob/b44221489f0c491e2b1d797a9c7f65ef6f045ed6/primitives/io/src/lib.rs#L391-L394) that is supposed to expose an identifier to the runtime but it was never properly implemented (it returned hardcoded 42). This PR removes removes this unused interface because the ss58 prefix should be used as identifier (or any other identifier determined by the runtime).

polkadot companion: https://github.com/paritytech/polkadot/pull/2182

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by xlc** [comment]
This closes https://github.com/paritytech/substrate/issues/3990

**Comment by athei** [comment]
bot merge

**Comment by sorpaas** [comment]
> There is a fn chain_id runtime interface that is supposed to expose an identifier to the runtime but it was never properly implemented (it returned hardcoded 42). This PR removes removes this unused interface because the ss58 prefix should be used as identifier (or any other identifier determined by the runtime).

This is actually a runtime breaking for anyone already using this interface, and it's actually really hard for any existing runtime to adopt this change if they happen to use it. The thing is, any existing runtime which already used `misc::chain_id` will simply refuse to execute when they cannot import the wasm extern `chain_id`. In the mean time, there is no way to fix those broken runtime because they are already on-chain.

My recommendation is that we never remove any runtime interface **ever** if they already made it into a stable release (in our case, `chain_id` is at least in v2.0.0). We can instead use versioning and other methods to properly document that those APIs should not be used in the future.

**Comment by athei** [comment]
While I agree with you that removing runtime interfaces should never be done I had a hard time imagining some actual live runtime which make use of an interface that returns hardcoded 42. This contributed to not applying the same level of strictness here that we would use for other runtime interfaces.

**Pull request merged**
