### PR TITLE
Remove pub in macros

### PR DESCRIPTION
**Pull request by guanqun**
This needs the latest rust version of 1.30.0 
This patch would save us lots of similar code. about 800 lines removed.

### CODE REVIEW

**Comment by bkchr** [comment]
Nice ty, I will take a closer look later.

**Comment by bkchr** [comment]
[clabot:check]

**Comment by guanqun** [comment]
Thank you for the review! The only short-term inconvenience is that all developers need to upgrade to 1.30.0 version...

**Comment by bkchr** [comment]
I know, but I already merged a pull request before yours from me, that required 1.30.0. And I think all of us work with rust nightly anyway 👍

**Pull request merged**
