### PR TITLE
Move Get and bounded types to sp-core

### PR DESCRIPTION
**Pull request by KiChjang**
This PR moves the `Get` traits, bounded types and associated macros to `sp-core` from `sp-runtime`.

The motivation here is a recognition that these types and traits don't really require a notion of the runtime, and are simply plain Rust new types that can be generally applied everywhere, which then makes it easier for new crates to resolve circular dependency issues as they do not necessarily need to depend on `sp-runtime`, but rather something even more basic and primitive than it.

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Comment by bkchr** [comment]
Can you be more specific on why this is needed? Where are we having circular depedencies?

**Review by shawntabrizi — APPROVED** [review]
would like basti's question to be answered, but it makes sense to me

**Comment by KiChjang** [comment]
@bkchr I'm in the middle of creating a new crate called `sp-weights`, with the intention of moving the `Weight` struct to it. The `Get` trait lives in `sp-runtime`, and some of the `Weight` impls depend upon it, so before this PR, `sp-weights` would have to depend upon `sp-runtime`, which could be problematic as the `DispatchInfo` stuff in `sp-runtime` depends on the `Weight` struct as well, creating a circular dependency.

**Review by bkchr — APPROVED** [review]

**Comment by KiChjang** [comment]
bot merge

**Pull request merged**
