### PR TITLE
Remove peerset debug output test

### PR DESCRIPTION
**Pull request by bkchr**
This test failed, I assume that the latest nightly changed the format of the debug output. I think we should not test this debug output, as there is no real value in it. Correct me if I'm wrong.

### CODE REVIEW

**Comment by Kianenigma** [comment]
Confirm that it is failing, the values are the same, and the test should probably be reformatted to compare the actual values.

**Comment by Kianenigma** [comment]
Though, I would probably either change the test or at least mark it as ignore so that the original author would fix it later.

**Comment by bkchr** [comment]
I requested review of the original author and as I have written in the pr description, I don't see any reason for testing the debug output. I don't see any value in testing the debug output of a struct.

**Comment by bkchr** [comment]
@Kianenigma could you maybe review this one?

**Comment by Kianenigma** [comment]
What I meant earlier was if the _content_ of the struct should be checked or not. I have no clue what the content of the struct was and why it was being tested in the first place, if you or @debris are in peace with it then this is good to go.

**Pull request merged**
