### PR TITLE
Run tests for the wasmer sandbox

### PR DESCRIPTION
**Pull request by rcny**
Resolves https://github.com/paritytech/ci_cd/issues/179.

### CODE REVIEW

**Review by athei — APPROVED** [review]
Looks good. Thanks.

**Review by sergejparity — APPROVED** [review]

**Comment by rcny** [comment]
bot merge

**Comment by rcny** [comment]
bot merge force

**Comment by rcny** [comment]
IMO there has to be a project owner for CI.

**Pull request merged**
