### PR TITLE
Replace JSON metadata with custom metadata structures

### PR DESCRIPTION
**Pull request by bkchr**
Requires: https://github.com/paritytech/parity-codec/pull/1

### CODE REVIEW

**Comment by gavofyork** [comment]
Can you explain why there's a need to allow no_std/wasm environments to be able to `Decode` into a `String` or `Cow::Owned`?

**Comment by bkchr** [comment]
Yeah that is not required. I just did not thought about just disabling it on `no_std`...

**Comment by bkchr** [comment]
Okay, I disabled decoding on `no_std` and compilation now works :)

**Comment by gavofyork** [comment]
Ok - so the point of this was to remove the dependency on any `RuntimeMetadata` from `core`.

Basically, you need to remove all the versioning stuff so that runtime's `metadata` just returns an opaque blob. This gets passed on blindly to the RPC and it's then up to the RPC to figure out what to do with it. There's no need to mess about with versioning here since we now have extensible feature versioning in the `RuntimeVersion`.

**Comment by bkchr** [comment]
By core you mean the `client`? And that should just return the `Vec<u8` blob it got from the runtime?

**Comment by gavofyork** [comment]
`core` is anything inside `substrate/core`

**Comment by bkchr** [comment]
Okay, new commit, new try :) `core` now just sees a `Vec<u8>` and does not know anything about the `Metadata`. I also removed the versioning stuff.

**Comment by gavofyork** [comment]
looks great.

**Pull request merged**
