### PR TITLE
update kvdb & co

### PR DESCRIPTION
**Pull request by ordian**
polkadot companion: https://github.com/paritytech/polkadot/pull/6111

Major updates:
* rocksdb 6.28.2 -> 7.4.4
* jemalloc 5.2.1 -> 5.3.0
* uint and fixed-hash (e.g. `U256` and `H256` types) can now be deserialized from hex string without 0x prefix
* [some](https://github.com/paritytech/parity-common/blob/master/kvdb/CHANGELOG.md) breaking changes to kvdb API (mostly for the companion)

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by ordian** [comment]
```
thread 'tests::should_parse_extrinsic_address' panicked at 'assertion failed: `(left == right)`
  left: `Ok(Bytes([18, 52]))`,
 right: `Err("Extrinsic index missing: example \"5:0\"")`', bin/node/inspect/src/lib.rs:299:9
```
doesn't seem to be related to the PR

**Comment by ordian** [comment]
`impl-serde` 0.3.2 added support for deserializing without `0x` prefix: https://github.com/paritytech/parity-common/pull/598. This broke the test. Should I change the test? Or this assumption is baked in other places?

**Comment by bkchr** [comment]
> `impl-serde` 0.3.2 added support for deserializing without `0x` prefix: [paritytech/parity-common#598](https://github.com/paritytech/parity-common/pull/598). This broke the test. Should I change the test? Or this assumption is baked in other places?

Looks reasonable to support without leading `0x` as you have done it.

**Review by cheme — APPROVED** [review]
LGTM (should have review 14 days ago but did miss it).

**Comment by ordian** [comment]
bot merge

**Pull request merged**
