### PR TITLE
Fix fast-unstake for accounts with slashing

### PR DESCRIPTION
**Pull request by kianenigma**
kinda subtle, but kinda ashamed that I made the mistake 🤦

### CODE REVIEW

**Comment by kianenigma** [comment]
bot fmt

**Review by rossbulat — APPROVED** [review]

**Review by Ank4n — APPROVED** [review]

**Comment by Ank4n** [comment]
Similar mistake here
https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L985

**Comment by kianenigma** [comment]
> Similar mistake here https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L985

@gpestana can you add a test for this as well?

**Comment by kianenigma** [comment]
we should make sure this goes to the next possible Polkadot release, which will probably be in 2023, would be good to have your tests in here @gpestana soon nonetheless.

**Comment by melekes** [comment]
> kinda subtle, but kinda ashamed that I made the mistake 🤦

can you explain what the issue was? neither issue's title does this nor there's an issue linked to this PR.

**Review by melekes — APPROVED** [review]
👍 (code-wise; don't know enough to reason about business logic)

**Comment by gpestana** [comment]
@kianenigma with the current flow, there's no path for the calculated [`real_num_slashing_spans`](https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L985) to be used in the `fn kill_stash` called by `fn do_withdraw_unbound`. Thus, the slash + unbound + do_witdraw tests are not required/possible.

---
**Explanation**:

When calling `Call::unbound()`, if the controller's `max_chunks` are filled, the `fn do_withdraw_unbond` is called:

[mod.rs#L984-L986](https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L984-L98)

```rust
if unlocking == T::MaxUnlockingChunks::get() as usize {
    let real_num_slashing_spans = Self::slashing_spans(&controller).iter().count();
    Some(Self::do_withdraw_unbonded(&controller, real_num_slashing_spans as u32)?)
}
```

In the `do_withdraw_unbond`, the account is checked to see if all the staking related information should be removed (`fn kill_stash`). The condition is the following:

```rust
if ledger.unlocking.is_empty() && ledger.active < T::Currency::minimum_balance() {
    Self::kill_stash(&stash, num_slashing_spans)?;
    // ... 
```
i.e. the account should be killed iff there's no unlocking chunks and the balance is below the ED.

Thus, the path `unbound() -> do_withdraw_unbond() -> kill_stash()` is disjoint and can never happen, because the condition to call `kill_stash()` prevents the `do_withdraw_unbond()` to be called (no chunks in the slots).

Note: since `withdraw_unbond()` is an extrinsic, the `fn kill_stash()` may be called, just not through the `fn unbond` call.

**Comment by kianenigma** [comment]
> > kinda subtle, but kinda ashamed that I made the mistake 🤦
> 
> can you explain what the issue was? neither issue's title does this nor there's an issue linked to this PR. Thanks 🙏

`fn slashing_spans` returns `Option<T>` where `T` implemented `Iterator` and I expected it check the `.count()` of this iterator, but, `Option<T>` also implements `Iterator`, who's count is 0 or 1.

**Comment by kianenigma** [comment]
bot rebase

**Comment by kianenigma** [comment]
bot merge

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/path-to-fast-unstake-in-polkadot-kusama/1539/1

**Pull request merged**
