### PR TITLE
Reuse wasmtime instances, the PR

### LINKED ISSUE #5141: Reuse wasmtime instances
`WasmtimeInstance::call` currently spins a new actual instnace of `wasmtime::Instance` for each `call`. Instead it should keep and re-use the same instance. The only thing that's preventing this currently is that the global variables can not be reset to the original state for an instance. So I see two ways of fixing this:

1. Require runtime not to use any mutable globals.
2. Reset globals to the original state on each call. This will require some changes in `wasmtime` probaly.

Re-using the same instance should make wasmtime-based calls significantly faster.

### PR DESCRIPTION
**Pull request by pepyakin**
Fixes #5141

So far, we have bug #5036. TL;DR: Basically, the linear memory is not completely zeroed. It is zeroed enough for avoiding the issues https://github.com/paritytech/substrate/pull/3011 was set to fix, but still not completely. 

What it means is that the contents of the memory are preserved from the previous call. I don't yet fully know if there any ramifications of this approach. There are some thoughts on this in [this comment](https://github.com/paritytech/substrate/issues/5036#issuecomment-606011950), again TL;DR I am thinking if this is OK or not.

So this PR fixes #5141 as if #5036 was not a bug.

I am not absolutely sure if I understand all ramifications treating #5036 as not a bug though and if we want to go the way I outlined in the comment. So this PR gives us a point for doing the change, because AFAICT, it yields more performance than the current implementation.

In any case, this is still a useful PR that improves the status quo.

### CODE REVIEW

**Comment by bkchr** [comment]
@NikVolf this should show improvements for syncing and not really for importing single blocks.

**Comment by arkpar** [comment]
Do these benches even use wasmtime? And if so, do they account for compilation overhead?

**Comment by NikVolf** [comment]
> Do these benches even use wasmtime? And if so, do they account for compilation overhead?

they do, there is an issue with rocksdb cache for benchmarks currently though

**Comment by NikVolf** [comment]
> @NikVolf this should show improvements for syncing and not really for importing single blocks.

@pepyakin said they should show improvement, so we decided to run them

**Comment by NikVolf** [comment]
> And if so, do they account for compilation overhead

they do account for compilation overhead

**Pull request merged**
