### PR TITLE
Replace 'Module' with 'Pallet' in construct_runtime macro

### PR DESCRIPTION
**Pull request by shaunxw**
Part of #8287 .

Changes in this PR:
- Replace `Module` with `Pallet` as pallet keyword in `construct_runtime` macro.
- Rename `module` related types/fns in `construct_runtime` impl.
- Add `Pallet` type alias in `decl_module`, to make it compatible with new `Pallet` keyword in `construct_runtime`.
- Updated `construct_runtime` usage in mocks, runtimes.
- Deprecated `Module` type alias in pallet macro. Additionally replace all deprecated usage.

cc @shawntabrizi @thiolliere 

Polkadot companion: https://github.com/paritytech/polkadot/pull/2629

### CODE REVIEW

**Comment by thiolliere** [comment]
This will needs a companion, and there is remainings usage of deprecated Modle type alias, you can see in the CI  continuous-integration/gitlab-test-linux-stable 

We should deprecate AllModule and AllModuleWithSystem instead of removing them IMHO.

Then the only breaking change of this PR is the construct_runtime macro which requires Pallet instead of Module.

**Review by thiolliere — APPROVED** [review]
looks good, needs ui tests to be fixed

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
gonna be honest, did not look at every line of code, but scrolled through quickly

**Comment by thiolliere** [comment]
bot merge

**Comment by AurevoirXavier** [comment]
I think a lot of thing need to be changed.

`decl_module`, `ModuleId`...

**Comment by thiolliere** [comment]
`decl_module` is deprecated in favor of `pallet` macro.

I agree `ModuleId` should be changed too.

**Comment by AurevoirXavier** [comment]
> `decl_module` is deprecated in favor of `pallet` macro.
> 
> I agree `ModuleId` should be changed too.

Well.

Can you assign that to me? : )

**Comment by thiolliere** [comment]
Yes a PR is welcome, I don't think ppl are working on it, you can ping me on the PR if you open it

**Pull request merged**
