### PR TITLE
Add `ConstFeeMultiplier` to the transaction payment pallet

### PR DESCRIPTION
**Pull request by MrShiposha**
Currently, the template node sets the `FeeMultiplierUpdate` of the `pallet_transaction_payment::Config` to the unit type.
It seems not obvious (and barely noticeable) that the default implementation of the `MultiplierUpdate` trait returns `0` (and not `1`).
Because of that, the transaction weights will be discarded due to the multiplication by 0 [inside the transaction payment pallet](https://github.com/paritytech/substrate/blob/5a48536a49859f83dbbbab1285311f14c192e7b1/frame/transaction-payment/src/lib.rs#L548-L561).

This PR suggests using the `FeeMultipleUpdate` equivalent to the [`SlowAdjustingFeeUpdate`](https://github.com/paritytech/polkadot/blob/87d6cfc7c0531d888898c9bbd1a1e299538a546b/runtime/common/src/lib.rs#L96-L97) from the Polkadot runtime common.

I believe it will fix the non-obvious behavior and will add extra useful info to the template node.

----

polkadot address: 11Ze4Gi9iHZ1qPEweUewWk5iUTYL4Zd18VxKZ6cHhqyrfep

### CODE REVIEW

**Comment by ggwpez** [comment]
The template node was kept simple on purpose, to not confuse new developers.  
Not sure what the idea was here. Maybe @kianenigma remembers?

**Comment by kianenigma** [comment]
Yeah, this is intentional. The `SlowAdjustment` is a feature made for Polkadot, and I don't think we should use it in node-template. 

That being said, I think the intention is to disable any weight multiplier update for node-template. This means that the default value should be set to 1, and the convert should be `struct Identity`. The current code is somewhat different because it basically disables any weight fee by using a multiplier that's zero.

**Review by kianenigma — CHANGES_REQUESTED** [review]
Valid concern, but needs a different approach! I would appreciate if you fix this.

**Comment by MrShiposha** [comment]
@kianenigma maybe it would be nice to change the [default implementation of the `MultiplierUpdate`](https://github.com/paritytech/substrate/blob/5a48536a49859f83dbbbab1285311f14c192e7b1/frame/transaction-payment/src/lib.rs#L142-L152) to return `1` in the `fn min()`?

So the default implementation won't change the multiplier. And I will revert all the changes to the template node.
What do you think?

**Comment by ggwpez** [comment]
> maybe it would be nice to change the [default implementation of the MultiplierUpdate](https://github.com/paritytech/substrate/blob/5a48536a49859f83dbbbab1285311f14c192e7b1/frame/transaction-payment/src/lib.rs#L142-L152) to return 1 in the fn min()?

IMO it would be better to add a new implement for the trait, since we extensively use `()` in testing.  
Something like `ConstFeeMultiplier<Get<u32>>` maybe.

**Review by kianenigma — APPROVED** [review]
Thanks! Can you put a polkadot address in the description for a tip https://github.com/apps/substrate-tip-bot?

**Comment by MrShiposha** [comment]
>Thanks! Can you put a polkadot address in the description for a tip https://github.com/apps/substrate-tip-bot?

Added, thank you! :)

**Review by ggwpez — APPROVED** [review]
Thanks!  
CI is currently broken, but that's not your fault.

**Review by kianenigma — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
