### PR TITLE
Removes incorrect `try-state` check in staking

### LINKED ISSUE #14246: [Staking] Active ledger balance may fall below ED if account chills before unbounding
Currently, there are some stashes in Polkadot (11) with `ledger.active` balance below the existential deposit. The call path for that to happen is to chill the stash before unbonding and not call `withdraw_unbonded` after the bonding period.

However, if the stash tries to call `unbond` with the full `ledger.active` balance, it will fail due to the checks enforcing that the active balance should be `MinNominatorBond` or `MinValidatorBond` at the end of the unbonding. In this case, the stash needs to call `chill` first to be able to unbond all the active balance (as described above). 

Given that reap stash can be called only against stashes that have `ledger.total` balance below ED, the stashes that were chilled and do not call `withdraw_unbonded` after the unbonding period will have remain in the ledger with active balance = 0 without any mechanism to "clean" the ledger besides the stash calling `withdraw_unbonded`.

Another path for the `ledger.active` balance to be below `MinBond` is through slashing. However, in that case it is possible to call `reap` against the stash if the total (and thus active) balance is below ED.

**Side effects**

Currently, the staking try-state checks that inspect the ledger state consistency are triggering if there are `ledger.active` balances below the ED which, as laid out above, can happen (related to https://github.com/paritytech/substrate/pull/14186).

**Allow `withdraw_unbonded` to be called permissionlessly**

From the reasoning above, it follows that some ledger entries may linger in the ledger indefinitely if the stash/controller does not call `withdraw_unbonded` after chilling and the unbonding period has passed. Currently, there is no way to enforce the withdrawal in those situations. 

Perhaps we should consider allowing anyone to call `withdraw_unbonded` for a third-party stash which has unbonded chunks for longer than N eras and active balance below ED, e.g.:

```rust
pub fn withdraw_unbonded_other(
  origin: OriginFor<T>,
  controller: T::AccountId,
  num_slashing_spans: u32,
) -> DispatchResultWithPostInfo {
  let controller = ensure_signed(origin)?;
  let ledger = Self::ledger(&controller).ok_or(Error::<T>::NotController)?;
   
  let ed = T::Currency::minimum_balance();
  ensure!(ledger.active < ed && unlocking_chunks_older_than_N(ledger), Error::<T>::CannotWithdrawOther);

  Self::do_withdraw_unbonded(&controller, num_slashing_spans) // perhaps refund weight if successful
}
```

Or even better, we could just allow anyone to call `withdraw_unbounded_other` on any stash, without any extra check as in the code above.

After `withdraw_unbonded_other`, the ledger can may be killed if the balance goes to 0.

---

PR with E2E test reproducing the behaviour described above https://github.com/paritytech/substrate/pull/14247

### PR DESCRIPTION
**Pull request by gpestana**
The current logic does not completely prevent the ledger active balance to remain above ED and there are code/config paths in which `ledger.active` may be 0. This PR removes the try-state check that is testing those invariants.

Closes https://github.com/paritytech/substrate/issues/14246

### CODE REVIEW

**Comment by kianenigma** [comment]
Has an issue been made about `minStake`/`minNominatorStake`/`minValidator` stake? if we had `minStake`, then it would have been reasonable to at least raise a warning if `ledger.active` is less than `minStake`, although even this is not great as `minStake` can reduce.

**Review by kianenigma — APPROVED** [review]

**Review by kianenigma — CHANGES_REQUESTED** [review]
Actually, I found the reason why we had this test: this code should prevent `ledger.active` from ever getting less than https://github.com/paritytech/substrate/blob/1bbde5d7c50e55458ff3925ed0ee911d035719d5/frame/staking/src/pallet/mod.rs#L1011. 

Although, slashing could still violate this. 

I think it is still better to first check a few of the stashes that cause this, and see what path they went through.

**Comment by gpestana** [comment]
> Actually, I found the reason why we had this test: this code should prevent `ledger.active` from ever getting less than (ED)

> Although, slashing could still violate this.

I think that's correct. However, if a stash has been slashed to the point of the active/total balance being below ED, someone needs to call `reap` for the stash to be killed and removed.

> I think it is still better to first check a few of the stashes that cause this, and see what path they went through.

As mentioned in https://github.com/paritytech/substrate/issues/14246, I see two paths for  `ledger.active` to be below ED:

- 1. First `chill` stash and not call `withdraw_unbonded` after the bonding period;
- 2. Slashing occurs that drops `ledger.total` below ED and no `reap` is called. 


From my current understanding, the try-state consistence check that this PR is removing is not correct and should be removed.

**Review by kianenigma — APPROVED** [review]
Fair enough.

All in all, I still find this situation with our assumptions around ledger a bit confusing. I hope you take a fundamental look at it and add new reasonable checks, if any.

**Review by rossbulat — APPROVED** [review]

**Review by kianenigma — COMMENTED** [review]
bot merge

**Comment by gpestana** [comment]
bot merge

**Pull request merged**
