### PR TITLE
Adding on enabling http2

### PR DESCRIPTION
**Pull request by jimmychu0807**
A few weeks ago I mentioned to @tomusdrw that the ocw couldn't fetch some requests, such as github api and our polkadot RPC content. Eventually I pinpointed the issue to missing http2 feature from hyper. Then @bkchr is faster than me in spoting the issue and applying the fixes.

This PR build on top of that and with two additional test cases written, one GET request to gh, and one POST request for polkadot RPC. See if they are good to go.

I added `http1` feature in hyper for completeness sake. 

@bkchr @tomusdrw

### CODE REVIEW

**Comment by tomusdrw** [comment]
Please see discussion in https://github.com/paritytech/substrate/pull/10305#issuecomment-972903443 I think Basti was not fond of adding unit tests that rely on external resources to avoid making the CI flaky. Perhaps running/asserting on these should be moved under a feature flag or sth?

**Comment by bkchr** [comment]
Yeah, no requests to external websites in tests. This will break for sure at some point.

**Comment by jimmychu0807** [comment]
Is it possible to mark a test with some kind of flag / feature, so similar to cargo feature, only be included when running test with those flags on?

**Comment by bkchr** [comment]
And then it will not be run? 

What would be the purpose of this?

There are also already some test that checks http2.

**Comment by jimmychu0807** [comment]
I see, cool. Let's close this then.

**Pull request closed without merging**
