### PR TITLE
Decouple contract from balances

### PR DESCRIPTION
**Pull request by thiolliere**
* Currency has now creation_fee and transfer_feee methods to be able to compute fee and charge them in gas
* Currency Imbalance are oppositing themselves, (also I don't think it can be constrained at module trait)
* introduction of TransactionFee trait which gives values of base_fee and byte_fee:
  
  I was mixed between exposing those values by module and use them to implement ComputeDispatchFee in contract or implementing ComputeDispatchFee on `balance::Module` itself.
  (Also now balance is Fee module but we want to decouple it in the future https://github.com/paritytech/substrate/issues/2052)
  
* no alteration of contract logic at all.

also as a side note: `ensure_free_balance_is` was a bit misleading at first because I thought it was a check function like `ensure_can_withdraw` or `ensure!`, I would expect it to be named `set_free_balance` or `make_free_balance`

related to https://github.com/paritytech/substrate/issues/1514

### CODE REVIEW

**Comment by thiolliere** [comment]
what is this CI expected status ?

**Comment by pepyakin** [comment]
I think the devops team does some changes. Don't think that we should pay much attention to it.

**Comment by gavofyork** [comment]
transaction fees (byte/base) in contract and transaction fees (byte/base) in balance are actually essentially unrelated and we certainly don't want them to be the same thing long term.

**Comment by gavofyork** [comment]
i'm not keen on merging this as long as we're dirtying the `Currency` module. it really shouldn't have any thing to do with fees in there. 

If Contract modules needs those values, it should store them itself or have a dependency to a module that does.

**Comment by thiolliere** [comment]
* transaction fees: transaction fees can be moved to a FeeModule as in the past or just configured
* transfer_fee, creation_fee: indeed I agree, we don't want to make currency as contrained in its implementation of fees, fee must be hidden. Contract want to simulate transfer and pays for fees in gas so it simulate balance module fee computation which is very specific and doesn't fit into Currency trait. I think I have to go to an overlay trait implemented by balance.

**Comment by thiolliere** [comment]
so it will result with this trait
```rust
pub trait OverlableCurrency<AccountId>: Currency<AccountId> {
	type Overlay: Currency<
		AccountId,
		Balance=<Self as Currency<AccountId>>::Balance,
		PositiveImbalance=Self::PositiveImbalanceOverlay,
		NegativeImbalance=Self::NegativeImbalanceOverlay,
	>;

	// TODO TODO: this might be done with where clause on trait..
	type PositiveImbalanceOverlay: Imbalance<Self::Balance, Opposite=Self::NegativeImbalanceOverlay>;
	type NegativeImbalanceOverlay: Imbalance<Self::Balance, Opposite=Self::PositiveImbalanceOverlay>;

	type ChangeSet;

	fn overlay() -> Self::Overlay;
	fn nested_overlay<'a>(overlay: &'a Self::Overlay) -> &'a Self::Overlay;

	fn into_change_set(overlay: Self::Overlay) -> Self::ChangeSet;
	fn commit_into_overlay(overlay: &mut Self::Overlay, change_set: Self::ChangeSet);
	fn commit_into_currency(change_set: Self::ChangeSet);
}
```

and one function in currency:
```rust
	/// Fee to transfer some liquid free balance to another staker.
	fn compute_transfer_fee(
		source: &AccountId,
		dest: &AccountId,
		value: Self::Balance,
	) -> result::Result<Self::Balance, &'static str>;
```

also only minimal currency will need to be overlayed after https://github.com/paritytech/substrate/issues/2120

So I think this abstraction is needed because if we want decoupling theoritically either we can have this method on an overlay, or we can reproduce it in our transfer function (which is what we do at the moment) by bringing a very retrained new trait

**Comment by thiolliere** [comment]
(note overlay design was based on contract accoundb, so borrows of underlying accounddb, but it could be made another way, without borrowing, thus we could remove changeset and just commit overlay direclty, then implementor would make Rc or Arc in its code)

**Comment by thiolliere** [comment]
hmm it seems our current implementation is wrong, this https://github.com/paritytech/substrate/blob/master/srml/contract/src/exec.rs#L531 bypass the locks

**Comment by pepyakin** [comment]
Hm, I am not sure what you mean: 

This line 

https://github.com/paritytech/substrate/blob/4c8a53b423666fb82756bb46da601802ef6fc581/srml/contract/src/exec.rs#L531

is exactly the same as the corresponding line in the balanaces module

https://github.com/paritytech/substrate/blob/4c8a53b423666fb82756bb46da601802ef6fc581/srml/balances/src/lib.rs#L730

**Comment by thiolliere** [comment]
hmm, the overlay change the logic in transfer:
* before: if a transactor new balance is below existential deposit then it can still be refund in another transfer no ?
* with overlay: if a transactor new balance is below existential deposit then, on_free_balance_zero will be called inside the the overlay and even if refund later, the account could have lost the money he had when killed (which was below existential deposit)

**Comment by thiolliere** [comment]
> Hm, I am not sure what you mean:
> 
> This line
> 
> [substrate/srml/contract/src/exec.rs](https://github.com/paritytech/substrate/blob/4c8a53b423666fb82756bb46da601802ef6fc581/srml/contract/src/exec.rs#L531)
> 
> Line 531 in [4c8a53b](/paritytech/substrate/commit/4c8a53b423666fb82756bb46da601802ef6fc581)
>  <balances::Module<T>>::ensure_can_withdraw(transactor, value, WithdrawReason::Transfer, new_from_balance)?; 
> 
> is exactly the same as the corresponding line in the balanaces module
> 
> [substrate/srml/balances/src/lib.rs](https://github.com/paritytech/substrate/blob/4c8a53b423666fb82756bb46da601802ef6fc581/srml/balances/src/lib.rs#L730)
> 
> Line 730 in [4c8a53b](/paritytech/substrate/commit/4c8a53b423666fb82756bb46da601802ef6fc581)
>  Self::ensure_can_withdraw(transactor, value, WithdrawReason::Transfer, new_from_balance)?;

yes but it is computed outside the overlay, if account has some balance locked and has already made a transfer so it actually only remains the locked amount, then ensure_can_withdraw can succeed but not actually should have failed

**Comment by thiolliere** [comment]
the OverlayableCurrency trait is not implementable by our Balance module because of OnFreeBalanceZero side effects. If we don't overlay OnFreeBalanceZero side effects then the overlay is not the same as if it was executed in Storage:

let's say we have 3 accounts A, B and C, a Coupling module that kills B when A is on free balance zero. 
then the transfer of A funds to B and then B funds to C result in C having all funds in overlay put in real storage B is killed after first operation so C doesn't receive any funds.

So it seems we run out of idea for the moment.

note: this behavior is already wrong without the decoupling

note: hmm, maybe we can make a AlmostOverlay implementation that is a best effort, but seems weird, our implementation is already a best effort. (because of the example above and also https://github.com/paritytech/substrate/blob/master/srml/contract/src/exec.rs#L531 I think)

**Comment by thiolliere** [comment]
After talks with @pepyakin this is what I can envision: as an in between something that could be done is:
having a quite precise trait in contract like:
```rust
pub trait Overlay<AccountId, Balance> {
fn compute_transfer_fee(origin, dest)
fn transfer_without_fee(origin, dest)
fn minimal_balance()

// overlay functions...
fn nested(&self) -> &'a Overlay
fn into_change_set(self) -> ChangeSet
fn apply_change_set(&mut self, ChangeSet)
fn commit(self)
}
```
this trait is only their to allow other module to work with contract.
inside contract we would implement it for a structure named `BestEffortBalanceOverlay` with the documentation specifying it can't handle OnFreeBalanceZero side effect

and a new associated type is added to contract::Trait:
```rust
trait Trait {
type overlay: Overlay<Self::AccountId, BalanceOf<Self>>
}
```

finally in node/runtime it will be written:
```rust
impl contract::Trait for Runtime {
...
type Overlay = contract::BestEffortBalanceOverlay
}

**Comment by gavofyork** [comment]
No fee information should be in `Currency` trait.

Fees are an attribute of the module doing the charging, not the currency.

Just because a country chooses to use Euros doesn't mean it is forced to set the VAT at 20%.

**Comment by gavofyork** [comment]
I'm generally against this heavy-duty trait extraction: It's a lot of extra API and code for only speculative gains. I see no compelling use case for it.

I'm happy with the existing PR except for the fees stuff. If the fees are pulled as additional parameters (storage items, set at genesis) in the contracts module and it should be good.

**Comment by thiolliere** [comment]
ok updated as such, I'm not sure about making the fee storage public though

**Pull request merged**
