### PR TITLE
Update sysinfo version to 0.11

### LINKED ISSUE #5163: Update sysinfo
We are still using `0.9` of the sysinfo crate. We should update this to latest.

### PR DESCRIPTION
**Pull request by DarkEld3r**
Closes #5163.

### CODE REVIEW

**Comment by gnunicorn** [comment]
@DarkEld3r web-wasm tests failing now, benches, too.

**Comment by DarkEld3r** [comment]
@gnunicorn There is some strange issue with the benches:
```
error: failed to get `sysinfo` as a dependency of package `sc-service v0.8.0-alpha.3 (/builds/parity/substrate/client/service)`
 Caused by:
   failed to fetch `https://github.com/rust-lang/crates.io-index`
 Caused by:
   missing delta bases; class=Indexer (15)
```
I'm not sure that it is caused by my changes.

As for web-wasm tests: it is an issue in the `sysinfo` crate itself: https://github.com/GuillaumeGomez/sysinfo/pull/276

**Comment by gnunicorn** [comment]
> As for web-wasm tests: it is an issue in the sysinfo crate itself: GuillaumeGomez/sysinfo#276

which means the current version isn't gonna work for us, but we need to wait for the next release including your patch. icing.

**Comment by DarkEld3r** [comment]
@gnunicorn The new version has been released, so I have updated the pull request.

**Pull request merged**
