### PR TITLE
Fix pallet_assets no_std compilation

### PR DESCRIPTION
**Pull request by GopherJ**
Could you port this to polkadot-v0.9.19 as well? thanks

### CODE REVIEW

**Comment by bkchr** [comment]
Hmm, it is included in the `bin/node/runtime`. So, it should already be compiled as part of the CI in wasm. Not sure why it didn't failed there :thinking: 

What compiler version are you using?

**Comment by GopherJ** [comment]
@bkchr we are using: `nightly-2021-11-07`, somehow I cannot compile into wasm yet due to missing `vec` import, wierd

**Comment by bkchr** [comment]
I found the problem. I bet with you that you have the `std` feature of `sp-std` somewhere in your project enabled. Please check this.

**Comment by GopherJ** [comment]
Not sure if it's caused by compiler though, it's also reporting some others:


image

**Comment by GopherJ** [comment]
> 

let me check thanks

**Comment by GopherJ** [comment]
@bkchr you are awesome! fixed now

**Comment by anantasty** [comment]
I am running into the same issue in v0.9.26
I have tried wit the sp-std/std flag enabled and disabled.
Suggestions?

**Comment by bkchr** [comment]
@anantasty it can also be any other crate that propagates `std` feature to `sp-std`. You can use `cargo tree` to find out which crate enables the `std` feature.

**Comment by anantasty** [comment]
Thanks @bkchr

**Pull request closed without merging**
