### PR TITLE
`sp-runtime`: make `parity-util-mem` dependency optional

### PR DESCRIPTION
**Pull request by ascjones**
`parity-util-mem` is only required for `std` so can be excluded via `default-features = false`.

### CODE REVIEW

**Comment by jsdw** [comment]
@ordian do you think we can go further here or do you reckon this is about the best we can do in the end? I recall you removing the dependency entirely but not sure how you handled that `TransactionSource` type :)

**Comment by ascjones** [comment]
> @ordian do you think we can go further here or do you reckon this is about the best we can do in the end? I recall you removing the dependency entirely but not sure how you handled that `TransactionSource` type :)

There are a few other `derive(parity_util_mem::MallocSizeOf)` in that crate (alll on `std`)

**Comment by bkchr** [comment]
As a lot of stuff, this `MallocSizeOf` stuff was added prematurely. I would try to remove it entirely from this crate and then fix the fallout around in the other crates. It should probably be removed from everywhere, but that is probably too much.

**Comment by ordian** [comment]
> @ordian do you think we can go further here or do you reckon this is about the best we can do in the end? I recall you removing the dependency entirely but not sure how you handled that `TransactionSource` type :)

This is exactly what I did as well, only removing `parity-util-mem` from `sp-core`. But that wasn't enough for `subxt`. @ascjones have you verified patching substrate in subxt to this branch prunes `parity-util-mem` from `Cargo.lock`?

**Comment by ascjones** [comment]
> As a lot of stuff, this `MallocSizeOf` stuff was added prematurely. I would try to remove it entirely from this crate and then fix the fallout around in the other crates. It should probably be removed from everywhere, but that is probably too much.

Main reason appears to be in `state-db` memory info:

https://github.com/paritytech/substrate/blob/master/client/state-db/src/lib.rs#L500-L506

I think if we replaced that then we should be able to remove all the `MallocSizeOf` impls.

**Comment by ascjones** [comment]
> > @ordian do you think we can go further here or do you reckon this is about the best we can do in the end? I recall you removing the dependency entirely but not sure how you handled that `TransactionSource` type :)
> 
> This is exactly what I did as well, only removing `parity-util-mem` from `sp-core`. But that wasn't enough for `subxt`. @ascjones have you verified patching substrate in subxt to this branch prunes `parity-util-mem` from `Cargo.lock`?

Yes `parity-util-mem` is no longer in the dependency tree: https://github.com/paritytech/subxt/pull/709

**Comment by ordian** [comment]
> I think if we replaced that then we should be able to remove all the MallocSizeOf impls.

There's also small usage [in](https://github.com/paritytech/polkadot/blob/a70d12ae1da07167bb33c5fce6f6f4f5ab511fff/node/core/runtime-api/src/cache.rs#L54-L58) Polkadot runtime-api cache, but it can also be estimated like https://github.com/paritytech/substrate/blob/20b5aac7e09e8b25abaa48c6781e653b36ba3ca0/client/db/src/storage_cache.rs#L62-L72

I'd be in favor or getting rid of `parity-util-mem` completely :)

**Review by ordian — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
