### PR TITLE
Add some proof comment

### PR DESCRIPTION
**Pull request by thiolliere**
The proof for `q_reduce < 2 * $max` is not completely obvious, this comment make the proof clear

### CODE REVIEW

**Comment by kianenigma** [comment]
the `round` can be implemented as such: 

```rust
let div_round_nearest = |x: N, f: N| -> N {
	let mut q = x / f;
	let r = x.rem(f);
	if r > (f / N::from(2)) {
		q = q + N::from(1);
	}
	q
};
```

**Comment by kianenigma** [comment]
https://www.desmos.com/calculator/z34z6eaetw although it is only correct when you do `ceil`. Makes sense, `q / max` will always be equal or an epsilon more than its _real_ value. Hence `q / (q/max)` will always be less than `max`.

**Comment by thiolliere** [comment]
> Sorry I got into thinking again :D
> 
> first, maybe it is better if you push to the offchian phragmne PR as there are some more changes over there?
> 
> And, this proof implies that we to further do
> 
> ```
> 				let part =
> 					p_reduce as $upper_type
> 					* <$upper_type>::from($max)
> 					/ q_reduce as $upper_type;
> ```
> 
> we need yet another type that can fit `2 * max * max`.

the comment state `// this implies that Self::Inner must be able to fit 2 * $max.`. If I remember correctly this was prooved by a test but I'll update the comment to mention the test if I find it.

> while if we change `factor = floor(q / max)` to `factor = round(q / max)`, then you can prove that:
> 
> `q_reduce` and `p_reduce` are always within `$max`, hence `let part = p_reduce as $upper_type * <$upper_type>::from($max) / ...` is also safe because `$upper_type` can fit `$max * $max`

I have to think if we loose some precision by using this factor, but maybe it is fine indeed.

**Comment by thiolliere** [comment]
I think using ceil is a good idea and it will avoid using a new type for PerU16 or PerU32

**Comment by thiolliere** [comment]
also mentionning maybe we should do ceil in the implementation of CurrencyToVoteHandler just to be more clean:
```rust
impl CurrencyToVoteHandler {
	fn factor() -> Balance { (Balances::total_issuance() / u64::max_value() as Balance).max(1) }
}

impl Convert<Balance, u64> for CurrencyToVoteHandler {
	fn convert(x: Balance) -> u64 { (x / Self::factor()) as u64 }
}

impl Convert<u128, Balance> for CurrencyToVoteHandler {
	fn convert(x: u128) -> Balance { x * Self::factor() }
}
```
it is fine because nobody has a balance close to total_issuance but actually if someone has its balance close to total_issuance then the conversion might not fit in u64 actually.

**Comment by kianenigma** [comment]
Curretn totalIssuance is actually a big big problem. We use this to `convert()` very often and every time it reads from storage (caching sometimes helps but not always). This should be changed anyhow.

**Comment by kianenigma** [comment]
@thiolliere can you check if https://github.com/paritytech/substrate/pull/4517 is now okay regards to documenting this section? and see if you prefer to update this PR or close it.

**Comment by thiolliere** [comment]
https://github.com/paritytech/substrate/pull/4517 indeed superseed correctly this need for proof.

Close because https://github.com/paritytech/substrate/pull/4517 superseed.

**Pull request closed without merging**
