### PR TITLE
Remove Prometheus metrics prefix

### PR DESCRIPTION
**Pull request by tomaka**
The situation right now is that, at initialization, we call `Registry::new_custom(Some("substrate"), None)`, which automatically adds a `substrate_` prefix in front of every single metric that we register.
Polkadot, however, overwrites this `Registry` by doing `Registry::new_custom(Some("polkadot"), None)`, meaning that, in Polkadot, all metrics, even the ones defined in Substrate, have the `polkadot_` prefix.

This causes a big issue: Grafana dashboards and alerts need to be created once for Polkadot nodes and once for all-Substrate-chains-except-Polkadot.

This PR modifies this system by removing the automatic metrics prefixing. Instead, I've manually added `substrate_` in front of all the metrics registered in Substrate and `polkadot_` in front of all the metrics registered in Polkadot. This matches the Prometheus good practices, which mention that libraries (Substrate is a library) can have their own prefix different from the binary.

However, in order to make things easier for devops, this PR also adds an automatic `{chain="chain_id"}` parameter behind every metric, where `chain_id` is the chain id found in the chain spec (e.g. "polkadot" or "ksmcc3").

polkadot companion: https://github.com/paritytech/polkadot/pull/3623

### CODE REVIEW

**Comment by tomaka** [comment]
Beep

**Review by adoerr — APPROVED** [review]
`BEEFY` LGTM

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@tomaka this doesn't compile, otherwise we should be good to merge this.

**Comment by bkchr** [comment]
@tomaka does not compile :grimacing:

**Comment by bkchr** [comment]
(cargo fmt :see_no_evil: )

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
