### PR TITLE
Network sync refactoring (part 7)

### PR DESCRIPTION
**Pull request by nazar-pc**
This is a small follow-up to #11940 that removes direct dependency on `sc-network` from a few generic crates. `sc-cli` and `sc-service` still depend on `sc-network`. Most of generic crates depend on `sc-network` only in tests, the rest of the codebase only depends on specific networking-related APIs it cares about. I didn't touch PoS-related crates as I don't have personal interest in them and changes there are unlikely to be helpful to anyone.

It was the logical next step already prepared when mentioned PR was done, but as suggested in comments there, stopping here.

Polkadot companion: https://github.com/paritytech/polkadot/pull/5913

### CODE REVIEW

**Review by dmitry-markin — APPROVED** [review]
Looks good to me. Still, it's better also approved by a more experienced substrate developer like @bkchr

**Review by bkchr — APPROVED** [review]
Ty!

**Comment by bkchr** [comment]
@nazar-pc this requires a polkadot companion.

**Comment by nazar-pc** [comment]
Merged `master` and created a Polkadot companion

**Pull request merged**
