### PR TITLE
Expose load_keys in pallet session.

### PR DESCRIPTION
**Pull request by DamianStraszak**
The only change in this PR is exposing a getter for NextKeys storage item in the Session pallet. We (Aleph Zero) build a blockchain with a custom finality gadget and thus require tighter control over session keys -- this seems to be the simplest way to expose these keys.

// I don't have appropriate rights to add labels to this PR :(

### CODE REVIEW

**Comment by bkchr** [comment]
> we know the ValidatorIds many sessions ahead, but cannot extract the corresponding session keys (the ones of type `Keys`) and would love to do so :)

But session module only stores the keys for the next session and not for many sessions ahead.



> 1) if we wanted to keep track of keys this way then we would probably need to keep another ValidatorId -> AuthorityId map in our pallet's storage (duplication of data w.r.t. to the pallet session)

That is what I meant. Every pallet that is using session keys is storing this data on its own. You also need to be aware that every pallet has its own session keys.

**Comment by DamianStraszak** [comment]
>  and it would be great to be able to query the future `Keys` of these `ValidatorId`'s.
Ok, this actually sounds like I don't know what I'm saying -- I'm aware that if I know ValidatorIds 5 sessions ahead, then I cannot be sure whether the `Keys` will not rotate in the meantime -- that's fine, still we would like to be able to query the most up-to-date keys :)

**Comment by DamianStraszak** [comment]
Uhh, you are right, sorry for that :/
The confusion is because we were using a slightly outdated branch `polkadot-v0.9.9`, but `polkadot-v0.9.11` is already there with these changes.

Thanks a lot for your time, and the help you provided! 

The PR can be closed.

**Comment by bkchr** [comment]
> Uhh, you are right, sorry for that :/

Np :) I also didn't realized it :D

**Pull request closed without merging**
