### PR TITLE
WASM executor: add `OutputExceedsBounds` variant to `Error`

### PR DESCRIPTION
**Pull request by mrcnski**
# PULL REQUEST

## Overview

Previously this was a `WasmError`, which is intended for runtime construction errors. However this led to confusion as output-exceeds-bounds occurs due to execution of `validate_block`.

(Please review closely and correct me if I'm mistaken about something, the error story here is pretty confusing.)

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2652703

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2652702

**Review by bkchr — APPROVED** [review]

**Review by koute — APPROVED** [review]
In general it'd be nice to just completely get rid of the `Other` variant if possible.

**Comment by mrcnski** [comment]
> In general it'd be nice to just completely get rid of the `Other` variant if possible.

Agreed and I thought about it, but didn't feel like doing it. 😛 Raised https://github.com/paritytech/substrate/issues/13853.

**Comment by mrcnski** [comment]
bot merge

**Pull request merged**
