### PR TITLE
Delete legacy runtime metadata macros

### PR DESCRIPTION
**Pull request by ascjones**
These were rewritten as proc macros in https://github.com/paritytech/substrate/pull/8801, and `construct_runtime!` now uses that instead of the legacy `impl_runtime_metadata!`.

This is required for https://github.com/paritytech/substrate/pull/8615, which would otherwise need to make changes to these legacy macros.

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]
yes, I don't expect people to have use it in tests or anywhere so should be fine, anyway if people want to generate metadata in tests they should use `construct_runtime`.

**Comment by ascjones** [comment]
> Do declarative macros support the #[deprecated] syntax?

I thought it didn't but apparently it has done for a couple of years now: https://github.com/rust-lang/rust/pull/62042, https://play.rust-lang.org/?gist=aa4c719a14da2bb5cf3ddf8c3066f452&version=stable.

Still, I'm in favour of just deleting it since although it is public it is intended for internal use only. But that is just my cavalier nature, so happy to just deprecate if @thiolliere thinks that is better.

**Comment by ascjones** [comment]
If we deprecate it here I will just delete it in https://github.com/paritytech/substrate/pull/8615, otherwise that will require changes to the deprecated macros.

**Comment by KiChjang** [comment]
Sorry, I wasn't quite clear when I said deprecate. What I meant was keep the declarative macro and its arguments, but leave the body blank and just add the deprecation notice -- maybe something along the lines of `this macro is not supported in FRAMEv2, please only use the construct_runtime macro`. This way, no one's ever going to be surprised by the deletion.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
We don't have any proper releases, so doing the deprecate game isn't really bringing any value. Instead it just costs us time to maintain this stuff etc.

**Pull request merged**
