### PR TITLE
Added ss58 prefix for metaprime.network family

### PR DESCRIPTION
**Pull request by yangwao**
Added ss58 prefix for https://metaprime.network family -- dapp chain by https://twitter.com/kodadot team

The prefix doesn't collide with other prefixes. 
I've added a prefix to
- [ss58-registry.json](https://github.com/yangwao/substrate/compare/master...yangwao-metaprime?quick_pull=1#diff-b501fa660c67a198b63b9d0ed792673bb94d91c275dfcf2d250ce06eafb66419)
- [primitives/core/src/crypto.rs](https://github.com/yangwao/substrate/commit/1072547e0721495cae59a307c23aaef66f9f7937)

- Will it appears on https://wiki.polkadot.network/docs/en/build-ss58-registry ?

I hope I made it properly, if something missing I can add it.

### CODE REVIEW

**Comment by yangwao** [comment]
> User @yangwao, please sign the CLA [here](https://cla.parity.io/sign_cla/5887929/3).

Signed 
> All done. Thank you for signing the CLA!

**Comment by yangwao** [comment]
I've just signed CLA @BenWhiteJam

**Comment by joao-paulo-parity** [comment]
Sorry @yangwao the cla-bot-2021's comments were bugged for a while. Your signature has been received. Please disregard the bot's messages.

**Comment by yangwao** [comment]
@joao-paulo-parity I'm glad! 

What's next? :)

**Comment by yangwao** [comment]
Hello @benwhitejam - is there something missing from our side to get this done? :)

**Comment by yangwao** [comment]
Seems the issue requires merging upstream. Can fix that later.

**Pull request closed without merging**
