### PR TITLE
WIP: [NFTs] Simplify collection creation and item mint

### PR DESCRIPTION
**Pull request by jsidorenko**
When trying to create a collection via traits, it requires providing the CollectionConfig param. This requires adding a lot of boilerplate code, which annoys when dealing with simple use cases.
This PR adds a new `CreateSimplified` trait that doesn't have the config param and puts the default collection's config.
Additionally, I made the item's config param optional in the mint_into() method

### CODE REVIEW

**Comment by jasl** [comment]
What about make the `config` optional? I'm concerning that in my use-case, I need customize the config when creating the collection, separates create and set may introduce avoidable state read and write?

**Comment by jsidorenko** [comment]
Making it optional, unfortunately, doesn't remove the requirement to have a lot of boilerplate code

**Comment by jsidorenko** [comment]
another possible solution would be to have two traits: `Create` and `CreateConfigurable`

**Comment by jasl** [comment]
> Making it optional, unfortunately, doesn't remove the requirement to have a lot of boilerplate code

Understood, I think it is acceptable because create and mutate collections ususally not high-frequent operations

**Comment by jasl** [comment]
Thank you for help! I see you're working on improving `mint_into` here

I've refactored my pallet to nonfungibles_v2 interface again, I have few feedbacks:

First, nonfungibles_v2 interface `mint_into` can only deposit by none or the collection owner, but pallet-nfts `do_mint` can support specify depositor, and `mint` extrinsic call will set the caller as depositor which is make sense
So, I'd propose change `mint_into` that accept `depositor: Option<Self:AccountId>` instead of `deposit_collection_owner: bool`

Second, `mint_into` lacking `MintWitness`, but `destroy` has `witness: Self::DestroyWitness,`

Third, `set_attribute` and `set_typed_attribute` pass `set_as: None` so no one can be the depositor of the attribute (or metadata)

Fourth, I propose separate read and write metadata from `set_attribute` and `set_typed_attribute`, this would help to make more clear and simplify R&W metadata (avoid to construct a default Vec)

**Comment by jasl** [comment]
Off-topic: just my opinion, `nonfungibles_v2` is used by pallet which 100% controlled by developers, so I'm thinking all of `maybe_check_*` argument can be simplified, developer can do the permission check before call nft api
and, feature gate check should move out from features implementations, as developer, I call `set_attribute` is I must to use the feature, configure to enable it on pallet-nfts is a little bit odd... instead, the feature gates should be used to restrict pallet-nfts extrinsic, that's more security than filter extrinsic calls on Runtime because pallet-nfts has too much extrinsics and may change in the future, besides like my WIP pallet, my pallet will do minting NFTs so I want disable pallet-nft `mint` extrinic

**Comment by jasl** [comment]
I would love for help if you can give me some directions, those changes I think shouldn't difficult to me

**Pull request closed without merging**
