### PR TITLE
change reference module to pallet

### PR DESCRIPTION
**Pull request by NoCtrlZ**
I changed the rust docs reference according to the latest update.
Please confirm.
Thank you.

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Comment by kianenigma** [comment]
@TriplEight aren't these README files autogenerated based on code docs? in that case the code should be changed, not the readme.

**Review by kianenigma — CHANGES_REQUESTED** [review]
You should change the code doc, not the .md file.

**Comment by thiolliere** [comment]
I believe the inner doc in the rust file are already fixed and so the readme should be fixed when publishing next version, but if not then yes they should be.

**Review by thiolliere — APPROVED** [review]

**Comment by kianenigma** [comment]
Hmm this one is not, the rest are fine. 🤷 
https://github.com/paritytech/substrate/blob/master/frame/assets/src/lib.rs#L115

**Review by kianenigma — APPROVED** [review]

**Comment by thiolliere** [comment]
bot merge

**Pull request merged**
