### PR TITLE
Test restoring zeroed data

### PR DESCRIPTION
**Pull request by pepyakin**
This PR adds a test similar to one we already had: `returns_mutable_static`. This time is for zero-initialized memory.

### CODE REVIEW

**Comment by athei** [comment]
Why is it important that the memory is an array and not only a single primitive? Shouldn't all zero initialized memory be located in the bss? I am asking because you only access a single element of the array.

**Comment by pepyakin** [comment]
It's not important. I started with `ptr::null()` but then for some reason switched to an array.

**Comment by athei** [comment]
Can you to just using a primitive?

Then it would be consistent with the non-BSS test.
```rust
static mut MUTABLE_STATIC_BSS: u32 = 0;
```

**Review by athei — APPROVED** [review]

**Comment by pepyakin** [comment]
bot merge

**Pull request merged**
