### PR TITLE
update UI tests to support rust 1.70

### PR DESCRIPTION
**Pull request by sam0x17**
Updating rust to 1.70

dependent on https://github.com/paritytech/ci_cd/issues/816

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Maybe we can get `bot update-ui` eventually.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2993280

**Review by bkchr — APPROVED** [review]

**Review by juangirini — APPROVED** [review]

**Comment by altaua** [comment]
> Maybe we can get `bot update-ui` eventually.

Done! https://github.com/paritytech/command-bot-scripts/pull/37

**Comment by altaua** [comment]
This is outdated, there have been ui test changes in the meantime. Let's get https://github.com/paritytech/substrate/pull/14399 merged instead, that contains both ui test updates and all other changes required for 1.70 in one atomic bundle.

**Pull request closed without merging**
