### PR TITLE
Make assets storage public

### PR DESCRIPTION
**Pull request by drewstone**

### CODE REVIEW

**Comment by bkchr** [comment]
Can you please give some reason why you want to do this? 

Do you need write access?

**Comment by drewstone** [comment]
I need read access from another pallet.

**Comment by drewstone** [comment]
Also is there any chance we can get these functions exposed for other pallets to use? Say I want the Issuer of an asset to be another pallet. Inside this other pallet, I want to mint/burn tokens, it is not possible at this moment because the fns are private, any reason why its so strict?

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by drewstone** [comment]
For example, I want to declare in a new module, which is why I'm making this public.
```
ensure!(<pallet_assets::Module<T> as Config>::Asset::contains_key(asset_id), Error::<T>::AssetIdDoesNotExist);
```

Additionally, if the asset exists, I'm trying to also mint/burn it depending on other criteria.

**Comment by shawntabrizi** [comment]
Changing this to `pub` really isnt harmful in anyway, but the correct approach here is to create a trait similar to `Currency` that other pallets can use to manipulate these funds. That would be a more appropriate PR.

The trait probably looks similar to ERC20.

**Comment by xlc** [comment]
Most of the pallets have storage `pub` anyway so I think this is fine. But I do agree have a trait abstraction is better approach.
If you do want to add a trait, take a look our one https://github.com/open-web3-stack/open-runtime-module-library/blob/master/traits/src/currency.rs

**Pull request closed without merging**
