### PR TITLE
Fix build error in no_std env

### PR DESCRIPTION
**Pull request by gguoss**
99  | / decl_storage! {
100 | |     trait Store for Module<T: Trait> as Assets {
101 | |         /// The number of units of assets held by any given account.
102 | |         Balances: map (AssetId, T::AccountId) => T::Balance;
...   |
105 | |     }
106 | | }
Vec not found in this scope

### CODE REVIEW

**Comment by bkchr** [comment]
Hey, could you please give more information on what command you executed? And on which branch are you?

**Comment by gguoss** [comment]
git commit: eee0395a895bebc067f8cfaa16997e1a00ba5a59
rustc 1.31.0-nightly (bef62ccdd 2018-10-16)
substrate/srml/assets:
[feature]
default = []

**Comment by gguoss** [comment]
master branch

**Comment by bkchr** [comment]
And which command did you execute exactly?

**Comment by niklasad1** [comment]
@gguoss 

I think you need to use `default-features = false` and then it will work but I'm not really familiar with the code-base @bkchr maybe you can confirm? :+1:

**Comment by bkchr** [comment]
@gguoss Thanks for finding this bug, I opened https://github.com/paritytech/substrate/pull/956 to fix the root cause of this error.

**Pull request closed without merging**
