### PR TITLE
include dispatch result in the Executed event

### PR DESCRIPTION
**Pull request by xlc**
So we can have some clue why it failed.

polkadot companion: paritytech/polkadot#3477

### CODE REVIEW

**Comment by xlc** [comment]
polkadot companion build error looks unrelated

**Review by seunlanlege — APPROVED** [review]
Hmm, this actually isn't a bad idea

**Review by kianenigma — APPROVED** [review]

**Comment by kianenigma** [comment]
companion build failing?

**Comment by xlc** [comment]
good now

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
