### PR TITLE
Remove warning about networking taking a lot of time

### PR DESCRIPTION
**Pull request by tomaka**
After https://github.com/paritytech/substrate/pull/6533, this duration no longer represents how long it took to poll the networking worker, but the time it took to wait plus poll. In other words, this log entry is misleading.

The information about how much time it takes to poll tasks is already tracked in Prometheus, so this warning doesn't bring much anymore anyway.

### CODE REVIEW

**Comment by mxinden** [comment]
What do you think of adding a Prometheus alert to ensure we don't silently introduce a regression in the future?

**Comment by tomaka** [comment]
This warning is unfortunately triggered fairly frequently already, except that I see it on Grafana and not in logs.

**Comment by mxinden** [comment]
> This warning is unfortunately triggered fairly frequently already, except that I see it on Grafana and not in logs.

Paraphrasing this to make sure I understood your point: As this `warn!` is already triggered quite frequently, the Prometheus alert would as well, thus it does not make sense to add a Prometheus alert to https://github.com/paritytech/substrate/blob/master/.maintain/monitoring/alerting-rules/alerting-rules.yaml.

**Comment by tomaka** [comment]
> Paraphrasing this to make sure I understood your point: As this warn! is already triggered quite frequently, the Prometheus alert would as well

Yes.

> thus it does not make sense to add a Prometheus alert to https://github.com/paritytech/substrate/blob/master/.maintain/monitoring/alerting-rules/alerting-rules.yaml.

We can open an issue about this, though.

**Pull request merged**
