### PR TITLE
Benchmark macro: Allow multiple bounds in where

### PR DESCRIPTION
**Pull request by weichweich**
The where clause in the benchmark macro supports only a single trait bound for each type constraint.

```rust
benchmarks!{
	where_clause {
		where
			// the bound `ThisIsNotSupported`  won't work because there is no rule to match that
			<T as OtherConfig>::OtherEvent: Into<<T as Config>::Event> + ThisIsNotSupported
	}
	...
}
```

To support multiple bounds, I changed the macro to use `tt` instead of `path` and added a few more bounds in the tests to check if it's working.

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by thiolliere — APPROVED** [review]

**Comment by thiolliere** [comment]
bot merge

**Comment by thiolliere** [comment]
maybe you can merge master to fix CI

**Comment by thiolliere** [comment]
:-/ it seems you merged master while substrate and polkadot were broken. If you merge master again it should be fine

**Comment by weichweich** [comment]
> :-/ it seems you merged master while substrate and polkadot were broken. If you merge master again it should be fine

I merged the latest master yesterday. There are no new commits to merge. :(

**Comment by thiolliere** [comment]
> > :-/ it seems you merged master while substrate and polkadot were broken. If you merge master again it should be fine
> 
> I merged the latest master yesterday. There are no new commits to merge. :(

indeed, I just rerun the job and it worked

**Pull request merged**
