### PR TITLE
Multithreaded POW mining worker

### PR DESCRIPTION
**Pull request by Wizdave97**
What this PR does?

This PR modifies the `sc_consensus_pow::start_mining worker` to return a clonable channel that recieves a broadcast of  the latest  mining metadata, so nodes can try to compute the seal using a multithreaded approach.

### CODE REVIEW

**Comment by Wizdave97** [comment]
@sorpaas  Here are the benchmarks results below, 
you can clone this repo https://github.com/polytope-labs/sybil and run them yourself using the bench.ts script in the blocktime 
folder

For the default mutex worker use the `update-master-to-work-with-latest-substrate` branch
For the multithreaded worker  branch you can use `wiz-mining-threaded` branch


## Default Mutex worker

Platform: linux

Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
 4 cores, 8 threads
 
Total memory: 25.047011328gb

Difficulty:1_000_000_000

Block times(seconds) from Genesis block
58.04699993133545
364.9449999332428
286.91600012779236
681.7999999523163
182.71200013160706
1674.4679999351501
2556.4079999923706
78.77099990844727
126.03200006484985
437.81699991226196
283.3200001716614
560.6549999713898
497.5529999732971
1444.0049998760223
51.52300000190735
168.64200019836426
2186.25
5240.287999868393
74.10000014305115

Average Block time: 892.329052636498


 ## Multithreaded mining worker

Platform: linux
Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
 4 cores, 8 threads

Total memory: 25.047011328gb

Benchmarked with 8 threads
Difficulty:1_000_000_000

Block times (seconds) from Genesis block
691.5700001716614
9.455999851226807
1174.965000152588
1441.9349999427795
184.58599996566772
158.2829999923706
163.4630000591278
238.4099998474121
417.4450001716614
149.61299991607666
236.46399998664856
82.84700012207031
116.86999988555908
5.727999925613403
463.8310000896454
512.045000076294
389.3139998912811
45.00600004196167
105.22699999809265

Average block time: 346.687263162512

**Comment by sorpaas** [comment]
You're using `metadata` call in your hot loop. Please fix that and other issues first! I know you're trying to show that this PR is merge-able but it's not the way to go to use the worst optimized code vs this PR.

Also I'd appreciate to see if you can port https://github.com/kulupu/kulupu/blob/master/pow/src/lib.rs over to work with this PR. It has an optimization where the execution of a new loop is dependent on the previous loop. This PR actually looks like a revert of #7060. We did handle the whole thread management within Substrate for mining workers, but later figured out that just won't work for any mining algorithms that's slightly complex.

**Comment by Wizdave97** [comment]
@sorpaas  I was not able to get the benchmarks for the multithreaded mining worker based on the mutex worker, it keeps deadlocking once multiple threads are enabled, if you can take a look at the  code  and see what's wrong, that would go a long way in helping speed up getting those benchmarks.  https://github.com/polytope-labs/sybil  -> branch  ->  `update-master-to-work-with-latest-substrate`.

**Comment by sorpaas** [comment]
Let me get this straight -- unless there can be drastic performance improvement with this change, I don't think we'd want to revert back to the model in this PR, and I see the chance of this ever getting merged to be slim.

Handling threads internally in the `pow` model is incompatible with many mining algorithms. Using additional abstractions like future or channel does not add much benefits when things can be described clearly with low-level primitives. You also do not want to wait for futures in the mining threads, because it adds extra latency.

**Comment by Wizdave97** [comment]
> Let me get this straight -- unless there can be drastic performance improvement with this change, I don't think we'd want to revert back to the model in this PR, and I see the chance of this ever getting merged to be slim.
> 
> Handling threads internally in the `pow` model is incompatible with many mining algorithms. Using additional abstractions like future or channel does not add much benefits when things can be described clearly with low-level primitives. You also do not want to wait for futures in the mining threads, because it adds extra latency.

@sorpaas  Any luck getting the multithreading to work here  https://github.com/polytope-labs/sybil -> branch -> `update-master-to-work-with-latest-substrate`

**Comment by sorpaas** [comment]
@Wizdave97 Try #9698 and see if it works for you. It handles locking internally now so should prevent most possible misuses.

**Comment by Wizdave97** [comment]
Mutex based worker

linux
Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
 8 cores
Total memory: 25.047007232gb
Difficulty:1_000_000_000

Block times(seconds)
60.77199983596802
180.78200006484985
93.36800003051758
51.019999980926514
38.34500002861023
177.07999992370605
393.3180000782013
16.391000032424927
531.3409998416901
208.5970001220703
59.675999879837036
692.7750000953674
177.0420000553131
77.00099992752075
748.1489999294281
348.3100001811981
214.72299981117249
487.49500012397766
252.47300004959106
592.5089998245239

Avg Block time: 270.0583499908447


Stream based worker

linux
Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
 8 threads
Total memory: 25.047007232gb
Difficulty:1_000_000_000

Block times(seconds)
16.628000020980835
317.0720000267029
499.17199993133545
116.1819999217987
2496.996999979019
20.974000215530396
181.79499983787537
1229.4260001182556
129.30999994277954
457.6329998970032
67.22200012207031
583.5969998836517
92.56900000572205
483.90000009536743
755.2969999313354
223.375
191.24100017547607
172.80299997329712
69.33599996566772
73.18400001525879

Average block time: 408.88565000295637

**Pull request closed without merging**
