### PR TITLE
Replace bitmask with bitflags

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

The `bitflags` library is a better alternative to the `bitmask`, with more users and more active maintenance.

polkadot companion: paritytech/polkadot#1747

### CODE REVIEW

**Comment by kianenigma** [comment]
Can you explain the motive behind the PR and provide a general description?

**Comment by koushiro** [comment]
This change will break the compilation of the runtime of polkadot, but I think it could be fixed easily.

```
➜  polkadot git:(master) rg "WithdrawReason"
runtime/common/src/crowdfund.rs
72:		Currency, Get, OnUnbalanced, WithdrawReason, ExistenceRequirement::AllowDeath
276:			let transfer = WithdrawReason::Transfer.into();
458:			let transfer = WithdrawReason::Transfer.into();
488:			let transfer = WithdrawReason::Transfer.into();

runtime/common/src/slots.rs
28:	traits::{Currency, ReservableCurrency, WithdrawReason, ExistenceRequirement, Get, Randomness},
633:						WithdrawReason::Fee.into(),
670:							WithdrawReason::Fee.into(),
```

Just need to rename `WithdrawReason` to `WithdrawReasons` and remove `into` conversion function.

**Comment by koushiro** [comment]
@kianenigma PTAL

**Comment by bkchr** [comment]
@koushiro you need to create a companion pr to make the companion pr happy.

**Comment by koushiro** [comment]
@kianenigma @bkchr PTAL

**Review by kianenigma — APPROVED** [review]
Looks sane to me, albeit since this is a new runtime dependency, I advise further reviewers to take that also into account. 

--- 

Your companion needs further work though.

**Comment by xlc** [comment]
> albeit since this is a new runtime dependency

Cargo.lock said otherwise. This removes a runtime dependency.

**Comment by kianenigma** [comment]
bitmask is removed and bitflags is added, no?

**Comment by xlc** [comment]
But bitflags is already used by other pallet.

https://github.com/paritytech/substrate/blob/0aa4ab40cc91745799bb441da2901fdae6b67ba3/frame/contracts/Cargo.toml#L16

Oh we have enumflags2 as well.

https://github.com/paritytech/substrate/blob/0aa4ab40cc91745799bb441da2901fdae6b67ba3/frame/identity/Cargo.toml#L18

**Review by thiolliere — APPROVED** [review]
PR code is good to me, I have no strict opinion between bitmask or bitflags though.

**Review by bkchr — APPROVED** [review]
@koushiro can you please update your companion so that we can merge this. TY

**Comment by koushiro** [comment]
@bkchr  sorry for the late reply, I have updated the polkadot companion. PTAL

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
Thank you

**Pull request merged**
