### PR TITLE
Sync: Fix issue of not freeing a block announcement slot

### PR DESCRIPTION
**Pull request by bkchr**
There was a bug that when the block announcement validation returned an
error, the slot reserved for this validation wasn't freed. This could
lead to a situation where we rejected any block announcement from such a
peer for that the block announcement returned an error multiple times.

### CODE REVIEW

**Review by arkpar — APPROVED** [review]

**Comment by bkchr** [comment]
Because of me being to dumb to use `saturating_sub`, this could actually lead to stop syncing from peers on chains without any block announcement data being added. Normally that probably shouldn't happen as we only receive one block announcement at a time.

**Review by tomaka — APPROVED** [review]
:shrug:

**Review by andresilva — APPROVED** [review]

**Comment by andresilva** [comment]
bot merge

**Comment by s3krit** [comment]
bot merge

**Pull request merged**
