### PR TITLE
Deprecate Pallet `decl_*` Macros

### PR DESCRIPTION
**Pull request by ggwpez**
It should come at no surprise that we are deprecating: `decl_module`, `decl_storage`, `decl_error` and `decl_event`.  
Any remaining usage should be migrated to use `#[frame_support::pallet]`.

Related https://github.com/paritytech/substrate/issues/12248  
Depends on https://github.com/paritytech/substrate/pull/12445, https://github.com/paritytech/substrate/pull/12401

### CODE REVIEW

**Comment by altaua** [comment]
[here](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2586935#L7833)'s the actual reason for the pipeline failure, the decl_storage_ui test is unsurpringly failing. Will investigate how the job log got truncated.

**Comment by ggwpez** [comment]
> Don't we first want to merge the prs that remove the usages in our code base?

Ideally yes, but they got closed as stale. Will need to check how much effort that is and maybe quickly do it.  
Otherwise this is already going to notify any other downstream projects who are still using them.

**Comment by bkchr** [comment]
They got reopened. Otherwise it should be fairly straightforward to remove them.

**Comment by ggwpez** [comment]
Okay will wait for the other MRs.

**Comment by ggwpez** [comment]
I searched on GitHub, and there are still lots of projects the old macrod. I think we should give at least 3 months lead period before finally deleting. Although, this old code is blocking a lot of issues…  
cc @juangirini @aaronbassett

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2803191

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2803189

**Review by sam0x17 — APPROVED** [review]
Yeah I agree that deprecation and then eventual removal is definitely the way to go

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2803321

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2803320

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2803322

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2803854

**Review by KiChjang — APPROVED** [review]

**Pull request merged**
