### PR TITLE
Fix V2 PoV benchmarking

### PR DESCRIPTION
**Pull request by ggwpez**
Changes:
- Fix case where Measured was too large for V2 syntax. We currently have some copy&paste code that was wrong in one part. Definitely need to clean it up somehow: 1. item in https://github.com/paritytech/substrate/issues/13132.
- Besides that the MEL proof size benchmarking uses `additional_trie_layers` to estimate the number of additional trie layers which have to be accounted for when generating a proof. The default value of `0` only works for extremely small runtimes, which have no more than 16 storage prefices. This is changed to a "sane" default of 2, which is safe for runtimes with up to 4096 storage prefices (eg `StorageValue`).

### CODE REVIEW

**Review by sam0x17 — APPROVED** [review]

**Comment by ggwpez** [comment]
bot bench $ pallet dev pallet_balances  
bot bench $ pallet dev pallet_message_queue

**Comment by ggwpez** [comment]
bot bench $ pallet dev pallet_glutton

**Review by gavofyork — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2458154

**Comment by ggwpez** [comment]
bot bench $ pallet dev pallet_glutton

**Comment by ggwpez** [comment]
bot merge

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2460488

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
