### PR TITLE
Make All FRAME Extrinsics Public

### PR DESCRIPTION
**Pull request by apopiak**
This PR changes the visibility of all extrinsics to `pub` so they are available from the outside.
This allows for e.g. state creation in tests.

Note: The extrinsics were available via the `Call` enum before, just not directly callable.

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]

**Review by athei — APPROVED** [review]

**Comment by apopiak** [comment]
DQ: Why would I be getting failed tests in the error reporting? (e.g. `derive_no_bound_ui/partial_eq.rs`)

**Comment by thiolliere** [comment]
> DQ: Why would I be getting failed tests in the error reporting? (e.g. `derive_no_bound_ui/partial_eq.rs`)

Weird, is there some inconsistency ? the PR https://github.com/paritytech/substrate/pull/9071 tried to fix it and got the opposite output.

**Review by kianenigma — APPROVED** [review]

**Comment by athei** [comment]
I think what happened is:

1. Nightly upgraded
2. CI failed
3. PR that fixes CI
4. CI success
4. Nightly downgraded
5. CI fails again

**Comment by thiolliere** [comment]
but UI test should only run for stable:
```
#[rustversion::attr(not(stable), ignore)]

**Review by shawntabrizi — APPROVED** [review]

**Pull request merged**
