### PR TITLE
txpool: enactment state forced update

### PR DESCRIPTION
**Pull request by michalkucharczyk**
When `tree_route` computation fails, we still need to update the
`enactment_state` to be aligned with last known finalized/best block.

We do not execute enactment phase of maintain procedure, but we do
update the state.

Fixes: #12623

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by davxy — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
I *dienerd* Polkadot this fixes the warp sync, but it still fails afterwards:  
`polkadot --sync warp --db paritydb -d empty-folder` works fine, but then try `Ctrl+C` it and restarting results in the error that i posted in the issue:  
```pre
# Many of these lines:
Block record is missing from the pruning window, block number 0   
… 
GRANDPA voter error: could not complete a round on disk: State Database error: Block record is missing from the pruning window    
Essential task `grandpa-voter` failed. Shutting down service.    
Block record is missing from the pruning window, block number 0    
Error: 
   0: Other: Essential task failed.
```

**Comment by davxy** [comment]
@ggwpez I've reproduced your issue.

And apparently it happens only when using `parity-db` and I'm not sure is related to the error I've initially signaled. Here the error comes from `state-db` and not from `txpool`

---

To reproduce:
1. start the node as @ggwpez suggested.
2. CTRL-C after warp sync when old blocks download starts
3. Restart

```
...
2022-11-07 17:57:01.461 ERROR tokio-runtime-worker state-db: Block record is missing from the pruning window, block number 0
2022-11-07 17:57:01.461 ERROR tokio-runtime-worker state-db: Block record is missing from the pruning window, block number 0
2022-11-07 17:57:01.461 ERROR tokio-runtime-worker afg: GRANDPA voter error: could not complete a round on disk: State Database error: Block record is missing from the pruning window
2022-11-07 17:57:01.461 ERROR tokio-runtime-worker sc_service::task_manager: Essential task `grandpa-voter` failed. Shutting down service.
2022-11-07 17:57:01.461 ERROR tokio-runtime-worker state-db: Block record is missing from the pruning window, block number 0
Error:
   0: Other: Essential task failed.
```

^ In some runs I had to `CTRL-C` here, otherwise the `Block record is missing...` message goes on forever 

---

Maybe this is a topic for a separate issue...

**Comment by michalkucharczyk** [comment]
> Maybe this is a topic for a separate issue...
+1

**Comment by ggwpez** [comment]
> Maybe this is a topic for a separate issue...

https://github.com/paritytech/substrate/issues/12635

**Pull request merged**
