### PR TITLE
Bump dependencies, respecting semver

### PR DESCRIPTION
**Pull request by DemiMarie-parity**

### CODE REVIEW

**Comment by bkchr** [comment]
You have done this just last week? Do we really need this every week?

**Comment by DemiMarie-parity** [comment]
@bkchr Ideally, this would be automated.

**Comment by kianenigma** [comment]
Such PRs can potentially break polkadot as well. So they should be checked pre-merge. I just some dependency divergence between some cli dep that breaks polkadot build

**Comment by kianenigma** [comment]
namely updating `structopt` which I assume happened recently.

**Comment by bkchr** [comment]
structopt was not updated in this pr.

**Comment by kianenigma** [comment]
Yes I had a general comment about "Such PRs", not this one in particular. I didn't really look into where when it was updated and I suppose it doesn't matter now. Next polkadot merge can fix it.

**Comment by DemiMarie-parity** [comment]
@kianenigma is there a reason this check is not part of CI?

**Comment by kianenigma** [comment]
Not sure. I practice, we can just add a check to every PR that tries to build polkadot with this branch. cc @gabreal

**Comment by bkchr** [comment]
This check would be useless. People are already confused about the check runtime test. When polkadot could not be built anymore, how should this be solved by an external contributor? Yes, that does not work.

**Comment by kianenigma** [comment]
I never said it would be a holy grail but it does not hurt anyone if there is a check that tells you "Hey polkadot will not build with this". If it has a sane reason, then it just helps you be more mindful and aware of it, like a warning. Similar to check runtime it can be optional. I really think it is a step forward at the least :D 🤷🏻‍♂️

**Comment by bkchr** [comment]
People already don't understand check runtime and think they have done something wrong.
I also think that we require much more important CI stuff (like a bot).

**Pull request merged**
