### PR TITLE
Don't send back empty proofs if light request fails

### PR DESCRIPTION
**Pull request by tomaka**
At the moment, if the node receives a so-called "light client request" (asking for a storage proof or a call proof), and this request cannot be served, we send back a message indicating that everything is ok, except that it contains an empty proof.
The reason why a request cannot be served is typically that the block has been pruned.

This PR modifies the protocol so that we send back a message without any proof instead.

To do an analogy, right now we more or less send back `Some(Vec::new())`, while this PR modifies this to send back `None`.

This makes it clearer from the point of view of the request sender that something bad has happened.

### CODE REVIEW

**Review by cheme — APPROVED** [review]
Change looks good (til I learn that oneof is not required).
I am wondering a bit about versioning, but will probably leave it like this.
Would need to be mentioned in release note as potentially breaking through.

**Comment by tomaka** [comment]
> I am wondering a bit about versioning, but will probably leave it like this.

As far as I know, only smoldot sends these requests at the moment, and I'm ok with my own change.

**Review by altonen — APPROVED** [review]

**Comment by lamafab** [comment]
What about the `Header` and `Changes` responses (currently both still just return `HandleRequestError::BadRequest("Not supported.")`)?

**Review by dmitry-markin — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
