### PR TITLE
Merge 2.0.1 backport branch into mainline master

### PR DESCRIPTION
**Pull request by Xanewok**
This is https://github.com/paritytech/substrate/pull/7686 (reviewed and accepted) but targeting master to retain future release tag in the master history line.

### CODE REVIEW

**Comment by Xanewok** [comment]
It's worth noting that this should be **merged directly** rather than squashed, as the point is to retain connection with backports from https://github.com/paritytech/substrate/pull/7842 done on top of `v2.0.0` tag via latest https://github.com/paritytech/substrate/pull/7842/commits/19610f952147b520d4775ac9d684cd6d5277cdcb merge commit.

**Review by gnunicorn — APPROVED** [review]

**Comment by Xanewok** [comment]
I'm somewhat torn on B-* labels - at the same time it's not really important in terms of API changes, runtime etc. but these definitely should be documented as a patch release. Leaving as B0-silent for now.

@gnunicorn Polkadot CI check is green now (thanks @bkchr) and everything seems to be good to go. Should we merge this?

**Comment by Xanewok** [comment]
We should probably backport https://github.com/paritytech/substrate/pull/7838 as well. Will do that tomorrow.

**Review by bkchr — APPROVED** [review]

**Comment by Xanewok** [comment]
@gnunicorn updated with latest changes from https://github.com/paritytech/substrate/pull/7686, hopefully this should be good to go once CI agrees

**Comment by Xanewok** [comment]
All is green so tagging #7686 for 2.0.1 release.

**Comment by Xanewok** [comment]
Force-pushed a new merge commit that includes a new signed commit for 2.0.1 (https://github.com/paritytech/substrate/pull/7842/commits/2cd20966cc09b059817c3ebe12fc130cdd850d62).

**Comment by Xanewok** [comment]
Blocked on #7844.

**Pull request merged**
