### PR TITLE
test run 2

### PR DESCRIPTION
**Pull request by oleg-plakida**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2760723

**Comment by oleg-plakida** [comment]
bot bench -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot bench -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot bench -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot bench -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot bench -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot cancel 32-c0b098c4-6b7c-41e6-bffa-712b0cf1c549

**Comment by oleg-plakida** [comment]
bot bench -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot bench -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot bench -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot bench-vm -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
bot bench-vm -v UPSTREAM_MERGE=n $ all

**Pull request closed without merging**
