### PR TITLE
Update futures dependency

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by bkchr** [comment]
Why only `futures`? What is with other dependencies?

**Comment by NikVolf** [comment]
@bkchr Haven't spotted any changes in them

what 0.3.4 has is 
> Fixed missing Drop for UnboundedReceiver (#2064)`

which we use a lot

**Comment by bkchr** [comment]
Please merge master to fix the `check_warnings` job.

**Comment by tomaka** [comment]
Note that according to https://github.com/rust-lang/futures-rs/pull/2064 this was only a bug in futures 0.3.3, and it was correct back in futures 0.3.2.

**Pull request merged**
