### PR TITLE
Reweigh Staking

### PR DESCRIPTION
**Pull request by shawntabrizi**
This PR does a sanity check of the weights in the Staking pallet.

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]
let's update polkadot as well. 

I guess the 10% regression that you fox here was just noise, or the machine being used by other users?

**Review by thiolliere — APPROVED** [review]

**Comment by shawntabrizi** [comment]
/benchmark runtime custom --chain dev --steps 50 --repeat 50 --extrinsic "*" --execution=wasm --wasm-execution=compiled --output ./bin/node/runtime/src/weights --header ./HEADER --pallet pallet_balances

**Comment by shawntabrizi** [comment]
/benchmark runtime custom --chain dev --steps 50 --repeat 100 --extrinsic "*" --execution=wasm --wasm-execution=compiled --output ./bin/node/runtime/src/weights --header ./HEADER --pallet pallet_balances

**Comment by kianenigma** [comment]
Will be done here https://github.com/paritytech/substrate/pull/7340

**Pull request closed without merging**
