### PR TITLE
Add a usable_balance_for function to the Currency trait

### PR DESCRIPTION
**Pull request by sorpaas**
This adds a `usable_balance_for` function to the Currency trait. In situations like EVM, we care about the *actually* transferrable balance, which currently can't be fetched via the `Currency` trait. With this function we can do `usable_balance_for(account_id, WithdrawReasons::TRANSFER)`.

### CODE REVIEW

**Comment by sorpaas** [comment]
^ It shouldn't need any Polkadot PR. The CI error looks like something else unrelated.

**Comment by gavofyork** [comment]
under what circumstance is this needed?

**Comment by sorpaas** [comment]
@gavofyork `pallet-evm` needs something like this. Right now, the EVM would return the account balance as `free_balance`. This, however, breaks the usual EVM assumption that if a balance is available, then it can be used in `TRANSFER`. By changing the returned balance to `used_balance_for(TRANSFER)` this issue can be then fixed.

**Comment by JoshOrndorff** [comment]
Is there any intention to merge this? If so the Moonbeam team is willing to brush the dust off of it. If this won't be merged we can begin looking for other solutions to https://github.com/paritytech/frontier/issues/291

**Comment by thiolliere** [comment]
now that https://crates.parity.io/frame_support/traits/tokens/fungible/trait.Inspect.html exists I think this is no longer required no ?

Also this doesn't take into account the providers restriction. so people could expect to be able to withdraw the total amount where it is actually not possible.
Related https://github.com/paritytech/substrate/issues/8258

**Comment by sorpaas** [comment]
@thiolliere Yeah I think you're right. This can be closed now!

**Pull request closed without merging**
