### PR TITLE
Enable wasm-opt optimizations in `wasm-builder`

### PR DESCRIPTION
**Pull request by athei**
A while back we made the switch from the abandoned `wasm-gc` to `wasm-opt`. However, we didn't enable any optimizations in order to make it a in-place replacement at first.

The plan was always to use those optimizations as we have seen big gains especially when running wasmi under wasmtime. The reason why this is the case is that LLVM as a register machine has a hard time optimizing wasm code. Hence this postprocessing step can be quite powerful.

A burn in with those optimization enabled [has already been performed by @koute](https://github.com/paritytech/substrate/pull/13312#issuecomment-1418583754). What is left is running all benchmarks to make sure we are not producing a performance regression.

For release builds we are using `O1` which just adds 3 seconds to the build. For production builds we use the slowest profile `O4` which adds 6 minutes on my machine. The production profile is already pretty slow and only used for benchmarking and releases. No developer should be using this profile locally in their workflow.

@alvicsam How can a produce a new baseline in this PR using the old bare metal machines?

cc @Robbepop 

[Weight Compare](https://weights.tasty.limo/compare?unit=time&ignore_errors=true&threshold=10&method=asymptotic&repo=substrate&old=master&new=at%2Fwasm-opt&path_pattern=frame%2F**%2Fsrc%2Fweights.rs)

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by lexnv — APPROVED** [review]

**Comment by athei** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by athei** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot clean

**Comment by oleg-plakida** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by oleg-plakida** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by oleg-plakida** [comment]
bot bench $ all

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by athei** [comment]
bot clean

**Comment by athei** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=mak/bench-all $ ""

**Comment by athei** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=mak/bench-all $ ""

**Comment by athei** [comment]
Don't merge before the benchmarks are in and we had a discussion about the result.

**Comment by athei** [comment]
Performance regressed. I started a new run on master to double-check that the regression is caused by wasm-opt: https://github.com/paritytech/substrate/pull/13507

**Comment by athei** [comment]
bot cancel

**Comment by athei** [comment]
bot clean

**Comment by athei** [comment]
bot bench $ all

**Comment by athei** [comment]
bot bench $ all

**Comment by ggwpez** [comment]
The last change does not seem to make a difference. Asymptotic is [stable](https://weights.tasty.limo/compare?repo=substrate&threshold=0&path_pattern=frame%2F**%2Fsrc%2Fweights.rs&method=asymptotic&ignore_errors=true&unit=time&old=4ca15fece0f5835db6bd509e34d5d49dc87da727&new=ff14c95b5561e07bb4c5e207ae29d89cefb4c451&git_pull=false&pallet=contracts).

**Comment by athei** [comment]
Yeah if `O4` and `O2` are similar we can just go with `O2` which is more conservative and faster. But the optimizations don't seems to help overall. They are supposed to be more important for newer wasmi versions. I will check the effect of them on the new wasmi version here: https://github.com/paritytech/substrate/pull/13312  before merging this.

**Comment by athei** [comment]
Neither this PR nor under the new wasmi 0.28 in #13312 we saw any performance improvements with wasm-opt. On the contrary: The performance regressed. This is why we do not enable the optimization. It should only be done if clear improvements can be demonstrated.

Can be revisited later but for now there does not seem to be a reason to enable it. Maybe we can enable some selective passes that deal with code size if we want to. Or we may look into it again once we are ready to use more wasm features (post MVP).

**Pull request closed without merging**
