### PR TITLE
Remove dependency on substrate-prometheus-endpoint that is no longer required

### PR DESCRIPTION
**Pull request by chevdor**
This PR follows #9319 and removes a dependency that is no longer required.

### CODE REVIEW

**Review by bkchr — CHANGES_REQUESTED** [review]
`futures_timer`
`sp_utils`
`sp_trie`
`sp_api`
`parking_lot`
`serde`
`wasm_timer`

Also do not seem to be used.

**Comment by bkchr** [comment]
Have you run any `cargo update`? Can you please revert this. You have updated deps like `rocksb`.

**Review by gilescope — APPROVED** [review]
Looks good to me.

**Comment by gilescope** [comment]
(FYI: the contribution guidelines suggest not to use force-push)

**Review by bkchr — APPROVED** [review]

**Pull request merged**
