### PR TITLE
Fix error on new version of structopt

### PR DESCRIPTION
**Pull request by kigawas**
structopt 0.3.6 added unimplemented `augment_clap`

### CODE REVIEW

**Comment by niklasad1** [comment]
@kigawas 

I don't understand the reasoning behind this PR but it is related to https://github.com/TeXitoi/structopt/issues/315 i.e, `structopt v0.3.6` has a breaking change?

I think this doesn't concern `substrate` itself because of `Cargo.lock` but other crates that depend on it?

**Comment by kigawas** [comment]
We need to lock the version of structopt to avoid unintentional change or block a normal cargo update.

**Comment by CreepySkeleton** [comment]
`structopt` devs here. We yanked `0.3.6`, from now on everything should work fine. We will decide what to do with the new release - and how should we do it - ASAP.

**Comment by CreepySkeleton** [comment]
@niklasad1 @kigawas Actually, there's no need for this PR anymore. We'll make sure that all the future releases pull the right dependencies.

**Comment by niklasad1** [comment]
Closing because it is not needed anymore,

> @niklasad1 @kigawas Actually, there's no need for this PR anymore. We'll make sure that all the future releases pull the right dependencies.

**Pull request closed without merging**
