### PR TITLE
No longer generate specs with consensus_engine field

### PR DESCRIPTION
**Pull request by tomaka**
Continuation of https://github.com/paritytech/substrate/pull/10345

This PR is based on top of https://github.com/paritytech/substrate/pull/10345
It is not intended to be merged now, but in a "long" time, for example two months, the time for everyone to upgrade to a recent Substrate version.

### CODE REVIEW

**Comment by tomaka** [comment]
Please don't close this, stalebot. We can merge at least after 0.9.16 is out.

**Comment by tomaka** [comment]
Not stale.

**Comment by bkchr** [comment]
Do we want to merge this?

**Comment by tomaka** [comment]
Sure!
I guess it would be in 0.9.18

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
You still need to make the compiler happy :D

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
