### PR TITLE
node: update flaming fir chain spec

### PR DESCRIPTION
**Pull request by andresilva**
Updates the flaming fir chain spec so that we can restart the testnet using latest master. The authority ids for Babe were updated since they now refer to sr25519 keys (previously using ed25519 in Aura).

Merge only after #3246 and #3251.

### CODE REVIEW

**Comment by andresilva** [comment]
cc @ddorgan

**Comment by tomaka** [comment]
We could also use this opportunity to change the network keys from secp256k1 to ed25519.

**Comment by andresilva** [comment]
@tomaka Apparently we are already using ed25519 network keys. Probably did it last time because `--node-key-type` default changed.

**Comment by andresilva** [comment]
Don't merge this afterwards, I want to rebase this over master to update chain spec (to make sure code storage entry is actually for the latest runtime that will end up in master at this commit).

**Pull request merged**
