### PR TITLE
Only use `substrate-wasm-builder` when `std` feature is enabled.

### PR DESCRIPTION
**Pull request by nazar-pc**
This is a much simpler version of #12786 that achieves the same result. Mostly an example for other projects to follow.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by nazar-pc** [comment]
@bkchr is there anything else that needs to be done here?

**Comment by bkchr** [comment]
> @bkchr is there anything else that needs to be done here?

No! Just a second approval is missing :D

**Comment by bkchr** [comment]
bot rebase

**Review by melekes — APPROVED** [review]
👍

**Review by michalkucharczyk — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
