### PR TITLE
Delete unused extern

### PR DESCRIPTION
**Pull request by gguoss**

### CODE REVIEW

**Comment by rphmeier** [comment]
Where's the CLI bot?

**Comment by bkchr** [comment]
@rphmeier I don't think that we have one for this repository.

**Comment by pepyakin** [comment]
Asked in sub/polka CI channel about that ^^

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot: check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by gavofyork** [comment]
needs resolving

**Pull request merged**
