### PR TITLE
Contracts: fix benchmark comment

### PR DESCRIPTION
**Pull request by pgherveou**

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2954208

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2954191

**Review by juangirini — CHANGES_REQUESTED** [review]
This is still used here

https://github.com/paritytech/substrate/blob/e7eb188d77ac155131519dcb75b02a7fc03276b6/frame/contracts/src/migration.rs#L325-L328

**Review by agryaznov — CHANGES_REQUESTED** [review]
I think we should keep this migration, as the [second one](https://github.com/paritytech/substrate/blob/e7eb188d77ac155131519dcb75b02a7fc03276b6/frame/contracts/src/benchmarking/mod.rs#L272) actually tests dispatchable.

**Comment by agryaznov** [comment]
> ah my bad, missed that in my grep, will just use this PR to amend the other docstring comment then

I don't think a docstring fix worth a standalone PR. Could you pls add it up to https://github.com/paritytech/substrate/pull/14313 or some other bigger change

**Review by juangirini — APPROVED** [review]

**Pull request merged**
