### PR TITLE
Lint TOML Files

### PR DESCRIPTION
**Pull request by shawntabrizi**
Using: https://github.com/shawntabrizi/substrate-toml-check

Probably still need to fix some rules, so consider this in-progress.

What it does:

1. Use `'` for all strings.
2. Alphabetize `[dependencies]`, `[dev-dependencies]`, `[features]`
3. Checks `[package]` for `edition`, `homepage`, and potentially more... TODO

TODO:

- [ ] Keep Comments?
- [x] Order dependency parameters
    - Note this is currently alphabetical, but we could have a custom order if needed.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
It is possible to have and keep comments, but only when they are inline with the things they are commenting.

So:

BAD

```
# my description
my-crate = '1.0.0'
```

GOOD

```
my-crate = '1.0.0' # my description
```

See: https://github.com/LongTengDao/j-toml/blob/master/docs/English/xOptions.md#xoptionscomment

**Comment by bkchr** [comment]
I'm not convinced by this. We should for sure not add custom tools for any `Cargo.toml` formatting. No one will maintain it and then we are fucked again. Your initial idea of checking for missing `std` etc sounded good, but this goes to far IMO.

**Comment by shawntabrizi** [comment]
@bkchr sounds reasonable.

My only thought is that if we do a 1 time format of the TOML, we could also have the tool automatically fix dependencies and commit the toml, but having users do this manually is also okay.

**Comment by bkchr** [comment]
Missing dependencies in the feature list will probably not be that much. So, having the user doing it manually will not be that problematic.

For general toml formatting, I would wait for something in rustfmt or similar. However, we should be really sure to not fuck ourself and also make it for people as easy as possible to run these tools. Any extra tools require some extra step for a contributor.

**Pull request closed without merging**
