### PR TITLE
Related #1134 - Add intermediate node setup

### PR DESCRIPTION
**Pull request by ltfschoen**
- Notes: https://hackmd.io/TXalNnBLQKamBZN6g7rcyQ

- [ ] Description:
  - What it does? **Add intermediate node setup. See Notes above for details**
  - What important points reviewers should know?
  - Anything left for follow-up PRs?
- [ ] Labeled PR with appropriate labels
- [x] Mentioned related issue e.g. `Fixes #228` or `Related #1337`.
- [ ] Asked any particular reviewers to review. If you aren't sure, start with GH suggestions.
- [ ] PR adheres [the style guide](https://github.com/paritytech/polkadot/wiki/Style-Guide)
  - In particular, mind the maximal line length.
  - No commented code checked in unless necessary.
  - Any panickers have a proof or removed.
- [ ] Updated any rustdocs which may have changed
- [x]  Remove `set_setup` and `get_setup` in implementation of `SetupState` (for storage/retrieval of latest state) since it should just happen in analog to
`FactoryFullConfiguration` Substrate service component configuration (which is just a fancy wrapper around Service::Configuration with some defaulting sugar on top) 
- [ ] Add generic to the `SetupState` struct to support different types
- [ ] Pass `setup_state` to all setup functions via `FullImportQueue` in node/cli/src/service.rs and core/service/src/lib.rs
- [ ] Allow `setup_state` to be discarded after setup of the systems
- [ ] Check if reference counting is required
- [ ] Update tests
- [ ] Fixing Rust compiler errors

### CODE REVIEW

**Comment by bkchr** [comment]
Any update for this pr?

**Comment by ltfschoen** [comment]
@bkchr it's still a WIP

**Comment by bkchr** [comment]
Yeah, but you will update this?

**Comment by ltfschoen** [comment]
@bkchr yes, but it takes time as i'm multitasking

**Comment by bkchr** [comment]
Please reopen when you return to this

**Pull request closed without merging**
