### PR TITLE
Spawn the network worker with spawn_blocking

### PR DESCRIPTION
**Pull request by tomaka**
As a mitigation for the network worker sometimes taking up to one second or even one minute, we spawn it on a background thread, just like we do for the import queue.

We should try to revert that after #5433

### CODE REVIEW

**Comment by NikVolf** [comment]
So import and network will now use same threads while they didn't before?

This might cause import to stall network stalls (but not vice versa, since import only takes 1 thread while network might take multiple).

**Comment by tomaka** [comment]
No, they should be on different threads. Each call to `spawn_blocking` results in a separate call to [tokio::spawn_blocking](https://docs.rs/tokio/0.2.20/tokio/task/fn.spawn_blocking.html), which in turn spawns a thread.

**Comment by arkpar** [comment]
Spawning lots of threads when  you have lots of network IO sounds like a terrible idea. IO should be queued all the way to the socket backpressure.

**Comment by tomaka** [comment]
We're not talking about spawning 1000 or even 10 threads, just one so that the network worker stops  sharing the same threads as the more lightweight tasks.

**Comment by bkchr** [comment]
But we have 4 cores, so 4 threads and even if Network is constantly using one core, there are still 3 cores/workers for the other tasks. You really think that this will bring any improvement? Do we see that the long running network task blocks anything else?

**Comment by tomaka** [comment]
> Do we see that the long running network task blocks anything else?

> You really think that this will bring any improvement?

If we're talking about the block production alert thingy that we have right now, I can see that tasks continue to be polled normally even during the period when the network takes ages to process its queue.

It's kind of hard to tell if this will change something. I opened this PR because I don't think it's a bad idea to move CPU-intensive stuff on the side.

One bit of argument is that the Linux kernel prioritizes I/O-intensive threads over CPU-intensive threads in order to minimize latency, and this change moves a CPU-intensive task on the side to give priority to I/O-intensive tasks.

**Comment by arkpar** [comment]
As I understand the problematic task is `on_block_request` that queries blocks from the DB. It does not block on anything, other than rocksdb, but still may take a few seconds according to this [comment](https://github.com/paritytech/substrate/issues/5831#issuecomment-623965607).  I expect this to improve with parity-db.

**Comment by tomaka** [comment]
Tests are failing probably because Ctrl+C doesn't work. I need to investigate this.

**Comment by arkpar** [comment]
But still, what happens if that blocking thread is busy? Do requests get queued? Is the queue size bound?

**Comment by tomaka** [comment]
> But still, what happens if that blocking thread is busy? Do requests get queued? Is the queue size bound?

In libp2p we have a bounded channel.
If I remember correctly the size of the buffer is 16, [plus each connection gets an extra free slot in the buffer](https://docs.rs/futures/0.3.4/futures/channel/mpsc/fn.channel.html).

In other words, the libp2p tasks will just "sleep" (sleep is not the right word since they're async, but you see what I mean) waiting for the worker. While they sleep they also won't touch the socket at all, even if a message is received.

**Comment by arkpar** [comment]
One thread is probably a bit too pessimistic. If we're serving a long block download request and there's a block announcement coming from a peer we want to process that announcement right away as long as there's available CPU resources. Is there such a thing as blocking thread pool?

**Comment by tomaka** [comment]
> If we're serving a long block download request and there's a block announcement coming from a peer we want to process that announcement right away as long as there's available CPU resources.

I think that we got lost in translation at the time, but that's exactly the reason why I opened #5433.

The network worker was really designed to be lightweight and use a little CPU as possible. Its role is normally to be a coordinator that dispatches work to other tasks, and not to do the CPU-intensive things itself.

**Comment by tomaka** [comment]
I think I'm going to tackle #5433 and open a PR instead of this one.

**Comment by tomaka** [comment]
Reviving this PR.

I've fixed the shutdown not working.

**Pull request merged**
