### PR TITLE
Check in block authoring that we can author with current authoring version

### PR DESCRIPTION
**Pull request by bkchr**
We need to make sure that we can still author with the current block authoring implementation, because there could have been a runtime update in between that made the current implementation incompatible.

### CODE REVIEW

**Comment by gavofyork** [comment]
@arkpar : didn't already implement this 18 months ago? :-)

**Comment by arkpar** [comment]
I did here: https://github.com/paritytech/substrate/pull/256/files#diff-76964ec8de481638ce29d022262cfc53R454
But it seems it was lost in one of many refactorings.

**Comment by gavofyork** [comment]
CI fails.

**Comment by gavofyork** [comment]
@bkchr will need a polkadot PR...

**Comment by bkchr** [comment]
Yeah, just waiting for https://github.com/paritytech/substrate/pull/4236 and than will open a pr for both :)

**Pull request merged**
