### PR TITLE
Add a readme about feature metered for sp-utils

### PR DESCRIPTION
**Pull request by kpp**
This PR adds a readme about feature `metered` for `sp-utils`.

### CODE REVIEW

**Review by bkchr — COMMENTED** [review]
This should also be put into the `lib.rs` file. As these readmes are generated from the `lib.rs` files

**Comment by kpp** [comment]
> As these readmes are generated from the lib.rs files

How? Where is the script?

**Comment by bkchr** [comment]
At least it was done once. I would assume that this is done for every release. Nevertheless, it is still good to also have this in the official docs of the crate.

**Comment by kpp** [comment]
`cargo-readme` geterates the previous version of readme. I will fix it. However there is no CI job to check readmes...

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
