### PR TITLE
WIP: Inter-Blockchain Communication (IBC) protocol pallet

### PR DESCRIPTION
**Pull request by DaviRain-Su**
The goal of the Substrate pallet for the [Inter-Blockchain Communication (IBC) protocol](https://github.com/cosmos/ibc) is to allow the Substrate chain to support the IBC protocol and establish connections with other chains that have also implemented it. 

This pallet has already implemented the essential components of the IBC protocol, such as client, connection, and channel. 

In the future, we *could implement* more application-level components described in the IBC protocol

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2191207

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2191206

**Comment by bkchr** [comment]
Thank you for this pr, but I'm not sure we want this in Substrate directly. I mean this could live outside of the Substrate repo.

**Comment by DaviRain-Su** [comment]
> Hey, is anyone still working on this? Due to the inactivity this issue has been automatically marked as stale. It will be closed if no further activity occurs. Thank you for your contributions.

We will maintain it in an [external warehouse](https://github.com/octopus-network/substrate-ibc)

**Pull request closed without merging**
