### PR TITLE
cargo fmt code

### PR DESCRIPTION
**Pull request by yunweb**
substrate lesson1, I need send a pull request. I also only fmt the master branch code.

### CODE REVIEW

**Comment by cecton** [comment]
Duplicated with #5456 

We don't use `rustfmt` in Substrate.

[Here](https://wiki.parity.io/Substrate-Style-Guide) you can find our style guide.

**Comment by accelsao** [comment]
What is the reason that Substrate don't use rustfmt?

**Comment by cecton** [comment]
Some people don't like the styling of rustfmt

**Comment by Demi-Marie** [comment]
I wonder if rustfmt is configurable enough to match our style guide.

**Comment by cecton** [comment]
It might very well be now. It's been a long time. There is an issue about exactly that somewhere actually.

**Comment by accelsao** [comment]
> It might very well be now. It's been a long time. There is an issue about exactly that somewhere actually.

I hope we can reconsider using rustfmt. 👍

**Comment by cecton** [comment]
Found it: https://github.com/paritytech/substrate/pull/286

**Comment by kianenigma** [comment]
also https://github.com/paritytech/substrate/pull/2156

**Pull request closed without merging**
