### PR TITLE
Improve doc

### PR DESCRIPTION
**Pull request by chevdor**
Improve doc
    
   * convert some md to adoc
   * include contrib docs to the main readme
   * add readme for some packages and include them

I don't like duplication so the `.adoc` files mostly fetch the doc from `Cargo-toml` or from the crate doc. It could look nicer but that provides a fair doc for now.

The result is similar to the attached PDF (may not be the very latest one...)
[README.pdf](https://github.com/paritytech/polkadot/files/2223521/README.pdf)

### CODE REVIEW

**Comment by gavofyork** [comment]
i think it might be sensible to wait until we've split apart the repos before trying to link together all the docs?

**Comment by chevdor** [comment]
Yes, that´s why I skipped substrate: https://github.com/paritytech/polkadot/pull/416/files#diff-49b095a76d035c47b4136b1da5a3b7d1R7
Do you plan on splitting more than just substrate ?

For the rest, the doc (mainly just the new `README.adoc`) can follow the refactoring and we´ll mainly have to add/remove/fix some includes.

I don´t plan on doing much more on the topic for now unless there is a fix required.

**Comment by gavofyork** [comment]
Yeah - at least the runtime will also be split out into a separate repo, possibly substrate-demo, too (though that could also just stay with `substrate`).

**Comment by chevdor** [comment]
I don't have access to solve this conflict.
The conflict comes from the fact that `CONTRUBUTING.md` was modified on master but deleted in this branch.

The conflict can be fixed: 
- the `CONTRUBUTING.md` file can be totally deleted
- I brought in the changes from @gnunicorn (68f83a257c69ce876f9daecc812c7548969521e3) into the renamed `.adoc`

**Comment by gnunicorn** [comment]
@chevdor you should be able to fix the conflict by [rebasing your changes on top of master](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).

**Comment by chevdor** [comment]
@gnunicorn ok will do and try to get this one done.

**Comment by gavofyork** [comment]
Lots of conflicts. Reopen once sorted, if desired.

**Comment by chevdor** [comment]
Superseded by #700 and https://github.com/paritytech/polkadot/pull/16

**Pull request closed without merging**
