### PR TITLE
`Contracts::put_code` benchmarks

### PR DESCRIPTION
**Pull request by expenses**
#3885 and #3819 note that `put_code` can take too long on large wasm files, and cause block production to fail. This PR adds benchmarks for this using compiled [ink examples](https://github.com/paritytech/ink/tree/master/examples).

### CODE REVIEW

**Comment by expenses** [comment]
Here's the resulting time for `erc20` by the way:

```
wasms/erc20.wasm        time:   [6.4462 ms 6.5215 ms 6.5997 ms]
                        thrpt:  [7.6973 MiB/s 7.7897 MiB/s 7.8806 MiB/s]
```

This seems pretty fast, so maybe the problems only occur under certain conditions?

**Comment by expenses** [comment]
@Stefie maybe you could run these benchmarks on your machine?

**Comment by thiolliere** [comment]
this does benchmark put_code in native. I don't remember precisely but thoughts wasm was used always for block production. maybe in wasm the put_code performance are very different 🤔 ?

**Comment by expenses** [comment]
Oh, good point! What would be the best way to benchmark in wasm then?

**Comment by thiolliere** [comment]
> Oh, good point! What would be the best way to benchmark in wasm then?

I don't know @pepyakin ?

**Comment by bkchr** [comment]
@expenses you can setup a wasm blob like this one: https://github.com/paritytech/substrate/tree/master/primitives/runtime-interface/test-wasm

Expose a function `benchmark_put_code` or whatever. This function internally calls 1000x `put_code`. And you call this function from your benchmark. See [here](https://github.com/paritytech/substrate/blob/b3a7c8e463ff7a63ce20e1eb14d8ccc63de4a412/primitives/runtime-interface/src/lib.rs#L154) for on how to call it.

**Comment by Stefie** [comment]
> @Stefie maybe you could run these benchmarks on your machine?

Sorry, I was out of office yesterday. If you tell me how, I'm happy to do that! I never ran any benchmarking tests for Substrate.

The times I mentioned in https://github.com/paritytech/substrate/issues/3885 were with the `latest` Docker image from https://hub.docker.com/r/parity/substrate/tags

**Comment by expenses** [comment]
@bkchr is this even possible, given that `GenesisConfig`s and `TestExternalities` only works under `std`?

**Comment by bkchr** [comment]
@expenses please look at the linked code, you create the storage etc from std and just call into wasm to execute the benchmark method.

**Comment by expenses** [comment]
Screen Shot 2019-12-04 at 4 31 23 PM

Here's the output from instrumentation.

**Comment by expenses** [comment]
Closing due to solutions having arised.

**Pull request closed without merging**
