### PR TITLE
Upgrade to libp2p-0.28.

### PR DESCRIPTION
**Pull request by romanb**
This PR upgrades substrate to `libp2p-0.28.1`. See [v24..v28](https://github.com/libp2p/rust-libp2p/compare/v0.24.0...v0.28.1) for the changes, as well as the [CHANGELOG](https://github.com/libp2p/rust-libp2p/blob/master/CHANGELOG.md)s. Includes a few simplifications of test code (i.e. simpler `Transport` construction).

### CODE REVIEW

**Review by twittner — APPROVED** [review]
LGTM.

**Review by mxinden — APPROVED** [review]
Looks good to me.

Just want to raise awareness for the fact that the max Kademlia packet size would now be 16KiB (see https://github.com/libp2p/rust-libp2p/pull/1730/). Please comment if you object to this change.

**Review by tomaka — APPROVED** [review]

**Comment by tomaka** [comment]
Everything looks normal on the burn-in.

The number of Kademlia k-bucket entries was at 141 before the reboot and is now only at 126. However, this value on other Kusama nodes ranges between 113 and 144, so 126 isn't really abnormal in this regard.

**Comment by romanb** [comment]
> Everything looks normal on the burn-in.

However, there is a large discrepancy in "Reserved peer disconnected" errors on `kusama-sentry-ae1-0` vs `kusama-sentry-ae1-1`. I don't know what that relates to, but https://github.com/libp2p/rust-libp2p/pull/1608 may of course be one suspect. So unless there is a good explanation for it, I would advise not to merge.

**Comment by tomaka** [comment]
> However, there is a large discrepancy in "Reserved peer disconnected" warnings on kusama-sentry-ae1-0 (this branch) vs kusama-sentry-ae1-1.

While I don't have an explanation for these messages (I wasn't aware of this issue), they were also happening on `ae1-0` before the deployment of this PR and at seemingly the same rate.

**Comment by romanb** [comment]
> While I don't have an explanation for these messages (I wasn't aware of this issue), they were also happening on ae1-0 before the deployment of this PR and at seemingly the same rate.

That is good to know, I didn't realise that. It is still suspicious, thought not w.r.t. the changes in this PR then.

**Comment by mxinden** [comment]
In regards to the reserved peer disconnects:

For what it is worth the line `Reserved peer XXX disconnected` is (as far as I can tell) always happening after `sync Obsolete timeout XXX`, which is logged [here](https://github.com/paritytech/substrate/blob/master/client/network/src/protocol.rs#L819).

**Comment by tomaka** [comment]
You might have to open [a Polkadot companion](https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc#updating-polkadot-as-well) to satisfy the bot :confused:

**Comment by romanb** [comment]
> You might have to open a Polkadot companion that updates parity-multiaddr, to satisfy the bot

Ok, I thought I can get by with an unapproved draft PR. There is now https://github.com/paritytech/polkadot/pull/1700 but apparently it even needs to approved before this PR can pass CI? So the Polkadot companions must be approved before the substrate PRs?

**Comment by tomaka** [comment]
The burn-in is revealing that at least the number of peers and bandwidth reported to the telemetry are at 0/empty, indicating that the node doesn't report these values to the telemetry server.
I've commented a bit [on another PR](https://github.com/paritytech/substrate/pull/6986/files#r487127101), but I'm not sure where the problem comes from.

**Comment by romanb** [comment]
> The burn-in is revealing that at least the number of peers and bandwidth reported to the telemetry are at 0/empty, indicating that the node doesn't report these values to the telemetry server.
I've commented a bit on another PR, but I'm not sure where the problem comes from.

Ok, thanks, I can take another look at that. Meanwhile I really don't have a clue why [`gitlab-check-polkadot-companion-build` is still failing here](https://gitlab.parity.io/parity/substrate/-/jobs/644408). Maybe I'm not seeing the wood for the trees in that console output. Or do you think it is related to the Telemetry problem?

**Comment by romanb** [comment]
> The burn-in is revealing that at least the number of peers and bandwidth reported to the telemetry are at 0/empty, indicating that the node doesn't report these values to the telemetry server.

See https://github.com/paritytech/substrate/pull/6986/files#r487778381 and the linked https://github.com/paritytech/substrate-telemetry/pull/289.

**Comment by tomaka** [comment]
I don't see how this PR could affect the telemetry, and the canary nodes, which are automatically updated every night with the latest Substrate master, now also report 0 peers/0 bandwidth on the telemetry, which to me shows that this is indeed a regression in Substrate master and not in this PR in particular.

I suggest to not block this PR on this problem, and I've opened https://github.com/paritytech/substrate/issues/7097 instead.

**Comment by tomaka** [comment]
I've merged the Polkadot pull request. Could you remove the `polkadot-companion: ` comment above and restart CI once more? :pray:

**Comment by romanb** [comment]
:tada:

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
