### PR TITLE
doc(frame): [nitpicks]

### PR DESCRIPTION
**Pull request by sacha-l**
Replaces #8319

### CODE REVIEW

**Comment by sacha-l** [comment]
@kianenigma @bkchr updated #8319.

**Review by bkchr — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
> Checks failed; merge aborted.

0__o

**Comment by bkchr** [comment]
> > Checks failed; merge aborted.
> 
> 0__o

bot successful :robot:

**Pull request merged**
