### PR TITLE
Fix consensus error between wasm and native

### LINKED ISSUE #1553: Consensus error between native and wasm while deploying a smart-contract
Discovered when I was deploying a smart-contract [erc20token.wasm.gz](https://github.com/paritytech/substrate/files/2792426/erc20token.wasm.gz) on 9040ca90

I'm getting this:

```
2019-01-24 16:04:20 Starting consensus session on top of parent 0x6e94274eddbca03ca6b59861e3f72f32d014a52b5e68080832a3f1e905f0244c
Runtime: 613ebf890e8f952cc3d61cc188bc27cab9fc115eef71b134e4a2b220f2a71aba
613ebf890e8f952cc3d61cc188bc27cab9fc115eef71b134e4a2b220f2a71aba
/Users/pepyakin/dev/parity/substrate/srml/contract/src/wasm/prepare.rs
44
60
2019-01-24 16:04:22 Consensus error between wasm and native runtime execution at block Hash(0x6e94274eddbca03ca6b59861e3f72f32d014a52b5e68080832a3f1e905f0244c)
2019-01-24 16:04:22    Function "BlockBuilder_apply_extrinsic"
2019-01-24 16:04:22    Native result Ok([0, 0])
2019-01-24 16:04:22    Wasm result Err(Error(Wasmi(Trap(Trap { kind: Unreachable })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } }))
```

(613ebf890e8f952cc3d61cc188bc27cab9fc115eef71b134e4a2b220f2a71aba is the hash of code to verify that they work with the same input code)

### PR DESCRIPTION
**Pull request by cmichi**
The bug from #1553 occurred because of two things playing into each other:

* The bucket size of 8192 bytes is quite large, which caused the available heap space to be exhausted too soon (even for allocating just 1 byte a whole bucket of 8192 bytes needs to allocated).  
This is an effect of the buddy allocator algorithm: There is less heap space available to be assigned, because a bucket does not necessarily have to be filled and thus the remaining bucket space is wasted.

* The other thing was that there was a bug when trying to allocate in a full heap. A double allocation to the first pointer happened then. I adapted the tests so that they would have catched this.

Closes #1553

### CODE REVIEW

**Comment by pepyakin** [comment]
(To clarify: I don't expect this to be done in this PR)

**Comment by gavofyork** [comment]
Even 1K is likely too large a hit to take unless there's concrete evidence that any allocations much below that are few. I think we need to avoid the buddy allocator until there is a slab allocator available to ensure that the lowest leaves in the tree don't get exhausted through numerous allocations of small pieces of data.

**Comment by gavofyork** [comment]
Just to be clear, until we have a compelling combination of slab+buddy allocator, I think we will need to keep the bump allocator.

**Comment by cmichi** [comment]
Alright, I have added a commit to this PR which reverts the current allocator to the linear allocator. 

In order to continue working on a better allocator we just need to revert `9c3cc024e66d71b2e459d50cc6669904196b85e1` to get back to the current buddy allocator.

Do we want to open #300 up again or create a new follow-up ticket?

**Comment by gavofyork** [comment]
Done: https://github.com/paritytech/substrate/issues/1615

**Comment by gavofyork** [comment]
We may also consider trying out a free-list allocator. https://en.wikipedia.org/wiki/Free_list

**Comment by rphmeier** [comment]
FWIW I did an implementation of that ages ago (before custom allocators were a thing in rust): https://github.com/rphmeier/allocators/blob/master/src/freelist.rs

maybe it can be ported over.

**Comment by bkchr** [comment]
Do we maybe want to make the allocator exchangable?

**Comment by gavofyork** [comment]
was thinking that, but i think it's not needed for now, and could even be dangerous in terms of consensus.

**Pull request merged**
