### PR TITLE
grandpa: store the authority id that is used for voting per round

### PR DESCRIPTION
**Pull request by andresilva**
The GRANDPA voter environment is responsible for updating (and persisting) the voter state whenever an action is performed by the voter (e.g. starting a new round, prevoting, precommitting, completing a round). In order to update the voter state it is required to figure out what is the current local authority id that is being used for voting, if none is available (i.e. we are not an active voter) then we don't need to update the voter state. Currently we always check from the keystore whenever we want to figure out what is the local authority id but this could lead to internal inconsistencies if the keystore state changes during the round, for example if a key is removed during the round we might not update the voter state after prevoting since there's no local authority id.

This PR adds a cache for the local authority id that we'll be using to vote on the given round that is populated when we start the round and cleared when the round is completed. This guarantees that we keep a static local authority id throughout the round lifecycle.

(NOTE: The reason this was implemented like this is because initially the `Environment` would own an `AuthorityPair` which would stay constant throughout the voter lifecycle. When the keystore was added later on the existing logic was kept.)

### CODE REVIEW

**Review by octol — APPROVED** [review]
Looks good! Appreciate the thorough comment blocks

**Comment by andresilva** [comment]
burn-in showed no issues. bot merge.

**Comment by andresilva** [comment]
bot merge

**Review by bkchr — APPROVED** [review]

**Comment by andresilva** [comment]
bot merge

**Pull request merged**
