### PR TITLE
Update wasmtime to 0.33.0

### PR DESCRIPTION
**Pull request by nazar-pc**
From [release notes](https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md) besides various fixes, there is SIMD support enabled by default.

The primary reason to upgrade was to make Substrate compile on latest nightly, see https://github.com/bytecodealliance/rustix/issues/142 for details.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
I think we should probably disable the simd stuff? So that nothing depends on this by accident?

**Review by pepyakin — CHANGES_REQUESTED** [review]
Yes, this is correct. Leaving it as Request changes until it's done.

**Comment by nazar-pc** [comment]
Just curious, is there a roadmap for enabling those various WASM features in wasmtime?
They seem useful for performance, maybe there is a ticket I can follow (I have not been able to find on in this repo)?

**Comment by koute** [comment]
> Just curious, is there a roadmap for enabling those various WASM features in wasmtime? They seem useful for performance, maybe there is a ticket I can follow (I have not been able to find on in this repo)?

I don't think there is. But it's good to stay conservative unless we can show that enabling them will actually be beneficial in some way. If there's no benefit then there's no point in turning them on just for the sake of turning them on.

**Comment by nazar-pc** [comment]
Just noticed SIMD was already disabled, so there was no need to change anything.

**Comment by koute** [comment]
Also, @nazar-pc FYI we tend to not force-push in our PRs; we just squash everything on merge.

**Comment by nazar-pc** [comment]
Will keep that in mind going forward :+1:

**Comment by koute** [comment]
> Just noticed SIMD was already disabled, so there was no need to change anything.

Indeed; I can confirm that we currently disable `wasm_simd`. (It was `false` by default in the previous release and they just switched the default to `true`, but we were already disabling it so nothing changes for us.)

One extra thing we should add is to also disable `wasm_memory64`. That *is* `false` by default for now, but we should just proactively disabled it anyway (since they'll probably turn it on by default in the future once the spec is finalized).

**Review by koute — APPROVED** [review]
I see no major performance regressions in benchmarks after this PR, so looks good to me.

**Review by pepyakin — APPROVED** [review]

**Pull request merged**
