### PR TITLE
Remove now unneeded empty hooks and calls #8873

### PR DESCRIPTION
**Pull request by timgestson**
Solves #8873 by removing empty pallet::hook and pallet::call functions

### CODE REVIEW

**Comment by timgestson** [comment]
I see some of the pallet_ui tests are failing.  Now that I have the test command gitlab is running, I'll fix this and get the build green.

**Review by KiChjang — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]
Nice 👍

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
