### PR TITLE
Use Subscription Manager from `jsonrpc-pubsub`

### PR DESCRIPTION
**Pull request by HCastano**
A subscription manager is used to execute RPC subscriptions. Substrate has had an implementation of this in [`sc-rpc-api::subscriptions`](https://github.com/paritytech/substrate/blob/master/client/rpc-api/src/subscriptions.rs) for a long time, and it's been pretty much only used within `sc-rpc`.

However, as more crates are starting to add their own RPC implementation (e.g the `finality-grandpa` crate) having a way to manage subscription is generally useful. For this reason I've added an implementation of a subscription manager to the `jsonrpc-pubsub` crate. What this PR does is remove the Substrate implementation in favour of the one in `jsonrpc-pubsub`.

The old Substrate based implementation had a numeric `IdProvider`, while the `jsonrpc-pubsub` implementation uses a string based provider by default. The advantage of this is that it reduced the chances of `SubscriptionId`s colliding. I don't think this change should cause any problems for Substrate, but it's worth keeping in mind. If it is a problem it's easy to swap out the `IdProvider` for a numeric based one.

Leaving this as a draft until some small fixes upstream get merged, and a release is cut.

Related `jsonrpc` PR: paritytech/jsonrpc#548

### CODE REVIEW

**Comment by jacogr** [comment]
This broke the JS API.

**Comment by HCastano** [comment]
Crap, sorry about that @jacogr. Do you want me to switch it back to numerical ids?

**Comment by andresilva** [comment]
@jacogr Yeah sorry didn't think about it and only reviewed the PR without testing it locally, although in hindsight it's obvious that changing the id type could cause errors for JS API. Do you want us to revert this so that there isn't any rush on the fix?

**Comment by jacogr** [comment]
Can only look at it reworking the id management tonight - I am stretched. (So this is a P1 on my list, I just have another P1 I am dealing with as it stands)

**Comment by andresilva** [comment]
Let's revert it right away then https://github.com/paritytech/substrate/pull/6252 to make sure this doesn't end up in polkadot or some other downstream project. @HCastano after the revert is merged feel free to re-open this PR again and let's coordinate with @jacogr on what to do (does it make sense to just go back to numerical ids and not introduce breakage?).

**Pull request merged**
