### PR TITLE
Use `rev` instead of branch whose tip is broken

### PR DESCRIPTION
**Pull request by dvdplm**

### CODE REVIEW

**Comment by dvdplm** [comment]
ping @tomaka

**Comment by tomaka** [comment]
I don't mind specifying the specific git commit. This PR however is no longer up to date.

**Comment by dvdplm** [comment]
> This PR however is no longer up to date.

What is the current best rev?

**Comment by tomaka** [comment]
The head of the `polkadot-2` branch, which is `835d574c572ebe26d5ab606840e993540e3c7403`

**Comment by dvdplm** [comment]
Isn't that the one where `varint` was tossed out, which broke things?

**Comment by gavofyork** [comment]
looks stale - closing. please reopen if i got it wrong.

**Pull request closed without merging**
