### PR TITLE
Add Zeitgeist ss58 prefix 73 reservation

### PR DESCRIPTION
**Pull request by lsaether**
Adds a prefix reservation for 73 for [Zeitgeist network](https://zeitgeist.pm).

### CODE REVIEW

**Comment by c410-f3r** [comment]
ping @apopiak @BenWhiteJam

**Comment by lsaether** [comment]
@BenWhiteJam Any chance we'll get this reviewed some time soon?

**Comment by lsaether** [comment]
@BenWhiteJam Can you review?

**Review by BenWhiteJam — APPROVED** [review]
fine from BD side.

- [x] contact
- [x] testnet
- [x] code repo
- [x] support
- [x] community

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
