### PR TITLE
Use correct length for Pallet and Storage prefix when calculating `KeyLenOf`

### PR DESCRIPTION
**Pull request by bkchr**
Closes: https://github.com/paritytech/substrate/issues/11992

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Added some tests :+1:   
The only part where `KeyLenOf` is used in storage is in `ranked-collective`, which is not live.  
Also this will probably increase the size so it should be fine.

**Comment by bkchr** [comment]
Thanks for the test :)

**Review by kianenigma — APPROVED** [review]

**Comment by shawntabrizi** [comment]
Does storage n map have similar logic?

**Comment by ggwpez** [comment]
> Does storage n map have similar logic?

Only `Map` and `DoubleMap` implement that trait. @shawntabrizi

**Pull request merged**
