### PR TITLE
pallet-contracts: Fix 16bit func_id

### PR DESCRIPTION
**Pull request by kvinwang**
It should mask the least 16bit as the doc comment said.

### CODE REVIEW

**Comment by athei** [comment]
Can you modify one of the tests so that both bytes are used for the function ids?

**Comment by kvinwang** [comment]
> Can you modify one of the tests so that both bytes are used for the function ids?

Done

**Review by athei — APPROVED** [review]
Thanks. You need to run `cargo +nightly fmt`.

**Review by cmichi — APPROVED** [review]

**Review by agryaznov — APPROVED** [review]

**Comment by athei** [comment]
bot merge

**Pull request merged**
