### PR TITLE
Only calculate tree route during finalization when there are multiple leaves

### PR DESCRIPTION
**Pull request by skunert**
Calculation of these tree routes is very expensive. When the finalized block is very far from the best block, it can take multiple seconds to calculate this tree route, blocking the import lock.

If there is only one leave, we can skip this calculation since the best block is guaranteed to be a descendant of the new finalized one.

Closes https://github.com/paritytech/cumulus/issues/2494, https://github.com/paritytech/substrate/issues/13947, 

Could impact the parachain part of https://github.com/paritytech/substrate/issues/14049

~Edit: Do not close the above issues for now, freshly syncing node still has issues.~

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by altonen — APPROVED** [review]
>Edit: Do not close the above issues for now, freshly syncing node still has issues.

what kind of issues?

**Review by lexnv — APPROVED** [review]

**Comment by skunert** [comment]
bot merge

**Review by melekes — APPROVED** [review]
👍

**Comment by jasl** [comment]
Thank you for the work!
Could it be backported to polkadot-v0.9.42 branch?

**Pull request merged**
