### PR TITLE
Bump libp2p to fix the broken Polkadot companions

### PR DESCRIPTION
**Pull request by tomaka**
Updates everything

### CODE REVIEW

**Comment by tomaka** [comment]
cc @s3krit The "burn-in" notification script failed.

**Comment by tomaka** [comment]
I opened this PR eagerly and optimistically, with the idea that the CI runs in parallel of the Riot discussions.
Since the problem has been solved by yanking libp2p-websocket 0.20.1, we can delay this update.

**Comment by s3krit** [comment]
> cc @s3krit The "burn-in" notification script failed.

I know this PR is now closed, but thanks for the heads up :) Confirming we've got the right secrets configured in the repo

**Comment by s3krit** [comment]
> cc @s3krit The "burn-in" notification script failed.

Figured this out. As per Github's docs:

> Secrets are not passed to workflows that are triggered by a pull request from a fork. Learn more. 

So it's working as intended.

**Pull request closed without merging**
