### PR TITLE
Bump `k256` from `0.10.4` to `0.11.4`

### PR DESCRIPTION
**Pull request by shekohex**
A small PR for updating k256 to the latest version.  

Polkadot Companion: https://github.com/paritytech/polkadot/pull/6238

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by davxy — APPROVED** [review]

**Comment by KiChjang** [comment]
No update to the lockfile?

**Comment by bkchr** [comment]
bot merge

**Comment by shekohex** [comment]
It looks like we will have to update `libp2p` too. Should I continue on this update?

**Comment by bkchr** [comment]
> It looks like we will have to update `libp2p` too. Should I continue on this update?

No that just requires a Polkadot companion.

**Comment by bkchr** [comment]
bot rebase

**Review by melekes — APPROVED** [review]
👍

**Comment by shekohex** [comment]
Hello @bkchr any updates on that PR? could we merge that?

**Comment by ggwpez** [comment]
It still needs a companion. I will create one

**Comment by ggwpez** [comment]
I added a Polkadot Companion https://github.com/paritytech/polkadot/pull/6238 but could not get it to update over there :thinking:   
@bkchr could you give it a shot please? All my cargo commands failed.

**Comment by bkchr** [comment]
> I added a Polkadot Companion [paritytech/polkadot#6238](https://github.com/paritytech/polkadot/pull/6238) but could not get it to update over there thinking @bkchr could you give it a shot please? All my cargo commands failed.

Fixed.

**Comment by ordian** [comment]
bot merge

**Pull request merged**
