### PR TITLE
First draft of a chain_getBlockWithTraces RPC

### PR DESCRIPTION
**Pull request by dvdplm**
WIP

Add an RPC to retrieve a block with execution traces included. This PR adds the RPC and the database column, `TRACES`, and some other menial footwork.

Lots of things to sort out still.

### CODE REVIEW

**Comment by bkchr** [comment]
Why do we want to store the execution traces in the database? Can we not store this stuff outside of Substrate?

**Comment by dvdplm** [comment]
> Why do we want to store the execution traces in the database? Can we not store this stuff outside of Substrate?

We could do that. It would require running something like `substrate-archive` which means more moving parts. Another alternative, suggested by @insipx, would be to have the RPC re-execute the block with tracing. That is very appealing in theory but could be a bit tricky to implement.

I'm fine not merging this (ever), but wouldn't mind keeping it open so we can explore the solutions.

**Comment by bkchr** [comment]
I thought that idea was that we could send this data continuously over a websocket or similar to everyone that is connected. I would assume that substrate archive would use this websocket to fetch all these information and store them.

I think this is something that shouldn't be stored by Substrate itself. We are a blockchain and no tracing data storage ;)

**Comment by insipx** [comment]
> I thought that idea was that we could send this data continuously over a websocket or similar to everyone that is connected. I would assume that substrate archive would use this websocket to fetch all these information and store them.
> 
> I think this is something that shouldn't be stored by Substrate itself. We are a blockchain and no tracing data storage ;)

Websocket stream does not work for substrate-archive since we index historical data (or to be redundant in the case where a node is running but archive is not), at which point we fetch and re-execute the block anyway

I think this API would be more for people who only want individual blocks or a piece of data without running something heavy like archive (which requires a full postgres setup + enough disk space) more in line with substrate sidecar maybe

**Comment by bkchr** [comment]
> I think this API would be more for people who only want individual blocks or a piece of data without running something heavy like archive (which requires a full postgres setup + enough disk space) more in line with substrate sidecar maybe

Who is interested in traces and can not run an archive node?

**Comment by gnunicorn** [comment]
Closing for a lack of progress. Feel free to reopen if there is progress made.

**Pull request closed without merging**
