### PR TITLE
add a new ci job to fuzz sp-arithmetic

### PR DESCRIPTION
**Pull request by altaua**
as requested in https://github.com/paritytech/ci_cd/issues/761

### CODE REVIEW

**Comment by altaua** [comment]
Yeah, the log  is unpleasantly noisy for sure. Unfortunately, ``--quiet`` also hides log messages about crashes encountered during fuzzing, and does /not/ hide the irrelevant internal hongfuzz warning ``input_getNext():129 No useful files in the input directory``.

I didn't want the logs to be empty except for some totally expected warnings, so I chose to leave the job in verbose mode.

**Review by ggwpez — APPROVED** [review]
Thanks!

(Approving from Runtime point of view)

**Review by rcny — APPROVED** [review]

**Comment by altaua** [comment]
We'll hold off on merging this PR until https://github.com/paritytech/substrate/pull/13660 lands; beyond that, it's ready.

**Comment by ggwpez** [comment]
bot rebase

**Review by rcny — APPROVED** [review]

**Review by sergejparity — APPROVED** [review]

**Pull request merged**
