### PR TITLE
Add Aventus ss58 address

### PR DESCRIPTION
**Pull request by nahuseyoum**
This pull request adds the ss58 prefix (65) for the Aventus mainnet chain which will go live shortly. Companion PR for polkadot.js [PR#871](https://github.com/polkadot-js/common/pull/871)

### CODE REVIEW

**Review by joepetrowski — COMMENTED** [review]
Reserved prefixes are generally not available to be claimed. @gavofyork ?

**Comment by apopiak** [comment]
> Reserved prefixes are generally not available to be claimed. @gavofyork ?

As discussed on Element, teams planning to launch soon can get prefixes <64 so they don't have to wait for the SS58 extension update happening here: https://github.com/paritytech/substrate/pull/8039

**Review by bkchr — APPROVED** [review]

**Comment by apopiak** [comment]
@gavofyork I did see that you marked 46 and 47 as reserved in the SS58 PR, so should Aventus pick a different one?

**Review by apopiak — APPROVED** [review]
LGTM

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@nahuseyoum please merge master

**Comment by gavofyork** [comment]
Master merge needed. Also, please change the index to one > 64.

**Comment by nahuseyoum** [comment]
Prefix updated to 65 and merged from master.

**Comment by apopiak** [comment]
bot merge

**Pull request merged**
