### PR TITLE
Add Test for Variable Components in Benchmarking

### PR DESCRIPTION
**Pull request by shawntabrizi**
This is a test that shows an example of how you can use an expression for a lower_bound of a benchmark.

I tried to add:

```
	// mutation arm to look for an expression for param_from.
	(
		{ $( $instance:ident )? }
		$name:ident
		{ $( $where_clause:tt )* }
		{ $( $parsed:tt )* }
		{ $eval:block }
		{
			let $param:ident in $param_from:expr .. $param_to:expr => $param_instancer:expr ;
			$( $rest:tt )*
		}
		$postcode:block
	) => {
		$crate::benchmark_backend! {
			{ $( $instance)? }
			$name
			{ $( $where_clause )* }
			{ $( $parsed )* }
			{ $eval }
			{
				let $param in ( $param_from ) .. $param_to => $param_instancer;
				$( $rest )*
			}
			$postcode
		}
	};
```

But got the error:

```
error: `$param_from:expr` is followed by `..`, which is not allowed for `expr` fragments
   --> frame/benchmarking/src/lib.rs:480:41
    |
480 |             let $param:ident in $param_from:expr .. $param_to:expr => $param_instancer:expr ;
    |                                                  ^^ not allowed after `expr` fragments
    |
    = note: allowed there are: `=>`, `,` or `;`
 ```

So instead we take advantage of this matching arm:

```
	(
		{ $( $instance:ident )? }
		$name:ident
		{ $( $where_clause:tt )* }
		{ $( $parsed:tt )* }
		{ $eval:block }
		{
			let $param:ident in ( $param_from:expr ) .. $param_to:expr => $param_instancer:expr;
			$( $rest:tt )*
		}
		$postcode:block
	) => {
		$crate::benchmark_backend! {
			{ $( $instance)? }
			$name
			{ $( $where_clause )* }
			{
				$( $parsed )*
				PARAM { $param , $param_from , $param_to , $param_instancer }
			}
			{ $eval }
			{ $( $rest )* }
			$postcode
		}
	};
```

Where the `param_from:expr` is wrapped in parenthesis.

@thiolliere is there a cleaner way to do this?

### CODE REVIEW

**Comment by thiolliere** [comment]
I don't really see other solution, you could read token by token until `..` but this could break if user use `..` inside the expression

**Review by kianenigma — APPROVED** [review]
Might be worth changing this `..` for 3.0.

**Review by thiolliere — APPROVED** [review]

**Comment by thiolliere** [comment]
maybe doc could emphasize it in a note ?

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
@kianenigma the `..` syntax is pretty natural to me. What would be your alternative?

**Pull request merged**
