### PR TITLE
Reserving Hedgeware ss58 registry slot 777

### PR DESCRIPTION
**Pull request by drewstone**
Changed to 77.

### CODE REVIEW

**Comment by bkchr** [comment]
Is that some test network? Why not use the same prefix as edgeware?

**Comment by drewstone** [comment]
Not a test network, a canary network.

**Comment by drewstone** [comment]
Status update on this?

**Comment by bkchr** [comment]
The problem is that we are slowly running out of prefixes and a Rococo chain doesn't require any special prefix.

**Comment by gavofyork** [comment]
Needs resolving. Also, please use an ID > 65.

**Comment by drewstone** [comment]
Changed to 77 @gavofyork @bkchr

**Comment by drewstone** [comment]
Updated

**Comment by drewstone** [comment]
@gavofyork @bkchr any update on this?

**Comment by drewstone** [comment]
@bkchr @gavofyork any update on this?

**Comment by drewstone** [comment]
Any update on this?

**Comment by bkchr** [comment]
@drewstone please get in contact with @BenWhiteJam

**Comment by drewstone** [comment]
@BenWhiteJam why have you ignored this to the point where now Manta has reserved this same SS58?

**Comment by drewstone** [comment]
This is extremely rude.

**Comment by drewstone** [comment]
Updated to 777.  Please let me know what the delay is for. I've been trying to get in contact with you on Element @BenWhiteJam .

**Comment by drewstone** [comment]
Linking @thom_ivy

**Pull request closed without merging**
