### PR TITLE
Decl_storage macro : force traits.

### LINKED ISSUE #1312: `srml_support::StorageValue` is not imported by `decl_storage!` macro
tldr: The following setup would not compile if `srml_support::StorageValue` is not in scope. 

```
decl_storage! {
	trait Store for Module<T: Trait> as Test {
		Foo get(foo) config(initial_foo): u32;
	}
}
```

That would result in an error like this:
```
error[E0599]: no function or associated item named `key` found for type `test::Test<T>` in the current scope
  --> runtime/src/test.rs:71:1
   |
71 |   decl_storage! {
   |   ^------------
   |   |
   |  _function or associated item `key` not found for this
   | |
72 | |     trait Store for Module<T: Trait> as Test {
73 | |         /// All valid unspent transaction outputs are stored in this map.
74 | |         Foo get(foo) config(initial_foo): u32;
75 | |     }
76 | | }
   | |_^ function or associated item not found in `test::Foo<T>`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following traits are implemented but not in scope, perhaps add a `use` for one of them:
           candidate #1: `use srml_support::storage::generator::StorageValue;`
           candidate #2: `use srml_support::StorageValue;`
```

Quick solution is to add `use srml_support::StorageValue;` to the module. Better solution would be to import `StorageValue` inside the macro.

This affects only storage items that use `config` attribute.

### LINKED ISSUE #1334: Have the `decl_storage!` macro import rstd::prelude::*
When trying to use the decl_storage macro and build to wasm, the compiler complains that the Vec type has not been declared.

For example, this minimum runtime:
```
use srml_support::{StorageValue, dispatch::Result};
pub trait Trait: system::Trait {}

decl_module! {
  pub struct Module<T: Trait> for enum Call where origin: T::Origin {
    fn set_value(_origin, value: u32) -> Result {
      <Value<T>>::put(value);
      Ok(())
    }
  }
}

decl_storage! {
  trait Store for Module<T: Trait> as RuntimeExampleStorage {
    Value: u32;
  }
}
```
will give the following error:
```
error[E0412]: cannot find type `Vec` in this scope
  --> src/runtime_example.rs:13:1
   |
13 | / decl_storage! {
14 | |   trait Store for Module<T: Trait> as RuntimeExampleStorage {
15 | |     Value: u32;
16 | |   }
17 | | }
   | |_^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use rstd::alloc::prelude::Vec;
   |
1  | use rstd::prelude::Vec;
   |
1  | use rstd::vec::Vec;
   |
1  | use srml_support::dispatch::Vec;
   |
and 1 other candidates

error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
error: Could not compile `runtime-example-runtime`.
```

To solve this issue, you simply need to add: `use rstd::prelude::*;`

We should have the decl_storage macro automatically do this if it requires this import.

### PR DESCRIPTION
**Pull request by cheme**
This PR fixes #1312 by specifying explicitly the trait used for this instruction.
Also fixes #1334 by specifying correctly Vec usage.

### CODE REVIEW

**Comment by bkchr** [comment]
For #1313 I think it is better to not generate the `GenesisConfig`, if it is not required at all. I would rather expect the documentation to reflect, which parameter does what.
For example, also `map` is not supported in the `GenesisConfig`. The user would still be confused, if a `GenesisConfig` is generated, but without any fields.

**Comment by 0x7CFE** [comment]
> PS : github diff is super hard to read on the second commit (genesis config part), I just did remove a condition and indent -1 the code.

You may always use this option to filter such changes:
ws

**Comment by cheme** [comment]
I agree that it is better to avoid genesis config (I did revert the commit).
The issue with #1313 seems to simply be the `construct_runtime` macro using `Config` parameter by default (hence querying genesis config). Should we remove `Config` out of the default value?
I also did observe that `GenesisConfig` is not available in `no_std` (not sure why).

**Comment by 0x7CFE** [comment]
> I also did observe that GenesisConfig is not available in no_std (not sure why).

Gavin mentioned that it's used only in std environment.

**Comment by bkchr** [comment]
Yeah Genesisconfig is only required on std and is not used in wasm.

**Pull request merged**
