### PR TITLE
Simplify onboarding when using `subkey restore`

### PR DESCRIPTION
**Pull request by webmaster128**
Some small improvementes that help understanding key derivation

### CODE REVIEW

**Comment by gavofyork** [comment]
[cla:check]

**Comment by webmaster128** [comment]
@gavofyork I suppose your comment should trigger some bot. I did not sign a CLA. How can I do that?

**Comment by bkchr** [comment]
[cla:check]

**Comment by bkchr** [comment]
[cla:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by webmaster128** [comment]
[clabot:check]

**Pull request merged**
