### PR TITLE
Improve the API of peerset slots

### PR DESCRIPTION
**Pull request by tomaka**
This PR modifies the API of the `Slots` struct. Instead of doing, for example `slots.mark_reserved(peer)` or `slots.add_peer(peer, slot_type)` you would now do `if let Occupied(e) = slots.peer_mut(peer) { e.mark_reserved() }` or `if let Vacant(e) = slots.peer_mut(peer) { e.insert(); }`.

The advantage of doing so is that we now force the user of `Slots` to cover all possible situations (eg. calling `mark_reserved` for nodes we don't know about).
This change has uncovered a few issues when it comes to reserved peers. It also checks much more often for inconsistent states, which might be useful in the future.

However the major reason for this PR is that I realized that introducing a reputation system with the current API would introduce so many more problematic situations. This is therefore the first step towards this direction.

cc @debris

### CODE REVIEW

**Comment by gavofyork** [comment]
This doesn't touch the API of the PSM <-> Substrate-Networking code, right?

**Comment by gavofyork** [comment]
The notion of slots only makes sense for non-dictated peers. Reserved peers are absolute. They should be separate from any notion of slots.

Peers := Reserved peers + Unreserved peers

Unreserved peers is made up of peers found through discovery, includes incoming and outgoing initiated peers, and each are subject to the machinations of whatever reputation system (or, more reasonably, "peer set optimiser") we need.

**Comment by tomaka** [comment]
> This doesn't touch the API of the PSM <-> Substrate-Networking code, right?

It doesn't, it's only internal within the peerset crate.

> The notion of slots only makes sense for non-dictated peers. Reserved peers are absolute. They should be separate from any notion of slots.

I see. I went for not touching the logic of the code in this PR.
If reserved peers don't count towards slots, this would also simplify the code a lot.

**Comment by gavofyork** [comment]
Cool - would you be ok doing this or do we wait for marek to return?

**Comment by tomaka** [comment]
I started looking at the peerset because that's what is causing the most networking issues at the moment.
It would be cool to have Marek's input, it just depends how urgent fixing the networking is.

**Comment by gavofyork** [comment]
It's urgent. It can't wait for marek to rematerialise.

**Comment by tomaka** [comment]
Actually, let me just rewrite the peerset entirely. I'll submit another PR when it's done.

**Pull request closed without merging**
