### PR TITLE
Fail docs on warnings

### PR DESCRIPTION
**Pull request by TriplEight**
- docs job optimized; 
- runs every commit; 
- fails on warnings

### CODE REVIEW

**Comment by TriplEight** [comment]
CI will be failing on this job until docs will be fixed. So I'll push the next commit with CI ignored.

**Comment by TriplEight** [comment]
Allowed it to temporary fail, please remove #FIXME after the docs are fixed.

**Comment by TriplEight** [comment]
can be merged

**Comment by gnunicorn** [comment]
the polkadot companion check sounds like this needs an merge with `master`.

**Comment by TriplEight** [comment]
@gnunicorn :+1:

**Comment by gnunicorn** [comment]
bot merge

**Comment by bkchr** [comment]
@gnunicorn there is a reason I did not merge it yet. The test fails because of doc errors in a dependency, that is something I don't want to have.

**Comment by bkchr** [comment]
This is blocked on: https://github.com/rust-lang/rust/issues/59367

**Comment by gnunicorn** [comment]
@bkchr fine by me. could have given it a `reuqest changes` review to block it. Will ice it for now.

**Comment by bkchr** [comment]
Please merge master, this should not make the `build-rust-doc` job work.

**Comment by gnunicorn** [comment]
@TriplEight please resolve the conflicts and fix the CI, then we can hopefully merge it soon.

**Comment by TriplEight** [comment]
Now it needs to fix some doc errors: https://gitlab.parity.io/parity/substrate/-/jobs/639981

**Review by bkchr — APPROVED** [review]

**Pull request merged**
