### PR TITLE
`BlockId` removal: refactor: `HeaderBackend::header`

### PR DESCRIPTION
**Pull request by michalkucharczyk**
BlockId removal: refactor: HeaderBackend::header

It changes the arguments of:
- `HeaderBackend::header`,
- `Client::header`,
- `PeersClient::header`
- `ChainApi::block_header`

methods from: `BlockId<Block>` to: `Block::Hash`

This PR is part of BlockId::Number refactoring analysis (https://github.com/paritytech/substrate/issues/11292)

polkadot companion: paritytech/polkadot#6418
cumulus companion: paritytech/cumulus#1977

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2136055

**Review by bkchr — APPROVED** [review]

**Review by lexnv — APPROVED** [review]
LGTM!

A couple of places where this needs changing: 

https://github.com/paritytech/substrate/blob/e6bbc53af99458c87b6fafe02314b4959b8da2b0/client/basic-authorship/src/lib.rs#L52-L54

And the readme: https://github.com/paritytech/substrate/blob/master/client/basic-authorship/README.md

**Review by davxy — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
bot rebase

**Review by acatangiu — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2177374

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2177426

**Comment by michalkucharczyk** [comment]
bot merge

**Comment by michalkucharczyk** [comment]
bot merge

**Comment by michalkucharczyk** [comment]
bot merge

**Pull request merged**
