### PR TITLE
Baseline weights VM runners

### PR DESCRIPTION
**Pull request by mateo-moon**
Baseline weights generated on VM runners.

https://forum.parity.io/t/investigating-new-benchmarking-hardware/687/134

### CODE REVIEW

**Comment by oleg-plakida** [comment]
bot bench $ all

**Comment by oleg-plakida** [comment]
bot rebase

**Comment by oleg-plakida** [comment]
bot bench-vm $ all
bot bench-vm $ all
bot bench-vm $ all
bot bench-vm $ all
bot bench-vm $ all

**Comment by oleg-plakida** [comment]
bot clean

**Comment by oleg-plakida** [comment]
bot clean

**Comment by oleg-plakida** [comment]
bot clean

**Comment by oleg-plakida** [comment]
bot bench-vm -v UPSTREAM_MERGE=n $ all
bot bench-vm -v UPSTREAM_MERGE=n $ all
bot bench-vm -v UPSTREAM_MERGE=n $ all
bot bench-vm -v UPSTREAM_MERGE=n $ all

**Comment by oleg-plakida** [comment]
@ggwpez This is what i've told you about) I will run them separately.

**Comment by oleg-plakida** [comment]
bot bench-vm -v UPSTREAM_MERGE=n $ all

**Comment by ggwpez** [comment]
> @ggwpez This is what i've told you about) I will run them separately.

Dont tell me, tell @mordamax :laughing:

**Comment by oleg-plakida** [comment]
bot bench-vm -v UPSTREAM_MERGE=n $ all

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2836587

**Comment by oleg-plakida** [comment]
bot bench-vm $ all

**Review by sam0x17 — APPROVED** [review]

**Comment by bkchr** [comment]
Did we already solve the benchmarking noise on these "machines"?

**Comment by oleg-plakida** [comment]
> Did we already solve the benchmarking noise on these "machines"?

We didn't, because there wasn't one in the first place)

**Comment by bkchr** [comment]
> > Did we already solve the benchmarking noise on these "machines"?
> 
> We didn't, because there wasn't one in the first place)

Could you give a Tldr?

**Comment by oleg-plakida** [comment]
> > > Did we already solve the benchmarking noise on these "machines"?
> > 
> > 
> > We didn't, because there wasn't one in the first place)
> 
> Could you give a Tldr?

During the test runs at firsts by @bakhtin then in my tests and @ggwpez ones we didn't observe any cases of 'noise neighbors'. Also i've only heard about this but never saw real proves. More info could be find in this thread https://forum.parity.io/t/investigating-new-benchmarking-hardware/687/134

**Comment by ggwpez** [comment]
> Did we already solve the benchmarking noise on these "machines"?

The only noise we still see is in 3-5 benchmarks (two of them in pallet-contracts) consistently, but that is also present on `bm3`. So I assume that these benches are unstable themselves, and not a hardware problem.  
@oleg-plakida can you maybe post some SWC links from the past VM+BM runs to demonstrate?

**Comment by oleg-plakida** [comment]
> > Did we already solve the benchmarking noise on these "machines"?
> 
> The only noise we still see is in 3-5 benchmarks (two of them in pallet-contracts) consistently, but that is also present on `bm3`. So I assume that these benches are unstable themselves, and not a hardware problem. @oleg-plakida can you maybe post some SWC links from the past VM+BM runs to demonstrate?

[Here](https://weights.tasty.limo/compare?repo=substrate&threshold=10&path_pattern=frame%2F**%2Fsrc%2Fweights.rs&method=asymptotic&ignore_errors=true&unit=time&old=oleg%2Ftest-weights-mar-bm1&new=oleg%2Ftest-weights-mar-bm5#frame/benchmarking/src/weights.rs.sr25519_verification) is one for BM with some fluctuations.
[Here](https://weights.tasty.limo/compare?repo=substrate&threshold=10&path_pattern=frame%2F**%2Fsrc%2Fweights.rs&method=asymptotic&ignore_errors=true&unit=time&old=oleg%2Ftest-weights-vm-base3&new=oleg%2Ftest-weights-vm-base2#frame/benchmarking/src/weights.rs.sr25519_verification) is the vm one with similar results.

**Comment by bkchr** [comment]
> The only noise we still see is in 3-5 benchmarks (two of them in pallet-contracts) consistently, but that is also present on `bm3`. So I assume that these benches are unstable themselves, and not a hardware problem.

What happened to https://github.com/paritytech/substrate/issues/13400?

**Review by ggwpez — APPROVED** [review]
After this is merged, please make another MR and then check that the bench-bot uses the new VM runners.

**Comment by oleg-plakida** [comment]
> After this is merged, please make another MR and then check that the bench-bot uses the new VM runners.

Needs one more approve from @paritytech/core-devs.

**Review by vstam1 — APPROVED** [review]

**Comment by koute** [comment]
> Problem is that even with very high repetitions (2000 instead of 50), some calls show consistent outlier behaviour.

@ggwpez For the benches which are noisy, maybe you could try running them with this script of mine and see if it helps? https://gist.github.com/koute/83fb86c0b80213949d2985903a03a7f8 (Make sure `ruby`, `setarch` and `schedtool` are installed, download the script, `chmod +x` it, and run `./perftest.rb $command`.)

It applies a bunch of system-level tweaks to make benchmarking more consistent; I find that on my machine it significantly helps in CPU bound benchmarks. (Most of which we honestly should most likely permanently preapply on our benchmarking machines.)

**Review by liamaharon — APPROVED** [review]

**Comment by oleg-plakida** [comment]
bot rebase

**Comment by oleg-plakida** [comment]
bot bench-vm $ all

**Comment by oleg-plakida** [comment]
bot bench-vm $ all

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3011605

**Comment by oleg-plakida** [comment]
bot clean

**Pull request merged**
