### PR TITLE
Add standalone set head operations

### PR DESCRIPTION
**Pull request by sorpaas**
This adds standalone set head operations `set_head` and `apply_head`. Those two takes an arbitrary block id, and set it as head. If the block id does not yet exist in storage, error. `apply_head` is meant to be used with `lock_import_and_run` so that it works together with other block import operations.

Current known issue -- light client backend is not yet fully atomic: https://github.com/paritytech/substrate/issues/1599

### CODE REVIEW

**Comment by arkpar** [comment]
Is this intended to be used for reverting to previous blocks? Ins that case it would also need to update finalization and pruning journals in `core/state-db`

**Comment by arkpar** [comment]
At least there needs to be a check that we are not switching away from the finalised chain.

**Comment by sorpaas** [comment]
@arkpar There is! The logic for that hasn't changed: https://github.com/paritytech/substrate/pull/1600/files#diff-c0982d5a95c967fde94ecf0a10d342dbR597

**Comment by gavofyork** [comment]
@arkpar all good for merge?

**Pull request merged**
