### PR TITLE
Add nominators option to chain-spec-builder

### PR DESCRIPTION
**Pull request by kianenigma**
For certain reasons I am interested in building chain-specs that have a handful of authorities (validators) and lots and lots of nominators (testing election stuff).

### CODE REVIEW

**Comment by bkchr** [comment]
You want to use this `chain-spec` builder in Substrate?

**Comment by shawntabrizi** [comment]
The alternative to hard coding this in our codebase is to generate a `chain-spec.json` file which you launch the node with. (`--chain=chain-spec.json`)

I made a tool for this: https://github.com/shawntabrizi/substrate-benchmark-genesis

I am not against this PR in general, just wanted to state the options.

**Comment by kianenigma** [comment]
> The alternative to hard coding this in our codebase is to generate a `chain-spec.json` file which you launch the node with. (`--chain=chain-spec.json`)
> 
> I made a tool for this: https://github.com/shawntabrizi/substrate-benchmark-genesis
> 
> I am not against this PR in general, just wanted to state the options.

I'll evaluate and see which one is worth it. Long term, I think the feature that I am adding here is also not something hardcoded but rather an option that others could also use.

**Comment by kianenigma** [comment]
well then for now lets at least let it make life a bit easier for me :D

**Comment by kianenigma** [comment]
> Hi @kianenigma
> 
> Plz support chain spec builder with SS58Prefix

What do you mean? You can already use the `new` instead of `generate` to pass in your own list of SS58 authorities and nominators.

**Review by shawntabrizi — APPROVED** [review]

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
