### PR TITLE
Fix libp2p features

### PR DESCRIPTION
**Pull request by tomaka**
Many of the feature requirements don't make any sense.

Additionally, `subkey` was activating all the default libp2p features, which added unnecessary dependencies.

### CODE REVIEW

**Comment by bkchr** [comment]
Why is `libp2p` enabling all its features by default?

**Comment by tomaka** [comment]
> Why is libp2p enabling all its features by default?

Convenience, and backwards-compatibility. We introduced these features recently, before you simply didn't have a choice.


I don't think the CI issues are caused by this PR:

```
 error[E0514]: found crate `byte_tools` compiled by an incompatible version of rustc
 --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/block-padding-0.1.5/src/lib.rs:9:1
  |
9 | extern crate byte_tools;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: please recompile that crate using this compiler (rustc 1.45.0-nightly (9912925c2 2020-05-10))
  = note: the following crate versions were found:
          crate `byte_tools` compiled by rustc 1.45.0-nightly (a74d1862d 2020-05-14): /builds/parity/substrate/target/release/wbuild/target/wasm32-unknown-unknown/release/deps/libbyte_tools-c32ba732f3d5ac81.rmeta
error: aborting due to previous error
error: could not compile `block-padding`.
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0514]: found crate `rand_core` compiled by an incompatible version of rustc
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rand_chacha-0.2.2/src/lib.rs:21:9
   |
21 | pub use rand_core;
   |         ^^^^^^^^^
   |
   = help: please recompile that crate using this compiler (rustc 1.45.0-nightly (9912925c2 2020-05-10))
   = note: the following crate versions were found:
           crate `rand_core` compiled by rustc 1.45.0-nightly (a74d1862d 2020-05-14): /builds/parity/substrate/target/release/wbuild/target/wasm32-unknown-unknown/release/deps/librand_core-137073ee261b6a3d.rmeta
error: aborting due to previous error
error: could not compile `rand_chacha`.
```

**Comment by bkchr** [comment]
Okay. Yeah the CI issues are related to sccache bug.

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
