### PR TITLE
u32 Refcounts, plus migration

### PR DESCRIPTION
**Pull request by gavofyork**
It is quite conceivable that runtimes will need more than 256 reference locks on accounts, especially with multi-asset pallets.

This switches the count type to `u32`.

A migration is needed.

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]
looks good to me

**Review by shawntabrizi — APPROVED** [review]

**Comment by apopiak** [comment]
This would make for a good candidate to try out a different migration process where we extract the migration.

**Review by kianenigma — APPROVED** [review]

**Comment by gnunicorn** [comment]
bot merge

**Comment by antonkhvorov** [comment]
It was fun seeing billions of USD on my balance in Fearless Wallet :D

**Pull request merged**
