### PR TITLE
Expose Benchmarking Component Ranges

### LINKED ISSUE #11397: Expose benchmark component ranges
## Problem

The range of a benchmarking component is not written to the weight file.  
Any downstream software (like [substrate-weight-compare](https://github.com/ggwpez/substrate-weight-compare)) can therefore not use this information.

## Context

A benchmarking component is defined in the form:  
```rust
let n in 0..100;
```
Substrate then samples some values in this range and measures the weight at each.  
The final weight file does not contain any information about the `0..100` range from above:  
```rust
fn nominate(n: u32, ) -> Weight {
		(45_566_000 as Weight)
			.saturating_add((3_063_000 as Weight).saturating_mul(n as Weight))
}
```

## Solution
One way would be to add attribute macros.  Eg:  
```rust
fn nominate(#[range(min=0, max=100, step=20)] n: u32, ) -> Weight {
		(45_566_000 as Weight)
			.saturating_add((3_063_000 as Weight).saturating_mul(n as Weight))
}
```
... or even easier with [comments](https://docs.rs/syn/latest/syn/struct.Attribute.html#syntax):
```rust
/// n: 0..100 with step size 20
fn nominate(n: u32, ) -> Weight {
		(45_566_000 as Weight)
			.saturating_add((3_063_000 as Weight).saturating_mul(n as Weight))
}
```
The step size of `20` in this example is picked by Substrate.  

Before implementing the doc solution, it would be wise to double-check that `syn` can parse this.

### PR DESCRIPTION
**Pull request by ggwpez**
Closes #11397

Changes:
- Put the component ranges as comments above the weight functions.

Example:
```rust
/// The range of component `b` is `[0, 3932160]`.
fn remark(_b: u32, ) -> Weight {
	(9_137_000 as Weight)
}
```

TODOS:
- [x] Run the bench bot
- [ ] Verify that the Polkadot spellcheck accepts this

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Review by dvdplm — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
