### PR TITLE
Reduce overhead of generating network event metrics

### PR DESCRIPTION
**Pull request by koute**
The `format!`s here were using 3.2% of the CPU; this should cut it down to roughly ~0.1%.

### CODE REVIEW

**Review by tomaka — APPROVED** [review]
This is probably the worst but also the easiest way to solve this problem

**Comment by tomaka** [comment]
IMO in an ideal world it would be the Prometheus library being a bit smarter. Literally all the Prometheus library does is hold a bunch of numbers and then concatenate strings. The fact that, in the Prometheus library's API, metric names are strings rather than for example an `enum` is already an overhead. But it was done this way because having an enum of all the possible metrics at compile time might be painful.

An alternative would be to no longer identify protocols by their name in the networking code, but by some sort of id, and then store the actual protocol name ahead of time in some hashmap instead of rebuilding it every time on the fly.

**Comment by koute** [comment]
I'll merge this for now since it's an easy win.

If you're fine with this as-is we can leave it like this, or if you want I could try take a stab at the better solution next week and whip up a PR to `prometheus` to expose an API which wouldn't require us to pack the label into a string and then we could revisit.

**Comment by tomaka** [comment]
> whip up a PR to prometheus to expose an API which wouldn't require us to pack the label into a string and then we could revisit.

I know this is considered bad and all, but the Prometheus format [is almost trivial](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details), and it would make sense to me to simply have our own code for it rather than going through a third-party library.

**Pull request merged**
