### PR TITLE
Guard some invalid node for proof decoding.

### PR DESCRIPTION
**Pull request by cheme**
The current node code allows proof to use branch without children<s> or without value and only one children</s>.
This PR add a guard against such proof.
This should be compatible with current proof that where build with a valid trie code.

### CODE REVIEW

**Comment by tomaka** [comment]
Maybe a dumb question, but is it not possible to do `if bitmap == 0 { return Err(...) }`? Right now the diff seems a bit convoluted.

**Comment by cheme** [comment]
> Maybe a dumb question, but is it not possible to do `if bitmap == 0 { return Err(...) }` instead? Right now the diff seems a bit convoluted.

Yes would work, just I also guard against the case where there is one child and no value, for this case I got to count children (could stop at 2 but I don't think it's worth it).

**Comment by cheme** [comment]
Making these change on the trie crate, I observe some issues (probably with compact proof decoding), tihs may require changes upstream first.

**Comment by cheme** [comment]
I reopen it but just it still allow branch with one children and no value as it is currently use by trie crate for some proof encoding.

**Comment by bkchr** [comment]
@cheme it doesn't build. Adding some test would also be nice.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot rebase

**Review by arkpar — APPROVED** [review]

**Comment by arkpar** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
