### PR TITLE
Remove with_gossip

### PR DESCRIPTION
**Pull request by tomaka**
Based on top of #2497. Only the last commit is relevant.

Removes the `Service::with_gossip` method and turn its usage around the code into individual method calls.

### CODE REVIEW

**Comment by rphmeier** [comment]
Also needs a PR in Polkadot when this is merged.

**Comment by gterzian** [comment]
What's the rationale for remove the generic `with_gossip` method with dedicated methods?  From the discussion me and @rphmeier  had over at https://github.com/paritytech/substrate/pull/1340#issuecomment-460315396 I took away that we didn't want to bloat the API with too many specific methods...

**Comment by tomaka** [comment]
Just like the other PRs, I'm trying to make the API less dependant on the threading strategy. To me, passing a closure to `with_gossip` that gets executed later is strictly worse than doing a "flat call" to a method that does what your closure contains.

**Comment by gterzian** [comment]
I fail to see how the last commit changes the situation with regards to the dependence on the threading strategy. 

We're trading a single `with_gossip` api endpoint for four specific ones. And those new methods still result in a message being sent across, which will run an "operation" on another task. 

The only difference is that every operation we come up with later will require a new method, and message, whereas `with_gossip` allowed the client to execute a generic operation using gossip. 

If what you mean is that you want the "operation" corresponding to the method call to execute immediately, we could still keep `with_gossip`, and make it a blocking call using a bounded sender, or a lock around gossip.

**Comment by rphmeier** [comment]
Yeah, I think `with_gossip` is still much more robust and we don't have to deal with `service` bloat.

**Comment by tomaka** [comment]
Well, ok. Will reopen at a later time on top of other changes.

**Pull request closed without merging**
