### PR TITLE
Re-activate profiling output, fix tracing macro

### LINKED ISSUE #7348: may be a small error in `sp-tracing` macro? target field is not from macro parameter
I'm not sure where this small tip is an error:

in `sp-tracing` crate, in `within_span` and `enter_span`, I find that the macro has parameter `$lvl:expr`, but it not used in macro implementation part, in impementation all is filled `TRACE` level, like:
```rust
	(
		$lvl:expr,
		$name:expr;
		$( $code:tt )*
	) => {
		{
			$crate::within_span!($crate::span!($crate::Level::TRACE, $name); $( $code )*)
		}
	};
```
may should be:
```rust
	(
		$lvl:expr,
		$name:expr;
		$( $code:tt )*
	) => {
		{
			$crate::within_span!($crate::span!($lvl, $name); $( $code )*)
		}
	};
```
I'm not sure, in my view, I think the `$lvl:expr` should be used...

https://github.com/paritytech/substrate/blob/900d034fc1ba0ccb30dd54b2dd7498ad5caa7fb5/primitives/tracing/src/lib.rs#L148-L165

https://github.com/paritytech/substrate/blob/900d034fc1ba0ccb30dd54b2dd7498ad5caa7fb5/primitives/tracing/src/lib.rs#L226-L236

if this target level just should be `TRACE`, so way? 
and if `TRACE` is be pointed, the parameter `$lvl:expr` in marco is useless, and should be removed.

### PR DESCRIPTION
**Pull request by mattrutherford**
This adds spans to all operations in `sp_io` that modify storage.

WASM has to be built with `with-tracing` feature.

Todo:

- [x] Add spans to storage operations
- [ ] Ensure each span has a parent where it's possible to identify where in the runtime caused each operation

Also, removes dependancy of `log` crate from `client::tracing` and fixes #7348

### CODE REVIEW

**Comment by bkchr** [comment]
What is the difference to this: https://github.com/paritytech/substrate/blob/master/primitives/state-machine/src/ext.rs#L225

**Comment by mattrutherford** [comment]
> What is the difference to this: https://github.com/paritytech/substrate/blob/master/primitives/state-machine/src/ext.rs#L225 ?

Actually this probably works better, because the subscriber can filter at the granularity of the event name and these events should be attributed to the automatically added spans in sp_io anyway.

**Comment by bkchr** [comment]
> Actually this probably works better, because the subscriber can filter at the granularity of the event name

By "this" you mean this pr? 

> events should be attributed to the automatically added spans in sp_io anyway.

You are aware that the linked code is being executed by the functions here in sp-io.

**Comment by mattrutherford** [comment]
Sorry, I meant what you pointed out is best - I'm going to revert that part, then just need to make sure all operations are covered by spans in the runtime.

**Comment by bkchr** [comment]
Thank you for clarifying.

**Comment by bkchr** [comment]
@mattrutherford what is the status of this pr?

**Comment by mattrutherford** [comment]
Closing - will open another PR for the small fixes

**Pull request closed without merging**
