### PR TITLE
Fixes CI

### PR DESCRIPTION
**Pull request by gupnik**

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Review by liamaharon — APPROVED** [review]
To clarify.. we are removing because `sp-core/std` is not a dep of this crate in the first place correct?

**Comment by gupnik** [comment]
> To clarify.. we are removing because `sp-core/std` is not a dep of this crate in the first place correct?

Correct!

**Review by bkchr — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
Cumulus will be red because of https://github.com/paritytech/cumulus/pull/2989, so we need to force merge this.

**Comment by gupnik** [comment]
bot merge force

**Pull request merged**
