### PR TITLE
Shorter keys

### PR DESCRIPTION
**Pull request by gavofyork**
NOTE: Not to be merged, yet.

This changes the hashes of keys to something somewhat shorter; item prefixex for storage maps are reduced to 32-bit (down from 2 * 128-bit), and values down to 64-bit (down from the same). Twox-64_concat is reduced to twox-32_concat and Blake2_128 down to Blake2_64. These should all still be adequately secure, but the question is whether this gives us any speedup.

If it's not significantly faster, then the first two commits can still be merged.

TODO:
- [ ] Benchmarking. Is it actually faster?
- [ ] Migration

### CODE REVIEW

**Comment by burdges** [comment]
@LeonGB

**Comment by shawntabrizi** [comment]
Initial test results:

Master + No Events on Genesis + 50K real accounts, 800 data points (20 steps, 20 repeats, 2 components)

<details>
<summary>

```
Median Slopes Analysis
========

Model:
Time ~=      454
    + u        0
    + e    0.015
              µs
```

</summary

```
Pallet: "balances", Extrinsic: "transfer", Lowest values: [], Highest values: [], Steps: [20], Repeat: 20
u,e,extrinsic_time,storage_root_time
1,1000,519000,161000
1,1000,423000,144000
1,1000,470000,143000
1,1000,275000,139000
1,1000,277000,141000
1,1000,425000,144000
1,1000,439000,145000
1,1000,567000,169000
1,1000,454000,147000
1,1000,424000,141000
1,1000,276000,139000
1,1000,444000,139000
1,1000,484000,146000
1,1000,409000,144000
1,1000,485000,137000
1,1000,456000,144000
1,1000,476000,154000
1,1000,503000,156000
1,1000,430000,149000
1,1000,422000,147000
50,1000,557000,235000
50,1000,299000,138000
50,1000,480000,142000
50,1000,1296000,242000
50,1000,489000,144000
50,1000,443000,140000
50,1000,480000,142000
50,1000,470000,136000
50,1000,311000,138000
50,1000,472000,141000
50,1000,523000,143000
50,1000,470000,141000
50,1000,472000,140000
50,1000,581000,168000
50,1000,306000,137000
50,1000,429000,141000
50,1000,461000,136000
50,1000,435000,141000
50,1000,475000,142000
50,1000,545000,147000
99,1000,464000,133000
99,1000,428000,139000
99,1000,291000,131000
99,1000,413000,166000
99,1000,447000,135000
99,1000,279000,128000
99,1000,457000,136000
99,1000,407000,129000
99,1000,429000,131000
99,1000,492000,131000
99,1000,457000,137000
99,1000,512000,195000
99,1000,285000,127000
99,1000,597000,214000
99,1000,433000,126000
99,1000,274000,129000
99,1000,302000,132000
99,1000,430000,129000
99,1000,506000,134000
99,1000,516000,298000
148,1000,273000,133000
148,1000,428000,137000
148,1000,320000,172000
148,1000,567000,150000
148,1000,476000,142000
148,1000,435000,141000
148,1000,284000,135000
148,1000,462000,146000
148,1000,470000,150000
148,1000,496000,147000
148,1000,285000,153000
148,1000,512000,150000
148,1000,296000,142000
148,1000,493000,146000
148,1000,536000,140000
148,1000,497000,159000
148,1000,489000,138000
148,1000,476000,143000
148,1000,515000,141000
148,1000,499000,149000
197,1000,454000,144000
197,1000,450000,157000
197,1000,478000,149000
197,1000,452000,149000
197,1000,490000,146000
197,1000,433000,147000
197,1000,493000,150000
197,1000,527000,179000
197,1000,443000,149000
197,1000,463000,146000
197,1000,527000,151000
197,1000,466000,152000
197,1000,548000,174000
197,1000,495000,147000
197,1000,466000,145000
197,1000,453000,149000
197,1000,456000,144000
197,1000,461000,149000
197,1000,472000,165000
197,1000,480000,158000
246,1000,522000,144000
246,1000,497000,142000
246,1000,287000,140000
246,1000,441000,149000
246,1000,459000,147000
246,1000,521000,164000
246,1000,796000,365000
246,1000,426000,142000
246,1000,459000,143000
246,1000,461000,144000
246,1000,508000,142000
246,1000,575000,172000
246,1000,612000,173000
246,1000,487000,148000
246,1000,279000,135000
246,1000,455000,142000
246,1000,424000,146000
246,1000,479000,144000
246,1000,414000,144000
246,1000,421000,140000
295,1000,548000,170000
295,1000,517000,189000
295,1000,609000,229000
295,1000,427000,144000
295,1000,637000,370000
295,1000,583000,176000
295,1000,510000,168000
295,1000,578000,151000
295,1000,459000,165000
295,1000,363000,150000
295,1000,335000,147000
295,1000,297000,146000
295,1000,597000,175000
295,1000,437000,142000
295,1000,489000,160000
295,1000,517000,155000
295,1000,443000,150000
295,1000,509000,153000
295,1000,493000,169000
295,1000,492000,146000
344,1000,550000,166000
344,1000,520000,139000
344,1000,414000,140000
344,1000,437000,136000
344,1000,481000,135000
344,1000,476000,142000
344,1000,286000,132000
344,1000,489000,139000
344,1000,406000,133000
344,1000,483000,139000
344,1000,405000,137000
344,1000,471000,140000
344,1000,260000,131000
344,1000,422000,129000
344,1000,460000,133000
344,1000,554000,163000
344,1000,416000,135000
344,1000,443000,134000
344,1000,258000,129000
344,1000,463000,137000
393,1000,414000,134000
393,1000,296000,167000
393,1000,477000,151000
393,1000,482000,144000
393,1000,476000,142000
393,1000,420000,142000
393,1000,513000,162000
393,1000,473000,140000
393,1000,266000,134000
393,1000,645000,207000
393,1000,413000,139000
393,1000,499000,143000
393,1000,533000,164000
393,1000,299000,147000
393,1000,303000,147000
393,1000,300000,144000
393,1000,440000,143000
393,1000,275000,140000
393,1000,494000,153000
393,1000,524000,148000
442,1000,472000,144000
442,1000,545000,149000
442,1000,462000,142000
442,1000,500000,159000
442,1000,378000,134000
442,1000,498000,141000
442,1000,479000,145000
442,1000,560000,170000
442,1000,488000,153000
442,1000,455000,173000
442,1000,488000,183000
442,1000,466000,148000
442,1000,288000,139000
442,1000,515000,147000
442,1000,476000,143000
442,1000,537000,167000
442,1000,439000,143000
442,1000,630000,269000
442,1000,596000,178000
442,1000,493000,146000
491,1000,486000,140000
491,1000,468000,150000
491,1000,347000,140000
491,1000,488000,149000
491,1000,440000,150000
491,1000,528000,147000
491,1000,442000,134000
491,1000,557000,169000
491,1000,408000,140000
491,1000,451000,144000
491,1000,495000,146000
491,1000,456000,137000
491,1000,448000,149000
491,1000,473000,160000
491,1000,438000,144000
491,1000,538000,145000
491,1000,459000,138000
491,1000,530000,141000
491,1000,459000,146000
491,1000,475000,149000
540,1000,536000,129000
540,1000,529000,147000
540,1000,538000,140000
540,1000,503000,145000
540,1000,436000,130000
540,1000,498000,130000
540,1000,533000,132000
540,1000,487000,148000
540,1000,527000,137000
540,1000,431000,131000
540,1000,451000,137000
540,1000,501000,129000
540,1000,512000,131000
540,1000,496000,203000
540,1000,291000,141000
540,1000,583000,198000
540,1000,445000,138000
540,1000,465000,140000
540,1000,438000,136000
540,1000,481000,135000
589,1000,485000,151000
589,1000,480000,155000
589,1000,451000,149000
589,1000,271000,140000
589,1000,483000,146000
589,1000,490000,161000
589,1000,277000,140000
589,1000,422000,144000
589,1000,422000,145000
589,1000,419000,140000
589,1000,468000,146000
589,1000,497000,146000
589,1000,509000,147000
589,1000,470000,145000
589,1000,489000,153000
589,1000,521000,147000
589,1000,280000,138000
589,1000,293000,142000
589,1000,267000,141000
589,1000,456000,148000
638,1000,438000,143000
638,1000,587000,204000
638,1000,424000,145000
638,1000,431000,144000
638,1000,489000,142000
638,1000,507000,169000
638,1000,545000,145000
638,1000,363000,164000
638,1000,436000,141000
638,1000,478000,139000
638,1000,297000,137000
638,1000,488000,142000
638,1000,450000,162000
638,1000,430000,159000
638,1000,527000,156000
638,1000,440000,143000
638,1000,432000,139000
638,1000,477000,164000
638,1000,490000,139000
638,1000,487000,142000
687,1000,306000,154000
687,1000,297000,165000
687,1000,480000,166000
687,1000,518000,190000
687,1000,497000,201000
687,1000,421000,157000
687,1000,285000,152000
687,1000,427000,154000
687,1000,456000,155000
687,1000,431000,170000
687,1000,435000,156000
687,1000,430000,151000
687,1000,437000,154000
687,1000,293000,162000
687,1000,290000,148000
687,1000,425000,154000
687,1000,428000,159000
687,1000,435000,151000
687,1000,415000,152000
687,1000,396000,180000
736,1000,493000,150000
736,1000,286000,142000
736,1000,304000,139000
736,1000,513000,148000
736,1000,508000,148000
736,1000,770000,258000
736,1000,441000,202000
736,1000,523000,153000
736,1000,479000,150000
736,1000,475000,145000
736,1000,659000,218000
736,1000,424000,154000
736,1000,472000,145000
736,1000,487000,147000
736,1000,539000,165000
736,1000,585000,163000
736,1000,456000,153000
736,1000,293000,138000
736,1000,429000,139000
736,1000,515000,145000
785,1000,440000,150000
785,1000,503000,148000
785,1000,425000,145000
785,1000,432000,155000
785,1000,427000,148000
785,1000,447000,150000
785,1000,504000,148000
785,1000,458000,146000
785,1000,283000,144000
785,1000,504000,144000
785,1000,477000,146000
785,1000,555000,145000
785,1000,498000,148000
785,1000,490000,150000
785,1000,469000,151000
785,1000,273000,139000
785,1000,507000,172000
785,1000,275000,140000
785,1000,453000,145000
785,1000,277000,149000
834,1000,281000,130000
834,1000,476000,132000
834,1000,499000,154000
834,1000,288000,152000
834,1000,547000,158000
834,1000,526000,241000
834,1000,422000,128000
834,1000,276000,127000
834,1000,276000,126000
834,1000,545000,135000
834,1000,546000,131000
834,1000,477000,130000
834,1000,424000,138000
834,1000,287000,133000
834,1000,464000,131000
834,1000,459000,140000
834,1000,422000,129000
834,1000,270000,138000
834,1000,522000,155000
834,1000,485000,146000
883,1000,570000,149000
883,1000,455000,139000
883,1000,464000,138000
883,1000,486000,144000
883,1000,441000,142000
883,1000,512000,176000
883,1000,581000,178000
883,1000,275000,137000
883,1000,461000,163000
883,1000,475000,148000
883,1000,284000,135000
883,1000,504000,143000
883,1000,566000,152000
883,1000,526000,147000
883,1000,282000,135000
883,1000,513000,168000
883,1000,495000,146000
883,1000,283000,135000
883,1000,757000,144000
883,1000,446000,147000
932,1000,542000,152000
932,1000,489000,146000
932,1000,571000,171000
932,1000,670000,269000
932,1000,289000,143000
932,1000,291000,141000
932,1000,296000,143000
932,1000,474000,157000
932,1000,479000,146000
932,1000,308000,145000
932,1000,477000,150000
932,1000,484000,160000
932,1000,479000,150000
932,1000,456000,145000
932,1000,457000,259000
932,1000,583000,150000
932,1000,312000,141000
932,1000,500000,148000
932,1000,431000,144000
932,1000,431000,141000
981,1000,472000,196000
981,1000,464000,129000
981,1000,298000,136000
981,1000,291000,128000
981,1000,509000,141000
981,1000,340000,152000
981,1000,493000,154000
981,1000,273000,128000
981,1000,271000,128000
981,1000,462000,132000
981,1000,419000,132000
981,1000,438000,133000
981,1000,275000,134000
981,1000,436000,161000
981,1000,478000,137000
981,1000,436000,134000
981,1000,515000,142000
981,1000,282000,127000
981,1000,482000,137000
981,1000,426000,127000
1000,2,583000,255000
1000,2,280000,137000
1000,2,328000,158000
1000,2,479000,178000
1000,2,485000,150000
1000,2,285000,137000
1000,2,470000,142000
1000,2,429000,143000
1000,2,496000,145000
1000,2,297000,145000
1000,2,285000,145000
1000,2,433000,137000
1000,2,484000,145000
1000,2,496000,263000
1000,2,469000,143000
1000,2,433000,147000
1000,2,496000,155000
1000,2,555000,184000
1000,2,526000,147000
1000,2,431000,142000
1000,51,518000,265000
1000,51,275000,138000
1000,51,449000,140000
1000,51,500000,145000
1000,51,443000,150000
1000,51,508000,145000
1000,51,427000,145000
1000,51,460000,142000
1000,51,430000,144000
1000,51,477000,146000
1000,51,519000,161000
1000,51,456000,140000
1000,51,540000,174000
1000,51,576000,187000
1000,51,503000,142000
1000,51,454000,139000
1000,51,279000,136000
1000,51,443000,142000
1000,51,415000,153000
1000,51,488000,146000
1000,100,468000,145000
1000,100,467000,157000
1000,100,448000,160000
1000,100,452000,143000
1000,100,293000,142000
1000,100,284000,145000
1000,100,555000,209000
1000,100,371000,341000
1000,100,438000,143000
1000,100,435000,140000
1000,100,509000,152000
1000,100,284000,138000
1000,100,468000,141000
1000,100,493000,171000
1000,100,570000,172000
1000,100,453000,159000
1000,100,492000,151000
1000,100,431000,147000
1000,100,301000,147000
1000,100,505000,193000
1000,149,591000,178000
1000,149,577000,212000
1000,149,665000,200000
1000,149,476000,151000
1000,149,582000,193000
1000,149,515000,166000
1000,149,499000,157000
1000,149,497000,150000
1000,149,496000,161000
1000,149,488000,154000
1000,149,526000,180000
1000,149,550000,157000
1000,149,628000,248000
1000,149,965000,182000
1000,149,884000,197000
1000,149,309000,150000
1000,149,290000,139000
1000,149,317000,157000
1000,149,444000,144000
1000,149,617000,173000
1000,198,479000,137000
1000,198,269000,140000
1000,198,422000,145000
1000,198,271000,136000
1000,198,292000,144000
1000,198,645000,145000
1000,198,480000,149000
1000,198,465000,141000
1000,198,605000,173000
1000,198,475000,136000
1000,198,465000,145000
1000,198,458000,145000
1000,198,435000,145000
1000,198,543000,144000
1000,198,463000,144000
1000,198,271000,184000
1000,198,475000,144000
1000,198,473000,141000
1000,198,438000,140000
1000,198,444000,143000
1000,247,275000,139000
1000,247,512000,147000
1000,247,496000,147000
1000,247,547000,181000
1000,247,556000,217000
1000,247,304000,147000
1000,247,265000,137000
1000,247,510000,146000
1000,247,416000,141000
1000,247,299000,145000
1000,247,474000,144000
1000,247,531000,149000
1000,247,522000,146000
1000,247,443000,151000
1000,247,267000,137000
1000,247,275000,150000
1000,247,494000,170000
1000,247,486000,145000
1000,247,464000,140000
1000,247,434000,148000
1000,296,414000,144000
1000,296,357000,168000
1000,296,529000,162000
1000,296,606000,173000
1000,296,328000,174000
1000,296,463000,148000
1000,296,486000,149000
1000,296,478000,155000
1000,296,521000,137000
1000,296,295000,143000
1000,296,423000,146000
1000,296,505000,146000
1000,296,416000,145000
1000,296,436000,150000
1000,296,476000,158000
1000,296,570000,187000
1000,296,608000,186000
1000,296,451000,154000
1000,296,499000,146000
1000,296,471000,153000
1000,345,438000,161000
1000,345,501000,153000
1000,345,466000,149000
1000,345,471000,143000
1000,345,440000,147000
1000,345,286000,191000
1000,345,439000,227000
1000,345,447000,141000
1000,345,512000,138000
1000,345,317000,152000
1000,345,478000,145000
1000,345,419000,146000
1000,345,534000,149000
1000,345,434000,149000
1000,345,504000,154000
1000,345,466000,169000
1000,345,459000,141000
1000,345,609000,178000
1000,345,585000,153000
1000,345,452000,152000
1000,394,472000,138000
1000,394,444000,145000
1000,394,366000,143000
1000,394,440000,147000
1000,394,545000,164000
1000,394,493000,155000
1000,394,471000,148000
1000,394,421000,145000
1000,394,508000,141000
1000,394,303000,146000
1000,394,500000,147000
1000,394,525000,144000
1000,394,321000,163000
1000,394,419000,140000
1000,394,319000,152000
1000,394,432000,151000
1000,394,444000,146000
1000,394,558000,147000
1000,394,518000,148000
1000,394,450000,150000
1000,443,283000,137000
1000,443,480000,164000
1000,443,517000,1239000
1000,443,548000,151000
1000,443,426000,144000
1000,443,479000,148000
1000,443,521000,162000
1000,443,485000,157000
1000,443,466000,145000
1000,443,513000,161000
1000,443,306000,143000
1000,443,299000,155000
1000,443,451000,148000
1000,443,465000,160000
1000,443,470000,150000
1000,443,564000,152000
1000,443,490000,160000
1000,443,568000,168000
1000,443,603000,175000
1000,443,475000,156000
1000,492,493000,142000
1000,492,277000,138000
1000,492,476000,141000
1000,492,445000,136000
1000,492,289000,140000
1000,492,488000,138000
1000,492,281000,142000
1000,492,432000,144000
1000,492,493000,142000
1000,492,500000,149000
1000,492,420000,143000
1000,492,446000,142000
1000,492,448000,139000
1000,492,482000,145000
1000,492,486000,156000
1000,492,526000,166000
1000,492,552000,151000
1000,492,444000,170000
1000,492,519000,155000
1000,492,518000,156000
1000,541,535000,187000
1000,541,483000,157000
1000,541,494000,146000
1000,541,477000,150000
1000,541,462000,152000
1000,541,469000,145000
1000,541,475000,147000
1000,541,785000,192000
1000,541,696000,255000
1000,541,431000,145000
1000,541,280000,140000
1000,541,532000,151000
1000,541,552000,158000
1000,541,532000,180000
1000,541,501000,193000
1000,541,472000,147000
1000,541,511000,153000
1000,541,485000,140000
1000,541,442000,146000
1000,541,489000,144000
1000,590,296000,139000
1000,590,426000,139000
1000,590,291000,160000
1000,590,292000,166000
1000,590,449000,143000
1000,590,451000,150000
1000,590,538000,156000
1000,590,278000,139000
1000,590,427000,145000
1000,590,442000,147000
1000,590,282000,145000
1000,590,487000,153000
1000,590,499000,142000
1000,590,719000,280000
1000,590,275000,139000
1000,590,315000,143000
1000,590,628000,176000
1000,590,490000,191000
1000,590,532000,168000
1000,590,432000,146000
1000,639,497000,139000
1000,639,461000,150000
1000,639,434000,148000
1000,639,480000,140000
1000,639,296000,144000
1000,639,732000,188000
1000,639,507000,144000
1000,639,582000,147000
1000,639,478000,149000
1000,639,516000,149000
1000,639,293000,141000
1000,639,456000,141000
1000,639,434000,144000
1000,639,518000,181000
1000,639,462000,155000
1000,639,480000,201000
1000,639,535000,163000
1000,639,440000,145000
1000,639,533000,150000
1000,639,510000,186000
1000,688,464000,145000
1000,688,493000,145000
1000,688,458000,146000
1000,688,423000,143000
1000,688,285000,142000
1000,688,461000,143000
1000,688,441000,150000
1000,688,281000,139000
1000,688,475000,141000
1000,688,473000,140000
1000,688,418000,145000
1000,688,422000,145000
1000,688,779000,193000
1000,688,453000,152000
1000,688,306000,138000
1000,688,401000,141000
1000,688,436000,146000
1000,688,544000,152000
1000,688,517000,156000
1000,688,462000,156000
1000,737,559000,209000
1000,737,566000,270000
1000,737,301000,143000
1000,737,491000,154000
1000,737,498000,191000
1000,737,470000,140000
1000,737,475000,184000
1000,737,517000,146000
1000,737,481000,146000
1000,737,538000,154000
1000,737,283000,138000
1000,737,543000,162000
1000,737,452000,177000
1000,737,535000,174000
1000,737,309000,185000
1000,737,445000,149000
1000,737,480000,148000
1000,737,455000,152000
1000,737,502000,246000
1000,737,575000,169000
1000,786,528000,188000
1000,786,559000,175000
1000,786,483000,147000
1000,786,502000,152000
1000,786,563000,147000
1000,786,527000,148000
1000,786,607000,178000
1000,786,522000,217000
1000,786,441000,154000
1000,786,520000,175000
1000,786,284000,141000
1000,786,517000,150000
1000,786,451000,146000
1000,786,492000,146000
1000,786,460000,145000
1000,786,469000,145000
1000,786,305000,140000
1000,786,457000,140000
1000,786,308000,144000
1000,786,517000,253000
1000,835,479000,151000
1000,835,429000,145000
1000,835,304000,142000
1000,835,489000,151000
1000,835,316000,141000
1000,835,456000,143000
1000,835,282000,140000
1000,835,496000,178000
1000,835,382000,148000
1000,835,545000,145000
1000,835,286000,147000
1000,835,306000,173000
1000,835,498000,145000
1000,835,486000,149000
1000,835,504000,160000
1000,835,445000,143000
1000,835,510000,148000
1000,835,464000,151000
1000,835,447000,145000
1000,835,582000,181000
1000,884,288000,141000
1000,884,319000,145000
1000,884,486000,143000
1000,884,509000,191000
1000,884,533000,191000
1000,884,492000,149000
1000,884,542000,193000
1000,884,510000,152000
1000,884,591000,192000
1000,884,492000,146000
1000,884,282000,150000
1000,884,454000,137000
1000,884,326000,144000
1000,884,435000,142000
1000,884,539000,155000
1000,884,505000,148000
1000,884,511000,147000
1000,884,283000,150000
1000,884,455000,153000
1000,884,698000,155000
1000,933,446000,139000
1000,933,480000,142000
1000,933,500000,138000
1000,933,464000,156000
1000,933,451000,164000
1000,933,453000,149000
1000,933,601000,162000
1000,933,514000,162000
1000,933,442000,147000
1000,933,779000,314000
1000,933,452000,155000
1000,933,513000,166000
1000,933,422000,140000
1000,933,488000,139000
1000,933,466000,164000
1000,933,365000,150000
1000,933,494000,153000
1000,933,443000,148000
1000,933,473000,145000
1000,933,533000,153000
1000,982,509000,145000
1000,982,288000,145000
1000,982,580000,148000
1000,982,503000,151000
1000,982,540000,169000
1000,982,505000,148000
1000,982,478000,148000
1000,982,437000,149000
1000,982,521000,149000
1000,982,516000,157000
1000,982,490000,155000
1000,982,478000,145000
1000,982,509000,149000
1000,982,531000,161000
1000,982,292000,139000
1000,982,503000,162000
1000,982,469000,152000
1000,982,449000,144000
1000,982,437000,147000
1000,982,492000,149000

Median Slopes Analysis
========

Model:
Time ~=      454
    + u        0
    + e    0.015
              µs

Min Squares Analysis
========

Data points distribution:
    u     e   mean µs  sigma µs       %
    1  1000     444.1     18.34    4.1%
   50  1000     471.2     11.78    2.5%
   99  1000     436.5      18.2    4.1%
  148  1000     472.2     23.17    4.9%
  197  1000     468.6     10.78    2.3%
  246  1000     467.2     24.06    5.1%
  295  1000     497.7     28.59    5.7%
  344  1000     448.3     24.02    5.3%
  393  1000     439.2     53.85   12.2%
  442  1000     487.5        14    2.8%
  491  1000     466.3     13.28    2.8%
  540  1000     492.1     21.05    4.2%
  589  1000     455.6     24.88    5.4%
  638  1000     461.5     22.99    4.9%
  687  1000     424.3     11.07    2.6%
  736  1000     483.9     23.13    4.7%
  785  1000     459.1      22.8    4.9%
  834  1000     441.6     57.52   13.0%
  883  1000     481.1     23.15    4.8%
  932  1000     465.7     20.01    4.2%
  981  1000     419.1     53.43   12.7%
 1000     2     460.9     25.08    5.4%
 1000    51     467.3     21.77    4.6%
 1000   100     455.2     17.82    3.9%
 1000   149     532.1     37.68    7.0%
 1000   198     459.1     14.27    3.1%
 1000   247     452.1     56.96   12.6%
 1000   296     468.8     24.86    5.3%
 1000   345     461.9     17.99    3.8%
 1000   394     456.7     24.82    5.4%
 1000   443       484     17.23    3.5%
 1000   492     470.1     20.44    4.3%
 1000   541     491.9      17.6    3.5%
 1000   590     421.5     61.87   14.6%
 1000   639     484.7     20.63    4.2%
 1000   688     449.3     16.87    3.7%
 1000   737     490.4     22.34    4.5%
 1000   786     493.9      24.2    4.8%
 1000   835     457.3     32.51    7.1%
 1000   884     484.9     25.95    5.3%
 1000   933     472.1        17    3.6%
 1000   982     493.6     13.74    2.7%

Quality and confidence:
param     error
u         0.006
e         0.006

Model:
Time ~=    465.1
    + u    0.006
    + e        0
              µs

```
</details>

**Comment by shawntabrizi** [comment]
Cherry pick dc67e89

<details>
<summary>511.7 microseconds</summary>

```
Pallet: "balances", Extrinsic: "transfer", Lowest values: [], Highest values: [], Steps: [20], Repeat: 20
Median Slopes Analysis
========

Model:
Time ~=    511.7
    + u        0
    + e        0
              µs

Min Squares Analysis
========

Data points distribution:
    u     e   mean µs  sigma µs       %
    1  1000     466.3     13.83    2.9%
   50  1000     519.7     32.04    6.1%
   99  1000     440.6     15.12    3.4%
  148  1000     533.8     52.08    9.7%
  197  1000     511.1     33.12    6.4%
  246  1000     515.1     53.14   10.3%
  295  1000     473.2      19.7    4.1%
  344  1000     502.4     33.48    6.6%
  393  1000     517.9      50.2    9.6%
  442  1000       540     72.49   13.4%
  491  1000     540.9     38.51    7.1%
  540  1000     500.6     43.95    8.7%
  589  1000     540.9     41.32    7.6%
  638  1000     496.3     31.53    6.3%
  687  1000     544.8     38.31    7.0%
  736  1000     478.9     27.89    5.8%
  785  1000     525.9     42.73    8.1%
  834  1000     505.2     27.28    5.4%
  883  1000     473.3      31.4    6.6%
  932  1000     491.1     18.89    3.8%
  981  1000     433.3     26.55    6.1%
 1000     2     506.3     34.19    6.7%
 1000    51     493.8     18.89    3.8%
 1000   100     557.6     50.21    9.0%
 1000   149     526.1     33.33    6.3%
 1000   198       527     44.97    8.5%
 1000   247       498     20.53    4.1%
 1000   296     516.7     51.54    9.9%
 1000   345     564.8      64.7   11.4%
 1000   394     497.6     37.16    7.4%
 1000   443       498     22.15    4.4%
 1000   492     508.9     44.23    8.6%
 1000   541     575.6     53.77    9.3%
 1000   590     529.2     63.73   12.0%
 1000   639     534.4     38.18    7.1%
 1000   688     475.3      19.6    4.1%
 1000   737     513.1     15.35    2.9%
 1000   786     551.4     42.73    7.7%
 1000   835     521.5     39.09    7.4%
 1000   884     514.5     41.37    8.0%
 1000   933       490     21.64    4.4%
 1000   982     476.3     15.74    3.3%

Quality and confidence:
param     error
u         0.008
e         0.008

Model:
Time ~=    528.9
    + u        0
    + e        0
              µs

```

</details>

**Comment by shawntabrizi** [comment]
Cherry pick b178929

Introduces a slowdown

<details>
<summary>

```
 855.8 microseconds
```

</summary>

```
Pallet: "balances", Extrinsic: "transfer", Lowest values: [], Highest values: [], Steps: [20], Repeat: 20
Median Slopes Analysis
========

Model:
Time ~=    855.8
    + u        0
    + e        0
              µs

Min Squares Analysis
========

Data points distribution:
    u     e   mean µs  sigma µs       %
    1  1000     866.8     55.26    6.3%
   50  1000       822     48.01    5.8%
   99  1000     839.1     100.4   11.9%
  148  1000     849.7     70.18    8.2%
  197  1000     884.9     42.42    4.7%
  246  1000     778.5     46.68    5.9%
  295  1000     800.1     45.17    5.6%
  344  1000     808.3     58.24    7.2%
  393  1000     813.4     46.36    5.7%
  442  1000     902.4     73.22    8.1%
  491  1000     788.5      49.6    6.2%
  540  1000     847.1     40.28    4.7%
  589  1000     862.7     61.73    7.1%
  638  1000     795.8     30.51    3.8%
  687  1000     829.2     46.07    5.5%
  736  1000     818.1     80.25    9.8%
  785  1000     816.7      50.8    6.2%
  834  1000     845.1     67.44    7.9%
  883  1000     821.6     55.04    6.7%
  932  1000     853.5     47.44    5.5%
  981  1000     822.2     67.26    8.1%
 1000     2       868     95.43   10.9%
 1000    51     834.3     79.07    9.4%
 1000   100     883.9      74.6    8.4%
 1000   149     862.9     90.92   10.5%
 1000   198     815.4     52.63    6.4%
 1000   247       784     43.41    5.5%
 1000   296     802.3     55.62    6.9%
 1000   345     823.4     66.45    8.0%
 1000   394     832.3     69.38    8.3%
 1000   443     862.2     52.91    6.1%
 1000   492     884.4     78.53    8.8%
 1000   541     826.7     62.52    7.5%
 1000   590       820     40.37    4.9%
 1000   639     848.3     51.42    6.0%
 1000   688     808.1     17.32    2.1%
 1000   737     833.3     51.38    6.1%
 1000   786     810.9     44.99    5.5%
 1000   835     862.5     70.79    8.2%
 1000   884     807.4      38.7    4.7%
 1000   933       802     50.89    6.3%
 1000   982     823.7     68.68    8.3%

Quality and confidence:
param     error
u         0.012
e         0.012

Model:
Time ~=    862.3
    + u        0
    + e        0
              µs

```
</details>

**Pull request closed without merging**
