### PR TITLE
Migrate pallet-utility to pallet attribute macro.

### PR DESCRIPTION
**Pull request by shaunxw**
Part of #7882.

Converts the `Utility` pallet to the new pallet attribute macro introduced in #6877.

Following the upgrade guidelines here: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines.

## ⚠️ Breaking Change ⚠️ 

From https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

> storages now use PalletInfo for module_prefix instead of the one given to decl_storage: Thus any use of this pallet in construct_runtime! should be careful to update name in order not to break storage or to upgrade storage (moreover for instantiable pallet). If pallet is published, make sure to warn about this breaking change.

So users of the `Utility` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed depending on the configuration of the `Utility` pallet.

### CODE REVIEW

**Comment by shaunxw** [comment]
@thiolliere @ascjones Could you please help to review? Thanks! :]

**Comment by shawntabrizi** [comment]
@shaunxw what is your Polkadot / Kusama address? I would like to open a tip for you for your work.

**Comment by shaunxw** [comment]
> @shaunxw what is your Polkadot / Kusama address? I would like to open a tip for your work.

Wow, thanks a lot! XD

Polkadot address: `16J5xxKKe63SqkSNz33C1yve7U2XP5R4bcCBeECbxVhPwhL1`
Kusama address: `DrrKdwEPPJmKEYPfTWdLyS2ZtqxLhnDaWVq9sQvD8DgcHJP`

**Review by thiolliere — APPROVED** [review]
Sorry I forgot about this one.

All good to me, though it shouldn't require a migration as there wasn't any storages in the pallet.

**Review by ascjones — APPROVED** [review]

**Comment by thiolliere** [comment]
can you merge master ? I think the github action needs the new labels and I suspect it get it from repo itself

**Comment by shaunxw** [comment]
> can you merge master ? I think the github action needs the new labels and I suspect it get it from repo itself

Done.

**Comment by thiolliere** [comment]
bot merge

**Comment by thiolliere** [comment]
bot merge

**Pull request merged**
