### PR TITLE
bump ed25519-dalek to 2.0

### PR DESCRIPTION
**Pull request by andresilva**
https://rustsec.org/advisories/RUSTSEC-2022-0093

Can't merge until https://github.com/mcginty/snow/issues/164 to remove cargo patch in this PR.

There is also `ed25519-zebra` "4.0" available, but can't update to it for the same reason as above. Zebra is unaffected by this issue though.

polkadot companion: https://github.com/paritytech/polkadot/pull/7648
cumulus companion: https://github.com/paritytech/cumulus/pull/3038

### CODE REVIEW

**Comment by andresilva** [comment]
Should probably be burned-in to make sure nothing breaks.

**Comment by bkchr** [comment]
> Should probably be burned-in to make sure nothing breaks.

Can probably don while we wait for the snow release.

**Comment by andresilva** [comment]
We'll still have `ed25519-dalek` 1.5 in our dependencies until https://github.com/libp2p/rust-libp2p/issues/4327 is fixed (which is also blocked on snow).

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3398965

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3398967

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3398966

**Comment by skunert** [comment]
Took the liberty to remove the snow patch here since 0.9.3 [has been released](https://github.com/mcginty/snow/issues/164) in the meantime (and I am also needing the new version for a PR of mine).

**Comment by ggwpez** [comment]
Can we merge this? Substrate master CI needs it.

**Review by skunert — APPROVED** [review]

**Comment by skunert** [comment]
bot merge

**Pull request merged**
