### PR TITLE
Fix check-polkadot

### PR DESCRIPTION
**Pull request by kigawas**

### CODE REVIEW

**Comment by bkchr** [comment]
What is the error?

**Comment by kigawas** [comment]
> What is the error?



> What is the error?

https://gitlab.parity.io/parity/substrate/-/jobs/327134
Like this

**Comment by kigawas** [comment]
> Next time just include the fix into your other pr ;)

just want it easier to track in other issues :)

**Comment by bkchr** [comment]
Your other pr was the only one with this issue.

**Pull request merged**
