### PR TITLE
Use Subscription Manager from `jsonrpc-pubsub`: The Sequel

### PR DESCRIPTION
**Pull request by HCastano**
This is a follow up to #6208 and #6252, as it breaks the JS API. Will be on ice until downstream changes are made.

Related JS issue:  polkadot-js/api#2331

cc @jacogr

### CODE REVIEW

**Comment by jacogr** [comment]
Can we please add this as a branch on the substrate repo - so fo testing we can actually switch branches instead of having to clone a fork and build it from completely from scratch?

**Comment by HCastano** [comment]
@jacogr I just pushed a branch with the same name

**Comment by jacogr** [comment]
Ok from my side, API betas now have support for this (and the currently live-deployed versions). Will be in the next stable API release to roll out.

**Comment by HCastano** [comment]
Last commit is simply changing the `jsonrpc` crate dependencies from `v14.2` to `v14.2.0`, so no _actual_ changes are being introduced

**Comment by andresilva** [comment]
bot merge

**Pull request merged**
