### PR TITLE
Remove rhododendron

### PR DESCRIPTION
**Pull request by DemiMarie-parity**
It is unused and unmaintained, and has presumably regressed.  Remove it
for now.  If anyone wants to use it in the future, and has the resources
to maintain it, they are encouraged to bring it back from git history.

### CODE REVIEW

**Comment by tomaka** [comment]
cc #1020

**Comment by andresilva** [comment]
The code is already behind a feature flag, it is compartmentalized and there's really no maintenance burden as it is. I would prefer to keep it for discoverability, and also because at some point we want to get it working again (which shouldn't be too hard anyway). Substrate is meant to have pluggable consensus so having different consensus engines available is a plus, and Rhododendron provides instant finality so it could be preferred to BABE + GRANDPA for some users.

**Comment by DemiMarie-parity** [comment]
Closing as per @andresilva’s review.

**Comment by kigawas** [comment]
@andresilva 

Any specific plan on making it work again?

**Comment by bkchr** [comment]
No, but if you need it. We are open to accept pull requests :)

**Comment by tomaka** [comment]
I'd still be favour of removing rhododendron. What we have today is basically commented out code that doesn't compile.
Restoring the code later is as easy as doing `git checkout <commit> ./core/consensus/rhd`.

**Comment by bkchr** [comment]
Cc @gnunicorn

**Comment by andresilva** [comment]
I can make a PR to fix this after kusama, that is the proper way to fix this instead of just removing the code. Someone else can take it either if they are interested but I can't focus on this right now.

**Comment by marcio-diaz** [comment]
> I can make a PR to fix this after kusama, that is the proper way to fix this instead of just removing the code. Someone else can take it either if they are interested but I can't focus on this right now.

I'm interested :raised_hands:

**Pull request closed without merging**
