### PR TITLE
Update all weights

### PR DESCRIPTION
**Pull request by ggwpez**
Baseline for https://github.com/paritytech/substrate/pull/13408

### CODE REVIEW

**Comment by ggwpez** [comment]
bot bench $ all

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2529425

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2529426

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2529427

**Comment by athei** [comment]
bot clean
bot bench $ all

**Comment by athei** [comment]
The original commit did remove a weight file which made the compilation file. I just use an empty commit instead.

**Review by athei — APPROVED** [review]

**Comment by athei** [comment]
The failure of `continuous-integration/gitlab-check-crate-publishing` is unrelated to this PR, right?

**Review by sam0x17 — APPROVED** [review]
It is indeed all weight changes 👍🏻 
Screenshot 2023-03-16 at 12 56 12 PM

**Pull request merged**
