### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by DemiMarie-parity**
This updates all dependencies to the latest semver-compatible versions.

Generated by:

```sh
find . -name Cargo.lock -execdir cargo update \;
```

### CODE REVIEW

**Comment by kianenigma** [comment]
only updates lock files?

**Comment by kianenigma** [comment]
> only updates lock files?

nvmd; `cargo update`

**Comment by thiolliere** [comment]
updating only the locks can make the Cargo.toml outdated. for instance if we accidentally use a feature of a new minor release without noticing (which obviously happens) then the Cargo.toml version is wrong and a user of our library can have his code break for no reason just because he updated substrate without updating on of its dependency.

(At some point things are even more difficult: if you have A depends on B:1.1 and C depends on B:1.0 and D depends on A, C and B:1.0 you actually never tested for B:1.0 and maybe you are using a feature of B:1.1 without noticing.)

All in all I don't really mind as we have the Cargo.lock in the git. and substrate is breaking quite often anyway. But I would prefer you increment minor version as well (also if we are strictly into semver we should only have the two first number updated: like 1.1 or 0.5.2 because 1.1.0 and 1.1.1 should just be a bugfix no feature if I remember semver correctly (I would prefer having 1.1.1 anyway actually.)

**Comment by DemiMarie-parity** [comment]
@thiolliere I have another PR that bumps `Cargo.toml` (#3556).

**Comment by bkchr** [comment]
Superseded by: https://github.com/paritytech/substrate/pull/3556

**Pull request closed without merging**
