### PR TITLE
Add `D3-trivial 🧸` to dependabot

### PR DESCRIPTION
**Pull request by expenses**
See https://github.com/paritytech/substrate/pull/8977/checks?check_run_id=2718325830.

Or should this be added manually?

### CODE REVIEW

**Comment by bkchr** [comment]
Probably not required. As this is only needed for stuff that changes the runtime

**Comment by TriplEight** [comment]
Is it possible that dependabot will commit to [these](https://github.com/paritytech/substrate/blob/master/.maintain/common/lib.sh#L111) dirs?

**Comment by bkchr** [comment]
Yes

**Review by TriplEight — APPROVED** [review]

**Comment by tomaka** [comment]
I don't really have an opinion on this PR.

A pull request from dependabot that just changes a dependency's version is indeed trivial by itself, but in an ideal world we want to make sure that the dependency update doesn't introduce a security issue, by auditing our dependencies as well.
That being said, people sometimes just run `cargo update` and we don't catch it, and it feels stupid to add more restrictions regarding PRs authored by dependabot compare to PRs authored by other people.

**Comment by TriplEight** [comment]
I do not know any other automatic way but to audit these PRs with `cargo audit` or the similar part of `cargo deny`, both use the same source.

**Comment by tomaka** [comment]
We're talking about "manual" audits by SRLabs, our auditing company

**Comment by TriplEight** [comment]
Then it shouldn't have exactly this label in order to be manually reviewed.

**Comment by s3krit** [comment]
The audit labels refer strictly to the auditing done by SRLabs.

* If auditing changes to dependencies is within the scope of the auditing done by SRLabs then we should not apply the trivial label, but rather do something more clever to determine whether or not the change needs auditing or not
* If auditing changes to dependencies is *not* within the scope of the auditing done by SRLabs (fwiw I'm not sure it is), then this PR is fine as-is.

**Pull request closed without merging**
