### PR TITLE
Bump `kvdb-rocksdb` to 0.19.0

### PR DESCRIPTION
**Pull request by tdimitrov**
polkadot companion: https://github.com/paritytech/polkadot/pull/7212

### CODE REVIEW

**Review by ordian — APPROVED** [review]
This is likely need a polkadot companion.

**Comment by tdimitrov** [comment]
How do we handle changes depending on each other?

`kvdb-rocksdb` should be bumped in polkadot but it won't compile until `substrate` is also bumped :see_no_evil:

**Comment by tdimitrov** [comment]
And cumulus fails because `polkadot-service` needs to be bumped with the companion above.

**Comment by ordian** [comment]
bot merge

**Comment by niklasad1** [comment]
bot merge

**Comment by ordian** [comment]
bot merge

**Pull request merged**
