### PR TITLE
Fix typo: PRORITY -> PRIORITY

### PR DESCRIPTION
**Pull request by subsocialdev**

### CODE REVIEW

**Comment by subsocialdev** [comment]
[clabot:check]

**Comment by subsocialdev** [comment]
`[clabot:check]`

**Comment by subsocialdev** [comment]
`[clabot:check]`

**Comment by bkchr** [comment]
Next time, please merge your prs. And not create one pr per typo.

**Comment by subsocialdev** [comment]
> Next time, please merge your prs. And not create one pr per typo.

Sure. Actually I didn't plan any PRs. I was just reading Substrate code and stumbled upon couple of typos at different time.

**Pull request merged**
