### PR TITLE
Prep for Altair - Add ss58 prefix

### PR DESCRIPTION
**Pull request by mikiquantum**
Just adds SS58 Prefix for Centrifuge Altair Network and renames symbol of Centrifuge Chain.

### CODE REVIEW

**Review by BenWhiteJam — APPROVED** [review]
fine from BD side.

- [x] contact
- [x] testnet
- [x] code repo
- [x] support
- [x] community

**Comment by bkchr** [comment]
@mikiquantum please merge master

**Review by bkchr — APPROVED** [review]

**Comment by mikiquantum** [comment]
@bkchr done

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
