### PR TITLE
Executor: Add `create_runtime_from_artifact_bytes`

### PR DESCRIPTION
**Pull request by mrcnski**
# PULL REQUEST

## Overview

See title. Also export `WasmtimeRuntime`, returned by the `create_runtime*` functions.

I benchmarked the performance regression out of curiosity: https://github.com/bytecodealliance/wasmtime/pull/6420. But since runtime creation is not at all a bottleneck, it makes sense to always use this new function for the reasons given in the related issue and PR.

## Relevant Issues/PRs

Needed for https://github.com/paritytech/polkadot/pull/7246#discussion_r1199178044
Closes https://github.com/paritytech/substrate/issues/13861

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by koute — APPROVED** [review]
Please note that AFAIK this can have performance implications on module *instantiation*, not just on module creation.

On Linux this most likely won't make a difference because when deserializing a precompiled module from a slice `wasmtime` will just create an internal memfd mapping for it anyway, but for macOS it cannot do so (since macOS doesn't have an equivalent of memfd) so it will prevent the copy-on-write instantiation codepath from kicking in.

**Comment by mrcnski** [comment]
@koute You are right, I missed that:

```rs
/// All of the CoW strategies (with `CopyOnWrite` suffix) are only supported when either:
///   a) we're running on Linux,
///   b) we're running on an Unix-like system and we're precompiling
///      our module beforehand.
```

I did some benchmarks [here](https://github.com/paritytech/polkadot/issues/7266). Might make testing on Mac a little slower but we can live with it.

**Comment by mrcnski** [comment]
Can someone please take a look at the latest commit before I merge this in? I'm wondering if there's a technical reason we didn't already have a `pooling_vanilla_precompiled` benchmark.

**Comment by bkchr** [comment]
> Can someone please take a look at the latest commit before I merge this in? I'm wondering if there's a technical reason we didn't already have a `pooling_vanilla_precompiled` benchmark. (i.e. that particular combination of options doesn't make sense for some reason.)

Probably just an oversight. From the Polkadot PVF validation side the instancing strategy isn't that important we only ever create one instance, not like for the runtime. However, the runtime doesn't use pre-compiled.

**Pull request merged**
