### PR TITLE
Adds a session getter to historical proofs

### PR DESCRIPTION
**Pull request by montekki**
Adds a session getter for `session::historical::Proof`. It is needed for offence handlers such as paritytech/polkadot#840 to determine the exact session of the commited equivocation and create the corresponding `Offence` struct.

### CODE REVIEW

**Comment by rphmeier** [comment]
cc @gnunicorn this is technically a breaking change, should we wait to merge? Something that's definitely needed for slashing.

**Comment by gnunicorn** [comment]
we are still in alpha-release-phase, we are accepting not-too-involved breaking changes.

**Comment by montekki** [comment]
Also added some trait derives that are necessary for using the `Proof` type inside runtime.

**Comment by gnunicorn** [comment]
failing test, merge conflict.

**Comment by montekki** [comment]
@gnunicorn can we now get this in?

**Pull request merged**
