### PR TITLE
Core BLS Crypto

### PR DESCRIPTION
**Pull request by drskalman**
This pull request implements `primitives/core/src/bls.rs` based on `primitives/core/src/ed25519.rs` implementation. This is needed in order to add BLS signatures to beefy.

Related Issues: #10469
While ed25519 implementation assumes seeds and secret keys are essentially the same here, we use, hash to field and so they are different and seeds are not recoverable from secret keys.

### CODE REVIEW

**Comment by drskalman** [comment]
I'm also getting this strange failure of failure but I haven't touched `u256` at all.

```
failures:

---- uint::tests::test_u256 stdout ----
thread 'uint::tests::test_u256' panicked at 'called `Result::unwrap_err()` on an `Ok` value: 16', primitives/core/src/uint.rs:61:5
```

**Comment by burdges** [comment]
We briefly discussed the structure of host calls today, but it seemingly requires further clarification.

**Comment by drskalman** [comment]
I'm working on this. This is pending review but I'm also working on [BEEFY client](https://github.com/drskalman/substrate/commits/skalman-bls-beefy-client) which depeneds on the changes to BEEFY primitives provided by this pull request.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/decentralized-dot-eth-bridges-a-comparison-thread/777/19

**Comment by claravanstaden** [comment]
@drskalman thanks for your work on this! This work is an important piece for our project, Snowbridge (Ethereum-Polkadot bridge). I would like to assist in getting this merged, if possible?

**Comment by vgeddes** [comment]
One idea to ease the passage of this work would be to split it into 2 smaller pieces:
1. Support for BLS in Substrate
2. Support for BLS in BEEFY

Snowfork doesn't mind taking on (1), and testing the changes on our parachain. Would be a nice first contribution to Substrate by @claravanstaden.

**Pull request closed without merging**
