### PR TITLE
Bump parity-db

### LINKED ISSUE #13179: Rococo validator using paritydb stuck on startup with "Missing table, starting reindex"
I have several Rococo validator which remains stuck after startup. The only way to fix the issue is to restore the database from a backup.

Version: 0.9.37
Relevant flags: 
```
--chain=rococo
--validator
--database=paritydb
--pruning=1000
--enable-offchain-indexing=true
```

```
2023-01-19 14:08:16.389  INFO main sc_cli::runner: Parity Polkadot    
2023-01-19 14:08:16.389  INFO main sc_cli::runner: ✌️  version 0.9.37-645723987cf    
2023-01-19 14:08:16.389  INFO main sc_cli::runner: ❤️  by Parity Technologies <admin@parity.io>, 2017-2023    
2023-01-19 14:08:16.389  INFO main sc_cli::runner: 📋 Chain specification: Rococo    
2023-01-19 14:08:16.389  INFO main sc_cli::runner: 🏷  Node name: rococo-validator-f-node-9    
2023-01-19 14:08:16.389  INFO main sc_cli::runner: 👤 Role: AUTHORITY    
2023-01-19 14:08:16.389  INFO main sc_cli::runner: 💾 Database: ParityDb at /chain-data/chains/rococo_v2_2/paritydb/full    
2023-01-19 14:08:16.389  INFO main sc_cli::runner: ⛓  Native runtime: rococo-9370 (parity-rococo-v2.0-0.tx18.au0)    
2023-01-19 14:08:27.060  WARN main parity-db: Missing table 09-19, starting reindex    
2023-01-19 14:08:27.060  INFO main parity-db: Started reindex for 09-18    
```

I also noticed that just before the node became stuck like this it experienced huge cpu/memory usage which caused several OOM kills. Maybe the database was corrupted by OOM kills ?

image

### PR DESCRIPTION
**Pull request by arkpar**
Fixes #13179
See https://github.com/paritytech/parity-db/pull/170

polkadot companion: https://github.com/paritytech/polkadot/pull/6617
cumulus companion: https://github.com/paritytech/cumulus/pull/2132

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2306828

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2306827

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2306831

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2306838

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2306832

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2306833

**Review by cheme — APPROVED** [review]
Works for me.
It requires some companion (certainly only to change parity-db versionning which I remember doing, maybe in polkadot, cumulus we could just set parity db version to 0.4 and save all this companion work).
I would propose to also make parity-db default, but probably worth waiting a week after this get released.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
