### PR TITLE
Refactor NotifsHandler::poll

### PR DESCRIPTION
**Pull request by tomaka**
Better version of https://github.com/paritytech/substrate/pull/8405 (and https://github.com/paritytech/substrate/pull/8410)
Now that the legacy substream is gone, this cleans up the hack introduced in https://github.com/paritytech/substrate/pull/7594

This PR does two things:

- Ensure that all messages are properly sent before we potentially generate `Poll::Ready`, and not the other way around.
- Avoids a lot of spurious wake ups when sending by removing the hack-y `cx.waker().wake_by_ref()` and by only calling `Sink::poll_ready()` on the substream only if there is actually something to send in the channel, and not all the time.

### CODE REVIEW

**Review by eskimor — APPROVED** [review]
I like :-)

**Review by romanb — APPROVED** [review]
:+1:

**Comment by tomaka** [comment]
Reduced polling rate seems to work:

image

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
