### PR TITLE
Full client snapshot draft.

### PR DESCRIPTION
**Pull request by cheme**
This PR is a draft pr for snapshot at a given blockchain state (polkadot branch used for test is https://github.com/cheme/polkadot-1/tree/flat_snapshot).
It is pretty similar to 'export-state' subcommand, but intend to allow importing a trusted export to avoid having to sync, and also uses a more compact format.

This is targetting full client (light client already got such functionalities).

It is an extract from a larger branch where I am working on compacting the canonical state of a archive node (originally it was a snapshot-db but I am not sure it makes much sense regarding current substrate chain (pretty small chain)), where those commands help me testing.

New subcommands are 'snapshot-export' and 'snapshot-import'.

My current testing scenario is:
```shell
# after release build
cp target/release/polkadot ./polkadot_clean2
# sync source
./polkadot_clean2 -d chain_clean_ksm2 --chain=kusama --wasm-execution Compiled --pruning=1000
# build new
rm -r chain_tmp2/
./polkadot_clean2 snapshot-export -d chain_test2 --chain=kusama  --log=info test2
./polkadot_clean snapshot-import -d chain_tmp2 --chain=kusama --log=info test2
# run new
./polkadot_clean2 -d chain_tmp2 --chain=kusama --wasm-execution Compiled --pruning=1000

```

Reason I create this draft PR:
I think it can be useful and does not bring major changes.
So I wanted to give some visibility to this code in case it can be useful, but it is 'experimental' and really a 'draft'.

Reason I keep this draft and experimental:

- Not really tested for something else than sync (see my testing scenario).
For instance in the command test, when restarting the chain, block are produced but not finalized (maybe some additional data is needed with grandpa or it is something else).

- Big heuristic on block headers needed: current substrate code expect presence of all block headers.
At this point I export the last 10k headers, but there is probably panicky rpc or even sync. 
Also for correct implementation, it would require grandpa and babe advanced knowledge (see their implementation of `SnapshotComponent` trait).
`ForkTree` is also one of the place that tend to look backward at headers and panic.
Also no real care on having a nice format around those components (I simply exported/imported aux data similarily to what is done for light client).

- Snapshot format is undocumented (it is some simple streaming of key value, with a bit of compression on key with custom payload for register component such as grandpa or babe).

### CODE REVIEW

**Comment by tomaka** [comment]
> At this point I export the last 10k headers, but there is probably panicky rpc or even sync.

Am I understanding that you're not exporting all blocks?
If so, then a node that has been restored from a snapshot is unable to serve blocks 1, 2, 3, etc.? Which would mean that ultimately if the entire network is made only of nodes restored from snapshots, nobody could sync?

**Comment by cheme** [comment]
> Which would mean that ultimately if the entire network is made only of nodes restored from snapshots, nobody could sync?

Yes

**Comment by cheme** [comment]
Probably nodes that reply to block query could have a better reputation, so it should be an incentive to also import blocks (we already got a 'export_block' command).

**Comment by cheme** [comment]
Closing it as it is inactive at the time and conflicts with other ongoing effort: https://github.com/paritytech/substrate/pull/8931

**Pull request closed without merging**
