### PR TITLE
Add keccak-512 to host functions.

### PR DESCRIPTION
**Pull request by tomusdrw**
Follow up on https://github.com/paritytech/substrate/pull/7428#discussion_r522146708 (#7428)

Related: https://github.com/w3f/polkadot-spec/issues/307

### CODE REVIEW

**Comment by bkchr** [comment]
The question is, do we really need this?

The problem is that we can not and will never be able to support any kind of random crypto in our host functions and I also don't think we should do this. Because the question is when do we stop with adding new host functions? Why not also keccak_1024? Or something else?

https://github.com/paritytech/substrate/issues/6918 here we had a similar discussion and I had some internal discussion with @folsen about this and we came to the conclusion to not support everything.

**Comment by tomusdrw** [comment]
> The question is, do we really need this?

I only added this for completeness of #7428 cause the code added there is pretty much dead otherwise and it mislead others to think that it's a new host function now (see w3f repo).

> The problem is that we can not and will never be able to support any kind of random crypto in our host functions and I also don't think we should do this.

I fully agree.

> to not support everything.

This specific function is needed for ETH bridge. Either this or `ethash` verification host function, which is even more cumbersome to maintain.

**Comment by drewstone** [comment]
Question, is this likely why extrinsics are so heavy when doing light-client verification of headers? I've been working on a light client here:
- https://github.com/hicommonwealth/substrate-eth-light-client

it works and verifies headers (adapted from rainbow bridge), but the extrinsic is around 0.6 MB and requires bumping a few parameters from the txpool's limits I believe. Would this type of change make the extrinsic less intensive?

**Review by bkchr — APPROVED** [review]

**Review by thiolliere — APPROVED** [review]
considering usage it seems good to me

**Pull request merged**
