### PR TITLE
Tip payment is a different withdraw reason.

### PR DESCRIPTION
**Pull request by gavofyork**
Several subsystems (staking, elections-phragmen) routinely introduce account locks. Though account locks are able to cover only a subset of funds, allowing there to be unlocked funds to do stuff like sending new transactions, often times it's easy to accidentally lock all funds in the account, preventing all further activity until the account is topped up with fresh, unlocked funds.

This introduces a new kind of `WithdrawReason`: `Tip`, which allows us to distinguish between transaction payment that goes primarily to the system `::TransactionPayment` and transaction payment that goes primarily to a validator `::Tip`. By doing this we can allow transactions to draw down on locked funds if all funds are exclusively used for `::TransactionPayment` and not `::Tip`, thereby removing the ability for a validator to recycle funds en masse and theoretically hold locked funds with nothing at stake.

### CODE REVIEW

**Comment by xlc** [comment]
Does it make sense to reuse the Transfer reason for tip payment? in the sense it is transfer fund to validators for additional service.

**Comment by gavofyork** [comment]
Thing is, it's not a straight transfer to validators - it depends on the chain's logic. Some chains might take e.g. 20% of the tip for the treasury.

**Comment by kianenigma** [comment]
at the first glance I can add: 

shouldn't this now update the `lock()` in staking/elections to lock for `reasons::all().except(Tip)`?

**Comment by gavofyork** [comment]
No - Should be `reasons::all().except(TransactionPayment)`

**Comment by kianenigma** [comment]
right about the lock type -- just needs to set those properly (now afaiu all locks are set for `::all()`) and then good to go.

**Pull request merged**
