### PR TITLE
Require `MaxEncodedLen` per default

### LINKED ISSUE #10652: Require `MaxEncodedLen` per default
Many pallets are currently missing `MaxEncodedLen` implementations. All future pallets should have it.   
To make it easier not to miss it, we could either:
- Add an optional `bool` argument to `generate_storage_info` which default to `true`
- Remove `generate_storage_info` and add a `without_storage_info` attribute

What do you favor?  

I personally like the second approach more, since we could then in the future remove both after all pallets have been migrated.

Related https://github.com/paritytech/substrate/issues/8629

### PR DESCRIPTION
**Pull request by ggwpez**
- Adds `without_storage_info` which is required on all Pallets that do not implement `MaxEncodedLen`
- Removes `generate_storage_info` which is applied per default

"inprogress" until I figured out how to create some meaningful `trybuild` test.

Closes #10652  
Related #8629  

Polkadot companion: https://github.com/paritytech/polkadot/pull/4746  
Cumulus companion: https://github.com/paritytech/cumulus/pull/917

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Comment by ggwpez** [comment]
Thanks @kianenigma for the *very* fast review!  
I still want to extend the testing. Seems like the automation bot removed my `inprogress` label…

**Review by shawntabrizi — APPROVED** [review]

**Review by KiChjang — APPROVED** [review]
This is basically flipping the default to generating the full storage info instead of the partial one, which could now cause issues for devs downstream who were not aware of the `MaxEncodedLen` changes required to keep the PoV sizes measurable.

We'll need to properly announce this change in the proper channels so that they are all well-informed, because I can 100% foresee an influx of devs asking why their chains don't compile after updating substrate to the latest monthly version or so.

**Comment by shawntabrizi** [comment]
The Developer Hub team (docs + support) has been notified of this change.

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
