### PR TITLE
Silence alert about large-statement-fetcher

### PR DESCRIPTION
**Pull request by eskimor**
That task is not continuous and behaving exactly as desired.
Fixes: https://github.com/paritytech/polkadot/issues/3786

### CODE REVIEW

**Comment by TriplEight** [comment]
@tomaka Can you confirm pls?

**Review by tomaka — APPROVED** [review]

**Comment by tomaka** [comment]
I'm in favor of removing the rule altogether due to nobody maintaining these exceptions in the list of tasks.

**Review by TriplEight — APPROVED** [review]

**Comment by eskimor** [comment]
> I'm in favor of removing the rule altogether due to nobody maintaining these exceptions in the list of tasks.

I will file a PR doing just that, next time we get an unjustified alert.

**Comment by bkchr** [comment]
Can we not move this file entirely to Polkadot? It just doesn't make any sense to have the Polkadot alerting rules in Substrate repo...

**Comment by eskimor** [comment]
> Can we not move this file entirely to Polkadot? It just doesn't make any sense to have the Polkadot alerting rules in Substrate repo...

I guess so. For now, I just removed the rule completely as suggested by @tomaka , in order to get rid of that 100% Polkadot exception.

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
