### PR TITLE
Bandersnatch VRF

### PR DESCRIPTION
**Pull request by davxy**
This PR introduces a new kind of VRF which uses `bandersnatch-vrfs` backend.

- Primitive codename used within Substrate : `bsnvrf` (→ Bandersnatch-Vrf)
- gated behind `bandernatch-experimental` feature flag

---

The primitive is used by Sassafras (https://github.com/paritytech/substrate/pull/11879).

IMO is worth splitting the sassafras PR in smaller pieces to be more easily reviewable (is already +9K)
so first I propose to introduce this VRF to trim it a bit.

---

### Open points:

1. Key derivation.
  - `sr25519` supports both hard and soft secret key derivation (see [here](https://github.com/davxy/substrate/blob/95c03584245dfbc340ee14ba754566de1765707c/primitives/core/src/sr25519.rs#L474-L479)). While `ecdsa` and `ed25519` support only hard secret key derivation (e.g. see [here](https://github.com/davxy/substrate/blob/95c03584245dfbc340ee14ba754566de1765707c/primitives/core/src/ed25519.rs#L389-L395)). What about bandersnatch?

2. When a first version `bandersnatch-vrfs` crate on crates.io?

3. Missing Ring proof integration. Is not clear if in the end `bandersnatch-vrfs` crate will provide a single `sign` function to get both thin and ring proofs.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2714614

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2714601

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2714603

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2714602

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2716422

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2716420

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2716409

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2716411

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2730084

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2730082

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2730072

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2730068

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2730083

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2730078

**Comment by davxy** [comment]
requires https://github.com/paritytech/substrate/pull/14036

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2783327

**Comment by koute** [comment]
> 2\. To be fair this is  an `ed-on-bls12-381-bandersnatch` with vrf capabilities etc etc. What is an appropriate (**please not verbose**) name synthesizing this primitive capabilities  and that fits well with the rest of the primitives?   (e.g. "schnorr using ristretto -> sr25519)?

Probably incredibly stupid random suggestion: maybe `bb12381`, with the `bb` pronounced as "baby" (one "b" is for bls, other is for "bandersnatch", and the numbers are numbers). Fits a similar pattern as sr25519. (:

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2821255

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2821254

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2872146

**Comment by davxy** [comment]
Because this key type will be used by a consensus protocol, is required to implement all the traits required by session pallet. One of these is `RuntimeAppPublic` which in turn required `RuntimePublic`.

This trait offers some methods requiring access to the keystore: `sign` and `generate_pair`

Was my intention to keep the required host functions to the minimum.

- `generate_pair` should be implemented. Apparently there is nothing we can do. As it is invoked at startup by the session pallet and also from the rpc interface to generate new keys on demand. I've added an host function for this...

- `sign`: this may be useful if we want to sign something from an offchain worker. Currently we don't. Maybe I can just return `None` here?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2873609

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2873610

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2873593

**Pull request closed without merging**
