### PR TITLE
Put some graphics in the README? 

### PR DESCRIPTION
**Pull request by kianenigma**
I didn't do a good job at making the gif, but this is just a proposal. If accepted, I can make a better one or ask Max to help with it, and of course put the gif somewhere in our repo.

### CODE REVIEW

**Comment by kianenigma** [comment]
So let me try and make a better gif before merging.

**Comment by kianenigma** [comment]
changed the gif to something better. A big big though, 4mb. But even around 3mb I got some glitches in it.

**Comment by bkchr** [comment]
4mb is ridiculous huge and it took quite a while to load on my internet connection(probably Github throttles).

**Comment by kianenigma** [comment]
I must find a better gif maker app then.

**Comment by kianenigma** [comment]
1.9mb: 
sub5

1.8mb:
s1

**Comment by kianenigma** [comment]
see them in full screen to see the effects of lower quality. There are some pixel glitches.

**Comment by gnunicorn** [comment]
yeah, didn't quite consider that this means putting a huge binary blob in the repo – thought it was a few 100ks.... If we want it in the (rendered) Readme and can't get the file below 500kb, I'd suggest we move the file off the repo to the website or AWS or something and include it from remote (it is in an html blob anyways).

**Comment by kianenigma** [comment]
I got a new version from Max wich is 477 Kb, is this okay?

**Comment by gnunicorn** [comment]
to me 477kb would be about okay. @bkchr ?

**Comment by bkchr** [comment]
Sounds fair to me as well.

**Pull request merged**
