### PR TITLE
optimize runtime-interface cargo path

### PR DESCRIPTION
**Pull request by honeywest**
optimize cargo sp-state-machine path

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by thiolliere — APPROVED** [review]

**Comment by thiolliere** [comment]
bot merge force

**Comment by thiolliere** [comment]
bot merge force

**Comment by thiolliere** [comment]
I can't merge manually :-/, maybe merge master @honeywest

**Comment by honeywest** [comment]
@thiolliere merge maste
 OK

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
