### PR TITLE
export aura/babe worker

### PR DESCRIPTION
**Pull request by yjhmelody**
Fix a problem about https://github.com/paritytech/substrate/pull/10831

### CODE REVIEW

**Comment by yjhmelody** [comment]
Hi @andresilva  can we export AuraWorker and BabeWorker ?

**Comment by yjhmelody** [comment]
@andresilva Hi，any other problem?

**Comment by bkchr** [comment]
@yjhmelody have you his question? "but does it solve your problem?"

I would say that you don't tested it, because then you would have seen that there is no way that you can instantiate the `BabeSlotWorker`.

**Comment by yjhmelody** [comment]
> @yjhmelody have you his question? "but does it solve your problem?"
> 
> I would say that you don't tested it, because then you would have seen that there is no way that you can instantiate the `BabeSlotWorker`.

I only want to get the `Type`.

**Comment by bkchr** [comment]
If you can not build the `BabeSlotWorker` type, there is no way you can put it into a type.

**Comment by bkchr** [comment]
I created a different proposal for solving your problem @yjhmelody https://github.com/paritytech/substrate/pull/10934

**Comment by yjhmelody** [comment]
https://github.com/paritytech/substrate/pull/10934 may be a better idea.

**Pull request closed without merging**
