### PR TITLE
Key storage proof v2

### PR DESCRIPTION
**Pull request by cheme**
This PR adds light client call as describe in https://github.com/paritytech/substrate/issues/10623 .

I only diverge from proposed spec at https://github.com/w3f/polkadot-spec/issues/590 by renaming `required bytes hash = 1;` in child trie description to `required bytes name = 1; `: so it is the same as the former `storage_key` but without prefixing.

Using child trie root hash sounds like a good idea but is not consistent with specifying a block number in the request.

When writing it I also did wonder if we should allow doing the query on multiple child trie (would be a bit of change in the format but pretty ok).

I also did remove the storage cache from the source (should have been removed already I think).

### CODE REVIEW

**Comment by bkchr** [comment]
> I also did remove the storage cache from the source (should have been removed already I think).

Yes, looks like some bad merge brought it back.

**Comment by cheme** [comment]
not stale.

**Comment by cheme** [comment]
not stale

**Comment by tomaka** [comment]
Opened https://github.com/w3f/PPPs/pull/5

**Comment by cheme** [comment]
Switched to "In Progress", as I will also integrate proposed changes from https://github.com/w3f/PPPs/pull/5 (prefix range query, restart and possibly ordering of keys).

**Comment by cheme** [comment]
Will open a new one with things for https://github.com/w3f/PPPs/pull/5

**Pull request closed without merging**
