### PR TITLE
Make event record easier to decode

### PR DESCRIPTION
**Pull request by thiolliere**
### Breaking change

the struct EventRecord changed the type of its field `event`. It is now a `WrapperOpaque<Event>` which means it is encoded with its encoded length in front, in order to be decodable as `Vec<u8>`.
To be more precise the field event is now encoded as compact encoding of the size in bytes of the encoding of event concatenated with the encoding of event. Instead of previously: encoding of event.
Some rust code can be also breaking, people should update by referencing to the inner type of `WrapperOpaque` using `.0` and some conversion using `.into()`.

### Description

This should fix https://github.com/paritytech/substrate/issues/9480 by making event record easier to decode when some event variant are not decodable.

The event record now wraps the event into a `OpaqueWrapper`, this wrapper implements codec in a way that is compatible with `Vec<u8>`. basically it encode its inner type and prepend the size (the size is encoded as a compact u32).

### TODO

* [x] add test
* [x] companion: https://github.com/paritytech/polkadot/pull/3945

### CODE REVIEW

**Comment by h4x3rotab** [comment]
So happy that the problem is addressed!

**Comment by thiolliere** [comment]
i don't know people opinion about this change, if people like it, then we can go on and notify UI people about this change

**Comment by h4x3rotab** [comment]
It's very welcome on our end (Phala Network), because we extensively rely on events to notify our offchain systems. I think it's also useful for indexers like SubQuery and Subscan.

**Review by ascjones — APPROVED** [review]
This is great, it will save a bunch of code to decode raw events in `subxt`.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
CC @jacogr

**Comment by jacogr** [comment]
So I looked at the issue logged - it refers to types not being available. This is not an issue with metadata v14. So I am trying to understand which current Substrate issue is addressed here.

**Comment by thiolliere** [comment]
@jacogr 
I made an error when implementing type info of WrapperOpaque https://github.com/paritytech/substrate/pull/9881
I merged this PR into this one, so maybe it fix the issue you found.

**Comment by jacogr** [comment]
Since the `WrapperOpaque` is already on master (used in networking), it would actually be great getting it fixed there instead of waiting for this PR. (Which, as I mentioned above, doesn't seem to solve anything anymore...)

**Comment by thiolliere** [comment]
> Since the WrapperOpaque is already on master (and used in networking, i.e. the API has support for it since yesterday), it would actually be great getting it fixed in master instead of waiting for this PR.

Yes the PR is opened here https://github.com/paritytech/substrate/pull/9881

> This PR, as I mentioned above, doesn't seem to solve anything anymore since metadata v14 landed... what it does do it break the whole ecosystem, forget about the apps UI, it affects everybody that listens on events everywhere. And this for a currently non-existent problem with types

I missread your first comment, I don't know it myself, if it doesn't solve anything, then there is no reason to land it, cc @ascjones @h4x3rotab

**Comment by ascjones** [comment]
It's true that now one can use the metadata to parse raw event bytes. e.g. https://github.com/paritytech/substrate-subxt/blob/184c0964ca3a68e411eff6400aa7fabce0973963/src/events.rs#L213.

However adding the `WrapperOpaque` means that this code can be removed entirely, for handling events for which we don't have a static definition.

What's more, it means that for just decoding events, a consumer would not need to consume the metadata at all, if they are just looking for some specific events they can only choose to decode those with custom local types/decoding and skip any others.

**Comment by jacogr** [comment]
You have the realize this break everybody out there, so it is not something to be done employed lightly. For instance all explorers now have different handling when trawling the chain for all events. 

So the best time for a break would be alongside metadata v14 (Not after, that is absolute chaos in the ecosystem). 

So skipping is certainly interesting. 

But the point stands - the reference is for „missing types“, which is now a non-existent issue. If the problem is partial decoding, yes, can see it adds value. (So you make the 0.5% happy and create chaos for all the rest)

**Pull request closed without merging**
