### PR TITLE
Fix issues related to Rust 2018, Macros, and node-template 

### PR DESCRIPTION
**Pull request by shawntabrizi**
This solves an error where node-template does not use `srml-support` as the imported name for the crate, but the macros have a dependency on it.

Additionally, some macros were not updated to use `$crate::` which I have addressed here.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
Solves #1741 and some of https://github.com/paritytech/substrate/issues/1509

**Comment by thiolliere** [comment]
OK so either we use the old way of importing macro and we can rename it in lib.rs or we use the 2018 way and we can't rename it because of srml-support incomplete support of it.

I approve this PR

**Comment by thiolliere** [comment]
Well except CI complains about versionning of runtime and also Serialize Deserialize issue which seems can't be found ?

**Comment by shawntabrizi** [comment]
@thiolliere: @bkchr recommends not to touch the `Contracts` module since there are still some limitations with Rust at the moment. I have rolled back those changes, which should hopefully fix the ci?

**Comment by DarkEld3r** [comment]
I have also updated the `srml-support` crate in #1725.

**Pull request merged**
