### PR TITLE
pallet-identity: Make identity generic

### PR DESCRIPTION
**Pull request by hirschenberger**
related issue paritytech/polkadot-sdk#179 

- [ ] Add companion PRs

### CODE REVIEW

**Comment by KiChjang** [comment]
Is this still WIP? Because as far as I can tell, this PR still hasn't been able to achieve what was described in the issue.

**Comment by hirschenberger** [comment]
Is this the correct approach or did I miss something?

* I'd add a polkadot companion which just maps the `IdentityInfo` type to the existing `IdentityInfo` struct to make it backwards compatible.

* And add a testcase to substrate which tests using a custom IdentityInfo struct.

**Comment by bkchr** [comment]
The introduced `IndentityInfo` isn't used anywhere?

**Comment by KiChjang** [comment]
> So, a IdentityInfo associated type should be added to the Config trait **and everywhere where currently IdentityInfo is being used, should be replaced by T::IdentityInfo.**

Emphasis mine. I don't believe this has been done in the PR?

**Comment by hirschenberger** [comment]
I have a problem with the implementation. I have to crate instances of the `Config::IdentityInfo` associated type. AFAIK it's only possible by introducing a new trait with a constructor that the associated type has to implement.

I assume it's not a breaking change adding that trait and implementing it for the `types::IdentityInfo` struct. 
Is this correct, is this a proper way?

**Comment by ggwpez** [comment]
>I have a problem with the implementation. I have to crate instances of the Config::IdentityInfo associated type. AFAIK it's only possible by introducing a new trait with a constructor that the associated type has to implement.

Where do you have to create the instance? In benchmarks?

**Comment by hirschenberger** [comment]
> > I have a problem with the implementation. I have to crate instances of the Config::IdentityInfo associated type. AFAIK it's only possible by introducing a new trait with a constructor that the associated type has to implement.
> 
> Where do you have to create the instance? In benchmarks?

Yes [here](https://github.com/paritytech/substrate/blob/master/frame/identity/src/benchmarking.rs#L105) for example.

**Comment by ggwpez** [comment]
Proper solution would probably to add some trait to FRAME benchmarking similar to `Arbitrary`, but with the worst-case scenario in mind.  

As hacky solution you can do a `where IdentityInfo: From<u32>` bound on your benchmarks module, but yea we should probably find a better solution.

**Comment by hirschenberger** [comment]
> Proper solution would probably to add some trait to FRAME benchmarking similar to `Arbitrary`, but with the worst-case scenario in mind.
> 
> As hacky solution you can do a `where IdentityInfo: From<u32>` bound on your benchmarks module, but yea we should probably find a better solution.

How about adding a trait like this to frame_benchmarking and implementing it for `IdentityInfo<>`

```rust
trait WorstCase {
    fn worst_case() -> Self;
}
 ```
But the [set_identity](https://github.com/paritytech/substrate/blob/master/frame/identity/src/benchmarking.rs#L133) benchmark is using the additional fields  length as complexity parameter.
Do you have an idea how to implement a generic `WorstCase` trait with respect to complexity parametrization?

**Comment by ggwpez** [comment]
> But the [set_identity](https://github.com/paritytech/substrate/blob/master/frame/identity/src/benchmarking.rs#L133) benchmark is using the additional fields length as complexity parameter.
> Do you have an idea how to implement a generic `WorstCase` trait with respect to complexity parametrization?

Maybe an associated type like:  

```rust
trait WorstCase {
    type Complexity;
    fn worst_case() -> Self;
}
```

The we could do where bounds like `Identity: WorstCase<Complexity=u32>` or something.  
For multi dimensional complexities the benchmarking would require `WorstCase<Complexity=(u32, u32)>`. Hope that is the correct syntax :laughing:

**Pull request closed without merging**
