### PR TITLE
Move `EraIndex` to sp-staking

### PR DESCRIPTION
**Pull request by emostov**
This is needed for the upcoming pools pallet. There is zero logic change.

polkadot companion: https://github.com/paritytech/polkadot/pull/4728

### CODE REVIEW

**Review by kianenigma — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
doesn't build.

**Comment by emostov** [comment]
bot merge

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
