### PR TITLE
Don't return misleading result with PostInfo in proxy-pallet

### LINKED ISSUE #9421: Avoid return DispatchResultWithPostInfo unless it is necessary
https://github.com/paritytech/substrate/blob/5b55e01046cc78e0fd2dec962f73aabce676e8c4/frame/proxy/src/lib.rs#L639-L659

It doesn't make sense to have this return `DispatchResultWithPostInfo` as it doesn't refund weights.

It is misleading to user that it may refund weights, which doesn't make a lot of sense anyway. As a public method it cannot know how the itself is used and cannot return a reasonable value.

Most other `DispatchResultWithPostInfo` in pallet-proxy should also be changed to `DispatchResult`

### PR DESCRIPTION
**Pull request by hirschenberger**
I didn't find any functions which really needs a PostInfo.

also autoformatting two unrelated files

fixes #9421

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@hirschenberger please merge master

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by xlc** [comment]
`Ok(().into())` can be simplified into `Ok(())`

**Comment by hirschenberger** [comment]
> `Ok(().into())` can be simplified into `Ok(())`

Maybe wrong PR?

**Pull request merged**
