### PR TITLE
Sensible locking for staking and council.

### LINKED ISSUE #2950: Allow fee withdraw on locked balance.
srml-council (and potentially other use cases) want to lockup the entire balance of an account for security reasons. This should not prevent them from submitting other transactions, namely to undo the lock. 

> it should be locked except, perhaps, for paying transaction fees.
(that's a specific feature of locking - you can provide a bit mask over what kinds of withdrawals are allowed)

### PR DESCRIPTION
**Pull request by Kianenigma**
closes #2950

### CODE REVIEW

**Comment by gavofyork** [comment]
@Kianenigma doesn't build? or just needs merge with master for the ui fix?

**Comment by gavofyork** [comment]
Icing until #3041 is in.

**Comment by gavofyork** [comment]
@Kianenigma will need resolving

**Comment by Kianenigma** [comment]
Done

**Pull request merged**
