### PR TITLE
Introduce notion of finality to substrate

### PR DESCRIPTION
**Pull request by rphmeier**
Partially addresses https://github.com/paritytech/substrate/issues/746

This rewrites the blockchain DB to handle non-instant finality and chain reorganizations.
Pruning and CHT generation is done after finality now.

### CODE REVIEW

**Comment by rphmeier** [comment]
I am not quite sure how to handle the finality case where we finalize a block that the "best" chain doesn't contain. One solution I had was to prevent indexing by number for non-finalized blocks, but that would probably hamstring the UX a little too much.

**Comment by arkpar** [comment]
I've noticed this changes DB keys for block data to use hashes instead of numbers. Using numbers is quite beneficial for DB performance.  Blocks tend to be requested in groups by number when syncing and it helps a lot when they are located close in the DB. Geth did that optimization a while a go and the improvement was significant. I'd prefer to keep the current design. Additional blocks sharing the same number could be suffixed with an extra index and the suffix would be removed on finalization.

**Comment by arkpar** [comment]
> I am not quite sure how to handle the finality case where we finalize a block that the "best" chain doesn't contain. One solution I had was to prevent indexing by number for non-finalized blocks, but that would probably hamstring the UX a little too much.

The way I see it only the best chain can be finalized. If there's a need to finalize some other chain the best chain should be reorganized to that chain first. I.e. it should become the new best

**Comment by gavofyork** [comment]
"best" here just means longest?

**Comment by arkpar** [comment]
> "best" here just means longest?

Currently yes, although the blockchain backend does not enforce this. The "is_new_best" flag is provided by the client.

**Comment by gavofyork** [comment]
If the finalised leaf is on the non-best-chain, then we'll need to reorg first.

**Comment by rphmeier** [comment]
Doing this correctly depends on #760 -- the logic for handling finality on a block which is not an ancestor of the current best block requires finding the `best_chain_containing(newly_finalized)`.

**Comment by rphmeier** [comment]
I'll add tree-route tests in the follow-up PR

**Pull request merged**
