### PR TITLE
Refactors election provider support benchmarks outside its own crate

### PR DESCRIPTION
**Pull request by gpestana**
The bench bot is having issues with running the `elections-provider-support` benchmarks and updating the `weights.rs` because the current elections provider support benchmark code is a separate crate. 

It seems that bench bot `--output` default is the same as the crate where the benchmarks are implemented.  Since the `--output` cannot be re-written in the bench bot CI, the output folder path is not the correct one.  (*Note: on top of this, the bench bot `EXCLUDE_PALLET` list needs to be updated, which is done in this PR as well*).

This PR removes the need for an separate benchmarking crate for `elections-provider-support`. This way, the dir where the CI bot pushes the weights match that of the expected by the CI bot.

**Expected behaviour**:
The following command works locally as expected (ie. generated `weights.rs` are added under `/frame/election-provider-support/src/weights.rs`) 

```
cargo run --release --features runtime-benchmarks benchmark pallet \
  --execution wasm \
  --wasm-execution compiled \
  --dev --pallet "pallet-elections-provider-support" \
  --extrinsic "*" \
  --steps 2 \
  --repeat 1 \
  --output frame/elections-provider-support/src/weights.rs \
  --template .maintain/frame-weight-template.hbs 
```

[frame/election-provider-support/src/weights.rs](https://github.com/paritytech/substrate/blob/17233c0024b68077c45ed4d5b6ff30f5e22d8ebb/frame/election-provider-support/src/weights.rs) has been updated with the bench bot.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2424726

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2424814

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2424813

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2425024

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2425025

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2425023

**Comment by gpestana** [comment]
bot bench $ pallet dev pallet_election_provider_support

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2425738

**Comment by gpestana** [comment]
bot bench $ pallet dev pallet_election_provider_support

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2425792

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2425791

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2425790

**Comment by gpestana** [comment]
bot bench $ pallet dev pallet_election_provider_support

**Comment by gpestana** [comment]
bot bench $ pallet dev frame_election_provider_support

**Review by ruseinov — APPROVED** [review]
This looks like a good simplification to me.
The only question I have is what was the reason to have this as a separate crate in the first place. Looking at the change set I cannot find any, but maybe the original author could chip in.

**Review by kianenigma — APPROVED** [review]
weight seem to have been submitted now 💯

**Pull request merged**
