### PR TITLE
BlockId removal: refactor: Backend::body

### PR DESCRIPTION
**Pull request by michalkucharczyk**
It changes the arguments of `Backend::body` method from: `BlockId<Block>` to: `&Block::Hash`

This PR is part of BlockId::Number refactoring analysis (paritytech/substrate#11292)

polkadot companion: paritytech/polkadot#6223

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by michalkucharczyk** [comment]
git rebase

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by michalkucharczyk** [comment]
bot merge

**Comment by michalkucharczyk** [comment]
bot merge

**Pull request merged**
