### PR TITLE
Remove multiply_by_rational 

### LINKED ISSUE #11477: Remove `multiply_by_rational`
Everything that uses it should instead be moved to use `multiply_by_rational_with_rounding`. `SignedRounding` should be used whenever inputs/outputs may be negative.

### PR DESCRIPTION
**Pull request by tifecool**
closes #11477

Removed multiply_by_rational and replaced all usages with multiply_by_rational_with_rounding.

### CODE REVIEW

**Comment by tifecool** [comment]
Please review @gavofyork

**Review by kianenigma — COMMENTED** [review]
Looks mostly good to me. Have you run the fuzzer with the new code?

**Comment by tifecool** [comment]
> Looks mostly good to me. Have you run the fuzzer with the new code?

How do I do that?

**Comment by kianenigma** [comment]
> > Have you run the fuzzer with the new code?
> 
> How do I do that?

there are exact instruction in the fuzzer file of multiply_by_rational which you have already altered.

**Comment by tifecool** [comment]
Testing it out now.

**Comment by tifecool** [comment]
> Have you run the fuzzer with the new code?
Getting crashes. Will start debugging

**Comment by tifecool** [comment]
@kianenigma fixed the fuzzer error.

**Review by kianenigma — APPROVED** [review]

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
@tifecool if you want a DOT tip, please include your polkadot address in your PR description.

**Comment by shawntabrizi** [comment]
bot merge

**Comment by tifecool** [comment]
> @tifecool if you want a DOT tip, please include your polkadot address in your PR description.

Added. Thank so much!

Would love to take on more issues and expand my abilities. Please consider me for more issues ❤️

**Pull request merged**
