### PR TITLE
Update to libp2p-0.36

### PR DESCRIPTION
**Pull request by romanb**
This PR updates `libp2p` to `0.36`. The full changelog compared to `0.35.1` [can be seen here](https://github.com/libp2p/rust-libp2p/compare/v0.35.1...v0.36.0). The highlights are:

  * "Parallel negotiation" is re-enabled for `multistream-select` (https://github.com/libp2p/rust-libp2p/pull/1934) and takes effect when the dialer has 3 or more alternative protocols for a particular upgrade. I don't think this case actually ever happens in substrate though, so there should be no surprises.

  * `libp2p-mdns` has undergone a larger refactoring and sends queries much less aggressively (https://github.com/libp2p/rust-libp2p/pull/1977), which should be compensated for by queries sent whenever a multicast group is joined on a network interface. If there should be unforeseen issues, the query interval can now be configured and could be lowered to the previous 20 seconds.

  * There is now a new implementation of the [relay protocol](https://github.com/libp2p/specs/blob/master/relay/README.md), implemented in https://github.com/libp2p/rust-libp2p/pull/1838.

  * `libp2p-dns` now uses the [`trust-dns`](https://github.com/bluejekyll/trust-dns) library (https://github.com/libp2p/rust-libp2p/pull/1927), thereby supporting new features and configuration options as well as removing the previous background thread for performing DNS resolution via [`std::net::ToSocketAddrs`](https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html). This also made it possible to implement support for `/dnsaddr` addresses (https://github.com/libp2p/rust-libp2p/pull/1931).

Given the larger changes to the (M)DNS libraries, a burn-in may be appropriate.

polkadot companion: https://github.com/paritytech/polkadot/pull/2672

### CODE REVIEW

**Comment by tomaka** [comment]
Note: I had to run `cargo update -p data-encoding -p futures:0.3.12 -p winapi:0.2.8 -p futures-lite` to get Polkadot to build.

**Comment by tomaka** [comment]
Also `cargo update -p fs-swap -p winapi:0.2.8`, otherwise you get compilation errors.

**Comment by tomaka** [comment]
Burn-in looks fine.

One thing that is curious is that before this PR we had little peaks to the number of libp2p tasks, presumably because of the periodic Kademlia requests. Now these peaks are gone.

image

The same shows on the number of connections. There are still little peaks of number of connections every 10 minutes, when Kademlia requests trigger, but they are way less pronounced.

Anyway, everything seems to work as intended. I think we need a Polkadot companion PR however.

**Comment by romanb** [comment]
> I think we need a Polkadot companion PR however.

Can we repurpose https://github.com/paritytech/polkadot/pull/2659 to serve as the companion?

**Review by tomaka — APPROVED** [review]

**Comment by tomaka** [comment]
I have no idea who to ask for reviews :upside_down_face:

**Review by eskimor — APPROVED** [review]

**Comment by tomaka** [comment]
The Polkadot companion needs two approvals as well.

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
