### PR TITLE
Weights for Treasury Refactor

### PR DESCRIPTION
**Pull request by shawntabrizi**
This is a PR to get the weights for the treasury refactor.

### CODE REVIEW

**Comment by thiolliere** [comment]
this PR also contains the Treasury/Bounty split. What is the purpose of the PR to be merged on the WIP branch or on master as a complete Treasury/Bounty split ?

**Comment by shawntabrizi** [comment]
@thiolliere sorry! i just opened this PR for doing weights. The real PR to be reviewed is: https://github.com/paritytech/substrate/pull/7536

**Pull request closed without merging**
