### PR TITLE
.maintain/monitoring: Add alert when continuous task ends

### PR DESCRIPTION
**Pull request by mxinden**
Through the `polkadot_tasks_ended_total` Prometheus metric one can tell
when a task ended. Use this metric to alert when specific
known-to-be-continuous tasks end on a node.

This would catch bugs like https://github.com/paritytech/substrate/pull/7000/#discussion_r498387783.

### CODE REVIEW

**Comment by tomaka** [comment]
I'm not such a fan of hard-coding the task names here. Someone will unavoidably add a new task and forget to update this list.

What do you think of `(polkadot_tasks_spawned_total == 1) - (polkadot_tasks_ended_total == 1)`?
This should detect tasks that have been started exactly once and have ended exactly once.
The 3 minutes should ensure that the alert isn't accidentally triggered at the node initialization.

**Comment by tomaka** [comment]
> (polkadot_tasks_spawned_total) == 1) - (polkadot_tasks_ended_total == 1)?

I'm not actually sure that this works.
I've checked that `(avg(polkadot_tasks_spawned_total) by (task_name) == 1) - (avg(polkadot_tasks_ended_total) by (task_name) == 1)` does work for a group of instances, but if I understand correctly these alerts work on individual instances.

**Comment by tomaka** [comment]
`(polkadot_tasks_spawned_total == 1) - on(instance, task_name) (polkadot_tasks_ended_total == 1)` should work

**Comment by mxinden** [comment]
> `(polkadot_tasks_spawned_total == 1) - on(instance, task_name) (polkadot_tasks_ended_total == 1)` should work

Good idea. I just hope no one spawns a singleton task at startup for some setup work. I guess we will find out.

Adjusted. Mind taking another look @tomaka?

**Review by tomaka — APPROVED** [review]

**Comment by tomaka** [comment]
bot merge

**Pull request merged**
