### PR TITLE
Cherry Pick of PR #9676 + #9391

### PR DESCRIPTION
**Pull request by chevdor**
This PR cherry picks the following PRs into the `polkadot-v0.9.10` branch for the `0.9.10` release:
- #9676 (dd297887c) 
- #9391 

It contains what #9707 did, making #9707 no longer required.

### CODE REVIEW

**Comment by chevdor** [comment]
The last commit is to prevent having to merge #9541 as well. There will be not need to backport since #9541 removes the crate entirely.

**Review by adoerr — APPROVED** [review]

**Comment by chevdor** [comment]
bot merge

**Comment by chevdor** [comment]
bot merge

**Review by bkchr — APPROVED** [review]

**Comment by chevdor** [comment]
bot merge

**Pull request merged**
