### PR TITLE
Minor edits 🖊️ 

### PR DESCRIPTION
**Pull request by sacha-l**
Minor edits addressing slight changes in syntax and typos.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@sacha-l you need to merge master

**Review by shawntabrizi — APPROVED** [review]

**Comment by sacha-l** [comment]
> @sacha-l you need to merge master

I don't have write access. Can you merge please?

**Review by athei — CHANGES_REQUESTED** [review]

**Comment by bkchr** [comment]
> > @sacha-l you need to merge master
> 
> I don't have write access. Can you merge please?

You need to merge master into your branch, not merge this pr into master.

**Comment by kianenigma** [comment]
ping @sacha-l

**Comment by sacha-l** [comment]
> ping @sacha-l

Having issues with GitKraken. One sec.

**Comment by sacha-l** [comment]
Replaced by #8396

**Pull request closed without merging**
