### PR TITLE
bump a bunch of deps in parity-common

### PR DESCRIPTION
**Pull request by ordian**
I'm not sure if db in utils/browser is needed at all, but did a minimal change. `kvdb-web` is decommissioned now.

polkadot companion: https://github.com/paritytech/polkadot/pull/3402

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by ordian** [comment]
oh, the companion is not gonna work because of beefy :facepalm:

**Review by Xanewok — APPROVED** [review]

**Review by tomaka — APPROVED** [review]
Ah yeah I remember wanting this update a couple years ago because of `kvdb-web` :sweat_smile:

**Comment by ordian** [comment]
@tomaka any idea why browser tests are failing?

**Comment by ordian** [comment]
@Xanewok would appreciate with https://gitlab.parity.io/parity/substrate/-/jobs/997446

**Comment by tomaka** [comment]
> @tomaka any idea why browser tests are failing?

No, maybe @expenses by any chance?

**Comment by Xanewok** [comment]
> @Xanewok would appreciate help with https://gitlab.parity.io/parity/substrate/-/jobs/997446

@ordian Can you try updating to primitive-types to `=0.10.0`, first? The patch has a new scale codec update which will make it harder to land (if possible) without https://github.com/paritytech/substrate/pull/9163.

**Comment by ordian** [comment]
bot merge

**Pull request merged**
