### PR TITLE
WIP: new nightly srml int test job

### PR DESCRIPTION
**Pull request by TriplEight**
https://github.com/paritytech/srml-contracts-waterfall
Integration tests for srml-contracts.
So the idea is that they would be coded in JS and they would speak with a running node in background
The node would be a default node.
The rest is simple actually. Some rust (nightly most likely also some stable) code, potentially some AssemblyScript
So more precisely something like this:
- submodule update
- building all ink contracts (requires nightly rustc)
- doing yarn (= some npm/js magic)
- downloading a substrate-node
- spinning it up in background exposing RPC interface locally
```
./target/release/substrate purge-chain --dev -y && ./target/release/substrate --dev
```
- then running yarn start, which uses the local RPC

### CODE REVIEW

**Comment by bkchr** [comment]
@TriplEight can this be closed?

**Comment by bkchr** [comment]
?

**Comment by TriplEight** [comment]
> ?

no, it's still WIP. @pepyakin asked me to do this.

**Comment by pepyakin** [comment]
oh, interesting. I assumed that this would be implemented as CI for https://github.com/paritytech/srml-contracts-waterfall, not in substrate.

**Pull request closed without merging**
