### PR TITLE
contracts: Expose environment types for offchain tooling

### PR DESCRIPTION
**Pull request by athei**
In order to implement https://github.com/paritytech/cargo-contract/issues/1167 we need to expose all types passed between `pallet-contracts` and the deployed contracts. The idea is to bundle all relevant types in an `Environment` struct mirroring  the ink! [`Environment`](https://docs.rs/ink_env/4.2.1/ink_env/trait.Environment.html) type. In order to expose it we add it to the config trait as `Get<Environment>`. The types are obviously only mentioned as `PhantomData` because we don't ever want to construct them. I did just this in this PR.

I think this would be an elegant solution if it wouldn't be for https://github.com/paritytech/scale-info/pull/111. @ascjones Can we maybe add an attribute to `scale-info` that allows to opt-in to `PhantomData` types?

cc @SkymanOne 

cumulus companion: https://github.com/paritytech/cumulus/pull/3036

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3362862

**Review by ascjones — COMMENTED** [review]
You could use a wrapper type e.g.:

```rust
#[derive(TypeInfo)]
struct EnvironmentType<T>(PhantomData<T>)

pub struct Environment<T: Config> {
	account_id: EnvironmentType<AccountIdOf<T>>,
```

**Comment by athei** [comment]
Hmm yes that could work. This whole solution seems a bit hacky. Even without the wrapper type. But I guess our only way to get this in without introducing a whole new way of just expressing types into the metadata.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3392558

**Comment by athei** [comment]
Implemented your idea. Seems to work. This is the output. I think we can work with that:
```json
{
  "id": 576,
  "type": {
    "path": [
      "pallet_contracts",
      "Environment"
    ],
    "params": [
      {
        "name": "T",
        "type": null
      }
    ],
    "def": {
      "composite": {
        "fields": [
          {
            "name": "account_id",
            "type": 577,
            "typeName": "EnvironmentType<AccountIdOf<T>>"
          },
          {
            "name": "balance",
            "type": 578,
            "typeName": "EnvironmentType<BalanceOf<T>>"
          },
          {
            "name": "hash",
            "type": 579,
            "typeName": "EnvironmentType<<T as frame_system::Config>::Hash>"
          },
          {
            "name": "hasher",
            "type": 580,
            "typeName": "EnvironmentType<<T as frame_system::Config>::Hashing>"
          },
          {
            "name": "timestamp",
            "type": 582,
            "typeName": "EnvironmentType<MomentOf<T>>"
          },
          {
            "name": "block_number",
            "type": 583,
            "typeName": "EnvironmentType<BlockNumberFor<T>>"
          }
        ]
      }
    }
  }
},
{
  "id": 577,
  "type": {
    "path": [
      "pallet_contracts",
      "EnvironmentType"
    ],
    "params": [
      {
        "name": "T",
        "type": 0
      }
    ],
    "def": {
      "composite": {}
    }
  }
},
{
  "id": 578,
  "type": {
    "path": [
      "pallet_contracts",
      "EnvironmentType"
    ],
    "params": [
      {
        "name": "T",
        "type": 6
      }
    ],
    "def": {
      "composite": {}
    }
  }
},
{
  "id": 579,
  "type": {
    "path": [
      "pallet_contracts",
      "EnvironmentType"
    ],
    "params": [
      {
        "name": "T",
        "type": 12
      }
    ],
    "def": {
      "composite": {}
    }
  }
},
{
  "id": 580,
  "type": {
    "path": [
      "pallet_contracts",
      "EnvironmentType"
    ],
    "params": [
      {
        "name": "T",
        "type": 581
      }
    ],
    "def": {
      "composite": {}
    }
  }
},
```

**Review by ascjones — APPROVED** [review]

**Review by SkymanOne — APPROVED** [review]
Yes, we can definitely work with this

**Comment by athei** [comment]
bot rebase

**Comment by athei** [comment]
Please also approve the companion.

**Comment by athei** [comment]
bot rebase

**Comment by athei** [comment]
bot merge

**Pull request merged**
