### PR TITLE
Update ss58 registry for Phala network

### PR DESCRIPTION
**Pull request by LusWar**

### CODE REVIEW

**Comment by LusWar** [comment]
Update ss58 registry for Phala network

**Review by bkchr — APPROVED** [review]

**Review by joepetrowski — APPROVED** [review]

**Comment by bkchr** [comment]
@LusWar please merge master to make CI happy. TY!

**Comment by LusWar** [comment]
> @LusWar please merge master to make CI happy. TY!

ok

**Comment by bkchr** [comment]
You have done something wrong when merging master

**Comment by LusWar** [comment]
> You have done something wrong when merging master

I‘ve rebased

**Pull request merged**
