### PR TITLE
Add MaxUsers Hint to Runtime for Map Depth

### PR DESCRIPTION
**Pull request by shawntabrizi**

### CODE REVIEW

**Comment by kianenigma** [comment]
what about a MaxAccounts in systems, and reading from that?

**Comment by shawntabrizi** [comment]
> what about a MaxAccounts in systems, and reading from that?

I was thinking that rather than program that into the pallet, if a user wanted to, they can simply copy the same config to each of the pallets below.

I can imagine some different value is actually used for different kinds of chains.

**Review by kianenigma — APPROVED** [review]
Code is correct, and I agree with `MaxUsers` in assets but for balances I think this constant should come from either `frame_system`, or through `type AccountStore`. balances is not really capable of storing account balances itself, not sure why it should dictate its upper bound?

**Comment by kianenigma** [comment]
>  I can imagine some different value is actually used for different kinds of chains.

Sure, then they can eacu define a different `Type MaxAccounts = ConstU32<x>` to their config. 

I think I didn't really understand your response, can you elaborate more? 

---

A bit more about my opinion: I don't like this because it seems to me like this change is intended to represented the total number of accounts (recent discussion about re-benchmarking with higher assumptions). But the balances pallet is not even in charge of keeping its account in storage. Given this fact, I think the same config should be added to the system pallet. 

For example, I can foresee: 

1. `frame_system` having `MaxAccount`, which should represent the upper bound of all account. 
2. `pallet-staking` having `MaxStakers` which should represent the upper bound of all stakers. 
3. `pallet-assets` having a `MaxUsers`, which should sensible always be a subset of `frame_system::MaxAccounts`.

**Review by thiolliere — APPROVED** [review]

**Comment by kianenigma** [comment]
@shawntabrizi should merge this.

**Pull request closed without merging**
