### PR TITLE
Allow `transfer_keep_alive` to transfer all free balance

### PR DESCRIPTION
**Pull request by thiolliere**
Fix https://github.com/paritytech/substrate/issues/6059

right now transfer with `KeepAlive` requirement fails when the sender free balance goes below ED. Instead we should check that the sender is still alive, i.e. its total balance is above ED.

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]
seems sensible to me

**Review by kianenigma — APPROVED** [review]
I wonder the original author (whoever and whenever that was) might have made the assumption that only the free balance counts for account existence? 

But even so, that seems wrong. Reserved balance is still yours and should be counted for account existance, thus approved.

**Comment by shawntabrizi** [comment]
> I wonder the original author (whoever and whenever that was) might have made the assumption that only the free balance counts for account existence?

Id be pretty pissed if I had a ton of reserved funds and my account was cleaned up...

Yeah, that def seems like it was not the intention.

**Comment by thiolliere** [comment]
bot merge

**Pull request merged**
