### PR TITLE
Get rid of unnecessary use of `async-std` in non-test code

### PR DESCRIPTION
**Pull request by koute**
No real point in using both `async-std` and `tokio`, especially considering that `async-std` is essentially dead at this point.

(This doesn't completely rip out `async-std` from the dependency tree; it's still used transitively by `libp2p` and by a few of the tests.)

### CODE REVIEW

**Comment by koute** [comment]
Looks like `libp2p` supports `tokio`, it's just its `async-std` feature is enabled by default, so it seems we could easily get rid of `async-std` completely from the whole dependency tree. @tomaka Do you perhaps know why `async-std` is the default for `libp2p` instead of `tokio`?

**Comment by wigy-opensource-developer** [comment]
It is "just" a matter of replacing `TcpListener` with `TokioTcpListener` in the transport made in `sc-network`. And maybe turn off some default features in libp2p. The questions still remain:

- Is tokio faster than async-std?
- Do you save cycles by removing some adapters here and there?
- Why Tomaka preferred async-std in the first place?

**Review by bkchr — APPROVED** [review]

**Comment by davxy** [comment]
IMO, because of its global execution context, async-std is a little bit easier to use (and harder to misuse)

I've found some motivations here https://github.com/libp2p/rust-libp2p/issues/1318

**Comment by koute** [comment]
>     * Is tokio faster than async-std?

Performance should be comparable, although I wouldn't be surprised if `tokio`'s faster now ([there were some more performance improvements in 0.16 and 0.17](https://github.com/tokio-rs/tokio/blob/master/tokio/CHANGELOG.md)). The most significant reason as to why we should just purge `async-std` is that `tokio`'s what the vast majority of the Rust's ecosystem supports, and is actually well supported and maintained (e.g. AWS has hired `tokio`'s maintainers) while `async-std`'s essentially dead.

**Comment by bkchr** [comment]
We are bound to Tokio already anyway with the current code. This is nothing that can not be changed, but there was also no real need to change this in 3 years. Tokio is also one of the projects that is in the Rust ecosystem for quite some time and it will probably not leave it that fast ;)

**Comment by wigy-opensource-developer** [comment]
Well, it is sad to see async-std losing momentum. Quite some Protocol Labs folks worked on it. I agree that tokio got quite mature, still it is too complex as an executor to be chosen for all Rust projects out there.

**Review by wigy-opensource-developer — APPROVED** [review]
I really like long red stripes on diffs. 117 lines less, a few hundred thousand to go. :wink:

**Comment by koute** [comment]
bot merge

**Pull request merged**
