### PR TITLE
Network sync refactoring (part 3)

### PR DESCRIPTION
**Pull request by nazar-pc**
This is the third step towards #8686.

As https://github.com/paritytech/substrate/issues/8686#issuecomment-1045993814 suggests, this moves `light.v1` proto scheme and a bunch of data structures related to sync into new `sc-network-light` crate, which `sc-network` now depends on.

As in [previous PR](https://github.com/paritytech/substrate/pull/11322) this is an implementation detail of `sc-network` for now.

A few minor changes, mostly just moving files around.

Polkadot address: 1vSxzbyz2cJREAuVWjhXUT1ds8vBzoxn2w4asNpusQKwjJd

### CODE REVIEW

**Review by arkpar — APPROVED** [review]

**Comment by nazar-pc** [comment]
@bkchr friendly ping here before there are merge conflicts

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
Ty @nazar-pc :) If you provide your polkadot address, I will call the bot again.

**Comment by bkchr** [comment]
bot merge

**Comment by nazar-pc** [comment]
> If you provide your polkadot address, I will call the bot again.

Done, thanks!

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
