### PR TITLE
Add `input_data` to `Event::Called` and `Event::Instantiated`

### PR DESCRIPTION
**Pull request by eval-exec**
This PR add input_data to `Event::Called` and `Event::Instantiated`, close #13895

Update: I think this PR is ready for review @athei :smile:

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2683396

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2683382

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2683381

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2829405

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2829406

**Comment by pgherveou** [comment]
I don't think this PR addresses the point raised by @athei  here

> The tricky part is that we don't limit the maximum amount of input data right now. So order for this to be safe we need to charge a weight for every contract interaction that is based on the size of the input data. This weight will probably be larger that what benchmarks indicate because of the memory allocation implications of emitting big events. Otherwise this could probably be abused to provoke an OOM.

See also this thread on storing unbounded data input https://substrate.stackexchange.com/a/4455

**Pull request closed without merging**
