### PR TITLE
docs: Extends #999. Remove disused package readmes. Rename to sr-metadata. Fix Readme Rustdoc names

### PR DESCRIPTION
**Pull request by ltfschoen**
* Remove disused package readmes (including those incorrectly introduced by #999.

* Remove `tag::description[]` from module comments in lib.rs files of packages when no associated Readme file

* Add module comment to SRML balances package lib.rs

* Rename srml/contract/COMPLEXITY.md to srml/contract/README.md

* Remove old links to CODE_OF_CONDUCT.adoc and CONTRIBUTING.adoc from the Readme (since we now have sections for each one in the Readme)

* Merge latest from master

* Rename substrate-metadata to sr-metadata, since it is in the "srml" subdirectory
    
* Change example to use package name that opens all packages in RustDocs
    
* Fix list of packages names that are available to open in RustDocs

### CODE REVIEW

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by ltfschoen** [comment]
[clabot:check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by gavofyork** [comment]
needs resolving

**Comment by ltfschoen** [comment]
I've fixed the merge conflicts

**Pull request merged**
