### PR TITLE
*/Cargo.toml: Remove unused dependencies

### PR DESCRIPTION
**Pull request by mxinden**
Using cargo-udeps to detect unused dependencies.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
You need to merge master

**Comment by mxinden** [comment]
bot merge

**Comment by mxinden** [comment]
> Merge failed: "At least 2 approving reviews are required by reviewers with write access."

Could someone else give this pull request a review as well?

**Review by wheresaddie — APPROVED** [review]
thanks for the pr @mxinden

**Pull request merged**
