### PR TITLE
[ci] Activate stale bot

### PR DESCRIPTION
**Pull request by gnunicorn**
Let's activate [the stale bot](https://github.com/paritytech/parity-processbot/issues/216#issuecomment-870841449)!

[ci skip]

### CODE REVIEW

**Review by kirushik — APPROVED** [review]

**Review by TriplEight — APPROVED** [review]

**Comment by tomaka** [comment]
Wait, will this simply close all the issues that have been using to track all the known flaws in our code over the past years?

**Comment by tomaka** [comment]
For what it's worth, all 66 issues in the "Networking" category are well-triaged and maintained and are all still relevant. I'd prefer not having to write a comment in 66 issues every 15 days.

**Comment by gnunicorn** [comment]
@tomaka you are welcome to add other tags to be exempted from the process... e.g. `I9-release 🏷` and `I9-meta 📦`... or any other that might be added to maintain this...

**Comment by shawntabrizi** [comment]
@gnunicorn I get this being applied to PRs, but why issues?

How else are we supposed to track long term work?

**Pull request merged**
