### PR TITLE
Ensure transactional with ? works in frame v2

### PR DESCRIPTION
**Pull request by thiolliere**
actually I'm not sure it is needed to test for it as transactional macro is independant from frame v2, but anyway having it in the test might be better to show usage

cc @apopiak 

EDIT: this comes from my missunderstood of Apopiak message, sorry

### CODE REVIEW

**Review by apopiak — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by xlc** [comment]
The underlying issue is fixed with https://github.com/paritytech/substrate/pull/7301

**Comment by thiolliere** [comment]
Yes but considering `set_value` never fails, I think the tests weren't actually triggering the early return `?`

**Comment by xlc** [comment]
The original issue was that the code won't compile if `?` is used and that's what the test in #7301 about.

**Comment by thiolliere** [comment]
ah indeed I see why it wouldn't compile

**Pull request merged**
