### PR TITLE
BREAKING: Rename Origin

### PR DESCRIPTION
**Pull request by Szegoo**
Renames `Origin` to `RuntimeOrigin`

polkadot companion: https://github.com/paritytech/polkadot/pull/6020
cumulus companion: https://github.com/paritytech/cumulus/pull/1628

#11736

### CODE REVIEW

**Review by kianenigma — COMMENTED** [review]
I think we have a few places where we have `type OverarchingCall = ..`. These should also be renamed to `RuntimeCall` I presume?

**Review by kianenigma — APPROVED** [review]
If we are to move forward, we should probably merge this sooner rather than later so there is one version that breaks a lot of things downstream, rather than two.

**Comment by Szegoo** [comment]
> I think we have a few places where we have `type OverarchingCall = ..`. These should also be renamed to `RuntimeCall` I presume? 

I assume this should be done in a separate PR. I will do that.

**Comment by Szegoo** [comment]
@kianenigma I don't think `OverarchingCall` is something we can rename since the `SendTransactionTypes` trait is implemented to types that already define the `RuntimeCall` type associated type. This causes an error.

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
@Szegoo please feel free to add your polkadot address for a tip :)

**Comment by Szegoo** [comment]
> @Szegoo please feel free to add your polkadot address for a tip :)

I have added my address, thanks :)

**Pull request merged**
