### PR TITLE
Support synching of blocks that are not `new_best`

### PR DESCRIPTION
**Pull request by bkchr**
When running a Parachain all collators will produce blocks that are not yet the new best block at import. They are not the new best, because it depends on the relay chain which block will be included. Collators also do not announce these blocks directly and wait instead to receive a candidate message. The candidate message means that the block will be included very likely into the relay chain. On receiving the candidate message for a block build by a collator, the collator starts to announce this message. Other clients receive this message, but the block is not tagged as new best block and thus, they don't request it. But we need to sync these blocks to build the next PoVBlock.

This pr changes the block announce validation in such a way that the custom block announcement validator can tell the sync code if this is a new best block and that we need to sync it.

### CODE REVIEW

**Comment by arkpar** [comment]
Looks good. Needs some testing on the network, including doing a full sync.

**Comment by gavofyork** [comment]
@ddorgan did you see the burn-in request?

**Comment by ddorgan** [comment]
@gavofyork it was already deployed to two hosts at 00:05 today, see chat.

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
