### PR TITLE
Migrate pallet-babe to pallet attribute macro.

### PR DESCRIPTION
**Pull request by shaunxw**
Part of #7882.

Converts the `Babe` pallet to the new pallet attribute macro introduced in #6877.

Following the upgrade guidelines here: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines.

## ⚠️ Breaking Change ⚠️ 

From https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

> storages now use PalletInfo for module_prefix instead of the one given to decl_storage: Thus any use of this pallet in construct_runtime! should be careful to update name in order not to break storage or to upgrade storage (moreover for instantiable pallet). If pallet is published, make sure to warn about this breaking change.

So users of the `Babe` pallet must be careful about the name they used in `construct_runtime!`. Hence the `runtime-migration` label, which might not be needed depending on the configuration of the `Babe` pallet.

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]
looks good to me, polkadot and kusama use Babe for the name of the pallet, thus no migration needed

**Review by ascjones — APPROVED** [review]
LGTM

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge

**Comment by shawntabrizi** [comment]
bot merge force

**Comment by shawntabrizi** [comment]
bot merge

**Pull request merged**
