### PR TITLE
Release `pallet-contracts-primitives`

### PR DESCRIPTION
**Pull request by athei**
This crate is needed in order to release `cargo contract` to crates.io.  I used `cargo unleash` to determine which crates need a bump. I will also use `cargo unleash` to release those crates once this PR is merged. I used `cargo edit` to help with bumping version numbers. I think `cargo unleash` can't do it. I also opted to bump the major version of any crate that yielded build errors as I can't determine the nature of each change.

Please note that I am not releasing the whole dependency graph of `pallet-contracts-primitives` but merely the crates which introduced compile breakage when not bumped.

This is what I did and also the list of packages which will be released as soon as this is merged:

```
cargo set-version --bump major -p pallet-contracts-primitives
cargo set-version --bump major -p sp-core
cargo set-version --bump major -p sp-runtime-interface
cargo set-version --bump major -p sp-wasm-interface
cargo set-version --bump major -p sp-runtime
cargo set-version --bump major -p sp-storage
cargo set-version --bump major -p sp-rpc
cargo set-version --bump major -p sp-io
cargo set-version --bump major -p sp-trie
cargo set-version -p sp-state-machine  -- 0.11.0
cargo set-version -p sp-externalities  -- 0.11.0
cargo set-version -p sp-keystore -- 0.11.0
cargo set-version --bump major -p sp-application-crypto

cargo unleash em-dragons --dry-run \
	-p \
	pallet-contracts-primitives \
	sp-core \
	sp-runtime-interface \
	sp-wasm-interface \
	sp-runtime \
	sp-storage \
	sp-rpc \
	sp-io \
	sp-trie \
	sp-state-machine \
	sp-externalities \
	sp-keystore \
	sp-application-crypto
```

### CODE REVIEW

**Review by ascjones — APPROVED** [review]
LGTM

**Comment by drahnr** [comment]
Relevant issue in `cargo-unleash` is https://github.com/paritytech/cargo-unleash/issues/65 - it's a non-trivial problem though.

**Review by dvdplm — APPROVED** [review]

**Comment by athei** [comment]
This needs a companion, right?

**Comment by athei** [comment]
I don't get why the polkadot CI job fails. Polkadot uses those dependencies without any version.

**Pull request merged**
