### PR TITLE
Expose more modules as public

### PR DESCRIPTION
**Pull request by drewstone**
We are looking to add our own networking/gossip implementations for external networking programs and need these exposed.

### CODE REVIEW

**Comment by bkchr** [comment]
Can you please explain for what exactly you need this? Polkadot has its own protocols and gossip and doesn't need any of this.

**Comment by drewstone** [comment]
@bkchr we're trying to implement our own custom gossiping protocol using the same `Network` struct passed into other methods, primarily to leverage the same peer set and allow these peers to gossip and exchange messages not immediately related to the consensus protocol.

At the moment we are leveraging the `GossipEngine` in a similar way to BEEFY, but we have been recommended now by @tomaka that we do not want to rely on `sc-network-gossip`. Instead, we should rely entirely on `sc-network`. We've been unable to get our questions answered on Substrate's stack exchange so we've investigated and decided this route might be best. Nonetheless, if anyone from Parity is available to discuss the advice would be tremendously helpful.

Let me know if this is pointing in the right direction, we'd really like to not need a fork of Substrate to efficiently build out our protocol.

**Comment by drewstone** [comment]
@bkchr any update on this?

**Comment by tomaka** [comment]
There is no need to expose more modules. Everything you need is already publicly exposed.

**Comment by drewstone** [comment]
@tomaka don't we need access to the `service::NetworkService` which is not publicly exposed to build our own sending/receiving interface for messages?

**Comment by tomaka** [comment]
Almost everything is re-exported from `lib.rs`: https://docs.substrate.io/rustdocs/latest/sc_network/index.html

**Comment by bkchr** [comment]
> There is no need to expose more modules. Everything you need is already publicly exposed.

That is already what I had expected.

**Pull request closed without merging**
