### PR TITLE
Revert "Add log rotation (#6564)"

### PR DESCRIPTION
**Pull request by bkchr**
This reverts commit 802a0d0b0ade796a3b2d4663212518315923fe8a.

polkadot-companion: https://github.com/paritytech/polkadot/pull/1389

### CODE REVIEW

**Comment by tomaka** [comment]
I believe you need a Polkadot companion.

**Comment by bkchr** [comment]
Yeah, working on this

**Comment by tomaka** [comment]
cc https://github.com/paritytech/substrate/pull/6564

The context of this PR is that logging `sub-libp2p` doesn't work anymore, and `sub_libp2p` neither.
If we do it, switching to `flexilogger` should be more thought out.

**Comment by bkchr** [comment]
Yeah, ty for writing what I should have done.

Not sure why `flex-logger` does not support dashes, but this is clearly a no go, because we have multiple places of `target`'s with dashes in the source code.

**Comment by pscott** [comment]
So flexinogger does not support “dashes”, but I believe swapoing dashes with underscore works.
Please see https://github.com/paritytech/substrate/pull/6608

This is ready to merge review, I was just waiting yesterday to know whether we should error when init_logger fails or not :)

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
