### PR TITLE
fix wasm executor compile error

### PR DESCRIPTION
**Pull request by woodsmur**

### CODE REVIEW

**Comment by pepyakin** [comment]
This actually very weird! We don't invoke `rust-lld` explicitly in any way and it should be an implementation details of the rust toolchain, so rustup should include lld and all libraries as part of the installation. And as far as I can tell, no additional installation steps are required for macOS and Linux environments.

Can you tell me more about your environment? Maybe it is Have you tried to reinstall rust?

**Comment by woodsmur** [comment]
I'm just using the [comics vagrant box](https://app.vagrantup.com/ubuntu/boxes/cosmic64).

**Comment by pepyakin** [comment]
Ok, this is surfaced [with the latest nightly](https://github.com/rust-lang/rust/issues/53813). Seems like a transient issue.

**Comment by pepyakin** [comment]
Should be fixed in the next nightly.

**Pull request merged**
