### PR TITLE
Add TypeInfo

### PR DESCRIPTION
**Pull request by zjb0807**
Please backport this to v0.9.11 branch.

### CODE REVIEW

**Comment by bkchr** [comment]
@ascjones I think we should probably skip the "outer" type info and just pretend that this is a `BTreeSet`?

**Comment by ascjones** [comment]
No this is fine, it's idiomatic for wrapper types to derive `TypeInfo`, even if they just wrap a single encodable field.

**Comment by bkchr** [comment]
bot merge

**Comment by bkchr** [comment]
DOne

**Pull request merged**
