### PR TITLE
Refactor service tests in `sc-network`

### PR DESCRIPTION
**Pull request by altonen**
Create a separate directory for the tests and move common network instantion related code to `mod.rs` from where it can be used by both service and chainsync tests.

Use the builder pattern when creating the `TestNetwork` object to reduce code duplication between the test files.

These changes are introduced in a separate PR in order to prevent cluttering future PRs with too many testing-related changes.

### CODE REVIEW

**Comment by altonen** [comment]
ping @bkchr

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> ping @bkchr

Sorry for the delay!

**Comment by altonen** [comment]
bot rebase

**Comment by altonen** [comment]
bot merge

**Pull request merged**
