### PR TITLE
[RFC] BEEFY: add support for slashing validators voting on non-finalized forks

### PR DESCRIPTION
**Pull request by acatangiu**
## Description

BEEFY voters should only vote on GRANDPA finalized blocks - vote only on canonic chain/fork.

Votes on blocks from different forks should (automatically) lead to stake slashing (more aggressive slashing than GRANDPA equivocations, since this scenario is intentionally dishonest).

We should add client/voter detection of such misbehavior as well as runtime logic for reporting proofs of misbehavior and subsequent slashing consequences.

### Runtime side (TODO)

- add new `pallet::call` to `pallet_beefy` similar to [report_equivocation](https://github.com/paritytech/substrate/blob/dfd82860feb5da6f74ca2aa04414d9cebe310204/frame/beefy/src/lib.rs#L207) that takes `InvalidPayloadProof` 
- hook `pallet_beefy_mmr` to `pallet_beefy::EquivocationReportSystem` to be able to verify `InvalidPayloadProof`:
  - verify inner GrandpaProof to make sure the current chain fork is finalized at least up to offending vote height,
  - verify `offending_vote.mmr_root` != on-chain `mmr_root` (combined with above, it proves what we need)
- report offense to staking so offending vote author gets slashed

### Client-side

- add "fisherman" capabilities to voter gossip - on detecting votes for historical forks, it builds the required proof of misbehavior and submits report.

Fixes https://github.com/paritytech/substrate/issues/14505

Polkadot companion TODO

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3132088

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3132087

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3132089

**Comment by acatangiu** [comment]
@andresilva please have a look and validate the proposed approach

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3227137

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3271904

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3323676

**Pull request closed without merging**
