### PR TITLE
frame: GenesisBuild::build allowed in no_std

### PR DESCRIPTION
**Pull request by michalkucharczyk**
`GenesisBuild::build` function will be required for no_std in no native runtime world.

`GenesisBuild::build` macro generated function allows to build the runtime `GenesisConfig` assembled from all pallets' `GenesisConfig`s. `build` for runtime will be implemented in follow-up.

Step towards: paritytech/polkadot-sdk#25

polkadot companion: paritytech/polkadot#7271
cumulus companion: paritytech/cumulus#2624

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2807783

**Review by bkchr — CHANGES_REQUESTED** [review]
I'm not sure we should already do this? I mean we can probably get rid off this trait entirely when we just write all genesis values to the state and on the node side, after calling the runtime api, taking the `OverlayedChanges` to fetch all the state changes. Then we basically achieve the same as currently is being achieved by this trait.

**Comment by bkchr** [comment]
> I know that we normally use it in tests to write a genesis config to storage.

Good point, I forgot about tests! Still doesn't mean we need it in `no_std` :D

**Comment by michalkucharczyk** [comment]
> I'm not sure we should already do this? I mean we can probably get rid off this trait entirely when we just write all genesis values to the state and on the node side, after calling the runtime api, taking the `OverlayedChanges` to fetch all the state changes. Then we basically achieve the same as currently is being achieved by this trait.

We need a function that calls the `build` function of all the pallets in runtime, which in turn put the values into storage (see: https://github.com/paritytech/substrate/blob/c014d4a876b1b9db9affabfc19ba1707831c8c3f/frame/system/src/lib.rs#LL647C15-L647C15).

So the idea is to use this generated function from new `GenesisBuilder` Runtime API.

The storage part can be removed later.

**Review by bkchr — APPROVED** [review]
Good points @michalkucharczyk!

**Review by liamaharon — APPROVED** [review]

**Review by KiChjang — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2811949

**Comment by michalkucharczyk** [comment]
`GenesisConfig::build` function expects `AccountId` to be `Display`:
https://github.com/paritytech/substrate/blob/14855e63b879a26f23186ed2a3ec4a8ad8a7c019/frame/elections-phragmen/src/lib.rs#L748-L750

What would be your preference to solve this?

Changing bounds of `AccountId` to `Display` seems to heavy for me:
https://github.com/paritytech/substrate/blob/14855e63b879a26f23186ed2a3ec4a8ad8a7c019/frame/system/src/lib.rs#L278-L284

**Comment by KiChjang** [comment]
Huh, so `MaybeDisplay` is not working because we now are making sure that `GenesisBuild` is always `Display` regardless of whether the std feature is enabled or not. I think it is fine to replace `MaybeDisplay` with `Display`, since most `AccountId` types would most certainly have a `Display` impl (otherwise I don't know how they attempt to show an account ID via the logs).

**Comment by michalkucharczyk** [comment]
> Huh, so `MaybeDisplay` is not working because we now are making sure that `GenesisBuild` is always `Display` 

Actually it is not about the `GenesisBuild` trait. It is only one stand-alone case where `panic!` is used in `GenesisBuild::build` function.

Adding `Display` bound is ok, but it will pull all the (maybe unneccesarily)  display staff into wasm runtime.

**Comment by bkchr** [comment]
> `GenesisConfig::build` function expects `AccountId` to be `Display`:
> https://github.com/paritytech/substrate/blob/14855e63b879a26f23186ed2a3ec4a8ad8a7c019/frame/elections-phragmen/src/lib.rs#L748-L750
> 
> What would be your preference to solve this?
> 
> Changing bounds of `AccountId` to `Display` seems to heavy for me:
> https://github.com/paritytech/substrate/blob/14855e63b879a26f23186ed2a3ec4a8ad8a7c019/frame/system/src/lib.rs#L278-L284

Just use debug printing?

**Comment by KiChjang** [comment]
Ah ok, yes, the `panic!` macro should really be using debug printing anyway.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2814139

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2814140

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2849173

**Review by sam0x17 — APPROVED** [review]

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/genesisconfig-in-wasm-runtime-a-step-towards-a-non-native-future/2887/1

**Review by KiChjang — APPROVED** [review]

**Comment by KiChjang** [comment]
As soon as CI is green, I believe this is ready to merge.

**Comment by michalkucharczyk** [comment]
> As soon as CI is green, I believe this is ready to merge.

We need https://github.com/paritytech/substrate/pull/14108 to be merged first.

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2864403

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2871785

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2871981

**Review by acatangiu — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by michalkucharczyk** [comment]
I've added requied companions, some pallets in `cumulus` and `polkadot` didn't implement `Default` in `no_std`.

**Review by gilescope — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by michalkucharczyk** [comment]
bot rebase

**Comment by michalkucharczyk** [comment]
bot merge

**Pull request merged**
