### PR TITLE
add debug derive generic tests

### PR DESCRIPTION
**Pull request by honeywest**
add generic test

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]

**Comment by thiolliere** [comment]
looks fine but I'm not really sure what the test is testing.

Also the doc says:

> //! This custom derive implements a `core::fmt::Debug` trait,
//! but in case the `std` feature is enabled the implementation
//! will actually print out the structure as regular `derive(Debug)`
//! would do. If `std` is disabled the implementation will be empty.

But actually it handles generic differently from `derive(Debug)`.
Also maybe we should have made that in `std` it is an alias to `std::fmt::Debug`.

**Comment by bkchr** [comment]
Yeah please give some description for these tests. 

What is the value of them?

**Comment by honeywest** [comment]
Macro code is not easy to understand
Its correctness can only be verified by test examples
Add this kind of generic test to perfect the test

**Comment by thiolliere** [comment]
bot merge

**Comment by bkchr** [comment]
This adds absolutely no value. If you look down you see a test for a generic enum.

I will close this. It is nice that you want to contribute, but please do proper contributions.

**Pull request closed without merging**
