### PR TITLE
Alliance: remove unused func from weight trait

### PR DESCRIPTION
**Pull request by muharem**
Follow up for https://github.com/paritytech/substrate/pull/12762

cumulus companion: https://github.com/paritytech/cumulus/pull/2030

### CODE REVIEW

**Review by joepetrowski — APPROVED** [review]

**Comment by ggwpez** [comment]
This should not be necessary to do manually, it rather means that the weights were not re-generated in the original MR.

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_alliance

**Review by ggwpez — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
