### PR TITLE
remove redundant arm

### PR DESCRIPTION
**Pull request by deepink-mas**
remove redundant arm

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3144004

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3146393

**Comment by ggwpez** [comment]
I think i tried to remove that duplicate `;` branch before, but it did not work. Lets see if the CI compiles it this time...

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3146812

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3146914

**Comment by deepink-mas** [comment]
I removed that semi-colon deduplication stuff.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3147940

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3168962

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate-macos
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3169094

**Comment by sam0x17** [comment]
looks like some stuff still failing

**Comment by ggwpez** [comment]
>Can we just require the semi-colon to be present? Or is that an externally visible change?

We want it to work with and without semi-colon.

**Comment by deepink-mas** [comment]
> > Can we just require the semi-colon to be present? Or is that an externally visible change?
> 
> We want it to work with and without semi-colon.

Yeah, that's what I figured :)

**Comment by deepink-mas** [comment]
> looks like some stuff still failing

Yeah, I'll park this for now...

**Pull request closed without merging**
