### PR TITLE
Strip out control codes from the logged messages

### PR DESCRIPTION
**Pull request by koute**

### CODE REVIEW

**Comment by bkchr** [comment]
bot merge

**Review by bkchr — APPROVED** [review]

**Comment by MOZGIII** [comment]
Why wasn't `strip_control_codes` shared? If there's no good idea - I'd create a PR to share it into yet another primitive create.

We need this for a custom panic handler - and copy-pasting cross-repos doesn't seem like a good idea.

**Comment by bkchr** [comment]
Because we don't wanted to create a crate for just one function and no, there is no other crate where this really fits into.

**Comment by gilescope** [comment]
There’s lots of other projects where this is a good idea (not just rusty
blockchains). Having a general crate to do it this one task well isn’t a
bad idea for the rust community. I’m not saying that created we would
definitely use it, but some projects surely would.

**Pull request merged**
