### PR TITLE
Remove `sp_tasks::spawn` API and related code + host functions

### PR DESCRIPTION
**Pull request by koute**
Fixes: https://github.com/paritytech/substrate/issues/11227

The `sp_tasks::spawn` API and the related host functions are currently horribly broken, not safe to use, and as far as I know no one uses them. Nothing in either `polkadot` nor `cumulus` uses this functionality, and as far as I can see both [Kagome](https://github.com/soramitsu/kagome) and [Gossamer](https://github.com/ChainSafe/gossamer) (which are two alternative Polkadot host implementations) don't even implement it.

It needs to be either reworked, or removed.

Since apparently no one uses it I propose to just remove it.

I've marked the PR as `E4-newhostfunctions` as a formality to mark the PR as it's technically changing the runtime interface, but instead of adding new host functions it *removes* them. (Since we essentially never remove host functions we don't have a tag for that.) Contrary to the tag's description no node release is necessary before a runtime upgrade.

If we want to be extra conservative we could revert the part which removes the host functions and just make the APIs inaccessible from freshly compiled runtimes, but, again, I don't think anyone actually uses this API, and *if* they do they probably shouldn't.

(This most likely needs `polkadot`/`cumulus` companions to update `Cargo.lock`s and whatnot; I'll make those once we decide whether we want to go through with this PR.)

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]
not an expert on whether this change should be merged, but code review is pretty easy to approve

**Review by bkchr — APPROVED** [review]

**Review by atenjin — APPROVED** [review]

**Review by pepyakin — APPROVED** [review]
LGTM

Do you think it's a good time to simplify the `InvokeMethod` and `EntryPoint` machinery? (Not necessary in this PR though).

**Comment by pepyakin** [comment]
So this effectively reverts the change that closed the original issue https://github.com/paritytech/substrate/issues/1459. Should it be re-opened as well?

**Comment by koute** [comment]
> Do you think it's a good time to simplify the `InvokeMethod` and `EntryPoint` machinery? (Not necessary in this PR though).

Yes.

Well, actually, I think it's time to simplify essentially the *whole* thing. (: Which is what I started working on recently. (And this PR is essentially part of that, deleting code we don't need.)

The interface to the executor as a whole could be simplified, and we can improve our resource footprint, how we cache the runtimes, add a proper QoS mechanisms so that e.g. calls originating from the the RPC run with lower priority and are limited in how much resources they can consume, make sure the executor will never fail to instantiate when used with the (now default) polling strategy, etc.

> So this effectively reverts the change that closed the original issue #1459. Should it be re-opened as well?

We could, but I'd really prefer if we'd have a solid use case for this. As in, someone who actively wants it/needs it and *will* use it once implemented. If no one needs this I don't think it makes sense to expand effort on implementing it.

**Comment by koute** [comment]
Huh, looks like this didn't need a companion after all.

Anyway, since no one had any objections so far I'm just going to merge this. If there's a need for this we can reintroduce it later in a non-broken fashion.

**Comment by koute** [comment]
bot merge

**Comment by nazar-pc** [comment]
> We could, but I'd really prefer if we'd have a solid use case for this. As in, someone who actively wants it/needs it and will use it once implemented. If no one needs this I don't think it makes sense to expand effort on implementing it.

I was looking to implement parallel transaction execution at it seemed like this was something that would be a requirement for it. I might be wrong though.

**Pull request merged**
