### PR TITLE
Fix possible consensus issue with storage_append

### PR DESCRIPTION
**Pull request by NikVolf**
As an alternative for #5839 

I think this overlay optimisation is complicated and premature @bkchr @cheme

### CODE REVIEW

**Comment by cheme** [comment]
could you copy my two tests from my pr?

**Comment by bkchr** [comment]
This kills again all the performance optimizations.

**Comment by NikVolf** [comment]
> This kills again all the performance optimizations.

Not all, most will be there
it is something 0.8s vs 1.2s, we measured this already

https://github.com/paritytech/substrate/pull/5795#issuecomment-619879748

**Comment by bkchr** [comment]
Yeah, I know that we measured this. However I don't see any problem of using @cheme's solution. It works and is faster.

So, I will close this.

**Pull request closed without merging**
