### PR TITLE
Remove sc_network::NetworkService::register_notifications_protocol and partially refactor Grandpa tests

### LINKED ISSUE #6827: Figure out the situation with `register_notifications_protocol`
The `NetworkService::register_notifications_protocol` method is a hack, as explained [here](https://github.com/paritytech/substrate/blob/f4bd80c4ca75e20ac028dfc57b1829b937976740/client/network/src/service.rs#L741-L745).
The problem with this method is that we might have started already connecting to other nodes.

At the moment, if two nodes connect before `register_notifications_protocol` has been called, and if then we try to send a message on the given protocol, it will be sent on the legacy substream as a fallback.

This is however getting in the way of removing the legacy substream. cc https://github.com/paritytech/substrate/issues/5670

The proper fix is to refactor Substrate to pass the list of protocols [in the `NetworkConfiguration`](https://github.com/paritytech/substrate/blob/7a4bd762e0e8c2ddf959787981cd2e55d080b47d/client/network/src/config.rs#L407-L409), but that's a lot of work.

### PR DESCRIPTION
**Pull request by tomaka**
polkadot companion: https://github.com/paritytech/polkadot/pull/2048

Close #6827 

This PR removes the `register_notifications_protocol` method from `sc_network`.
Instead of registering new protocols *after* the networking has started (like `register_notifications_protocol` allows), it is now mandatory to mention the protocol name in `NetworkConfiguration`.
This has never been done because Polkadot used to make use of this method as well, and getting rid of it would have been a bit tricky. This is no longer the case, and Polkadot does it through `NetworkConfiguration`.

This change is, in my opinion, not only more correct, but will also simplify the implementation of #7374, as it guarantees the possibility to know in advance the number of notifications protocols.

Consequently, I've also removed `setup_disabled_grandpa` whose only effect is to register the protocol.

[This hack](https://github.com/paritytech/substrate/blob/5eadb3c5ce9e9a60615ae0a06ace6928ee644c2e/bin%2Fnode-template%2Fnode%2Fsrc%2Fservice.rs#L293), where the network doesn't start until initialization of the service is complete, is still in place and is still necessary because we grab event streams (using `NetworkService::events_stream()`) during the service initialization. Calling `events_stream()` after the networking has started could lead to events being missed. This problem is covered by https://github.com/paritytech/substrate/issues/6403.

### CODE REVIEW

**Review by romanb — APPROVED** [review]

**Comment by tomaka** [comment]
Grandpa tests are failing because the tests initialize Grandpa only half-way through the test, and thus miss messages. This is a bit infuriating.

**Comment by tomaka** [comment]
Note for myself: `tests::force_change_to_new_set` is apparently also failing, but inconsistently.

**Comment by tomaka** [comment]
bot merge

**Comment by tomaka** [comment]
bot merge

**Comment by tomaka** [comment]
Could someone also approve https://github.com/paritytech/polkadot/pull/2048 ? :pray:

**Review by andresilva — APPROVED** [review]

**Comment by andresilva** [comment]
bot merge

**Pull request merged**
