### PR TITLE
nomination-pools: clear pool metadata after a pool is deleted.

### PR DESCRIPTION
**Pull request by tifecool**
PR for: #12077

### CODE REVIEW

**Comment by tifecool** [comment]
I'm aware a test would must likely necessary, but I don't have experience with tests.

Would appreciate some guidance

**Review by kianenigma — CHANGES_REQUESTED** [review]
Not quire correct.

To begin with, you should make sure `dissolve_pool` also clears the metadata, as the issue is asking for.

Then, you should make sure this is tested. You can just add relevant assertions to some tests that already end up dissolving a pool.

The migration can be dealt with later. 

This PR is rather time-sensitive for the next release. If not able to attend to it ASAP, let me know and I will do it myself.

**Comment by tifecool** [comment]
> To begin with, you should make sure `dissolve_pool` also clears the metadata, as the issue is asking for.

The metadata of the bonded pool or all the metadata?

>This PR is rather time-sensitive for the next release. If not able to attend to it ASAP, let me know and I will do it myself.

I'll try running the assertions now. I should be able to finish off today, if I'm unable to I'll drop it,

**Comment by tifecool** [comment]
I don't see any specific test for dissolve_pool.

**Comment by kianenigma** [comment]
> The metadata of the bonded pool or all the metadata?

The metadata of the pool, what's stored in `Metadata::<T>::get(pool_id)`.

**Comment by ruseinov** [comment]
I'll take over this in a new PR.

**Comment by tifecool** [comment]
@ruseinov @kianenigma 

Give me till the end of the day.
Plan on writing a test.

**Comment by tifecool** [comment]
@ruseinov I think I'm on the right track, just no test.

**Pull request closed without merging**
