### PR TITLE
check_polkadot now runs nightly and on master (merges) only

### PR DESCRIPTION
**Pull request by TriplEight**
I've been asked to run this job only nightly and on merges, anyways it's always failing.

### CODE REVIEW

**Comment by bkchr** [comment]
What is the purpose of running this job on nightly? Who requested that? Next question is, where do we see nightly jobs? Is anyone informed by the result of these jobs?

**Comment by TriplEight** [comment]
I remember you hinting this, and a couple of other devs. That's why I did this PR.
There will be a chat bot telling about failed schedules.

**Comment by bkchr** [comment]
When this is run per PR, what should we get from running it on nightly? We already know when a pr breaks polkadot when the check is run for each pr.

**Comment by gavofyork** [comment]
To make it effective when running on PRs, we would need to merge every PR to master and re-run every time master changes. That's going to hit the build server much harder than just rerunning on master and for not much point as the vast majority of the time, merging and re-running gives the same result as the original.

**Pull request merged**
