### PR TITLE
Drop ClientProvider

### PR DESCRIPTION
**Pull request by seunlanlege**
Unfortunately Mega traits are hard to maintain.
Consumers should assemble the minimum required set of traits they need for client functionality.

### CODE REVIEW

**Comment by gnunicorn** [comment]
test's failing.

**Comment by gnunicorn** [comment]
though I wonder if we want to keep it somewhere, like in the docs... :thinking:

**Comment by seunlanlege** [comment]
technically the polkadot companion PR is already merged :man_shrugging:

**Comment by gnunicorn** [comment]
@seunlanlege seems like the  polkadot companion was incomplete – https://gitlab.parity.io/parity/substrate/-/jobs/486540 . Raise another companion PR please.

**Comment by seunlanlege** [comment]
aii, both green https://github.com/paritytech/polkadot/pull/1054 @gnunicorn

**Pull request merged**
