### PR TITLE
Remove the last bits of unknown_os in the code base

### PR DESCRIPTION
**Pull request by bkchr**

### CODE REVIEW

**Review by gilescope — APPROVED** [review]
LGTM. (cargo fmt will reduce the diffs)

**Comment by TriplEight** [comment]
Lovely!
I wonder how doe this solve the current [issue](https://gitlab.parity.io/parity/substrate/-/jobs/1104630) which is red on master.

**Comment by bkchr** [comment]
@TriplEight how is your comment related to this pr?

**Comment by TriplEight** [comment]
@bkchr I was looking what could fix master and found it, now just curious.

**Comment by bkchr** [comment]
Okay :) Yeah regarding the errors on master. Master uses the exact same CI image? Did you tried to delete the cache?

**Review by dvdplm — APPROVED** [review]

**Pull request merged**
