### PR TITLE
Do not drop the `task_manager` for benchmarking stuff

### PR DESCRIPTION
**Pull request by bkchr**
We can not drop the `task_manager` for benchmarking stuff, because otherwise stuff that may needs
this feature (like background signature verification) will fail. Besides the base path setup is
moved to `SharedParams` directly. Meaning any call to `base_path` will now directly return a tmp
path when `--dev` is given.

cumulus companion: https://github.com/paritytech/cumulus/pull/1587

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Nice, thanks!

**Review by shawntabrizi — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by MOZGIII** [comment]
Won't this be confusing, as the path will be different each time this fn is called?

**Comment by ggwpez** [comment]
> Won't this be confusing, as the path will be different each time this fn is called?

It has to be different, since we need an ephemeral database when called with `--dev`.  
The problem was that it actually used an existing DB in a few cases.

**Comment by MOZGIII** [comment]
Why not add something like `OnceCell` there to keep the path from chaning?

**Comment by ggwpez** [comment]
> Why not add something like `OnceCell` there to keep the path from chaning?

Ahh, you mean as internal detail, okay. I thought you were talking about the benchmarking commands.  
Yea could do that I guess, or @bkchr ?

**Comment by bkchr** [comment]
> Why not add something like `OnceCell` there to keep the path from chaning?

We would need to ensure that we call `Drop` somewhere in the program to delete the temporary path.

**Comment by MOZGIII** [comment]
> > Why not add something like `OnceCell` there to keep the path from chaning?
> 
> We would need to ensure that we call `Drop` somewhere in the program to delete the temporary path.

I don't think it would be necessary. It's not something that's happening with the current implementation, or what happened previously.

If it was to be added, I'd consider it a separate feature, and allow for opting-in/out of it (an extra flag maybe?).

**Comment by bkchr** [comment]
> I don't think it would be necessary. It's not something that's happening with the current implementation, or what happened previously.

This is not true. The current implementation deletes the temporary path on drop. Or at least it should be.

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/pull/12246

**Pull request merged**
