### PR TITLE
Fix companion status check by requiring at least 3 approvals

### PR DESCRIPTION
**Pull request by bkchr**

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by andresilva — COMMENTED** [review]
Won't this be a bit annoying? These are not the rules for a `bot merge` and in most cases we won't get 3 reviews on the companion.

**Comment by bkchr** [comment]
> Won't this be a bit annoying? These are not the rules for a `bot merge` and in most cases we won't get 3 reviews on the companion.

Not sure: https://github.com/paritytech/polkadot/pull/1734#issuecomment-694947143

**Review by andresilva — CHANGES_REQUESTED** [review]
I think the bot is enforcing github's approval threshold over its own rules, i.e. if some team lead approves the bot shouldn't care about having less than 3 reviews. We should fix that in the bot and this PR shouldn't be needed.

**Comment by bkchr** [comment]
> I think the bot is enforcing github's approval threshold over its own rules, i.e. if some team lead approves the bot shouldn't care about having less than 3 reviews. We should fix that in the bot and this PR shouldn't be needed.

While you are right, you are only half right. 

People could start merging prs to Substrate if they have the required amount of approvals, while the companion doesn't have them and we end in the situation where we are currently. The Substrate pr was merged, but the polkadot pr can not yet be merged.

I think the solution to this problem should be that the process-bot ignores the `check-polkadot-status` and do it on its own. It could check if the companion was approved by a team lead and if yes, merge both prs.

**Comment by bkchr** [comment]
@andresilva so what you think on how we want to continue here?

**Pull request closed without merging**
