### PR TITLE
remove FunctionOf

### PR DESCRIPTION
**Pull request by kianenigma**
This has already been deprecated since substrate 2.0.0

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by kianenigma** [comment]
bot merge

**Review by ggwpez — APPROVED** [review]
CI keeps failing with 'draft' status?!

**Comment by kianenigma** [comment]
CI is drunk again on a monday morning.

**Comment by bkchr** [comment]
> CI is drunk again on a monday morning.

But there is still some usage of `FunctionOf` :P Or the CI is ultra drunk

**Comment by kianenigma** [comment]
> > CI is drunk again on a monday morning.
> 
> But there is still some usage of `FunctionOf` :P Or the CI is ultra drunk

Both CI and and I drunk 🧠

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
bot rebase

**Comment by kianenigma** [comment]
bot merge

**Pull request merged**
