### PR TITLE
Fix max log level

### PR DESCRIPTION
**Pull request by bkchr**
With the switch to tracing we did not set the `max_log_level` anymore.
This resulted in a performance degradation as logging did not early
exited and thus, `trace` logs were at least resolved every time.

This pr fixes it by ensuring that we set the correct max log level.

Fixes: https://github.com/paritytech/substrate/issues/7800

### CODE REVIEW

**Comment by notlesh** [comment]
Thanks for this!

**Review by andresilva — APPROVED** [review]
🥳

**Review by pepyakin — APPROVED** [review]
On my local machine I can no longer see the bottleneck that was described in the issue. The code change looks sensible as well.

**Comment by pepyakin** [comment]
bot merge

**Pull request merged**
