### PR TITLE
contracts: Remove ConfigCache

### PR DESCRIPTION
**Pull request by athei**
This is a small PR. The chunk is just repetitiv test changes and automated weight results.

The `ConfigCache` was meant to load values needed contract execution once instead of on-demand. The reality is that the only in-storage value of the `ConfigCache` is the `Schedule`. The other values are just simple getters which mostly return constant values or results of simple calculation. Also cache usage was inconsequential at best because all the values are pervasive as they are defined on the public trait.

For all these reason i consider the `ConfigCache` clutter and remove it with this PR.

### CODE REVIEW

**Review by thiolliere — APPROVED** [review]
ppl can still implement those `Get` stuff using some storage.
(for instance `parameter_types` allows to do:
```rust
parameter_types! {
   pub storage MyGetter: u64 = 5;
}
```
)

But I think using storage to implement getter is not very advised for production runtime, also it would be in cache anyway.

Code looks good though

**Comment by athei** [comment]
Yes I know. But I would not consider this case as this is something you really shouldn't do.

**Review by ascjones — APPROVED** [review]

**Comment by athei** [comment]
bot merge

**Pull request merged**
