### PR TITLE
Create Balances RPC

### PR DESCRIPTION
**Pull request by zachanon**
This is an early draft pull request for Create Balances RPC ([#8752](https://github.com/paritytech/substrate/issues/8752))
c.c. @apopiak @shawntabrizi @xlc

As suggested, I have created the PR early. The goal is to provide a node RPC that allows calling free_balance given an account ID. This is done through a runtime api exposing pallet functions. I wish to have a working RPC before attempting to implement subscription, mentioned in the issue, as I am new to both Rust and Substrate and wish to keep complexity to a minimum.

Hoping to find out from review whether this approach makes sense. As well, I am planning to add the testing logic to the frame/balances crate to avoid boilerplate. Is this okay or should I move all test logic as well to the rpc crate?

(Sorry for the delay between mentioning interest and this PR. I hope you have had a good week so far, and thank you for review.)

### CODE REVIEW

**Comment by zachanon** [comment]
Finished the logic for the RPC. Next step is to add test coverage and confirm it does more than compile.

**Comment by zachanon** [comment]
I have run into a snag and would like some advice on how I might solve it.

Apparently serde still has an issue with u128 types. I get the same error as issue [#4641](https://github.com/paritytech/substrate/issues/4641) when I attempt to curl the balances_freeBalance method I added.

[Here](https://github.com/paritytech/substrate/commit/0b647cffac438bd3642bb40d7898d8c7bdf68356) is a link to the code I added to the node-template for testing.

I ran ```cargo build --release && ./target/release/node-template --dev --tmp``` and when built I called from the terminal

```
curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d   '{
     "jsonrpc":"2.0",
      "id":1,
      "method":"balances_freeBalance",
      "params": ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"]
    }'
```

As a result of the call. my node crashes and gives me a trace ending in 
```
Thread 'http.worker10' panicked at 'Expected always-serializable type; qed: Error("u128 is not supported", line: 0, column: 0)', /home/zach/projects/substrate/substrate/frame/balances/rpc/src/lib.rs:44
```

I tried to wrap the result in the struct ```BalanceDetails``` but it failed to work where I have it [instantiated](https://github.com/paritytech/substrate/blob/4b00fa10bb09a45d06c347a5f43c88a6941a8d55/frame/balances/rpc/src/lib.rs#L39). Looking at one example of a solution, it appears I would have to add code [directly to the pallet](https://github.com/celer-network/cChannel-substrate/blob/016223b210fa5913029063507bcb7aa7e6ca1f20/pallets/celer-pay/src/lib.rs#L1012) for a workaround, which I do not want to do if there is another way.

Is there an approach I can take to solve this without modifying the balances pallet directly?

**Comment by zachanon** [comment]
By sheer serendipity I happened to find a solution when browsing the code for [zeitgeist](https://github.com/zeitgeistpm/zeitgeist). I implemented, and it works!

Tomorrow I shall add some testing logic and ask for a review.

**Comment by zachanon** [comment]
Update: I have tried and failed to make a minimal mock to test the runtime api. I've looked at all the examples I could find of the rpc tests in the codebase and simply cannot figure out what I am doing wrong in my implementation. Spent far too much time on this, but at least I have learned a lot about how the client works.

I will ensure at least the rpc works in the full node under a few conditions, then see about how I might implement pubsub functionality. Apologies for taking my time on this, I want to use the opportunity to really grok every bit of substrate as I go along.

**Comment by kianenigma** [comment]
This one seems like it could be merged, adding it to our project to get more eyes.

**Pull request closed without merging**
