### PR TITLE
Fix logging filter parsing

### LINKED ISSUE #6607: Breaking CLI changes in latest master
Seeing a new error when trying to use the latest master with the same CLI options that had been working..

```
Jul 08 18:30:41 hostname kusama[3658]: Error: FlexiLogger(Parse("ignoring invalid part in log spec \'sub-authority-discovery\' (contains a dash or whitespace)", LogSpecification { module_filters: [ModuleFilter { module_name: Some("sc_offchain"), level_filter: Trace }, ModuleFilter { module_name: Some("consensus"), level_filter: Trace }, ModuleFilter { module_name: Some("imonline"), level_filter: Trace }, ModuleFilter { module_name: Some("runtime"), level_filter: Trace }, ModuleFilter { module_name: Some("client"), level_filter: Trace }, ModuleFilter { module_name: Some("txpool"), level_filter: Debug }, ModuleFilter { module_name: Some("slots"), level_filter: Trace }, ModuleFilter { module_name: Some("forks"), level_filter: Trace }, ModuleFilter { module_name: Some("babe"), level_filter: Trace }, ModuleFilter { module_name: Some("sync"), level_filter: Trace }, ModuleFilter { module_name: Some("afg"), level_filter: Trace }], textfilter: None }))
```

Removing ```sub-authority-discovery``` from the logging options was required.

### PR DESCRIPTION
**Pull request by pscott**
This PR fixes a bug where adding a log filter that contains dashes would result in an error.

This is my bad, as [flexi_logger](https://docs.rs/flexi_logger/0.15.7/flexi_logger/struct.LogSpecification.html#method.parse) specifies
> Note that external module names are to be specified like in "extern crate ...", i.e., for crates with a dash in their name this means: the dash is to be replaced with the underscore (e.g. karl_heinz, not karl-heinz).

This PR fixes this bug by replacing dashes by underscores.

It does not however, replace dashes from the `RUST_LOG` env variables, as we simply call `LogSpecification::env()`, so we can't replace dashes.

Closes #6607

### CODE REVIEW

**Comment by pscott** [comment]
Shouldn't get merged right now as I'm waiting on @ddorgan 's answer on https://github.com/paritytech/substrate/issues/6607 :D

The questions basically is: when logger fails to initialize or fails to parse some log filters, should we error or simply warn? :)

**Comment by gnunicorn** [comment]
then the right label is `on-ice`

**Comment by tomaka** [comment]
Since this is a breaking change, it doesn't matter what people's opinion is.
It should be a warning, at least initially.

**Comment by pscott** [comment]
Closed in favor of #6702

**Pull request closed without merging**
