### PR TITLE
Bump `Cargo.lock`

### PR DESCRIPTION
**Pull request by rcny**
...to keep up with the `cargo update` changes.

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Review by ggwpez — CHANGES_REQUESTED** [review]
Sorry saw it wrong. `cargo update` should not be needed, let me try.

**Review by ggwpez — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Comment by bkchr** [comment]
What was the point of this pr?

**Comment by koute** [comment]
> What was the point of this pr?

Someone accidentally didn't fully commit the `Cargo.lock` with their PR, so for everyone building the current `master` even with no changes they had `cargo` always update the `Cargo.lock` with the same patch as the one in this PR.

**Pull request merged**
