### PR TITLE
implement exponential decay curve

### PR DESCRIPTION
**Pull request by pifragile**
This PR introduces a new curve `ExponentialDecay` in the `referenda` pallet. For the implementation we rely on [Encointer's substrate-fixed](https://github.com/encointer/substrate-fixed), which provides efficient fixed point numbers and implements transcendental functions like `exp` and `log`. 

Changes at unrelated locations in the code were necessary because `substrate-fixed` introduces some conflicting impls and  we got errors along the lines of
`type annotations needed`
`multiple impls satisfying usize: PartialOrd<_> found in the following crates: core, substrate_fixed`

### CODE REVIEW

**Comment by brenzi** [comment]
@shawntabrizi @kianenigma as discussed at parachain summit

*full disclosure : I asked @pifragile to implement this PR as a tangible demonstration of substrate-fixed because we would very much like to have the [substrate-fixed](https://github.com/encointer/substrate-fixed) crate included in the substrate/polkadot codebase or [parity-common](https://github.com/paritytech/parity-common) - and have its primitives supported by ecosystem tools like js/apps*

On the topic of this PR: After discussing Gov2 ideas with @joepetrowski, I had the strong feeling that linear curves will not be satisfactory. Non-linear curves for approval and turnout thresholds will be much more powerful and much closer to the behaviour we actually desire.

Of course, piecewise-linear curves are an option, but they offer worse dev experience when setting them up and they naturally come with discontinuities of the first derivative. (Taking the example of bitcoin mining rewards, such discontinuities can cause a lot of unnecessary turbulence).

With this PR, it is possible to define smooth curves with reasonable computational complexity with only few easy-to-understand parameters: 
* starting point
* offset
* halving-time (relative to decision period)

**Comment by brenzi** [comment]
@pifragile please fix the reported CI errors

**Comment by kianenigma** [comment]
note that I think the first step in this is: https://github.com/paritytech/substrate/issues/12040, and then we can re-export `fixed` from `common` or `sp-arithmetic`.

I am not the best person to judge of the change to the referendum pallet is sensible, but I will have a look.

**Comment by brenzi** [comment]
Waiting for #12509

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/community-suggestions-and-requests-for-the-opengov-model-on-kusama/1179/6

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/community-suggestions-and-requests-for-the-opengov-model-on-kusama/1179/7

**Comment by brenzi** [comment]
not sure how to move on, still waiting for https://github.com/paritytech/substrate/pull/12509

**Comment by brenzi** [comment]
> note that I think the first step in this is: #12040, and then we can re-export `fixed` from `common` or `sp-arithmetic`.
> 
> I am not the best person to judge of the change to the referendum pallet is sensible, but I will have a look.

As #12040 has been aborted, is there another way to move ahead with substrate-fixed?
If not for this PR, it still would be valuable for us to see support in this codebase and I still believe the implementation is more computationally efficient than the current one, but benchmarking that is an effort we can't currently do.

**Pull request closed without merging**
