### PR TITLE
What happens if we remove wat?

### PR DESCRIPTION
**Pull request by pepyakin**
In response to [this comment](https://github.com/paritytech/substrate/pull/7050#discussion_r485361639)

### CODE REVIEW

**Review by gnunicorn — APPROVED** [review]
yay, removed a line!

**Review by thiolliere — APPROVED** [review]

**Comment by thiolliere** [comment]
bot merge

**Comment by pepyakin** [comment]
😭

**Comment by gnunicorn** [comment]
bot merge

**Pull request merged**
