### PR TITLE
CI: revert me [skip ci]

### PR DESCRIPTION
**Pull request by TriplEight**
In order to update Rust nightly, [fmt](https://gitlab.parity.io/parity/substrate/-/jobs/1209976) should be fixed, I've opened this PR for you. @athei 
 - [x] update `ci-linux:staging` with Rust `nightly-2021-11-08` in .gitlab-ci.yml
 - [x] fix the tests
 - [x] push `staging` ci image to `production`
 - [x] revert the debug commit
 - [ ] Merge pr

### CODE REVIEW

**Comment by athei** [comment]
I guess you will need to run `cargo +nightly fmt` as a last step in this PR.

**Comment by TriplEight** [comment]
@athei the point is, it's executed in the CI pipeline: https://gitlab.parity.io/parity/substrate/-/jobs/1209976#L82
Please fix those errors and after I'll push the CI image to prod, otherwise we'll break `master`.

**Comment by ordian** [comment]
@TriplEight fixed it for you

**Review by ordian — APPROVED** [review]

**Review by athei — APPROVED** [review]

**Comment by ordian** [comment]
bot merge

**Comment by ordian** [comment]
bot merge cancel

**Comment by ordian** [comment]
looks like fmt change already landed in master

**Comment by TriplEight** [comment]
> looks like fmt change already landed in #10253

oh this is great!

**Pull request closed without merging**
