### PR TITLE
build-script-utils: allow reading the git commit hash from env var

### PR DESCRIPTION
**Pull request by andresilva**
This is useful for build environments where the .git folder is not available. This is the case in nix since bundling a .git folder can lead to reproducibility issues.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by xlc** [comment]
I guess I can _really_ close my issue now https://github.com/paritytech/substrate/issues/8334

**Comment by nazar-pc** [comment]
I had to strategically copy only a few files from `.git` to make sure `rev-parse --short HEAD` works when building container images without resorting to have the whole `.git` in build context. This makes it much easier, thank you!

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/moving-frame-out-of-substrate/907/1

**Pull request merged**
