### PR TITLE
[DNM] mak/testing-all-pallets-bench

### PR DESCRIPTION
**Pull request by mordamax**

### CODE REVIEW

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot rebase

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak/bench-all

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak/bench-all

**Comment by mordamax** [comment]
bot help

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak/bench-all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all -v RUST_LOG=warn $ all

**Comment by mordamax** [comment]
bot cancel 2-4870f092-283e-4432-951f-643d6a9e3d85

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot cancel

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot rebase

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot clean

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot cancel 32-e46a4c96-8924-43e6-81cb-e9a1917899e8

**Comment by mordamax** [comment]
bot bench-bm -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ pallet dev pallet_democracy

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ pallet dev pallet_democracy

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ pallet dev pallet_democracy

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2436437

**Comment by mordamax** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=mak/bench-all

**Comment by mordamax** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=mak/bench-all $ ""

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ pallet dev pallet_democracy

**Comment by mordamax** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=mak/bench-all $ ""

**Comment by mordamax** [comment]
bot help

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak/bench-all

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot cancel

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by mordamax** [comment]
bot cancel

**Pull request closed without merging**
