### PR TITLE
clippy arithmetic

### PR DESCRIPTION
**Pull request by honeywest**
warning: redundant closure found
   --> primitives/arithmetic/src/fixed_point.rs:122:9
    |
122 |             .map(|inner| Self::from_inner(inner))
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove closure as shown: `Self::from_inner`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

### CODE REVIEW

**Comment by bkchr** [comment]
Hey, as you probably already have seen, we don't use clippy.

If you want to fix this "fine", but than please do not create one pr per crate/file. You can just combine all into one pr

**Comment by honeywest** [comment]
I see. 
I only do this when I have time.
I just had time to do something this morning

**Review by kianenigma — APPROVED** [review]
Let's either merge this if the CI is green after a merge with master, or archive due to inactivity.

**Comment by gnunicorn** [comment]
closing for a lack of progress.

**Pull request closed without merging**
