### PR TITLE
feat: add propose method for SimpleSlotWorker

### PR DESCRIPTION
**Pull request by yjhmelody**
A new PR that will close old PR #11675.

The `propose` method need to be reimplemented in some situations.

### CODE REVIEW

**Comment by bkchr** [comment]
Can you please write some proper explanation on what you want to do and why it currently doesn't work.

**Comment by yjhmelody** [comment]
Hi, @andresilva Could you give me a review ?

**Comment by yjhmelody** [comment]
Anyone could give me a feedback?

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@yjhmelody please fmt and merge master.

**Comment by yjhmelody** [comment]
@bkchr  Hi, have fmt and merged master

**Review by davxy — APPROVED** [review]

**Pull request merged**
