### PR TITLE
Update Reference Hardware Specs

### LINKED ISSUE #13308: Update hardware requirements for `benchmark machine`
Run the `benchmark machine` on new reference hardware and update the requirements JSON file. Showed up on [SE](https://substrate.stackexchange.com/questions/7074).

### PR DESCRIPTION
**Pull request by ggwpez**
Updating to the new hardware specs. CPU got slower but disk faster. This was the trade-off for chosing Cloud VM machines.  
The new numbers were generated on a Cloud reference server with:
```bash
./target/production/substrate benchmark machine --dev --memory-duration 60 --verify-duration 60 --hash-duration 60 --disk-duration 60
```

Value changes:
|Bench|Old|New|Relative Change|Unit|
|-|-|-|-|-|
|Blake2256|1029.0 | 783.27| -23.88 %|MiBs|
|Sr25519Verify|666|560.67|-15.82 %|MiBs|
|Memcopy|14.323|11.49|-19.78 %|GiBs|
|Disk Seq Write|450|950|+111.11 %|MiBs|
|Disk Rnd Write|200|420|+110.0 %|MiBs|

I rounded the new disk speed down a bit (971->950, 445->420) since the disk benches are known to not be as consistent as the CPU ones.  

Closes https://github.com/paritytech/substrate/issues/13308. Marking as noteworthy so this is mentioned in the change log.

### CODE REVIEW

**Comment by 99Kies** [comment]
@ggwpez  `Disk Seq Write` and `Disk Rnd Write` values mainly affect which part of the function, my current Disk Seq Write's Disk Rnd Write values are `290.10 MiBs` and `125.07 MiBs` respectively, can I go run polkadot's verifier node.

**Comment by ggwpez** [comment]
>Disk Seq Write and Disk Rnd Write values mainly affect which part of the function, my current Disk Seq Write's Disk Rnd Write values are 290.10 MiBs and 125.07 MiBs respectively, can I go run polkadot's verifier node.

You are probably using a network drive and not a NVMe SSD disk as mentioned in the wiki. In AWS it is probably possible to use multiple disks like in GCP. We should extend the explanations in the wiki for that. In GCP I used 4 network disks to archive performance close to a local disk.  
Polkadot will update to use the same stats as soon as this merges.

**Comment by bkchr** [comment]
Why do we need faster disks? Instead of a faster CPU?

**Comment by ggwpez** [comment]
> Why do we need faster disks? Instead of a faster CPU?

It would be nice to have faster CPU as well, but the most widely available cloud hosters only offer server CPUs, like Xeon and EPYC. These are mostly inferior in single-thread speed when compared to consumer hardware like Intel i7 or i9.  
That is the trade-off for allowing machines to be virtual instead of bare metal.  
Most validators used VMs anyway despite the old bare-metal recommendation, so this should help them to pick good VMs.

**Comment by bkchr** [comment]
Okay, ty for the explanation!

**Comment by 99Kies** [comment]
image

@ggwpez Disk Seq Write's Disk Rnd Write values are `290.10 MiBs` and `125.07 MiBs`. 

My main confusion is, can I use this configuration to run polkadot/kusama verifier nodes. I mainly want to avoid slashing my assets, which should be related to the outgoing blocks of the node, so as long as I have the CPU and Mem up to par, is it possible to run the node. (And then I don't have to worry about my assets getting slashed?

**Comment by ggwpez** [comment]
>My main confusion is, can I use this configuration to run polkadot/kusama validator-node. I mainly want to avoid slashing my assets, which should be related to the outgoing blocks of the node, so as long as I have the CPU and Mem up to par, is it possible to run the node. (And then I don't have to worry about my assets getting slashed?

I cannot tell you that on a case-by-case basis. These are just recommendations; they are not hard requirements nor exhaustive.  
It allows for quickly sorting out bad hosters and VM types. That is mostly the indented use-case.  
  
For more concrete advice you can ask in the 1KV Program matrix/discord chat, they often talk about their server hardware.

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
What is the sTPS after this chance?

**Comment by 99Kies** [comment]
@ggwpez  I can't find the matrix/discord link you mentioned. I would like to confirm that the machines running kusama are not also of this standard. Aren't there many parallel chains on the kusama network. Compared to polkadot, does kusama require the same machine performance as polkadot?

**Comment by shawntabrizi** [comment]
@99Kies if this PR goes in, you should probably assume that both Polkadot and Kusama are updated to the same standard. Generally speaking, Kusama will always be as close to Polkadot as possible in these kinds of things, as that is the purpose of the canary network.

**Comment by bkchr** [comment]
BTW the discussion around this change continues in the issue: https://github.com/paritytech/substrate/issues/13308

We will not merge this before we have not solved the weight noise issue.

**Comment by ggwpez** [comment]
@99Kies see https://thousand-validators.kusama.network/#/getting-started the matrix channel is `#KusamaValidatorLounge:polkadot.builders`.

>What is the sTPS after this change? (as compared to 1,500)

Currently getting a build error in the VM ref hardware image :man_facepalming:. Will need to update the DB weights first.

**Review by kianenigma — APPROVED** [review]

**Comment by kianenigma** [comment]
Not sure if the aforementioned issues are solved, but seems like something that we want to see merged.

**Comment by ggwpez** [comment]
@oleg-plakida just to check: Substrate and Polkadot is updated? Now just Cumulus, or?

**Comment by oleg-plakida** [comment]
> @oleg-plakida just to check: Substrate and Polkadot is updated? Now just Cumulus, or?

Rococo and cumulus remain.

**Comment by ggwpez** [comment]
bot rebase

**Review by sam0x17 — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
