### PR TITLE
CI: address the bug with .env

### PR DESCRIPTION
**Pull request by TriplEight**
to properly trigger Simnet.
Also, add `TRIGGERER` for more grained pipelines there.

### CODE REVIEW

**Comment by TriplEight** [comment]
@bkchr this label was needed to start gitlab CI

**Comment by bkchr** [comment]
What does the `trivial` label starts?

**Review by bkchr — APPROVED** [review]

**Comment by shawntabrizi** [comment]
@bkchr the trivial label is for PRs which do not require an audit

**Comment by bkchr** [comment]
> @bkchr the trivial label is for PRs which do not require an audit

I know, I requested the label. However, @TriplEight said this label started a special ci job and I want to know which.

This pr doesn't need the trivial label as it doesn't touch anything runtime related and the bot not enforcing it.

**Comment by TriplEight** [comment]
@bkchr now, without `D*` label, GitLab CI jobs won't start.

**Review by rcny — APPROVED** [review]

**Pull request merged**
