### PR TITLE
Add BEEFY key type

### PR DESCRIPTION
**Pull request by adoerr**
- Add BEEFY key type to the list of well-known key types.

### CODE REVIEW

**Comment by bkchr** [comment]
Why not keep them in beefy?

**Comment by adoerr** [comment]
We have a use case, where we need to check from within Substrate (`LocalKeystore`) whether a key id is a BEEFY key type. 

Also, since BEEFY should be integrated (one way or another) with Substrate anyway, this could be seen as a first step towards this  goal :-)

**Comment by bkchr** [comment]
> We have a use case, where we need to check from within Substrate (`LocalKeystore`) whether a key id is a BEEFY key type.

This is not required for the `LocalKeystore`. We don't use any hard coded key type in the keystore.

**Comment by adoerr** [comment]
But we will. We need a special version of `Pair::sign()` spcial cased on BEEFY. It's going to be a bit hacky but the best we can do for now.

**Comment by bkchr** [comment]
Why? 

This sounds rather fishy. Please explain more what kind of `Pair::sign` you need?

**Comment by adoerr** [comment]
Closing this PR.

The immediate reason for this PR has been superseded by a solution proposed with [Allow hasher configuration before signing with app-crypto](https://github.com/paritytech/grandpa-bridge-gadget/issues/82)

**Pull request closed without merging**
