### PR TITLE
change HashFor to HashingFor

### LINKED ISSUE #10386: Refactor `HashFor` and `HashingFor`
This code comment explains it: 

```
// NOTE: this is a horrible choice of name, `Header` has both `type Hash` and `type Hashing`, and
// this is exactly what you would NOT expect. Should be called `HashingFor` and have a separate one
// called `HashFor`.
pub type HashFor<B> = <<B as Block>::Header as Header>::Hashing;
```

### PR DESCRIPTION
**Pull request by deepink-mas**
fixes https://github.com/paritytech/substrate/issues/10386

Patch created using:
`find * -name '.*' -prune -o -name '*.rs' -type f -execdir sed -i -- 's#HashFor#HashingFor#g' '{}' +`

polkadot companion: https://github.com/paritytech/polkadot/pull/7465
cumulus companion: https://github.com/paritytech/cumulus/pull/2828

### CODE REVIEW

**Comment by bkchr** [comment]
bot fmt

**Comment by ggwpez** [comment]
Next time if you want to rebase, just do `git merge origin/master` and then push that.

**Comment by bkchr** [comment]
@deepink-mas this also requires a Cumulus/Polkadot companion.

**Comment by deepink-mas** [comment]
Companions for Cumulus/Polkadot: https://github.com/paritytech/polkadot/pull/7465 and https://github.com/paritytech/cumulus/pull/2828

**Review by bkchr — APPROVED** [review]

**Comment by deepink-mas** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3172473

**Comment by deepink-mas** [comment]
I did a 'cargo fmt' with rust 1.70, but it still seems to contain unrelated formatting changes, which is why I avoided doing it until now. And looking at the CI it seems to want to revert some of those unrelated changes.

Not sure what is going on, unless there is some configuration file that my cargo is not picking up for some reason.

**Comment by bkchr** [comment]
bot fmt

**Review by sam0x17 — APPROVED** [review]

**Comment by sam0x17** [comment]
> Am I correct in understanding that this is blocked pending one more review or is there something I should do?

looks like the companions both have issues

**Comment by ggwpez** [comment]
bot rebase

**Review by ggwpez — APPROVED** [review]

**Comment by ggwpez** [comment]
bot merge

**Comment by ggwpez** [comment]
bot merge

**Pull request merged**
