### PR TITLE
Small fix to block response completion reporting

### PR DESCRIPTION
**Pull request by tomaka**
Report events immediately instead of en-queueing them and returning `Poll::Pending`.
This is only relevant to reporting to Prometheus how much time we took to answer requests, so it's not related to the current sync stalling issue.

### CODE REVIEW

**Comment by arkpar** [comment]
`while` loop should be replaced with `if`

**Comment by bkchr** [comment]
Wait. What is with the other data in the stream? The runtime will not wake us up anymore for any new data in the Stream and we rely on something else to call `poll` again, is that okay?

**Comment by tomaka** [comment]
As long as we return `Poll::Ready`, then the caller has to continue calling `poll`.
It's the current code that is buggy: we return `Pending` and there's no guarantee to be waken up again.

**Comment by bkchr** [comment]
Okay :)

**Pull request merged**
