### PR TITLE
impl Zero and One for fixed point numbers

### PR DESCRIPTION
**Pull request by xlc**
useful for some generic code

polkadot companion: paritytech/polkadot#2922

### CODE REVIEW

**Comment by bkchr** [comment]
Does not compile

**Comment by xlc** [comment]
also did `cargo update -p librocksdb-sys` to support M1. let me know if you want to in another PR

**Comment by xlc** [comment]
This is a minor breaking change that people may need to import `One` or `Zero` in additional to `FixedPointNumber`

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
Still needs a polkadot companion

**Review by kianenigma — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
