### PR TITLE
Allow multiple bounds to be specified at decl_error!

### PR DESCRIPTION
**Pull request by athei**
Follow up to #7324 by @bkchr .

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
There is a test somewhere that adds a bound, would be nice to add there a second bound to have a test for this.

**Comment by thiolliere** [comment]
you can improve the test at frame/support/test/tests/instance.rs line 82

**Review by thiolliere — APPROVED** [review]

**Comment by athei** [comment]
The tests in that directory are failing for me even without modifying them:
```
test tests/derive_no_bound_ui/eq.rs ... mismatch

EXPECTED:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0277]: can't compare `Foo<T>` with `Foo<T>`
   --> $DIR/eq.rs:6:8
    |
6   | struct Foo<T: Trait> {
    |        ^^^ no implementation for `Foo<T> == Foo<T>`
    |
    = help: the trait `std::cmp::PartialEq` is not implemented for `Foo<T>`
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

ACTUAL OUTPUT:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0277]: can't compare `Foo<T>` with `Foo<T>`
   --> $DIR/eq.rs:6:8
    |
6   | struct Foo<T: Trait> {
    |        ^^^ no implementation for `Foo<T> == Foo<T>`
    |
   ::: $RUST/core/src/cmp.rs
    |
    | pub trait Eq: PartialEq<Self> {
    |               --------------- required by this bound in `std::cmp::Eq`
    |
    = help: the trait `std::cmp::PartialEq` is not implemented for `Foo<T>`
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

I am on `rustc 1.49.0-nightly (1eaadebb3 2020-10-21)`.

**Comment by thiolliere** [comment]
this test should only be executed on stable rust https://github.com/paritytech/substrate/blob/master/frame/support/test/tests/derive_no_bound_ui.rs#L18

are all ui tests executing ? is it actually executing by stable and this stable is not latest ?

**Comment by athei** [comment]
I just assumed it had something to do with nightly. I suppose it is executing on stable.
```
~/Developer/parity/substrate/frame/support/test% cargo test
```

Other UI tests are also executing:
```
running 1 test
    Checking frame-support-test-tests v0.0.0 (/Users/alexander/Developer/parity/substrate/target/tests/frame-support-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s

test tests/derive_no_bound_ui/clone.rs ... ok
test tests/derive_no_bound_ui/debug.rs ... ok
test tests/derive_no_bound_ui/eq.rs ... mismatch
```

**Comment by thiolliere** [comment]
I actually reproduced your result locally, not sure how the CI is getting its result 🤔 then.

**Comment by thiolliere** [comment]
bot merge

**Comment by athei** [comment]
> I actually reproduced your result locally, not sure how the CI is getting its result 🤔 then.

Are we **sure** that the CI actually executes those tests?

**Comment by thiolliere** [comment]
> > I actually reproduced your result locally, not sure how the CI is getting its result thinking then.
> 
> Are we **sure** that the CI actually executes those tests?

we will see here https://github.com/paritytech/substrate/pull/7456 but when I introduced the test I was convinced so

**Comment by athei** [comment]
Interesting. No idea why it does fail locally. I use macOS locally. Maybe that is the culprit?

**Comment by thiolliere** [comment]
probably not, I reproduced on linux.
the command is `cargo test --workspace --locked --release --verbose --features runtime-benchmarks --manifest-path bin/node/cli/Cargo.toml`
maybe workspace argument 🤔

**Pull request merged**
