### PR TITLE
Expose block number in seal_random

### LINKED ISSUE #8297: Expose block number in seal_random
Changes to the `Randomness` trait require contracts to expose the block at which the randomness was collected. This should be done using a new version of the `seal_random` function.

New versions should be exposed through a function of the same name but with a different module name. For this the `define_env!` macro needs to be amended.

Changes to randomness in #8180

### PR DESCRIPTION
**Pull request by athei**
Fixes #8297

- Allow to specify the wasm module when defining a contract callable function
- Add new version of `seal_random` (by scoping it under `seal1`) that returns the block number in addition to the seed
- Deprecate the old version

In the long term we should convert `define_env!` to a proc macro. This stuff is becoming ugly.

The new contract callable function has the same name `seal_random` but is scoped under another wasm module. The module of the function is `seal1` in contrast to the old module `seal0` that hosts the original function.

@Robbepop ink! should switch to the new interface and make the block number available to its users. It is not a breaking change, though. The old version remains to be supported indefinitely.

### CODE REVIEW

**Comment by Robbepop** [comment]
>     * Add new version of `seal_random` that returns the block number in addition to the seed

Can you elaborate on this change in design?

**Comment by athei** [comment]
> > ```
> > * Add new version of `seal_random` that returns the block number in addition to the seed
> > ```
> 
> 
> Can you elaborate on this change in design?

Updated the initial post.

**Review by thiolliere — APPROVED** [review]
I'm 100% familiar with this part of the code, but all changes looks good to me

**Comment by Robbepop** [comment]
ink! `master` already merged this.

**Comment by athei** [comment]
bot merge

**Review by Robbepop — APPROVED** [review]

**Comment by athei** [comment]
bot merge

**Pull request merged**
